"""
autogenerated_draft_class.py
Basketball Manager fictional draft class generator.

Prospects are generated before they become rookies. draft_logic.py converts drafted
prospects into your game's normal player format.
"""

from __future__ import annotations

import random
from typing import Any, Dict, List, Optional, Tuple

AUTOGENERATED_DRAFT_CLASS_VERSION = "2026-05-29_autogenerated_draft_class_identity_faces_safe20_names_v4_academy_aliases"

FIRST_NAMES = [
    "Jalen", "Marcus", "Darius", "Cam", "Malik", "Isaiah", "Trey", "Jordan", "Kobe", "Jaylen",
    "Nolan", "Miles", "Devin", "Tyrese", "Andre", "Elijah", "Carter", "Bryce", "Amari", "Kellan",
    "Terrence", "Micah", "Zion", "Damon", "Cole", "Jabari", "Ashton", "Quentin", "Landon", "Makai",
    "Luca", "Mateo", "Niko", "Rafael", "Thiago", "Emil", "Jonas", "Oskar", "Henrik", "Kai",
    "Ayo", "Kofi", "Moussa", "Idris", "Sekou", "Tariq", "Yusuf", "Baye", "Oumar", "Nassir",
]

LAST_NAMES = [
    "Bennett", "Carter", "Brooks", "Hamilton", "Reed", "Coleman", "Harris", "Morris", "Turner", "Hayes",
    "Jackson", "Walker", "Murray", "Porter", "Griffin", "Daniels", "Owens", "Simmons", "Lawson", "Bradley",
    "Cross", "Holland", "Ellis", "Foster", "Warren", "Banks", "Fields", "Stone", "Price", "Knight",
    "Petrovic", "Markovic", "Kovalenko", "Santos", "Mendes", "Silva", "Moretti", "Bianchi", "Novak", "Schmidt",
    "Okafor", "Diop", "Mensah", "Kamara", "Diallo", "Bamba", "Ndiaye", "Traore", "Konate", "Adebayo",
]

COLLEGES = [
    "Duke", "Kentucky", "Kansas", "North Carolina", "UCLA", "Arizona", "Michigan State", "Gonzaga",
    "Villanova", "Baylor", "Texas", "Arkansas", "Alabama", "Houston", "Connecticut", "Tennessee",
    "Overtime Elite", "G League Ignite", "Mega Basket", "Real Madrid", "Barcelona", "ASVEL", "Partizan",
    "Melbourne United", "Sydney Kings", "Auckland Academy", "Toronto Prep", "Montverde", "IMG Academy",
]

NATIONALITIES = [
    "USA", "Canada", "France", "Spain", "Serbia", "Australia", "Germany", "Brazil", "Nigeria", "Senegal",
    "Slovenia", "Lithuania", "Turkey", "Greece", "Italy", "Croatia",
]


# Wider identity-aware name pools. The old pools were intentionally small for early testing,
# which made names like "Makai Kim" appear far too often across draft classes.
# These extras create thousands of possible full-name combinations while keeping names
# loosely aligned with each prospect identity profile.
ADDITIONAL_FIRST_NAMES_BY_PROFILE = {
    "black_american_dark": [
        "Ace", "Aden", "Ahmad", "Akeem", "Alijah", "Brandon", "Cedric", "Corey", "Damian", "Davion",
        "DeAndre", "DeShawn", "Donovan", "Emanuel", "Jaden", "Jaheim", "Jamal", "Jamari", "Javon", "Jeremiah",
        "Josiah", "Keon", "Khalil", "Kyrie", "Lamar", "Marquis", "Nasir", "Omari", "Rashad", "Rayan",
        "Taj", "Talen", "Xavier", "Zaire", "Zionte", "Zyair",
    ],
    "black_american_lightskin": [
        "Aidan", "Amani", "Braylon", "Cade", "Cassius", "Cayden", "Coby", "Dalen", "Dorian", "Emoni",
        "Jace", "Jaiden", "Jayce", "Jett", "Julian", "Kaden", "Kael", "Kameron", "Kason",
        "Keegan", "Kendall", "Kylen", "Levi", "Mason", "Myles", "Nassir", "Rylan", "Sincere", "Tavian",
        "Taylen", "Trevor", "Zayden", "Zeke", "Zyon",
    ],
    "african_international": [
        "Abdou", "Abdoulaye", "Abel", "Adama", "Ade", "Ademola", "Amadou", "Bismack", "Cheikh", "Demba",
        "Ebrima", "Femi", "Hamidou", "Ibrahima", "Ismael", "Karim", "Khalifa", "Mamadou", "Mouhamed", "Nana",
        "Obinna", "Olu", "Pascal", "Rui", "Saliou", "Salif", "Samba", "Sidy", "Souleymane",
        "Tendai", "Thabo", "Usman", "Youssou", "Zubair", "Zyon",
    ],
    "white_american_european": [
        "Adam", "Anders", "Anton", "Aron", "Austin", "Bastian", "Bodhi", "Caleb", "Callum", "Cooper",
        "Dawson", "Dominik", "Elias", "Elliot", "Felix", "Finn", "Gavin", "Gregor", "Hugo", "Jack",
        "Jakob", "Kasper", "Kieran", "Liam", "Logan", "Lukas", "Magnus", "Matteo", "Max", "Milan",
        "Noah", "Nikolai", "Oliver", "Oscar", "Theo", "Viktor", "Wyatt",
    ],
    "latino": [
        "Adrian", "Alejandro", "Andres", "Angel", "Bruno", "Carlos", "Cristian", "Dario", "Eduardo", "Emilio",
        "Enzo", "Esteban", "Felipe", "Francisco", "Gabriel", "Hector", "Hugo", "Javier", "Joaquin", "Jose",
        "Juan", "Julian", "Luis", "Manuel", "Matias", "Miguel", "Pablo", "Pedro", "Raul", "Renato",
        "Rodrigo", "Sergio", "Tomas", "Valentin", "Victor", "Xavi",
    ],
    "mixed_blasian": [
        "Akari", "Andre", "Arin", "Cameron", "Dante", "Dax", "Emery", "Enzo", "Hiro", "Jace",
        "Jaden", "Jai", "Jaxon", "Jin", "Jiro", "Kairo", "Kasen", "Kian", "Koa", "Kylan",
        "Leandro", "Luca", "Makaius", "Malachi", "Milo", "Niko", "Rai", "Rakai", "Ren", "Rio",
        "Rohan", "Sage", "Taj", "Tao", "Zane", "Zen",
    ],
    "east_asian": [
        "Akio", "Ari", "Daichi", "Daisuke", "Eiji", "Hiroki", "Hyun", "Issei", "Itsuki", "Jae",
        "Jiho", "Joon", "Jun", "Kazuki", "Kei", "Kenta", "Kian", "Kaito", "Minho", "Minseok",
        "Ren", "Riku", "Ryota", "Seojun", "Shin", "Shota", "Sora", "Taiga", "Takumi", "Taro",
        "Tatsu", "Tomo", "Yuki", "Yuma", "Yusei", "Zen",
    ],
}

ADDITIONAL_LAST_NAMES_BY_PROFILE = {
    "black_american_dark": [
        "Alexander", "Anderson", "Bates", "Bell", "Booker", "Bridges", "Brown", "Butler", "Clark", "Cook",
        "Cooper", "Davis", "Douglas", "Edwards", "Evans", "Freeman", "Green", "Hardy", "Henderson", "Hill",
        "Howard", "Jefferson", "Johnson", "Jones", "King", "Lewis", "Marshall", "Mitchell", "Nelson", "Parker",
        "Perry", "Powell", "Robinson", "Scott", "Stewart", "Thomas", "Washington", "Williams", "Young",
    ],
    "black_american_lightskin": [
        "Adams", "Allen", "Bailey", "Barrett", "Bishop", "Bryant", "Burton", "Chandler", "Crawford", "Dawson",
        "Fleming", "Fox", "Gaines", "Garland", "Gray", "Hampton", "Hawkins", "Hunter", "Irving",
        "Jordan", "Lane", "Maxwell", "McBride", "Miles", "Monroe", "Payton", "Pierce", "Rivers", "Russell",
        "Sanders", "Sharp", "Tate", "Wade", "Wallace", "West", "Wheeler",
    ],
    "african_international": [
        "Abebe", "Afolayan", "Agbaji", "Ajayi", "Akpan", "Bassey", "Camara", "Cisse", "Dieng", "Doumbia",
        "Eze", "Faye", "Gueye", "Keita", "Kouyate", "Mbaye", "Mbeki", "N'Dour", "Ngom", "Okeke",
        "Okoro", "Olawale", "Omotayo", "Sane", "Sanogo", "Senghor", "Sy", "Toure", "Udoka",
        "Umeh", "Yeboah", "Yoro", "Zongo", "Zuma",
    ],
    "white_american_european": [
        "Andersen", "Armstrong", "Baker", "Berg", "Black", "Boucher", "Carlsen", "Cohen", "Dixon", "Elliott",
        "Eriksen", "Fischer", "Gallagher", "Gordon", "Hansen", "Hart", "Hoffman", "Holm", "Hughes", "Johansen",
        "Keller", "Klein", "Kovac", "Larsen", "Lindberg", "Lund", "Madsen", "Miller", "Murphy", "Olsen",
        "Peterson", "Reynolds", "Rossi", "Schaefer", "Smith", "Sorensen", "Thompson", "Weber", "Wright",
    ],
    "latino": [
        "Aguilar", "Almeida", "Alvarez", "Barbosa", "Campos", "Castillo", "Castro", "Costa", "Cruz", "Delgado",
        "Diaz", "Dominguez", "Fernandez", "Ferreira", "Flores", "Garcia", "Gomez", "Gonzalez", "Gutierrez", "Herrera",
        "Lopez", "Marquez", "Martinez", "Medina", "Morales", "Navarro", "Ortega", "Pereira", "Perez", "Ramirez",
        "Ramos", "Reyes", "Rivera", "Rodriguez", "Romero", "Torres", "Vargas",
    ],
    "mixed_blasian": [
        "Ahn", "Akana", "Bae", "Bennett", "Brooks", "Chambers", "Choi", "Cole", "Ellis", "Han",
        "Harris", "Hayashi", "Ho", "Hughes", "Jackson", "Jeong", "Kang", "Kato", "Kobayashi", "Kwon",
        "Lam", "Lee", "Lin", "Matsuda", "Moon", "Nakamura", "Nguyen", "Okada", "Reed", "Sato",
        "Shin", "Song", "Tan", "Taylor", "Yamamoto", "Young",
    ],
    "east_asian": [
        "Abe", "Aoki", "Bae", "Chang", "Cho", "Chung", "Fujii", "Fujimoto", "Han", "Hashimoto",
        "Hirano", "Huang", "Ito", "Jeon", "Jung", "Kang", "Kawamura", "Kim", "Kobayashi", "Kwon",
        "Lee", "Li", "Lin", "Liu", "Maeda", "Matsui", "Mori", "Nakamura", "Ng", "Oda",
        "Park", "Qian", "Saito", "Sasaki", "Seo", "Shimizu", "Wang", "Yang", "Zhao",
    ],
}


def _unique_text_list(values: List[str]) -> List[str]:
    out: List[str] = []
    seen = set()
    for value in values or []:
        text = str(value or "").strip()
        key = text.lower()
        if not text or key in seen:
            continue
        seen.add(key)
        out.append(text)
    return out


IDENTITY_PROFILES = [
    {
        "key": "black_american_dark",
        "ethnicityGroup": "black",
        "subgroup": "african_american",
        "skinTone": "dark",
        "region": "usa",
        "nationalityWeights": [("USA", 0.86), ("Canada", 0.10), ("France", 0.04)],
        "collegeWeights": [("college", 0.78), ("prep", 0.12), ("g_league", 0.10)],
        "weight": 0.30,
        "portraitRange": (1, 30),
        "firstNames": [
            "Jalen", "Jaylen", "Malik", "Darius", "Trey", "Isaiah", "Cam", "Amari", "Makai", "Jabari",
            "Terrence", "Micah", "Damon", "Kobe", "Tyrese", "Devin", "Andre", "Elijah", "Zion", "Quentin",
        ],
        "lastNames": [
            "Carter", "Brooks", "Harris", "Jackson", "Walker", "Murray", "Porter", "Daniels", "Owens", "Simmons",
            "Lawson", "Bradley", "Ellis", "Foster", "Warren", "Banks", "Fields", "Knight", "Reed", "Coleman",
        ],
    },
    {
        "key": "black_american_lightskin",
        "ethnicityGroup": "black",
        "subgroup": "african_american",
        "skinTone": "light_brown",
        "region": "usa",
        "nationalityWeights": [("USA", 0.82), ("Canada", 0.14), ("France", 0.04)],
        "collegeWeights": [("college", 0.76), ("prep", 0.14), ("g_league", 0.10)],
        "weight": 0.15,
        "portraitRange": (31, 45),
        "firstNames": [
            "Jaylen", "Tyrese", "Bryce", "Carter", "Cam", "Nolan", "Miles", "Jordan", "Kellan", "Ashton",
            "Devin", "Trey", "Isaiah", "Landon", "Jalen", "Micah", "Makai", "Amari",
        ],
        "lastNames": [
            "Bennett", "Carter", "Brooks", "Hamilton", "Reed", "Morris", "Turner", "Hayes", "Murray", "Porter",
            "Griffin", "Daniels", "Lawson", "Cross", "Holland", "Ellis", "Stone", "Price", "Knight",
        ],
    },
    {
        "key": "african_international",
        "ethnicityGroup": "black",
        "subgroup": "african",
        "skinTone": "dark",
        "region": "international",
        "nationalityWeights": [("Nigeria", 0.30), ("Senegal", 0.28), ("France", 0.14), ("Canada", 0.08), ("Greece", 0.06), ("Turkey", 0.04), ("USA", 0.10)],
        "collegeWeights": [("international", 0.45), ("college", 0.35), ("g_league", 0.12), ("prep", 0.08)],
        "weight": 0.10,
        "portraitRange": (46, 55),
        "firstNames": [
            "Ayo", "Kofi", "Moussa", "Idris", "Sekou", "Yusuf", "Baye", "Oumar", "Nassir", "Amadou",
            "Boubacar", "Chinedu", "Tariq", "Ibrahim", "Malick", "Demba",
        ],
        "lastNames": [
            "Okafor", "Diop", "Mensah", "Kamara", "Diallo", "Bamba", "Ndiaye", "Traore", "Konate", "Adebayo",
            "Nwosu", "Coulibaly", "Fall", "Sarr", "Balogun", "Onyeka",
        ],
    },
    {
        "key": "white_american_european",
        "ethnicityGroup": "white",
        "subgroup": "american_european",
        "skinTone": "light",
        "region": "usa_or_europe",
        "nationalityWeights": [("USA", 0.46), ("Canada", 0.10), ("Serbia", 0.10), ("Croatia", 0.08), ("Germany", 0.08), ("Spain", 0.06), ("France", 0.06), ("Australia", 0.06)],
        "collegeWeights": [("college", 0.48), ("international", 0.36), ("prep", 0.08), ("g_league", 0.08)],
        "weight": 0.20,
        "portraitRange": (56, 75),
        "firstNames": [
            "Nolan", "Cole", "Carter", "Bryce", "Landon", "Luca", "Mateo", "Niko", "Emil", "Jonas",
            "Oskar", "Henrik", "Kai", "Tomas", "Aleksa", "Ivan", "Luka", "Mason", "Blake", "Luke",
        ],
        "lastNames": [
            "Bennett", "Hayes", "Foster", "Stone", "Knight", "Petrovic", "Markovic", "Kovalenko", "Moretti", "Bianchi",
            "Novak", "Schmidt", "Jovic", "Vukic", "Collins", "Walker", "Turner", "Price",
        ],
    },
    {
        "key": "latino",
        "ethnicityGroup": "latino",
        "subgroup": "latino_mixed",
        "skinTone": "medium",
        "region": "americas",
        "nationalityWeights": [("Brazil", 0.34), ("Spain", 0.18), ("USA", 0.18), ("Canada", 0.06), ("France", 0.06), ("Australia", 0.04), ("Italy", 0.14)],
        "collegeWeights": [("college", 0.46), ("international", 0.38), ("prep", 0.08), ("g_league", 0.08)],
        "weight": 0.07,
        "portraitRange": (76, 82),
        "firstNames": ["Mateo", "Rafael", "Thiago", "Luca", "Dante", "Marco", "Nico", "Santi", "Diego", "Leo"],
        "lastNames": ["Santos", "Mendes", "Silva", "Moretti", "Bianchi", "Alvarez", "Reyes", "Costa", "Ferreira", "Marquez"],
    },
    {
        "key": "mixed_blasian",
        "ethnicityGroup": "mixed",
        "subgroup": "blasian",
        "skinTone": "medium_brown",
        "region": "usa_or_canada",
        "nationalityWeights": [("USA", 0.70), ("Canada", 0.16), ("Australia", 0.06), ("France", 0.04), ("Japan", 0.02), ("Korea", 0.02)],
        "collegeWeights": [("college", 0.70), ("prep", 0.14), ("g_league", 0.10), ("international", 0.06)],
        "weight": 0.10,
        "portraitRange": (83, 92),
        "firstNames": ["Kai", "Jalen", "Jaylen", "Micah", "Cameron", "Trey", "Kobe", "Makai", "Jordan", "Miles"],
        "lastNames": ["Lee", "Kim", "Chen", "Brooks", "Carter", "Ellis", "Hayes", "Murray", "Banks", "Stone"],
    },
    {
        "key": "east_asian",
        "ethnicityGroup": "asian",
        "subgroup": "east_asian",
        "skinTone": "light_medium",
        "region": "international_or_us",
        "nationalityWeights": [("USA", 0.30), ("Canada", 0.16), ("Australia", 0.12), ("Japan", 0.14), ("Korea", 0.14), ("France", 0.06), ("Germany", 0.04), ("Spain", 0.04)],
        "collegeWeights": [("college", 0.46), ("international", 0.34), ("prep", 0.12), ("g_league", 0.08)],
        "weight": 0.08,
        "portraitRange": (93, 100),
        "firstNames": ["Kai", "Kenji", "Yuto", "Minjun", "Jin", "Leo", "Ethan", "Noah", "Ryan", "Haru"],
        "lastNames": ["Lee", "Kim", "Park", "Chen", "Zhang", "Watanabe", "Tanaka", "Choi", "Lin", "Kang"],
    },
]

COLLEGE_GROUPS = {
    "college": [
        "Duke", "Kentucky", "Kansas", "North Carolina", "UCLA", "Arizona", "Michigan State", "Gonzaga",
        "Villanova", "Baylor", "Texas", "Arkansas", "Alabama", "Houston", "Connecticut", "Tennessee",
    ],
    "prep": ["Toronto Prep", "Montverde", "IMG Academy", "Auckland Academy"],
    "g_league": ["G League Ignite", "Overtime Elite"],
    "international": ["Mega Basket", "Real Madrid", "Barcelona", "ASVEL", "Partizan", "Melbourne United", "Sydney Kings"],
}

# Phase 1 convention for the 100-face pack:
# 0001-0030 black_american_dark, 0031-0045 black_american_lightskin,
# 0046-0055 african_international, 0056-0075 white_american_european,
# 0076-0082 latino, 0083-0092 mixed_blasian, 0093-0100 east_asian.
# If you generate the image pack differently, update these portraitRange values.

CLASS_TYPES = [
    "weak",
    "normal",
    "deep",
    "star_heavy",
    "generational",
    "defensive_class",
    "guard_heavy",
    "big_man_heavy",
]

ROOKIE_FACE_BASE_URL = "/assets/rookie_faces"
ROOKIE_FACE_COUNT = 100

# Phase 1 active portrait pool.
# Only these PNGs have been manually verified as 1040x760 with real alpha transparency.
# Until more clean portraits are added, the generator must never assign IDs outside this list.
SAFE_ROOKIE_FACE_IDS_BY_PROFILE = {
    "black_american_dark": [
        "rookie_face_0003", "rookie_face_0004", "rookie_face_0005", "rookie_face_0006",
    ],
    "black_american_lightskin": [
        "rookie_face_0033", "rookie_face_0034", "rookie_face_0035", "rookie_face_0036",
    ],
    "african_international": [
        "rookie_face_0047", "rookie_face_0048",
    ],
    "white_american_european": [
        "rookie_face_0059", "rookie_face_0060", "rookie_face_0061", "rookie_face_0062",
        "rookie_face_0063", "rookie_face_0064",
    ],
    # No clean Latino-specific portraits are confirmed yet, so this profile falls back
    # to the full safe pool instead of assigning missing 0076-0082 files.
    "latino": [],
    "mixed_blasian": [
        "rookie_face_0084", "rookie_face_0085",
    ],
    "east_asian": [
        "rookie_face_0094", "rookie_face_0095",
    ],
}

SAFE_ROOKIE_FACE_IDS = []
for _safe_face_group in SAFE_ROOKIE_FACE_IDS_BY_PROFILE.values():
    for _safe_face_id in _safe_face_group:
        if _safe_face_id not in SAFE_ROOKIE_FACE_IDS:
            SAFE_ROOKIE_FACE_IDS.append(_safe_face_id)

POSITION_WEIGHTS = {
    "normal": [("PG", 0.18), ("SG", 0.22), ("SF", 0.22), ("PF", 0.20), ("C", 0.18)],
    "guard_heavy": [("PG", 0.26), ("SG", 0.28), ("SF", 0.20), ("PF", 0.15), ("C", 0.11)],
    "big_man_heavy": [("PG", 0.14), ("SG", 0.16), ("SF", 0.20), ("PF", 0.25), ("C", 0.25)],
}

SECONDARY_BY_POS = {
    "PG": ["SG", ""],
    "SG": ["PG", "SF", ""],
    "SF": ["SG", "PF", ""],
    "PF": ["SF", "C", ""],
    "C": ["PF", ""],
}

HEIGHT_RANGES = {
    "PG": (72, 77),
    "SG": (75, 80),
    "SF": (78, 82),
    "PF": (80, 84),
    "C": (82, 88),
}

WEIGHT_RANGES = {
    "PG": (175, 205),
    "SG": (185, 220),
    "SF": (200, 235),
    "PF": (215, 255),
    "C": (235, 285),
}

ARCHETYPES_BY_POS = {
    "PG": [
        "Floor General", "Shot-Creating Guard", "Two-Way Playmaker", "Speedy Slasher", "Pull-Up Shooter",
    ],
    "SG": [
        "Three-Level Scorer", "Movement Shooter", "Two-Way Wing", "Athletic Slasher", "Combo Guard",
    ],
    "SF": [
        "Two-Way Wing", "Point Forward", "Scoring Wing", "3-and-D Forward", "Athletic Finisher",
    ],
    "PF": [
        "Stretch Four", "Defensive Forward", "Interior Finisher", "Face-Up Forward", "Glass Cleaner",
    ],
    "C": [
        "Rim Protector", "Post Scorer", "Stretch Big", "Rebounding Big", "Playmaking Center",
    ],
}

# Attribute order used by the current game UI:
# 0 3PT, 1 MID, 2 CLOSE, 3 FT, 4 BALL, 5 PASS, 6 SPEED, 7 ATH,
# 8 PER D, 9 INS D, 10 BLK, 11 STL, 12 REB, 13 OIQ, 14 DIQ
ARCHETYPE_BIASES = {
    "Floor General":       [0, 2, -1, 3, 9, 10, 4, 1, 1, -8, -9, 2, -7, 7, 3],
    "Shot-Creating Guard": [6, 8, 3, 5, 8, 3, 5, 3, -1, -8, -9, 1, -7, 6, 0],
    "Two-Way Playmaker":   [2, 3, 1, 2, 7, 8, 5, 5, 7, -3, -4, 7, -3, 5, 6],
    "Speedy Slasher":      [-2, 1, 8, 1, 6, 2, 9, 9, 2, -5, -6, 3, -4, 3, 1],
    "Pull-Up Shooter":     [9, 8, 0, 4, 5, 2, 3, 0, -1, -8, -9, 0, -7, 5, 0],
    "Three-Level Scorer":  [7, 8, 6, 4, 5, 1, 3, 4, -1, -6, -7, 0, -5, 6, 0],
    "Movement Shooter":    [10, 5, -2, 5, 2, 0, 4, 1, 0, -7, -8, 1, -7, 5, 1],
    "Two-Way Wing":        [4, 2, 3, 2, 2, 1, 5, 6, 9, 3, 1, 8, 2, 4, 7],
    "Athletic Slasher":    [-1, 0, 9, 0, 4, 0, 8, 10, 3, 0, 1, 3, 2, 2, 1],
    "Combo Guard":         [5, 5, 3, 4, 7, 5, 5, 2, 1, -7, -8, 2, -6, 5, 1],
    "Point Forward":       [2, 3, 5, 2, 7, 9, 2, 5, 3, 3, 0, 3, 4, 7, 4],
    "Scoring Wing":        [6, 6, 6, 3, 4, 1, 3, 5, 0, -2, -2, 1, 0, 6, 0],
    "3-and-D Forward":     [8, 2, 0, 3, 0, -1, 3, 3, 10, 4, 2, 9, 2, 3, 8],
    "Athletic Finisher":   [-3, -1, 10, -1, 1, -1, 6, 10, 3, 4, 4, 2, 5, 2, 3],
    "Stretch Four":        [8, 5, 3, 3, -1, 1, -1, 2, 2, 5, 3, 1, 5, 5, 4],
    "Defensive Forward":   [-2, -1, 3, 0, -1, 0, 3, 7, 8, 8, 7, 6, 8, 1, 9],
    "Interior Finisher":   [-7, -2, 10, -2, -4, -2, -2, 7, -1, 8, 7, -1, 8, 3, 4],
    "Face-Up Forward":     [4, 6, 6, 3, 3, 3, 1, 4, 1, 5, 3, 1, 5, 6, 3],
    "Glass Cleaner":       [-7, -3, 6, -2, -5, -3, -3, 7, -2, 9, 8, -1, 11, 1, 5],
    "Rim Protector":       [-10, -5, 6, -4, -7, -3, -4, 6, -3, 10, 12, -2, 9, 0, 8],
    "Post Scorer":         [-9, 2, 11, -1, -5, 0, -5, 4, -4, 8, 5, -4, 7, 5, 2],
    "Stretch Big":         [9, 5, 4, 3, -3, 2, -4, 1, -2, 6, 5, -2, 6, 6, 4],
    "Rebounding Big":      [-10, -4, 7, -3, -7, -4, -5, 6, -3, 9, 9, -3, 12, 1, 6],
    "Playmaking Center":   [2, 3, 7, 1, 1, 8, -3, 3, -1, 6, 6, -2, 8, 8, 4],
}


def _plain(value: Any) -> Any:
    if value is None:
        return None
    if isinstance(value, dict):
        return {str(k): _plain(v) for k, v in value.items()}
    if isinstance(value, list):
        return [_plain(v) for v in value]
    if isinstance(value, tuple):
        return [_plain(v) for v in value]
    try:
        if hasattr(value, "to_py"):
            return _plain(value.to_py())
    except Exception:
        pass
    return value


def _safe_int(value: Any, default: int = 0) -> int:
    try:
        if value is None:
            return default
        return int(float(value))
    except Exception:
        return default


def _stable_seed(*parts: Any) -> int:
    text = "|".join(str(part) for part in parts)
    total = 0
    for i, ch in enumerate(text):
        total = (total + (i + 1) * ord(ch)) % 2_147_483_647
    return total or 20260527


def _clamp(value: float, lo: int, hi: int) -> int:
    return int(max(lo, min(hi, round(value))))


def _weighted_choice(rng: random.Random, weighted: List[Tuple[str, float]]) -> str:
    total = sum(weight for _, weight in weighted)
    ticket = rng.random() * total
    running = 0.0
    for item, weight in weighted:
        running += weight
        if ticket <= running:
            return item
    return weighted[-1][0]


def _tier_for_rank(rank: int, class_type: str, rng: random.Random) -> Tuple[str, Tuple[int, int], Tuple[int, int]]:
    generational_cut = 1 if class_type == "generational" else 0
    if rank == 1 and (class_type == "generational" or rng.random() < 0.18):
        return "Generational", (80, 84), (94, 99)

    if rank <= 3 + (1 if class_type == "star_heavy" else 0):
        return "Franchise", (76, 81), (90, 97)

    if rank <= 8 + generational_cut:
        return "High Lottery", (72, 78), (85, 94)

    if rank <= (26 if class_type == "deep" else 22):
        return "First Round", (68, 75), (78, 90)

    if rank <= 45:
        return "Second Round", (62, 71), (72, 85)

    return "Undrafted", (55, 67), (65, 82)


def _adjust_for_class_type(overall: int, potential: int, rank: int, class_type: str) -> Tuple[int, int]:
    if class_type == "weak":
        if rank <= 10:
            potential -= 2
        overall -= 1
    elif class_type == "deep":
        if 12 <= rank <= 45:
            overall += 1
            potential += 1
    elif class_type == "star_heavy":
        if rank <= 6:
            potential += 2
    elif class_type == "defensive_class":
        potential += 0
    return _clamp(overall, 50, 88), _clamp(potential, overall, 99)


def _build_attrs(
    rng: random.Random,
    pos: str,
    archetype: str,
    overall: int,
    potential: int,
    class_type: str,
) -> List[int]:
    bias = ARCHETYPE_BIASES.get(archetype, [0] * 15)
    base = overall - 2

    attrs = []
    for idx, b in enumerate(bias):
        noise = rng.randint(-6, 6)
        value = base + b + noise
        attrs.append(_clamp(value, 25, 99))

    if pos == "PG":
        attrs[9] = min(attrs[9], overall - 5)
        attrs[10] = min(attrs[10], overall - 10)
        attrs[12] = min(attrs[12], overall - 5)
    elif pos == "C":
        attrs[4] = min(attrs[4], overall + 1)
        attrs[6] = min(attrs[6], overall)
        attrs[8] = min(attrs[8], overall + 2)

    if class_type == "defensive_class":
        for idx in [8, 9, 10, 11, 12, 14]:
            attrs[idx] = _clamp(attrs[idx] + rng.randint(2, 6), 25, 99)

    # Make true stars feel a bit cleaner across IQ and stamina-adjacent skills.
    if potential >= 92:
        attrs[13] = _clamp(attrs[13] + rng.randint(2, 5), 25, 99)
        attrs[14] = _clamp(attrs[14] + rng.randint(1, 4), 25, 99)

    return attrs


def _ratings_from_attrs(attrs: List[int]) -> Tuple[int, int, float]:
    off_indices = [0, 1, 2, 3, 4, 5, 7, 13]
    def_indices = [8, 9, 10, 11, 12, 14]

    off_rating = round(sum(attrs[i] for i in off_indices) / len(off_indices))
    def_rating = round(sum(attrs[i] for i in def_indices) / len(def_indices))

    scoring_rating = (
        attrs[0] * 0.28
        + attrs[1] * 0.21
        + attrs[2] * 0.24
        + attrs[4] * 0.10
        + attrs[7] * 0.08
        + attrs[13] * 0.09
    )

    return int(off_rating), int(def_rating), float(scoring_rating)


def _weighted_profile_choice(rng: random.Random) -> Dict[str, Any]:
    total = sum(float(profile.get("weight", 0.0)) for profile in IDENTITY_PROFILES)
    ticket = rng.random() * total
    running = 0.0

    for profile in IDENTITY_PROFILES:
        running += float(profile.get("weight", 0.0))
        if ticket <= running:
            return dict(profile)

    return dict(IDENTITY_PROFILES[0])


def _weighted_value_choice(rng: random.Random, weighted: List[Tuple[str, float]], fallback: str = "") -> str:
    if not weighted:
        return fallback

    total = sum(float(weight) for _, weight in weighted)
    ticket = rng.random() * total
    running = 0.0

    for item, weight in weighted:
        running += float(weight)
        if ticket <= running:
            return item

    return weighted[-1][0]


def _make_identity_profile(rng: random.Random) -> Dict[str, Any]:
    profile = _weighted_profile_choice(rng)
    profile_key = profile.get("key") or "unknown"
    nationality = _weighted_value_choice(rng, profile.get("nationalityWeights") or [], "USA")
    college_bucket = _weighted_value_choice(rng, profile.get("collegeWeights") or [], "college")
    college_options = COLLEGE_GROUPS.get(college_bucket, COLLEGES)

    first_names = _unique_text_list(
        list(profile.get("firstNames") or FIRST_NAMES)
        + list(ADDITIONAL_FIRST_NAMES_BY_PROFILE.get(profile_key) or [])
    )
    last_names = _unique_text_list(
        list(profile.get("lastNames") or LAST_NAMES)
        + list(ADDITIONAL_LAST_NAMES_BY_PROFILE.get(profile_key) or [])
    )

    return {
        "identityKey": profile_key,
        "ethnicityGroup": profile.get("ethnicityGroup") or "other",
        "subgroup": profile.get("subgroup") or "other",
        "skinTone": profile.get("skinTone") or "medium",
        "region": profile.get("region") or "unknown",
        "nationality": nationality,
        "collegeBucket": college_bucket,
        "college": rng.choice(college_options),
        "firstNames": first_names or FIRST_NAMES,
        "lastNames": last_names or LAST_NAMES,
        "portraitRange": profile.get("portraitRange") or (1, ROOKIE_FACE_COUNT),
    }


def _make_name(rng: random.Random, used: set, identity_profile: Optional[Dict[str, Any]] = None) -> str:
    first_names = (identity_profile or {}).get("firstNames") or FIRST_NAMES
    last_names = (identity_profile or {}).get("lastNames") or LAST_NAMES

    for _ in range(200):
        name = f"{rng.choice(first_names)} {rng.choice(last_names)}"
        if name not in used:
            used.add(name)
            return name

    name = f"{rng.choice(first_names)} {rng.choice(last_names)} Jr."
    used.add(name)
    return name


def _rookie_face_id(index: int) -> str:
    return f"rookie_face_{index:04d}"


def _rookie_face_url(face_id: str) -> str:
    return f"{ROOKIE_FACE_BASE_URL}/{face_id}.png"


def _rookie_face_entry(face_id: str) -> Dict[str, str]:
    url = _rookie_face_url(face_id)
    return {
        "id": face_id,
        "url": url,
        "headshot": url,
        "image": url,
        "img": url,
    }


def _portrait_ids_for_range(start: int, end: int, portrait_count: int) -> List[str]:
    start = max(1, _safe_int(start, 1))
    end = min(_safe_int(end, portrait_count), portrait_count)
    if end < start:
        return []
    return [_rookie_face_id(i) for i in range(start, end + 1)]


def _all_portrait_ids(portrait_count: int) -> List[str]:
    return [_rookie_face_id(i) for i in range(1, portrait_count + 1)]


def _choose_portrait_for_identity(
    identity_profile: Dict[str, Any],
    rng: random.Random,
    used_portrait_ids: Optional[List[str]] = None,
    assigned_this_class: Optional[set] = None,
    portrait_count: int = ROOKIE_FACE_COUNT,
) -> Dict[str, str]:
    # Phase 1 safety: only use manually verified portrait IDs.
    # Do not fall back to the old 1-100 range because most of those files do not exist
    # or have not been confirmed as clean transparent PNGs yet.
    profile_key = (identity_profile or {}).get("identityKey") or ""
    matching = list(SAFE_ROOKIE_FACE_IDS_BY_PROFILE.get(profile_key) or [])
    all_safe_ids = list(SAFE_ROOKIE_FACE_IDS)

    if not all_safe_ids:
        return _rookie_face_entry(_rookie_face_id(1))

    # If a profile has no verified bucket yet, use the full safe pool.
    # This keeps every generated prospect visually valid until more assets are added.
    if not matching:
        matching = all_safe_ids

    used = {str(face_id) for face_id in (used_portrait_ids or []) if face_id}
    assigned = assigned_this_class if assigned_this_class is not None else set()

    candidate_layers = [
        [face_id for face_id in matching if face_id not in used and face_id not in assigned],
        [face_id for face_id in matching if face_id not in assigned],
        [face_id for face_id in matching],
        [face_id for face_id in all_safe_ids if face_id not in used and face_id not in assigned],
        [face_id for face_id in all_safe_ids if face_id not in assigned],
        all_safe_ids,
    ]

    for candidates in candidate_layers:
        if candidates:
            face_id = rng.choice(candidates)
            assigned.add(face_id)
            return _rookie_face_entry(face_id)

    return _rookie_face_entry(all_safe_ids[0])


def _build_prospect(
    rank: int,
    season_year: int,
    class_type: str,
    rng: random.Random,
    used_names: set,
    portrait_info: Optional[Dict[str, str]] = None,
    identity_profile: Optional[Dict[str, Any]] = None,
) -> Dict[str, Any]:
    identity_profile = identity_profile or _make_identity_profile(rng)

    pos_weights = POSITION_WEIGHTS.get(class_type, POSITION_WEIGHTS["normal"])
    if class_type not in {"guard_heavy", "big_man_heavy"}:
        pos_weights = POSITION_WEIGHTS["normal"]

    pos = _weighted_choice(rng, pos_weights)
    secondary = rng.choice(SECONDARY_BY_POS.get(pos, [""]))
    archetype = rng.choice(ARCHETYPES_BY_POS[pos])

    tier, ovr_range, pot_range = _tier_for_rank(rank, class_type, rng)
    overall = rng.randint(*ovr_range)
    potential = rng.randint(max(overall, pot_range[0]), pot_range[1])
    overall, potential = _adjust_for_class_type(overall, potential, rank, class_type)

    age = rng.choices([18, 19, 20, 21, 22, 23], weights = [0.06, 0.44, 0.24, 0.16, 0.08, 0.02])[0]
    height = rng.randint(*HEIGHT_RANGES[pos])
    weight = rng.randint(*WEIGHT_RANGES[pos])

    attrs = _build_attrs(rng, pos, archetype, overall, potential, class_type)
    off_rating, def_rating, scoring_rating = _ratings_from_attrs(attrs)

    boom_bust = round(rng.uniform(0.12, 0.55), 2)
    if tier in {"Generational", "Franchise"}:
        boom_bust = round(rng.uniform(0.08, 0.40), 2)
    if tier == "Undrafted":
        boom_bust = round(rng.uniform(0.20, 0.70), 2)

    floor = _clamp(overall - rng.randint(2, 8), 45, overall)
    ceiling = _clamp(potential + rng.randint(0, 3), potential, 99)

    visible_rank = _clamp(rank + rng.randint(-5, 7), 1, 110)
    if rank <= 5:
        visible_rank = _clamp(rank + rng.randint(-1, 2), 1, 10)

    name = _make_name(rng, used_names, identity_profile)
    birth_month = rng.randint(1, 12)
    birth_day = rng.randint(1, 28)

    prospect_id = f"draft_{season_year}_{rank:03d}_{name.lower().replace(' ', '_').replace('.', '')}"
    portrait_info = portrait_info or {}
    portrait_id = portrait_info.get("id") or ""
    portrait_url = portrait_info.get("url") or ""

    return {
        "id": prospect_id,
        "draftClassYear": season_year,
        "name": name,
        "portraitId": portrait_id,
        "portraitFamilyId": portrait_id,
        "portraitVariant": "rookie",
        "headshot": portrait_url,
        "image": portrait_url,
        "img": portrait_url,
        "age": age,
        "birthMonth": birth_month,
        "birthDay": birth_day,
        "pos": pos,
        "secondaryPos": secondary,
        "height": height,
        "weight": weight,
        # Keep the rookie source in multiple aliases so draft conversion/front-end
        # code can display it consistently after a player is drafted.
        "college": identity_profile.get("college") or rng.choice(COLLEGES),
        "school": identity_profile.get("college") or rng.choice(COLLEGES),
        "university": identity_profile.get("college") or "",
        "academy": identity_profile.get("college") or "",
        "academyName": identity_profile.get("college") or "",
        "sourceName": identity_profile.get("college") or "",
        "draftSource": identity_profile.get("college") or "",
        "sourceType": identity_profile.get("collegeBucket") or "college",
        "collegeBucket": identity_profile.get("collegeBucket") or "college",
        "nationality": identity_profile.get("nationality") or rng.choice(NATIONALITIES),
        "ethnicityGroup": identity_profile.get("ethnicityGroup") or "other",
        "subgroup": identity_profile.get("subgroup") or "other",
        "skinTone": identity_profile.get("skinTone") or "medium",
        "identityKey": identity_profile.get("identityKey") or "unknown",
        "region": identity_profile.get("region") or "unknown",
        "archetype": archetype,
        "tier": tier,
        "overall": overall,
        "potential": potential,
        "floor": floor,
        "ceiling": ceiling,
        "attrs": attrs,
        "offRating": off_rating,
        "defRating": def_rating,
        "stamina": _clamp(rng.randint(72, 91) + (2 if age >= 21 else 0), 60, 96),
        "scoringRating": scoring_rating,
        "draftProjection": visible_rank,
        "trueRank": rank,
        "scouting": {
            "projectedRangeLow": _clamp(visible_rank - rng.randint(1, 7), 1, 100),
            "projectedRangeHigh": _clamp(visible_rank + rng.randint(3, 12), 1, 100),
            "scoutedOverallRange": [
                _clamp(overall - rng.randint(1, 4), 45, 99),
                _clamp(overall + rng.randint(1, 4), 45, 99),
            ],
            "scoutedPotentialRange": [
                _clamp(potential - rng.randint(2, 7), overall, 99),
                _clamp(potential + rng.randint(1, 5), overall, 99),
            ],
        },
        "traits": {
            "nbaReady": round(max(0.05, min(0.98, (overall - 55) / 32)), 2),
            "boomBust": boom_bust,
            "workEthic": round(rng.uniform(0.35, 0.95), 2),
            "injuryRisk": round(rng.uniform(0.04, 0.24), 2),
            "starUpside": round(max(0.02, min(0.98, (potential - 70) / 29)), 2),
        },
    }


def generate_draft_class(
    season_year: int = 2026,
    count: int = 84,
    seed: Optional[int] = None,
    class_type: Optional[str] = None,
    used_portrait_ids: Optional[List[str]] = None,
    portrait_count: int = ROOKIE_FACE_COUNT,
) -> Dict[str, Any]:
    if seed is None:
        seed = _stable_seed("draft_class", season_year)

    rng = random.Random(seed)
    if not class_type:
        class_type = rng.choices(
            CLASS_TYPES,
            weights = [0.12, 0.43, 0.15, 0.10, 0.06, 0.06, 0.04, 0.04],
        )[0]

    count = max(60, min(110, _safe_int(count, 84)))
    used_names = set()
    assigned_portrait_ids = set()
    prospects = []

    for rank in range(1, count + 1):
        identity_profile = _make_identity_profile(rng)
        portrait_info = _choose_portrait_for_identity(
            identity_profile = identity_profile,
            rng = rng,
            used_portrait_ids = used_portrait_ids,
            assigned_this_class = assigned_portrait_ids,
            portrait_count = portrait_count,
        )
        prospects.append(
            _build_prospect(
                rank,
                season_year,
                class_type,
                rng,
                used_names,
                portrait_info,
                identity_profile,
            )
        )

    # Sort by true rank, but keep draftProjection as the visible noisy board.
    prospects = sorted(prospects, key = lambda p: p["trueRank"])

    return {
        "ok": True,
        "version": AUTOGENERATED_DRAFT_CLASS_VERSION,
        "seasonYear": season_year,
        "seed": seed,
        "classType": class_type,
        "count": len(prospects),
        "draftClass": prospects,
        "classMeta": {
            "seasonYear": season_year,
            "classType": class_type,
            "seed": seed,
            "prospectCount": len(prospects),
            "portraitCount": portrait_count,
            "activeSafePortraitCount": len(SAFE_ROOKIE_FACE_IDS),
            "activeSafePortraitIds": list(SAFE_ROOKIE_FACE_IDS),
            "assignedPortraitCount": len([p for p in prospects if p.get("portraitId")]),
            "identityProfiles": sorted(list({p.get("identityKey") for p in prospects if p.get("identityKey")})),
            "summary": f"{season_year} generated {class_type.replace('_', ' ')} draft class",
        },
    }


def handle_request(request: Dict[str, Any]) -> Dict[str, Any]:
    req = _plain(request) or {}
    payload = req.get("payload") or {}
    action = req.get("action") or "generate_draft_class"

    if action not in {"generate_draft_class", "create_draft_class", "load_or_generate_draft_class"}:
        return {
            "ok": False,
            "reason": f"UNKNOWN_DRAFT_CLASS_ACTION: {action}",
            "version": AUTOGENERATED_DRAFT_CLASS_VERSION,
        }

    season_year = _safe_int(payload.get("seasonYear"), 2026)
    count = _safe_int(payload.get("count"), 84)
    seed = payload.get("seed")
    seed = _safe_int(seed, _stable_seed("draft_class", season_year)) if seed is not None else None
    class_type = payload.get("classType") or payload.get("classStrength") or None
    used_portrait_ids = payload.get("usedPortraitIds") or payload.get("usedPortraitIDs") or []
    portrait_count = _safe_int(payload.get("portraitCount"), ROOKIE_FACE_COUNT)

    return generate_draft_class(
        season_year = season_year,
        count = count,
        seed = seed,
        class_type = class_type,
        used_portrait_ids = used_portrait_ids,
        portrait_count = portrait_count,
    )
