"""
autogenerated_draft_class.py
Basketball Manager fictional draft class generator.

Prospects are generated before they become rookies. draft_logic.py converts drafted
prospects into your game's normal player format.
"""

from __future__ import annotations

import random
import math
import time
from typing import Any, Dict, List, Optional, Tuple

AUTOGENERATED_DRAFT_CLASS_VERSION = "2026-06-13_autogenerated_draft_class_histogram_personality_v11"

FIRST_NAMES = [
    "Jalen", "Marcus", "Darius", "Cam", "Malik", "Isaiah", "Trey", "Jordan", "Kobe", "Jaylen",
    "Nolan", "Miles", "Devin", "Tyrese", "Andre", "Elijah", "Carter", "Bryce", "Amari", "Kellan",
    "Terrence", "Micah", "Zion", "Damon", "Cole", "Jabari", "Ashton", "Quentin", "Landon", "Makai",
    "Luca", "Mateo", "Niko", "Rafael", "Thiago", "Emil", "Jonas", "Oskar", "Henrik", "Kai",
    "Ayo", "Kofi", "Moussa", "Idris", "Sekou", "Tariq", "Yusuf", "Baye", "Oumar", "Nassir",
]

LAST_NAMES = [
    "Bennett", "Carter", "Brooks", "Hamilton", "Reed", "Coleman", "Harris", "Morris", "Turner", "Hayes",
    "Jackson", "Walker", "Murray", "Porter", "Griffin", "Daniels", "Owens", "Simmons", "Lawson", "Bradley",
    "Cross", "Holland", "Ellis", "Foster", "Warren", "Banks", "Fields", "Stone", "Price", "Knight",
    "Petrovic", "Markovic", "Kovalenko", "Santos", "Mendes", "Silva", "Moretti", "Bianchi", "Novak", "Schmidt",
    "Okafor", "Diop", "Mensah", "Kamara", "Diallo", "Bamba", "Ndiaye", "Traore", "Konate", "Adebayo",
]

COLLEGES = [
    "Duke", "Kentucky", "Kansas", "North Carolina", "UCLA", "Arizona", "Michigan State", "Gonzaga",
    "Villanova", "Baylor", "Texas", "Arkansas", "Alabama", "Houston", "Connecticut", "Tennessee",
    "Overtime Elite", "G League Ignite", "Mega Basket", "Real Madrid", "Barcelona", "ASVEL", "Partizan",
    "Melbourne United", "Sydney Kings", "Auckland Academy", "Toronto Prep", "Montverde", "IMG Academy",
]

NATIONALITIES = [
    "USA", "Canada", "France", "Spain", "Serbia", "Australia", "Germany", "Brazil", "Nigeria", "Senegal",
    "Slovenia", "Lithuania", "Turkey", "Greece", "Italy", "Croatia",
]


# Wider identity-aware name pools. The old pools were intentionally small for early testing,
# which made names like "Makai Kim" appear far too often across draft classes.
# These extras create thousands of possible full-name combinations while keeping names
# loosely aligned with each prospect identity profile.
ADDITIONAL_FIRST_NAMES_BY_PROFILE = {
    "black_american_dark": [
        "Ace", "Aden", "Ahmad", "Akeem", "Alijah", "Brandon", "Cedric", "Corey", "Damian", "Davion",
        "DeAndre", "DeShawn", "Donovan", "Emanuel", "Jaden", "Jaheim", "Jamal", "Jamari", "Javon", "Jeremiah",
        "Josiah", "Keon", "Khalil", "Kyrie", "Lamar", "Marquis", "Nasir", "Omari", "Rashad", "Rayan",
        "Taj", "Talen", "Xavier", "Zaire", "Zionte", "Zyair",
    ],
    "black_american_lightskin": [
        "Aidan", "Amani", "Braylon", "Cade", "Cassius", "Cayden", "Coby", "Dalen", "Dorian", "Emoni",
        "Jace", "Jaiden", "Jayce", "Jett", "Julian", "Kaden", "Kael", "Kameron", "Kason",
        "Keegan", "Kendall", "Kylen", "Levi", "Mason", "Myles", "Nassir", "Rylan", "Sincere", "Tavian",
        "Taylen", "Trevor", "Zayden", "Zeke", "Zyon",
    ],
    "african_international": [
        "Abdou", "Abdoulaye", "Abel", "Adama", "Ade", "Ademola", "Amadou", "Bismack", "Cheikh", "Demba",
        "Ebrima", "Femi", "Hamidou", "Ibrahima", "Ismael", "Karim", "Khalifa", "Mamadou", "Mouhamed", "Nana",
        "Obinna", "Olu", "Pascal", "Rui", "Saliou", "Salif", "Samba", "Sidy", "Souleymane",
        "Tendai", "Thabo", "Usman", "Youssou", "Zubair", "Zyon",
    ],
    "white_american_european": [
        "Adam", "Anders", "Anton", "Aron", "Austin", "Bastian", "Bodhi", "Caleb", "Callum", "Cooper",
        "Dawson", "Dominik", "Elias", "Elliot", "Felix", "Finn", "Gavin", "Gregor", "Hugo", "Jack",
        "Jakob", "Kasper", "Kieran", "Liam", "Logan", "Lukas", "Magnus", "Matteo", "Max", "Milan",
        "Noah", "Nikolai", "Oliver", "Oscar", "Theo", "Viktor", "Wyatt",
    ],
    "latino": [
        "Adrian", "Alejandro", "Andres", "Angel", "Bruno", "Carlos", "Cristian", "Dario", "Eduardo", "Emilio",
        "Enzo", "Esteban", "Felipe", "Francisco", "Gabriel", "Hector", "Hugo", "Javier", "Joaquin", "Jose",
        "Juan", "Julian", "Luis", "Manuel", "Matias", "Miguel", "Pablo", "Pedro", "Raul", "Renato",
        "Rodrigo", "Sergio", "Tomas", "Valentin", "Victor", "Xavi",
    ],
    "mixed_blasian": [
        "Akari", "Andre", "Arin", "Cameron", "Dante", "Dax", "Emery", "Enzo", "Hiro", "Jace",
        "Jaden", "Jai", "Jaxon", "Jin", "Jiro", "Kairo", "Kasen", "Kian", "Koa", "Kylan",
        "Leandro", "Luca", "Makaius", "Malachi", "Milo", "Niko", "Rai", "Rakai", "Ren", "Rio",
        "Rohan", "Sage", "Taj", "Tao", "Zane", "Zen",
    ],
    "east_asian": [
        "Akio", "Ari", "Daichi", "Daisuke", "Eiji", "Hiroki", "Hyun", "Issei", "Itsuki", "Jae",
        "Jiho", "Joon", "Jun", "Kazuki", "Kei", "Kenta", "Kian", "Kaito", "Minho", "Minseok",
        "Ren", "Riku", "Ryota", "Seojun", "Shin", "Shota", "Sora", "Taiga", "Takumi", "Taro",
        "Tatsu", "Tomo", "Yuki", "Yuma", "Yusei", "Zen",
    ],
}

ADDITIONAL_LAST_NAMES_BY_PROFILE = {
    "black_american_dark": [
        "Alexander", "Anderson", "Bates", "Bell", "Booker", "Bridges", "Brown", "Butler", "Clark", "Cook",
        "Cooper", "Davis", "Douglas", "Edwards", "Evans", "Freeman", "Green", "Hardy", "Henderson", "Hill",
        "Howard", "Jefferson", "Johnson", "Jones", "King", "Lewis", "Marshall", "Mitchell", "Nelson", "Parker",
        "Perry", "Powell", "Robinson", "Scott", "Stewart", "Thomas", "Washington", "Williams", "Young",
    ],
    "black_american_lightskin": [
        "Adams", "Allen", "Bailey", "Barrett", "Bishop", "Bryant", "Burton", "Chandler", "Crawford", "Dawson",
        "Fleming", "Fox", "Gaines", "Garland", "Gray", "Hampton", "Hawkins", "Hunter", "Irving",
        "Jordan", "Lane", "Maxwell", "McBride", "Miles", "Monroe", "Payton", "Pierce", "Rivers", "Russell",
        "Sanders", "Sharp", "Tate", "Wade", "Wallace", "West", "Wheeler",
    ],
    "african_international": [
        "Abebe", "Afolayan", "Agbaji", "Ajayi", "Akpan", "Bassey", "Camara", "Cisse", "Dieng", "Doumbia",
        "Eze", "Faye", "Gueye", "Keita", "Kouyate", "Mbaye", "Mbeki", "N'Dour", "Ngom", "Okeke",
        "Okoro", "Olawale", "Omotayo", "Sane", "Sanogo", "Senghor", "Sy", "Toure", "Udoka",
        "Umeh", "Yeboah", "Yoro", "Zongo", "Zuma",
    ],
    "white_american_european": [
        "Andersen", "Armstrong", "Baker", "Berg", "Black", "Boucher", "Carlsen", "Cohen", "Dixon", "Elliott",
        "Eriksen", "Fischer", "Gallagher", "Gordon", "Hansen", "Hart", "Hoffman", "Holm", "Hughes", "Johansen",
        "Keller", "Klein", "Kovac", "Larsen", "Lindberg", "Lund", "Madsen", "Miller", "Murphy", "Olsen",
        "Peterson", "Reynolds", "Rossi", "Schaefer", "Smith", "Sorensen", "Thompson", "Weber", "Wright",
    ],
    "latino": [
        "Aguilar", "Almeida", "Alvarez", "Barbosa", "Campos", "Castillo", "Castro", "Costa", "Cruz", "Delgado",
        "Diaz", "Dominguez", "Fernandez", "Ferreira", "Flores", "Garcia", "Gomez", "Gonzalez", "Gutierrez", "Herrera",
        "Lopez", "Marquez", "Martinez", "Medina", "Morales", "Navarro", "Ortega", "Pereira", "Perez", "Ramirez",
        "Ramos", "Reyes", "Rivera", "Rodriguez", "Romero", "Torres", "Vargas",
    ],
    "mixed_blasian": [
        "Ahn", "Akana", "Bae", "Bennett", "Brooks", "Chambers", "Choi", "Cole", "Ellis", "Han",
        "Harris", "Hayashi", "Ho", "Hughes", "Jackson", "Jeong", "Kang", "Kato", "Kobayashi", "Kwon",
        "Lam", "Lee", "Lin", "Matsuda", "Moon", "Nakamura", "Nguyen", "Okada", "Reed", "Sato",
        "Shin", "Song", "Tan", "Taylor", "Yamamoto", "Young",
    ],
    "east_asian": [
        "Abe", "Aoki", "Bae", "Chang", "Cho", "Chung", "Fujii", "Fujimoto", "Han", "Hashimoto",
        "Hirano", "Huang", "Ito", "Jeon", "Jung", "Kang", "Kawamura", "Kim", "Kobayashi", "Kwon",
        "Lee", "Li", "Lin", "Liu", "Maeda", "Matsui", "Mori", "Nakamura", "Ng", "Oda",
        "Park", "Qian", "Saito", "Sasaki", "Seo", "Shimizu", "Wang", "Yang", "Zhao",
    ],
}


# Extra deep name pools added after the 44-face patch. These are intentionally
# profile-aware so Black/African/Latino/European/Asian prospects do not all pull
# from the same tiny first-name/last-name combinations.
MEGA_FIRST_NAMES_BY_PROFILE = {
    "black_american_dark": [
        "Aarion", "Adonis", "Alonzo", "Antoine", "Armani", "Ayden", "Blaise", "Brice", "Cairo", "Cedarius",
        "Chance", "Cortez", "Damarion", "Damari", "Dashawn", "Davonte", "Dejon", "Demar", "Denzel", "Desmond",
        "Dominique", "Dre", "Eli", "Ezekiel", "Gervin", "Hakeem", "Imani", "Jabriel", "Jacari", "Jahmir",
        "Jaire", "Jalenzo", "Jamarion", "Jamir", "Jase", "Javari", "Javonte", "Jaylin", "Jaylon", "Jerrick",
        "Kadeem", "Kamari", "Kareem", "Kasen", "Kendrick", "Kentrell", "Kevon", "Kobi", "Kordell", "Kyree",
        "LaDarius", "Lamont", "Lavon", "Malachi", "Marcellus", "Marion", "Maurice", "Mekhi", "Montrell", "Naji",
        "Nari", "Nayden", "Quade", "Quincy", "Raheem", "Rashawn", "Rayvon", "Romello", "Ronin", "Shemar",
        "Trevon", "Tyrell", "Tyshawn", "Vince", "Xzavier", "Zaiden", "Zamir", "Zaylen", "Zionel", "Zylen",
    ],
    "black_american_lightskin": [
        "Avery", "Baylor", "Benson", "Blaine", "Braden", "Braxton", "Brody", "Callen", "Cason", "Colby",
        "Colson", "Darian", "Daxen", "Daylen", "Easton", "Evan", "Gage", "Grayson", "Hayden", "Hudson",
        "Jalen", "Jayden", "Jensen", "Kairo", "Karter", "Kayden", "Keenan", "Keion", "Kellen", "Kobe",
        "Kyler", "Layton", "Lennox", "Maddox", "Marley", "Maverick", "Nico", "Paxton", "Rhett", "Roman",
        "Rowan", "Ryker", "Sage", "Skyler", "Tatum", "Teagan", "Trent", "Tristan", "Tyson", "Weston",
    ],
    "african_international": [
        "Abasi", "Abdoul", "Adisa", "Akin", "Akwasi", "Ansu", "Babacar", "Bacar", "Bamba", "Bassirou",
        "Bilal", "Birame", "Boubacar", "Chima", "Chisom", "Dikembe", "Efe", "Emeka", "Etienne", "Fousseyni",
        "Habib", "Hassan", "Idrissa", "Ikenna", "Ilyas", "Issa", "Jean-Baptiste", "Kadri", "Khaman", "Khalid",
        "Lamine", "Mahamadou", "Makhtar", "Malang", "Mansour", "Matar", "Modou", "Mor", "Moustapha", "Musa",
        "Nadir", "Nnamdi", "Oladipo", "Olumide", "Pape", "Rasheed", "Sadio", "Serigne", "Tidiane", "Yacine",
        "Yahya", "Youssouf", "Zacharie", "Zayd", "Zinedine",
    ],
    "white_american_european": [
        "Alec", "Ansel", "Archer", "Atlas", "August", "Beckett", "Bennett", "Brennan", "Briggs", "Brooks",
        "Calvin", "Camden", "Casey", "Clark", "Conrad", "Dane", "Declan", "Drew", "Eamon", "Emmett",
        "Everett", "Ezra", "Frederik", "Graham", "Greyson", "Griffin", "Hayes", "Holden", "Iver", "Jasper",
        "Kieran", "Knox", "Kyran", "Lachlan", "Lane", "Lawson", "Leif", "Lennon", "Maddox", "Malte",
        "Marco", "Matteus", "Nash", "Odin", "Otto", "Rhys", "Ronan", "Soren", "Stellan", "Sullivan",
        "Tanner", "Tobias", "Truett", "Wesley", "Zander",
    ],
    "latino": [
        "Agustin", "Alonso", "Antonio", "Benicio", "Camilo", "Cesar", "Damián", "Dante", "Emanuel", "Fabian",
        "Fausto", "Federico", "Fernando", "Gael", "Ignacio", "Isaac", "Izan", "Leandro", "Leonardo", "Lorenzo",
        "Luciano", "Marcos", "Maximiliano", "Nicolas", "Octavio", "Ramon", "Rocco", "Salvador", "Samuel", "Santiago",
        "Sebastian", "Simón", "Teo", "Tiago", "Valentino", "Vicente", "Yago", "Zacarías",
    ],
    "mixed_blasian": [
        "Aki", "Akira", "Ariya", "Bodhi", "Cai", "Cairo", "Dairo", "Duke", "Ezra", "Harlan",
        "Hendrix", "Izaiah", "Jairo", "Jalen", "Jiraiya", "Kace", "Kaiden", "Kenzo", "Khai", "Koda",
        "Koji", "Kyro", "Lakai", "Liko", "Makai", "Makoa", "Nakai", "Neo", "Niko", "Nori",
        "Raihan", "Rami", "Riku", "Rio", "Ryo", "Sakai", "Tajiri", "Tenzin", "Toshi", "Zakai",
    ],
    "east_asian": [
        "Akihiro", "Aoto", "Chen", "Daiki", "Donghyun", "Haruto", "Hayate", "Hikaru", "Hinata", "Hojun",
        "Ichiro", "Jaemin", "Jian", "Jisung", "Junho", "Kenshin", "Kosei", "Kyosuke", "Masato", "Naoki",
        "Rensuke", "Rintaro", "Ryusei", "Seiji", "Seung", "Shun", "Sungjae", "Taeyang", "Takuya", "Tian",
        "Tomoya", "Yejun", "Yong", "Yuto", "Zhiyuan",
    ],
}

MEGA_LAST_NAMES_BY_PROFILE = {
    "black_american_dark": [
        "Abbott", "Akins", "Austin", "Baldwin", "Benton", "Blair", "Boyd", "Britt", "Burns", "Caldwell",
        "Campbell", "Clay", "Cobb", "Collier", "Conley", "Curry", "Davenport", "Dawkins", "Dorsey", "Doyle",
        "Duncan", "Frazier", "Gibbs", "Goodwin", "Grant", "Hale", "Harper", "Harrison", "Hines", "Holloway",
        "Hopkins", "Ingram", "Jennings", "Joseph", "Kelley", "Kendrick", "Lambert", "Little", "Mack", "Mason",
        "Mayfield", "McCoy", "McIntyre", "Merritt", "Nance", "Neal", "Osborne", "Patterson", "Pierce", "Pope",
        "Randolph", "Reese", "Reid", "Rhodes", "Richardson", "Saunders", "Shelton", "Simms", "Thornton", "Vaughn",
        "Walton", "Ward", "Watkins", "Webster", "Welch", "Whitfield", "Wilkins", "Winston", "Woodard", "Woods",
    ],
    "black_american_lightskin": [
        "Abbott", "Archer", "Atkins", "Baxter", "Beasley", "Benson", "Bowman", "Boyle", "Briggs", "Burnett",
        "Cannon", "Carson", "Clayton", "Collins", "Conway", "Dalton", "Dennis", "Dunn", "Eaton", "Fletcher",
        "Forbes", "Francis", "Franklin", "Glover", "Greene", "Harding", "Holland", "Houston", "Kendall", "Kirkland",
        "Langston", "Lawrence", "Maddox", "Manning", "McClain", "McKinney", "Mills", "Nixon", "Page", "Parrish",
        "Preston", "Quinn", "Reeves", "Riley", "Rowe", "Shepherd", "Sutton", "Tyler", "Vance", "Watson",
    ],
    "african_international": [
        "Abdulahi", "Adekunle", "Adesanya", "Akindele", "Akinola", "Aminu", "Anigbogu", "Awolowo", "Ba", "Badji",
        "Bakayoko", "Balde", "Bengaly", "Biyombo", "Camara", "Coulibaly", "Dabo", "Diarra", "Diedhiou", "Diouf",
        "Eke", "Enyia", "Fofana", "Gomis", "Iroegbu", "Kaba", "Kamagate", "Kante", "Kebe", "Kone",
        "Makinde", "Mamadou", "Mane", "Mbacke", "Mbenga", "Mudiay", "Ndour", "Nwora", "Okafor", "Okongwu",
        "Olujobi", "Omoruyi", "Onuaku", "Samb", "Sarr", "Seck", "Sow", "Tall", "Tchamwa", "Toure",
    ],
    "white_american_european": [
        "Ackerman", "Albrecht", "Andersson", "Barker", "Beck", "Bennett", "Bishop", "Brandt", "Brenner", "Carver",
        "Christensen", "Clements", "Cole", "Dahl", "Davies", "Dempsey", "Donovan", "Doyle", "Eklund", "Farrell",
        "Finley", "Fleming", "Forster", "Frost", "Gibson", "Graves", "Harrington", "Hawthorne", "Heath", "Hendrix",
        "Holt", "Kessler", "Kirby", "Klausen", "Kramer", "Larkin", "Magnusson", "Meyer", "Nielsen", "O'Connor",
        "Parker", "Pearson", "Porter", "Quinn", "Rasmussen", "Reilly", "Richter", "Rourke", "Schneider", "Slater",
        "Sloan", "Stevens", "Sweeney", "Vaughan", "Vogel", "Walsh", "Warner", "Westbrook", "Whitaker", "Zimmerman",
    ],
    "latino": [
        "Acosta", "Aguirre", "Araya", "Bautista", "Benitez", "Bravo", "Cabrera", "Calderon", "Cardenas", "Carrillo",
        "Cervantes", "Chavez", "Contreras", "Cordero", "Correa", "Espinoza", "Figueroa", "Fuentes", "Galindo", "Gallardo",
        "Guerrero", "Ibanez", "Jimenez", "Lara", "Lima", "Luna", "Machado", "Mendoza", "Molina", "Montero",
        "Nieves", "Nunez", "Palacios", "Paredes", "Pineda", "Quintero", "Rangel", "Rivas", "Rosales", "Salazar",
        "Sanchez", "Serrano", "Soto", "Suarez", "Valdez", "Vega", "Velasquez", "Villalobos", "Zamora",
    ],
    "mixed_blasian": [
        "Akita", "Amano", "Bautista", "Cabrera", "Chen", "Dela Cruz", "Fujita", "Hamada", "Henderson", "Higa",
        "Hoshino", "Ishikawa", "Jang", "Kagawa", "Kaneko", "Kawasaki", "Kita", "Kumagai", "Le", "Liang",
        "Lim", "Ma", "Miyamoto", "Morioka", "Nishida", "Ocampo", "Ogawa", "Ono", "Park", "Pham",
        "Qiu", "Reyes", "Sugimoto", "Takahashi", "Tam", "Tran", "Tsai", "Ueda", "Villanueva", "Yoon",
    ],
    "east_asian": [
        "Ando", "Chiba", "Deng", "Endo", "Fan", "Fujiwara", "Guo", "Hasegawa", "Hayashi", "Hong",
        "Hoshino", "Inoue", "Ishida", "Ishikawa", "Jang", "Jiang", "Kagawa", "Kawaguchi", "Kawasaki", "Kita",
        "Kuroda", "Lim", "Luo", "Miyamoto", "Nakajima", "Nishimura", "Ogawa", "Ono", "Qi", "Shen",
        "Son", "Sugimoto", "Sun", "Takahashi", "Takeda", "Tamura", "Tang", "Tsai", "Ueda", "Wu",
        "Xu", "Yamada", "Yamashita", "Yoon", "Yu", "Zhou",
    ],
}

OVERUSED_FULL_NAMES = {
    "Lamar Thomas",
    "Bryce Bennett",
}


def _unique_text_list(values: List[str]) -> List[str]:
    out: List[str] = []
    seen = set()
    for value in values or []:
        text = str(value or "").strip()
        key = text.lower()
        if not text or key in seen:
            continue
        seen.add(key)
        out.append(text)
    return out


IDENTITY_PROFILES = [
    {
        "key": "black_american_dark",
        "ethnicityGroup": "black",
        "subgroup": "african_american",
        "skinTone": "dark",
        "region": "usa",
        "nationalityWeights": [("USA", 0.86), ("Canada", 0.10), ("France", 0.04)],
        "collegeWeights": [("college", 0.78), ("prep", 0.12), ("g_league", 0.10)],
        "weight": 0.30,
        "portraitRange": (1, 30),
        "firstNames": [
            "Jalen", "Jaylen", "Malik", "Darius", "Trey", "Isaiah", "Cam", "Amari", "Makai", "Jabari",
            "Terrence", "Micah", "Damon", "Kobe", "Tyrese", "Devin", "Andre", "Elijah", "Zion", "Quentin",
        ],
        "lastNames": [
            "Carter", "Brooks", "Harris", "Jackson", "Walker", "Murray", "Porter", "Daniels", "Owens", "Simmons",
            "Lawson", "Bradley", "Ellis", "Foster", "Warren", "Banks", "Fields", "Knight", "Reed", "Coleman",
        ],
    },
    {
        "key": "black_american_lightskin",
        "ethnicityGroup": "black",
        "subgroup": "african_american",
        "skinTone": "light_brown",
        "region": "usa",
        "nationalityWeights": [("USA", 0.82), ("Canada", 0.14), ("France", 0.04)],
        "collegeWeights": [("college", 0.76), ("prep", 0.14), ("g_league", 0.10)],
        "weight": 0.15,
        "portraitRange": (31, 45),
        "firstNames": [
            "Jaylen", "Tyrese", "Bryce", "Carter", "Cam", "Nolan", "Miles", "Jordan", "Kellan", "Ashton",
            "Devin", "Trey", "Isaiah", "Landon", "Jalen", "Micah", "Makai", "Amari",
        ],
        "lastNames": [
            "Bennett", "Carter", "Brooks", "Hamilton", "Reed", "Morris", "Turner", "Hayes", "Murray", "Porter",
            "Griffin", "Daniels", "Lawson", "Cross", "Holland", "Ellis", "Stone", "Price", "Knight",
        ],
    },
    {
        "key": "african_international",
        "ethnicityGroup": "black",
        "subgroup": "african",
        "skinTone": "dark",
        "region": "international",
        "nationalityWeights": [("Nigeria", 0.30), ("Senegal", 0.28), ("France", 0.14), ("Canada", 0.08), ("Greece", 0.06), ("Turkey", 0.04), ("USA", 0.10)],
        "collegeWeights": [("international", 0.45), ("college", 0.35), ("g_league", 0.12), ("prep", 0.08)],
        "weight": 0.10,
        "portraitRange": (46, 55),
        "firstNames": [
            "Ayo", "Kofi", "Moussa", "Idris", "Sekou", "Yusuf", "Baye", "Oumar", "Nassir", "Amadou",
            "Boubacar", "Chinedu", "Tariq", "Ibrahim", "Malick", "Demba",
        ],
        "lastNames": [
            "Okafor", "Diop", "Mensah", "Kamara", "Diallo", "Bamba", "Ndiaye", "Traore", "Konate", "Adebayo",
            "Nwosu", "Coulibaly", "Fall", "Sarr", "Balogun", "Onyeka",
        ],
    },
    {
        "key": "white_american_european",
        "ethnicityGroup": "white",
        "subgroup": "american_european",
        "skinTone": "light",
        "region": "usa_or_europe",
        "nationalityWeights": [("USA", 0.46), ("Canada", 0.10), ("Serbia", 0.10), ("Croatia", 0.08), ("Germany", 0.08), ("Spain", 0.06), ("France", 0.06), ("Australia", 0.06)],
        "collegeWeights": [("college", 0.48), ("international", 0.36), ("prep", 0.08), ("g_league", 0.08)],
        "weight": 0.20,
        "portraitRange": (56, 75),
        "firstNames": [
            "Nolan", "Cole", "Carter", "Bryce", "Landon", "Luca", "Mateo", "Niko", "Emil", "Jonas",
            "Oskar", "Henrik", "Kai", "Tomas", "Aleksa", "Ivan", "Luka", "Mason", "Blake", "Luke",
        ],
        "lastNames": [
            "Bennett", "Hayes", "Foster", "Stone", "Knight", "Petrovic", "Markovic", "Kovalenko", "Moretti", "Bianchi",
            "Novak", "Schmidt", "Jovic", "Vukic", "Collins", "Walker", "Turner", "Price",
        ],
    },
    {
        "key": "latino",
        "ethnicityGroup": "latino",
        "subgroup": "latino_mixed",
        "skinTone": "medium",
        "region": "americas",
        "nationalityWeights": [("Brazil", 0.34), ("Spain", 0.18), ("USA", 0.18), ("Canada", 0.06), ("France", 0.06), ("Australia", 0.04), ("Italy", 0.14)],
        "collegeWeights": [("college", 0.46), ("international", 0.38), ("prep", 0.08), ("g_league", 0.08)],
        "weight": 0.07,
        "portraitRange": (76, 82),
        "firstNames": ["Mateo", "Rafael", "Thiago", "Luca", "Dante", "Marco", "Nico", "Santi", "Diego", "Leo"],
        "lastNames": ["Santos", "Mendes", "Silva", "Moretti", "Bianchi", "Alvarez", "Reyes", "Costa", "Ferreira", "Marquez"],
    },
    {
        "key": "mixed_blasian",
        "ethnicityGroup": "mixed",
        "subgroup": "blasian",
        "skinTone": "medium_brown",
        "region": "usa_or_canada",
        "nationalityWeights": [("USA", 0.70), ("Canada", 0.16), ("Australia", 0.06), ("France", 0.04), ("Japan", 0.02), ("Korea", 0.02)],
        "collegeWeights": [("college", 0.70), ("prep", 0.14), ("g_league", 0.10), ("international", 0.06)],
        "weight": 0.10,
        "portraitRange": (83, 92),
        "firstNames": ["Kai", "Jalen", "Jaylen", "Micah", "Cameron", "Trey", "Kobe", "Makai", "Jordan", "Miles"],
        "lastNames": ["Lee", "Kim", "Chen", "Brooks", "Carter", "Ellis", "Hayes", "Murray", "Banks", "Stone"],
    },
    {
        "key": "east_asian",
        "ethnicityGroup": "asian",
        "subgroup": "east_asian",
        "skinTone": "light_medium",
        "region": "international_or_us",
        "nationalityWeights": [("USA", 0.30), ("Canada", 0.16), ("Australia", 0.12), ("Japan", 0.14), ("Korea", 0.14), ("France", 0.06), ("Germany", 0.04), ("Spain", 0.04)],
        "collegeWeights": [("college", 0.46), ("international", 0.34), ("prep", 0.12), ("g_league", 0.08)],
        "weight": 0.08,
        "portraitRange": (93, 100),
        "firstNames": ["Kai", "Kenji", "Yuto", "Minjun", "Jin", "Leo", "Ethan", "Noah", "Ryan", "Haru"],
        "lastNames": ["Lee", "Kim", "Park", "Chen", "Zhang", "Watanabe", "Tanaka", "Choi", "Lin", "Kang"],
    },
]

COLLEGE_GROUPS = {
    "college": [
        "Duke", "Kentucky", "Kansas", "North Carolina", "UCLA", "Arizona", "Michigan State", "Gonzaga",
        "Villanova", "Baylor", "Texas", "Arkansas", "Alabama", "Houston", "Connecticut", "Tennessee",
    ],
    "prep": ["Toronto Prep", "Montverde", "IMG Academy", "Auckland Academy"],
    "g_league": ["G League Ignite", "Overtime Elite"],
    "international": ["Mega Basket", "Real Madrid", "Barcelona", "ASVEL", "Partizan", "Melbourne United", "Sydney Kings"],
}

# Phase 1 convention for the 100-face pack:
# 0001-0030 black_american_dark, 0031-0045 black_american_lightskin,
# 0046-0055 african_international, 0056-0075 white_american_european,
# 0076-0082 latino, 0083-0092 mixed_blasian, 0093-0100 east_asian.
# If you generate the image pack differently, update these portraitRange values.

CLASS_TYPES = [
    "weak",
    "normal",
    "deep",
    "star_heavy",
    "generational",
    "defensive_class",
    "guard_heavy",
    "big_man_heavy",
]

# Rating model guardrails for autogenerated classes.
# These values intentionally mirror the stronger custom 2026 draft-class baseline:
# smooth rank curve, no 60 OVR rookies, and a rare absolute peak around 82 OVR / 98 POT.
DRAFT_RATING_MODEL_VERSION = "histogram_personality_100_player_v3"
MIN_GENERATED_DRAFT_OVR = 66
MAX_GENERATED_DRAFT_OVR = 82
MAX_GENERATED_DRAFT_POTENTIAL = 98
DRAFT_CLASS_FIXED_COUNT = 100

ROOKIE_FACE_BASE_URL = "/assets/rookie_faces"
ROOKIE_FACE_COUNT = 100

# Active verified portrait pool.
# The actual usable face count is len(SAFE_ROOKIE_FACE_IDS). File numbers are sparse
# because older/manual packs used reserved ranges. The generator should only assign IDs
# from SAFE_ROOKIE_FACE_IDS_BY_PROFILE, not from a continuous 0001-N range.
SAFE_ROOKIE_FACE_IDS_BY_PROFILE = {
    "black_american_dark": [
        "rookie_face_0003", "rookie_face_0004", "rookie_face_0005", "rookie_face_0006",
        "rookie_face_0106", "rookie_face_0107", "rookie_face_0109",
        "rookie_face_0121", "rookie_face_0122", "rookie_face_0123",
        "rookie_face_0130", "rookie_face_0131",
    ],
    "black_american_lightskin": [
        "rookie_face_0033", "rookie_face_0035", "rookie_face_0108", "rookie_face_0112",
        "rookie_face_0124", "rookie_face_0132",
    ],
    "african_international": [
        "rookie_face_0047", "rookie_face_0048", "rookie_face_0110",
        "rookie_face_0121", "rookie_face_0122", "rookie_face_0123", "rookie_face_0125",
        "rookie_face_0134",
    ],
    "white_american_european": [
        "rookie_face_0059", "rookie_face_0060", "rookie_face_0061", "rookie_face_0062",
        "rookie_face_0063", "rookie_face_0064", "rookie_face_0111", "rookie_face_0113",
        "rookie_face_0127", "rookie_face_0128", "rookie_face_0133",
    ],
    "latino": [
        "rookie_face_0034", "rookie_face_0036", "rookie_face_0126", "rookie_face_0129",
    ],
    "mixed_blasian": [
        "rookie_face_0084", "rookie_face_0085",
    ],
    "east_asian": [
        "rookie_face_0094", "rookie_face_0095", "rookie_face_0114", "rookie_face_0115",
    ],
}

SAFE_ROOKIE_FACE_IDS = []
for _safe_face_group in SAFE_ROOKIE_FACE_IDS_BY_PROFILE.values():
    for _safe_face_id in _safe_face_group:
        if _safe_face_id not in SAFE_ROOKIE_FACE_IDS:
            SAFE_ROOKIE_FACE_IDS.append(_safe_face_id)

POSITION_WEIGHTS = {
    "normal": [("PG", 0.18), ("SG", 0.22), ("SF", 0.22), ("PF", 0.20), ("C", 0.18)],
    "guard_heavy": [("PG", 0.26), ("SG", 0.28), ("SF", 0.20), ("PF", 0.15), ("C", 0.11)],
    "big_man_heavy": [("PG", 0.14), ("SG", 0.16), ("SF", 0.20), ("PF", 0.25), ("C", 0.25)],
}

SECONDARY_BY_POS = {
    "PG": ["SG", ""],
    "SG": ["PG", "SF", ""],
    "SF": ["SG", "PF", ""],
    "PF": ["SF", "C", ""],
    "C": ["PF", ""],
}

HEIGHT_RANGES = {
    "PG": (72, 77),
    "SG": (75, 80),
    "SF": (78, 82),
    "PF": (80, 84),
    "C": (82, 88),
}

WEIGHT_RANGES = {
    "PG": (175, 205),
    "SG": (185, 220),
    "SF": (200, 235),
    "PF": (215, 255),
    "C": (235, 285),
}

ARCHETYPES_BY_POS = {
    "PG": [
        "Floor General", "Shot-Creating Guard", "Two-Way Playmaker", "Speedy Slasher", "Pull-Up Shooter",
    ],
    "SG": [
        "Three-Level Scorer", "Movement Shooter", "Two-Way Wing", "Athletic Slasher", "Combo Guard",
    ],
    "SF": [
        "Two-Way Wing", "Point Forward", "Scoring Wing", "3-and-D Forward", "Athletic Finisher",
    ],
    "PF": [
        "Stretch Four", "Defensive Forward", "Interior Finisher", "Face-Up Forward", "Glass Cleaner",
    ],
    "C": [
        "Rim Protector", "Post Scorer", "Stretch Big", "Rebounding Big", "Playmaking Center",
    ],
}

# Attribute order used by the current game UI:
# 0 3PT, 1 MID, 2 CLOSE, 3 FT, 4 BALL, 5 PASS, 6 SPEED, 7 ATH,
# 8 PER D, 9 INS D, 10 BLK, 11 STL, 12 REB, 13 OIQ, 14 DIQ
ARCHETYPE_BIASES = {
    "Floor General":       [0, 2, -1, 3, 9, 10, 4, 1, 1, -8, -9, 2, -7, 7, 3],
    "Shot-Creating Guard": [6, 8, 3, 5, 8, 3, 5, 3, -1, -8, -9, 1, -7, 6, 0],
    "Two-Way Playmaker":   [2, 3, 1, 2, 7, 8, 5, 5, 7, -3, -4, 7, -3, 5, 6],
    "Speedy Slasher":      [-2, 1, 8, 1, 6, 2, 9, 9, 2, -5, -6, 3, -4, 3, 1],
    "Pull-Up Shooter":     [9, 8, 0, 4, 5, 2, 3, 0, -1, -8, -9, 0, -7, 5, 0],
    "Three-Level Scorer":  [7, 8, 6, 4, 5, 1, 3, 4, -1, -6, -7, 0, -5, 6, 0],
    "Movement Shooter":    [10, 5, -2, 5, 2, 0, 4, 1, 0, -7, -8, 1, -7, 5, 1],
    "Two-Way Wing":        [4, 2, 3, 2, 2, 1, 5, 6, 9, 3, 1, 8, 2, 4, 7],
    "Athletic Slasher":    [-1, 0, 9, 0, 4, 0, 8, 10, 3, 0, 1, 3, 2, 2, 1],
    "Combo Guard":         [5, 5, 3, 4, 7, 5, 5, 2, 1, -7, -8, 2, -6, 5, 1],
    "Point Forward":       [2, 3, 5, 2, 7, 9, 2, 5, 3, 3, 0, 3, 4, 7, 4],
    "Scoring Wing":        [6, 6, 6, 3, 4, 1, 3, 5, 0, -2, -2, 1, 0, 6, 0],
    "3-and-D Forward":     [8, 2, 0, 3, 0, -1, 3, 3, 10, 4, 2, 9, 2, 3, 8],
    "Athletic Finisher":   [-3, -1, 10, -1, 1, -1, 6, 10, 3, 4, 4, 2, 5, 2, 3],
    "Stretch Four":        [8, 5, 3, 3, -1, 1, -1, 2, 2, 5, 3, 1, 5, 5, 4],
    "Defensive Forward":   [-2, -1, 3, 0, -1, 0, 3, 7, 8, 8, 7, 6, 8, 1, 9],
    "Interior Finisher":   [-7, -2, 10, -2, -4, -2, -2, 7, -1, 8, 7, -1, 8, 3, 4],
    "Face-Up Forward":     [4, 6, 6, 3, 3, 3, 1, 4, 1, 5, 3, 1, 5, 6, 3],
    "Glass Cleaner":       [-7, -3, 6, -2, -5, -3, -3, 7, -2, 9, 8, -1, 11, 1, 5],
    "Rim Protector":       [-10, -5, 6, -4, -7, -3, -4, 6, -3, 10, 12, -2, 9, 0, 8],
    "Post Scorer":         [-9, 2, 11, -1, -5, 0, -5, 4, -4, 8, 5, -4, 7, 5, 2],
    "Stretch Big":         [9, 5, 4, 3, -3, 2, -4, 1, -2, 6, 5, -2, 6, 6, 4],
    "Rebounding Big":      [-10, -4, 7, -3, -7, -4, -5, 6, -3, 9, 9, -3, 12, 1, 6],
    "Playmaking Center":   [2, 3, 7, 1, 1, 8, -3, 3, -1, 6, 6, -2, 8, 8, 4],
}


def _plain(value: Any) -> Any:
    if value is None:
        return None
    if isinstance(value, dict):
        return {str(k): _plain(v) for k, v in value.items()}
    if isinstance(value, list):
        return [_plain(v) for v in value]
    if isinstance(value, tuple):
        return [_plain(v) for v in value]
    try:
        if hasattr(value, "to_py"):
            return _plain(value.to_py())
    except Exception:
        pass
    return value


def _safe_int(value: Any, default: int = 0) -> int:
    try:
        if value is None:
            return default
        return int(float(value))
    except Exception:
        return default


def _stable_seed(*parts: Any) -> int:
    text = "|".join(str(part) for part in parts)
    total = 0
    for i, ch in enumerate(text):
        total = (total + (i + 1) * ord(ch)) % 2_147_483_647
    return total or 20260527


def _fresh_generation_seed(*parts: Any) -> int:
    """Create a new unpredictable seed when the caller does not provide one.

    The old generator used only season_year as the fallback seed, which made
    every auto-generated 2026 class identical across new leagues/tests. This
    keeps seeded calls reproducible, but makes unseeded auto classes fresh.
    """
    try:
        entropy = random.SystemRandom().randint(1, 2_147_483_646)
    except Exception:
        entropy = random.randint(1, 2_147_483_646)

    try:
        clock = time.time_ns()
    except Exception:
        clock = int(time.time() * 1_000_000)

    return _stable_seed("fresh_draft_class", *parts, clock, entropy)


def _clamp(value: float, lo: int, hi: int) -> int:
    return int(max(lo, min(hi, round(value))))


def _weighted_choice(rng: random.Random, weighted: List[Tuple[str, float]]) -> str:
    total = sum(weight for _, weight in weighted)
    ticket = rng.random() * total
    running = 0.0
    for item, weight in weighted:
        running += weight
        if ticket <= running:
            return item
    return weighted[-1][0]

# Source-of-truth overall calculator used by progression and draft conversion.
# Keep this aligned with progression.py / draft_logic.py so generated prospects
# do not enter the league with hidden higher overalls than their displayed OVR.
OVERALL_POS_PARAMS = {
    "PG": {
        "weights": [0.11, 0.05, 0.03, 0.05, 0.17, 0.17, 0.10, 0.07, 0.10, 0.02, 0.01, 0.07, 0.05, 0.01, 0.01],
        "prim": [5, 6, 1, 7],
        "alpha": 0.25,
    },
    "SG": {
        "weights": [0.15, 0.08, 0.05, 0.05, 0.12, 0.07, 0.11, 0.07, 0.11, 0.03, 0.02, 0.08, 0.06, 0.01, 0.01],
        "prim": [1, 5, 7],
        "alpha": 0.28,
    },
    "SF": {
        "weights": [0.12, 0.09, 0.07, 0.04, 0.08, 0.07, 0.10, 0.10, 0.10, 0.06, 0.04, 0.08, 0.05, 0.01, 0.01],
        "prim": [1, 8, 9],
        "alpha": 0.22,
    },
    "PF": {
        "weights": [0.07, 0.07, 0.12, 0.03, 0.05, 0.05, 0.08, 0.12, 0.07, 0.13, 0.08, 0.08, 0.05, 0.01, 0.01],
        "prim": [3, 10, 8],
        "alpha": 0.24,
    },
    "C": {
        "weights": [0.04, 0.06, 0.17, 0.03, 0.02, 0.04, 0.07, 0.12, 0.05, 0.16, 0.13, 0.06, 0.08, 0.01, 0.01],
        "prim": [3, 10, 11, 13],
        "alpha": 0.30,
    },
}


def _normalize_attrs_for_overall(attrs: Any, default: int = 75) -> List[int]:
    out: List[int] = []
    if isinstance(attrs, list):
        for value in attrs[:15]:
            out.append(_clamp(_safe_int(value, default), 25, 99))

    while len(out) < 15:
        out.append(default)

    return out


def _calc_overall_from_attrs(attrs: List[int], pos: str) -> int:
    p = OVERALL_POS_PARAMS.get(str(pos or "SF").upper(), OVERALL_POS_PARAMS["SF"])
    safe_attrs = _normalize_attrs_for_overall(attrs)

    weighted = sum(float(w) * float(safe_attrs[i]) for i, w in enumerate(p["weights"]))
    primary_indices = [max(0, int(i) - 1) for i in p["prim"]]
    peak = max(float(safe_attrs[i]) for i in primary_indices)

    blended = float(p["alpha"]) * peak + (1.0 - float(p["alpha"])) * weighted
    overall = round(min(99, max(60, 60 + 39 * (1 / (1 + math.exp(-0.12 * (blended - 77)))))))

    num_90 = len([a for a in safe_attrs if a >= 90])
    if num_90 >= 3:
        overall = min(99, overall + (num_90 - 2))

    return int(overall)


def _overall_impact_order(pos: str, rng: random.Random, direction: int, attrs: List[int]) -> List[int]:
    p = OVERALL_POS_PARAMS.get(str(pos or "SF").upper(), OVERALL_POS_PARAMS["SF"])
    primary_indices = {max(0, int(i) - 1) for i in p["prim"]}
    scored: List[Tuple[float, int]] = []

    for idx, weight in enumerate(p["weights"]):
        impact = float(weight) + (0.08 if idx in primary_indices else 0.0)
        if direction < 0:
            impact += max(0.0, (attrs[idx] - 70) / 150.0)
        else:
            impact += max(0.0, (80 - attrs[idx]) / 180.0)
        impact += rng.random() * 0.01
        scored.append((impact, idx))

    scored.sort(reverse = True)
    return [idx for _, idx in scored]


def _calibrate_attrs_to_source_overall(
    attrs: List[int],
    pos: str,
    target_overall: int,
    rng: random.Random,
) -> List[int]:
    # The source formula cannot represent OVR below 60, so generated prospects
    # should not pretend to be 55-59 and then jump when progression recalculates.
    target = int(_clamp(target_overall, 60, 99))
    current_attrs = _normalize_attrs_for_overall(attrs)

    best_attrs = list(current_attrs)
    best_dist = abs(_calc_overall_from_attrs(best_attrs, pos) - target)

    for _ in range(900):
        current = _calc_overall_from_attrs(current_attrs, pos)
        current_dist = abs(current - target)

        if current_dist < best_dist:
            best_attrs = list(current_attrs)
            best_dist = current_dist

        if current == target:
            return current_attrs

        direction = 1 if current < target else -1
        candidates = [
            idx
            for idx in _overall_impact_order(pos, rng, direction, current_attrs)
            if (direction > 0 and current_attrs[idx] < 99) or (direction < 0 and current_attrs[idx] > 25)
        ]

        if not candidates:
            break

        chosen_attrs: Optional[List[int]] = None
        chosen_dist = 999
        chosen_overshoots = True

        for idx in candidates:
            trial = list(current_attrs)
            trial[idx] = int(_clamp(trial[idx] + direction, 25, 99))
            trial_overall = _calc_overall_from_attrs(trial, pos)
            trial_dist = abs(trial_overall - target)
            overshoots = (direction > 0 and trial_overall > target) or (direction < 0 and trial_overall < target)

            if trial_dist < chosen_dist or (
                trial_dist == chosen_dist and chosen_overshoots and not overshoots
            ):
                chosen_attrs = trial
                chosen_dist = trial_dist
                chosen_overshoots = overshoots

        if chosen_attrs is None:
            break

        # Allow flat steps because the sigmoid formula often needs several
        # one-point attribute moves before OVR changes by one.
        if chosen_dist > current_dist and current_dist <= best_dist and current_dist <= 1:
            break

        current_attrs = chosen_attrs

    return best_attrs



def _linear_anchor_value(rank: int, anchors: List[Tuple[int, float]]) -> float:
    safe_rank = max(1, _safe_int(rank, 1))
    ordered = sorted((int(r), float(v)) for r, v in anchors)

    if safe_rank <= ordered[0][0]:
        return ordered[0][1]

    for (left_rank, left_value), (right_rank, right_value) in zip(ordered, ordered[1:]):
        if safe_rank <= right_rank:
            span = max(1, right_rank - left_rank)
            t = (safe_rank - left_rank) / span
            return left_value + (right_value - left_value) * t

    return ordered[-1][1]


DRAFT_OVR_CURVES = {
    # Typical good class shape: top player around 80, top 5 strong, bottom never useless.
    "normal": [
        (1, 80.0), (2, 79.0), (3, 78.2), (5, 77.0), (8, 75.6),
        (14, 74.0), (30, 71.5), (45, 70.0), (60, 68.5), (100, 66.6), (110, 66.0),
    ],
    # Weak means less star power, not 60 OVR prospects.
    "weak": [
        (1, 78.7), (2, 77.8), (3, 77.0), (5, 75.8), (8, 74.2),
        (14, 72.9), (30, 70.2), (45, 68.8), (60, 67.2), (100, 66.0), (110, 66.0),
    ],
    # Deep classes keep the top sane but carry more useful players through the second round.
    "deep": [
        (1, 79.8), (2, 79.0), (3, 78.3), (5, 77.2), (8, 75.9),
        (14, 74.7), (30, 72.8), (45, 71.5), (60, 70.0), (100, 67.2), (110, 66.5),
    ],
    # Top-heavy classes make the top scarier while leaving the depth closer to normal/weak.
    "star_heavy": [
        (1, 80.8), (2, 79.8), (3, 78.9), (5, 77.6), (8, 75.7),
        (14, 73.9), (30, 71.3), (45, 69.8), (60, 68.0), (100, 66.4), (110, 66.0),
    ],
    # Generational classes are the only normal path to the rare 82 OVR / 98 POT outcome.
    "generational": [
        (1, 81.4), (2, 79.7), (3, 78.7), (5, 77.2), (8, 75.7),
        (14, 73.9), (30, 71.3), (45, 69.8), (60, 68.0), (100, 66.4), (110, 66.0),
    ],
    "defensive_class": [
        (1, 79.8), (2, 79.0), (3, 78.2), (5, 77.0), (8, 75.5),
        (14, 74.0), (30, 71.5), (45, 70.0), (60, 68.6), (100, 66.6), (110, 66.0),
    ],
    "guard_heavy": [
        (1, 79.8), (2, 79.0), (3, 78.2), (5, 77.0), (8, 75.5),
        (14, 74.0), (30, 71.5), (45, 70.0), (60, 68.5), (100, 66.6), (110, 66.0),
    ],
    "big_man_heavy": [
        (1, 79.8), (2, 79.0), (3, 78.2), (5, 77.0), (8, 75.5),
        (14, 74.0), (30, 71.5), (45, 70.0), (60, 68.5), (100, 66.6), (110, 66.0),
    ],
}

DRAFT_POT_GAP_CURVES = {
    "normal": [(1, 15.0), (5, 14.0), (10, 13.0), (30, 12.0), (60, 10.5), (100, 8.5), (110, 8.0)],
    "weak": [(1, 13.5), (5, 12.5), (10, 11.5), (30, 10.5), (60, 9.0), (100, 7.5), (110, 7.0)],
    "deep": [(1, 14.2), (5, 13.8), (10, 13.2), (30, 12.6), (60, 11.2), (100, 9.0), (110, 8.5)],
    "star_heavy": [(1, 16.0), (5, 15.0), (10, 12.8), (30, 11.2), (60, 10.0), (100, 8.0), (110, 7.5)],
    "generational": [(1, 16.6), (5, 14.6), (10, 12.8), (30, 11.2), (60, 10.0), (100, 8.0), (110, 7.5)],
    "defensive_class": [(1, 14.6), (5, 13.8), (10, 12.8), (30, 11.8), (60, 10.3), (100, 8.5), (110, 8.0)],
    "guard_heavy": [(1, 14.8), (5, 13.8), (10, 12.8), (30, 11.8), (60, 10.3), (100, 8.5), (110, 8.0)],
    "big_man_heavy": [(1, 14.8), (5, 13.8), (10, 12.8), (30, 11.8), (60, 10.3), (100, 8.5), (110, 8.0)],
}


# Final OVR distribution guardrails.
# v11 is histogram-first: the generator decides the full 100-player OVR shape
# before individual prospects are built. This keeps every draft league-safe while
# still letting the class feel top-heavy, deep, thin, weak, or generational.
DRAFT_OVR_COUNT_TEMPLATES: Dict[str, Dict[int, int]] = {
    # Balanced 100-player class, close to the custom 2026 baseline shape:
    # one 80, normal mid-tier, and a real 66 OVR bottom bucket.
    "normal": {
        80: 1, 79: 1, 78: 2, 77: 2, 76: 3, 75: 4, 74: 5, 73: 6,
        72: 8, 71: 10, 70: 12, 69: 13, 68: 14, 67: 9, 66: 10,
    },
    # Rare bad class: best player is 79, but the bottom still looks like real NBA
    # undrafted/free-agent depth instead of unusable 60 OVR players.
    "weak": {
        79: 1, 78: 1, 77: 2, 76: 2, 75: 3, 74: 4, 73: 5, 72: 7,
        71: 10, 70: 13, 69: 14, 68: 15, 67: 11, 66: 12,
    },
    # Deep class: top is sane, but the 70-75 area is stronger and the 66-68 tail
    # shrinks a bit without disappearing.
    "deep": {
        80: 1, 79: 1, 78: 2, 77: 2, 76: 4, 75: 5, 74: 7, 73: 8,
        72: 10, 71: 12, 70: 14, 69: 12, 68: 9, 67: 6, 66: 7,
    },
    # Top-heavy class: best player is 81, top is better, middle is thinner, and
    # the bottom remains normal/average rather than being dragged up.
    "star_heavy": {
        81: 1, 80: 1, 79: 2, 78: 2, 77: 3, 76: 3, 75: 3, 74: 4,
        73: 5, 72: 7, 71: 9, 70: 11, 69: 13, 68: 14, 67: 10, 66: 12,
    },
    # Rare great class: best player is 82. This can also create another high-end
    # prospect depending on the distribution personality, but never floods the league.
    "generational": {
        82: 1, 80: 1, 79: 2, 78: 2, 77: 3, 76: 3, 75: 3, 74: 4,
        73: 5, 72: 7, 71: 9, 70: 11, 69: 13, 68: 14, 67: 10, 66: 12,
    },
    "defensive_class": {
        80: 1, 79: 1, 78: 2, 77: 2, 76: 3, 75: 4, 74: 5, 73: 6,
        72: 8, 71: 10, 70: 12, 69: 13, 68: 14, 67: 9, 66: 10,
    },
    "guard_heavy": {
        80: 1, 79: 1, 78: 2, 77: 2, 76: 3, 75: 4, 74: 5, 73: 6,
        72: 8, 71: 10, 70: 12, 69: 13, 68: 14, 67: 9, 66: 10,
    },
    "big_man_heavy": {
        80: 1, 79: 1, 78: 2, 77: 2, 76: 3, 75: 4, 74: 5, 73: 6,
        72: 8, 71: 10, 70: 12, 69: 13, 68: 14, 67: 9, 66: 10,
    },
}

# Soft bounds used by the variation pass. These are intentionally wider than the
# exact templates so classes can differ, but tight enough that the league shape stays stable.
DRAFT_OVR_COUNT_LIMITS: Dict[str, Dict[int, Tuple[int, int]]] = {
    "weak": {
        82: (0, 0), 81: (0, 0), 80: (0, 0), 79: (1, 1), 78: (1, 2), 77: (1, 3),
        76: (1, 3), 75: (2, 4), 74: (3, 5), 73: (4, 7), 72: (6, 9),
        71: (8, 12), 70: (11, 15), 69: (12, 16), 68: (13, 17), 67: (9, 13), 66: (10, 14),
    },
    "normal": {
        82: (0, 0), 81: (0, 0), 80: (1, 1), 79: (1, 2), 78: (1, 3), 77: (1, 3),
        76: (2, 4), 75: (3, 5), 74: (4, 6), 73: (5, 8), 72: (7, 10),
        71: (8, 12), 70: (10, 14), 69: (11, 15), 68: (11, 16), 67: (8, 12), 66: (8, 12),
    },
    "deep": {
        82: (0, 0), 81: (0, 0), 80: (1, 1), 79: (1, 2), 78: (1, 3), 77: (1, 3),
        76: (3, 5), 75: (4, 6), 74: (6, 8), 73: (7, 10), 72: (9, 12),
        71: (10, 14), 70: (12, 16), 69: (10, 14), 68: (7, 11), 67: (5, 8), 66: (6, 8),
    },
    "star_heavy": {
        82: (0, 0), 81: (1, 1), 80: (1, 2), 79: (1, 3), 78: (1, 3), 77: (2, 4),
        76: (2, 4), 75: (2, 4), 74: (3, 5), 73: (4, 7), 72: (5, 9),
        71: (7, 11), 70: (9, 13), 69: (11, 15), 68: (12, 16), 67: (8, 12), 66: (10, 14),
    },
    "generational": {
        82: (1, 1), 81: (0, 1), 80: (1, 2), 79: (1, 3), 78: (1, 3), 77: (2, 4),
        76: (2, 4), 75: (2, 4), 74: (3, 5), 73: (4, 7), 72: (5, 9),
        71: (7, 11), 70: (9, 13), 69: (11, 15), 68: (12, 16), 67: (8, 12), 66: (10, 14),
    },
}
DRAFT_OVR_COUNT_LIMITS["defensive_class"] = dict(DRAFT_OVR_COUNT_LIMITS["normal"])
DRAFT_OVR_COUNT_LIMITS["guard_heavy"] = dict(DRAFT_OVR_COUNT_LIMITS["normal"])
DRAFT_OVR_COUNT_LIMITS["big_man_heavy"] = dict(DRAFT_OVR_COUNT_LIMITS["normal"])

DRAFT_DISTRIBUTION_SHAPE_WEIGHTS: Dict[str, List[Tuple[str, float]]] = {
    "weak": [("balanced", 0.42), ("bottom_heavy", 0.38), ("thin_middle", 0.20)],
    "normal": [("balanced", 0.42), ("mid_heavy", 0.22), ("thin_middle", 0.20), ("bottom_heavy", 0.16)],
    "deep": [("mid_heavy", 0.58), ("balanced", 0.32), ("top_cluster", 0.10)],
    "star_heavy": [("top_cluster", 0.44), ("thin_middle", 0.34), ("balanced", 0.22)],
    "generational": [("top_cluster", 0.54), ("thin_middle", 0.30), ("balanced", 0.16)],
    "defensive_class": [("balanced", 0.42), ("mid_heavy", 0.22), ("thin_middle", 0.20), ("bottom_heavy", 0.16)],
    "guard_heavy": [("balanced", 0.42), ("mid_heavy", 0.22), ("thin_middle", 0.20), ("bottom_heavy", 0.16)],
    "big_man_heavy": [("balanced", 0.42), ("mid_heavy", 0.22), ("thin_middle", 0.20), ("bottom_heavy", 0.16)],
}


def _template_key_for_class_type(class_type: str) -> str:
    return class_type if class_type in DRAFT_OVR_COUNT_TEMPLATES else "normal"


def _count_limit(limits: Dict[int, Tuple[int, int]], overall: int) -> Tuple[int, int]:
    return limits.get(overall, (0, 0))


def _can_move_ovr_count(counts: Dict[int, int], limits: Dict[int, Tuple[int, int]], src: int, dst: int) -> bool:
    if src == dst:
        return False
    src_min, _ = _count_limit(limits, src)
    _, dst_max = _count_limit(limits, dst)
    return counts.get(src, 0) > src_min and counts.get(dst, 0) < dst_max


def _move_ovr_count(counts: Dict[int, int], limits: Dict[int, Tuple[int, int]], src: int, dst: int, amount: int = 1) -> int:
    moved = 0
    for _ in range(max(0, int(amount))):
        if not _can_move_ovr_count(counts, limits, src, dst):
            break
        counts[src] = counts.get(src, 0) - 1
        counts[dst] = counts.get(dst, 0) + 1
        moved += 1
    return moved


def _apply_distribution_shape(counts: Dict[int, int], limits: Dict[int, Tuple[int, int]], shape: str, rng: random.Random) -> None:
    # These moves create class personality without changing the 100-player total.
    if shape == "top_cluster":
        moves = [(72, 79), (73, 78), (71, 80), (74, 77), (72, 81)]
        rng.shuffle(moves)
        for src, dst in moves[:rng.randint(2, 4)]:
            _move_ovr_count(counts, limits, src, dst, 1)
    elif shape == "thin_middle":
        moves = [(73, 66), (74, 67), (72, 68), (75, 69), (71, 66)]
        rng.shuffle(moves)
        for src, dst in moves[:rng.randint(2, 5)]:
            _move_ovr_count(counts, limits, src, dst, 1)
    elif shape == "mid_heavy":
        moves = [(66, 72), (67, 71), (68, 73), (69, 74), (66, 70)]
        rng.shuffle(moves)
        for src, dst in moves[:rng.randint(2, 5)]:
            _move_ovr_count(counts, limits, src, dst, 1)
    elif shape == "bottom_heavy":
        moves = [(71, 66), (70, 67), (72, 68), (69, 66)]
        rng.shuffle(moves)
        for src, dst in moves[:rng.randint(2, 4)]:
            _move_ovr_count(counts, limits, src, dst, 1)


def _apply_distribution_noise(counts: Dict[int, int], limits: Dict[int, Tuple[int, int]], rng: random.Random) -> None:
    # Small adjacent noise prevents every normal class from having the exact same histogram.
    possible_overalls = list(range(MIN_GENERATED_DRAFT_OVR, MAX_GENERATED_DRAFT_OVR + 1))
    for _ in range(rng.randint(3, 7)):
        src = rng.choice(possible_overalls)
        dst = src + rng.choice([-1, 1])
        if dst < MIN_GENERATED_DRAFT_OVR or dst > MAX_GENERATED_DRAFT_OVR:
            continue
        _move_ovr_count(counts, limits, src, dst, 1)


def _normalize_count_template(counts: Dict[int, int], limits: Dict[int, Tuple[int, int]]) -> Dict[int, int]:
    # Keep all tracked OVRs present so summaries are predictable.
    normalized = {overall: int(counts.get(overall, 0)) for overall in range(MIN_GENERATED_DRAFT_OVR, MAX_GENERATED_DRAFT_OVR + 1)}

    # Safety clamp to declared limits, then restore the exact 100-player total by
    # moving counts between legal buckets. This should rarely do anything, but it
    # keeps the function robust if future template numbers are edited.
    for overall, (lo, hi) in limits.items():
        normalized[overall] = max(lo, min(hi, normalized.get(overall, 0)))

    total = sum(normalized.values())
    while total > DRAFT_CLASS_FIXED_COUNT:
        changed = False
        for overall in range(MIN_GENERATED_DRAFT_OVR + 1, MAX_GENERATED_DRAFT_OVR + 1):
            lo, _ = _count_limit(limits, overall)
            if normalized.get(overall, 0) > lo:
                normalized[overall] -= 1
                total -= 1
                changed = True
                break
        if not changed:
            break

    while total < DRAFT_CLASS_FIXED_COUNT:
        changed = False
        for overall in [66, 68, 69, 70, 67, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82]:
            _, hi = _count_limit(limits, overall)
            if normalized.get(overall, 0) < hi:
                normalized[overall] += 1
                total += 1
                changed = True
                break
        if not changed:
            break

    return normalized


def _overall_slots_for_class(class_type: str, rng: random.Random) -> Tuple[List[int], Dict[str, Any]]:
    safe_class_type = _template_key_for_class_type(class_type)
    counts = dict(DRAFT_OVR_COUNT_TEMPLATES[safe_class_type])
    limits = DRAFT_OVR_COUNT_LIMITS[safe_class_type]

    shape_options = DRAFT_DISTRIBUTION_SHAPE_WEIGHTS.get(safe_class_type, DRAFT_DISTRIBUTION_SHAPE_WEIGHTS["normal"])
    shape_names = [name for name, _weight in shape_options]
    shape_weights = [weight for _name, weight in shape_options]
    shape = rng.choices(shape_names, weights = shape_weights)[0]

    _apply_distribution_shape(counts, limits, shape, rng)
    _apply_distribution_noise(counts, limits, rng)
    counts = _normalize_count_template(counts, limits)

    # Mandatory hard guardrails.
    if counts.get(MIN_GENERATED_DRAFT_OVR, 0) <= 0:
        raise ValueError("Draft histogram generated no 66 OVR players")
    if sum(counts.values()) != DRAFT_CLASS_FIXED_COUNT:
        raise ValueError(f"Draft histogram count mismatch: {sum(counts.values())}")

    slots: List[int] = []
    for overall in sorted(counts.keys(), reverse = True):
        slots.extend([overall] * counts[overall])

    return slots, {
        "shape": shape,
        "targetDistribution": {
            str(overall): counts[overall]
            for overall in sorted(counts.keys(), reverse = True)
            if counts[overall] > 0
        },
    }


def _overall_from_distribution(rank: int, total_count: int, class_type: str) -> int:
    # Fallback for older direct calls. Main generation uses _overall_slots_for_class.
    safe_class_type = _template_key_for_class_type(class_type)
    counts = _normalize_count_template(dict(DRAFT_OVR_COUNT_TEMPLATES[safe_class_type]), DRAFT_OVR_COUNT_LIMITS[safe_class_type])
    slots: List[int] = []
    for overall in sorted(counts.keys(), reverse = True):
        slots.extend([overall] * counts[overall])
    index = _clamp(max(1, _safe_int(rank, 1)), 1, len(slots)) - 1
    return slots[index]


def _overall_distribution_summary(prospects: List[Dict[str, Any]]) -> Dict[str, int]:
    counts: Dict[str, int] = {}
    for prospect in prospects or []:
        overall = str(_safe_int((prospect or {}).get("overall"), 0))
        if overall == "0":
            continue
        counts[overall] = counts.get(overall, 0) + 1

    return {
        key: counts[key]
        for key in sorted(counts.keys(), key = lambda value: int(value), reverse = True)
    }


def _tier_label_for_rank(rank: int, class_type: str, overall: int, potential: int) -> str:
    # Keep the word "Generational" special. It should only appear for the true
    # rare ceiling outcome, not every 80/97 or 81/97 top pick.
    if rank == 1 and overall >= 82 and potential >= 98:
        return "Generational"
    if rank <= 4 and potential >= 92:
        return "Franchise"
    if rank <= 8:
        return "High Lottery"
    if rank <= 14:
        return "Lottery"
    if rank <= 30:
        return "First Round"
    if rank <= 45:
        return "Late First / Early Second"
    if rank <= 60:
        return "Second Round"
    return "Undrafted"


def _max_overall_for_rank(rank: int, class_type: str) -> int:
    if rank == 1 and class_type == "generational":
        return 82
    if rank == 1 and class_type in {"star_heavy", "normal", "deep", "defensive_class", "guard_heavy", "big_man_heavy"}:
        return 81
    if rank <= 3 and class_type in {"star_heavy", "generational"}:
        return 80
    if rank <= 5:
        return 79
    if rank <= 8 and class_type in {"star_heavy", "generational"}:
        return 78
    if rank <= 10:
        return 77
    return MAX_GENERATED_DRAFT_OVR


def _potential_cap_for_rank(rank: int, class_type: str) -> int:
    if rank == 1 and class_type == "generational":
        return 98
    if rank == 1 and class_type == "weak":
        return 95
    if rank == 1:
        return 97
    if rank <= 3:
        if class_type == "generational":
            return 97
        if class_type == "weak":
            return 95
        return 96
    if rank <= 5:
        return 96 if class_type in {"generational", "star_heavy", "normal", "deep"} else 94
    if rank <= 10:
        return 94 if class_type != "weak" else 92
    if rank <= 14:
        return 91
    if rank <= 30:
        return 89
    if rank <= 45:
        return 86
    if rank <= 60:
        return 84
    return 82


def _overall_jitter_for_rank(rank: int, rng: random.Random) -> float:
    if rank <= 3:
        spread = 0.45
    elif rank <= 10:
        spread = 0.75
    elif rank <= 30:
        spread = 0.95
    else:
        spread = 0.85
    return rng.triangular(-spread, spread, 0.0)


def _age_for_rank(rank: int, class_type: str, rng: random.Random) -> int:
    # Top prospects skew younger. Later prospects skew older/NBA-ready.
    # This lets two same-OVR prospects separate naturally by upside.
    if rank <= 10:
        ages = [18, 19, 20, 21, 22, 23]
        weights = [0.06, 0.70, 0.20, 0.04, 0.00, 0.00]
    elif rank <= 30:
        ages = [18, 19, 20, 21, 22, 23]
        weights = [0.04, 0.42, 0.30, 0.14, 0.07, 0.03]
    elif rank <= 60:
        ages = [18, 19, 20, 21, 22, 23]
        weights = [0.02, 0.22, 0.27, 0.21, 0.18, 0.10]
    else:
        ages = [18, 19, 20, 21, 22, 23]
        weights = [0.01, 0.13, 0.19, 0.24, 0.24, 0.19]

    if class_type == "deep" and rank >= 30:
        # Deep classes can include a few more young second-round upside swings.
        weights = [weights[0] + 0.01, weights[1] + 0.04, weights[2], max(0.0, weights[3] - 0.01), max(0.0, weights[4] - 0.02), max(0.0, weights[5] - 0.02)]

    return rng.choices(ages, weights = weights)[0]


def _age_potential_adjustment(age: int, rng: random.Random) -> int:
    if age <= 18:
        return rng.randint(2, 4)
    if age == 19:
        return rng.randint(1, 3)
    if age == 20:
        return rng.randint(0, 2)
    if age == 21:
        return rng.randint(-1, 1)
    if age == 22:
        return rng.randint(-2, 0)
    return rng.randint(-3, -1)


def _potential_noise_for_rank(rank: int, rng: random.Random) -> int:
    if rank <= 5:
        return rng.choice([-1, 0, 0, 1, 1, 2])
    if rank <= 14:
        return rng.choice([-2, -1, 0, 0, 1, 2])
    if rank <= 60:
        return rng.choice([-2, -1, 0, 0, 1, 1])
    return rng.choice([-3, -2, -1, 0, 0, 1])


def _talent_for_rank(
    rank: int,
    class_type: str,
    age: int,
    rng: random.Random,
    total_count: int = DRAFT_CLASS_FIXED_COUNT,
    overall_slot: Optional[int] = None,
) -> Tuple[str, int, int]:
    safe_class_type = _template_key_for_class_type(class_type)

    # v11: OVR is assigned from the pre-built class histogram. This keeps the
    # full draft distribution stable while still allowing class personality.
    if overall_slot is None:
        overall = _overall_from_distribution(rank, total_count, safe_class_type)
    else:
        overall = _safe_int(overall_slot, MIN_GENERATED_DRAFT_OVR)

    overall = _clamp(
        overall,
        MIN_GENERATED_DRAFT_OVR,
        _max_overall_for_rank(rank, safe_class_type),
    )

    base_gap = _linear_anchor_value(rank, DRAFT_POT_GAP_CURVES[safe_class_type])
    raw_potential = overall + base_gap + _age_potential_adjustment(age, rng) + _potential_noise_for_rank(rank, rng)
    potential = _clamp(
        raw_potential,
        overall,
        min(MAX_GENERATED_DRAFT_POTENTIAL, _potential_cap_for_rank(rank, safe_class_type)),
    )

    # Preserve the requested rare ceiling: the only normal 82 OVR outcome is a
    # generational #1, and that player should carry 98 POT.
    if rank == 1 and safe_class_type == "generational" and overall >= 82:
        potential = 98

    # 81/97 is elite franchise talent, but not labeled generational.
    if rank == 1 and safe_class_type == "generational" and overall < 82:
        potential = min(potential, 97)

    tier = _tier_label_for_rank(rank, safe_class_type, overall, potential)
    return tier, overall, potential

# Backwards-compatible helper names kept for any older imports/tests that may call them directly.
def _tier_for_rank(rank: int, class_type: str, rng: random.Random) -> Tuple[str, Tuple[int, int], Tuple[int, int]]:
    age = _age_for_rank(rank, class_type, rng)
    tier, overall, potential = _talent_for_rank(rank, class_type, age, rng, DRAFT_CLASS_FIXED_COUNT)
    return tier, (overall, overall), (potential, potential)


def _adjust_for_class_type(overall: int, potential: int, rank: int, class_type: str) -> Tuple[int, int]:
    return (
        _clamp(overall, MIN_GENERATED_DRAFT_OVR, MAX_GENERATED_DRAFT_OVR),
        _clamp(potential, max(MIN_GENERATED_DRAFT_OVR, overall), MAX_GENERATED_DRAFT_POTENTIAL),
    )


def _build_attrs(
    rng: random.Random,
    pos: str,
    archetype: str,
    overall: int,
    potential: int,
    class_type: str,
) -> List[int]:
    bias = ARCHETYPE_BIASES.get(archetype, [0] * 15)
    base = overall - 2

    attrs = []
    for idx, b in enumerate(bias):
        noise = rng.randint(-6, 6)
        value = base + b + noise
        attrs.append(_clamp(value, 25, 99))

    if pos == "PG":
        attrs[9] = min(attrs[9], overall - 5)
        attrs[10] = min(attrs[10], overall - 10)
        attrs[12] = min(attrs[12], overall - 5)
    elif pos == "C":
        attrs[4] = min(attrs[4], overall + 1)
        attrs[6] = min(attrs[6], overall)
        attrs[8] = min(attrs[8], overall + 2)

    if class_type == "defensive_class":
        for idx in [8, 9, 10, 11, 12, 14]:
            attrs[idx] = _clamp(attrs[idx] + rng.randint(2, 6), 25, 99)

    # Make true stars feel a bit cleaner across IQ and stamina-adjacent skills.
    if potential >= 92:
        attrs[13] = _clamp(attrs[13] + rng.randint(2, 5), 25, 99)
        attrs[14] = _clamp(attrs[14] + rng.randint(1, 4), 25, 99)

    return attrs


def _ratings_from_attrs(attrs: List[int]) -> Tuple[int, int, float]:
    off_indices = [0, 1, 2, 3, 4, 5, 7, 13]
    def_indices = [8, 9, 10, 11, 12, 14]

    off_rating = round(sum(attrs[i] for i in off_indices) / len(off_indices))
    def_rating = round(sum(attrs[i] for i in def_indices) / len(def_indices))

    scoring_rating = (
        attrs[0] * 0.28
        + attrs[1] * 0.21
        + attrs[2] * 0.24
        + attrs[4] * 0.10
        + attrs[7] * 0.08
        + attrs[13] * 0.09
    )

    return int(off_rating), int(def_rating), float(scoring_rating)


def _weighted_profile_choice(rng: random.Random) -> Dict[str, Any]:
    total = sum(float(profile.get("weight", 0.0)) for profile in IDENTITY_PROFILES)
    ticket = rng.random() * total
    running = 0.0

    for profile in IDENTITY_PROFILES:
        running += float(profile.get("weight", 0.0))
        if ticket <= running:
            return dict(profile)

    return dict(IDENTITY_PROFILES[0])


def _weighted_value_choice(rng: random.Random, weighted: List[Tuple[str, float]], fallback: str = "") -> str:
    if not weighted:
        return fallback

    total = sum(float(weight) for _, weight in weighted)
    ticket = rng.random() * total
    running = 0.0

    for item, weight in weighted:
        running += float(weight)
        if ticket <= running:
            return item

    return weighted[-1][0]


def _make_identity_profile(rng: random.Random) -> Dict[str, Any]:
    profile = _weighted_profile_choice(rng)
    profile_key = profile.get("key") or "unknown"
    nationality = _weighted_value_choice(rng, profile.get("nationalityWeights") or [], "USA")
    college_bucket = _weighted_value_choice(rng, profile.get("collegeWeights") or [], "college")
    college_options = COLLEGE_GROUPS.get(college_bucket, COLLEGES)

    first_names = _unique_text_list(
        list(profile.get("firstNames") or FIRST_NAMES)
        + list(ADDITIONAL_FIRST_NAMES_BY_PROFILE.get(profile_key) or [])
        + list(MEGA_FIRST_NAMES_BY_PROFILE.get(profile_key) or [])
    )
    last_names = _unique_text_list(
        list(profile.get("lastNames") or LAST_NAMES)
        + list(ADDITIONAL_LAST_NAMES_BY_PROFILE.get(profile_key) or [])
        + list(MEGA_LAST_NAMES_BY_PROFILE.get(profile_key) or [])
    )

    return {
        "identityKey": profile_key,
        "ethnicityGroup": profile.get("ethnicityGroup") or "other",
        "subgroup": profile.get("subgroup") or "other",
        "skinTone": profile.get("skinTone") or "medium",
        "region": profile.get("region") or "unknown",
        "nationality": nationality,
        "collegeBucket": college_bucket,
        "college": rng.choice(college_options),
        "firstNames": first_names or FIRST_NAMES,
        "lastNames": last_names or LAST_NAMES,
        "portraitRange": profile.get("portraitRange") or (1, ROOKIE_FACE_COUNT),
    }


def _make_name(rng: random.Random, used: set, identity_profile: Optional[Dict[str, Any]] = None) -> str:
    first_names = (identity_profile or {}).get("firstNames") or FIRST_NAMES
    last_names = (identity_profile or {}).get("lastNames") or LAST_NAMES

    # Try a lot harder than before so generated classes do not keep recycling
    # familiar combinations like Lamar Thomas or Bryce Bennett.
    for _ in range(500):
        name = f"{rng.choice(first_names)} {rng.choice(last_names)}"
        if name not in used and name not in OVERUSED_FULL_NAMES:
            used.add(name)
            return name

    # Extremely rare fallback if a pool somehow gets exhausted.
    for suffix in ["Jr.", "II", "III"]:
        name = f"{rng.choice(first_names)} {rng.choice(last_names)} {suffix}"
        if name not in used and name not in OVERUSED_FULL_NAMES:
            used.add(name)
            return name

    name = f"{rng.choice(first_names)} {rng.choice(last_names)}"
    used.add(name)
    return name


def _rookie_face_id(index: int) -> str:
    return f"rookie_face_{index:04d}"


def _rookie_face_url(face_id: str) -> str:
    return f"{ROOKIE_FACE_BASE_URL}/{face_id}.png"


def _rookie_face_entry(face_id: str) -> Dict[str, str]:
    url = _rookie_face_url(face_id)
    return {
        "id": face_id,
        "url": url,
        "headshot": url,
        "image": url,
        "img": url,
    }


def _portrait_ids_for_range(start: int, end: int, portrait_count: int) -> List[str]:
    start = max(1, _safe_int(start, 1))
    end = min(_safe_int(end, portrait_count), portrait_count)
    if end < start:
        return []
    return [_rookie_face_id(i) for i in range(start, end + 1)]


def _all_portrait_ids(portrait_count: int) -> List[str]:
    return [_rookie_face_id(i) for i in range(1, portrait_count + 1)]


def _choose_portrait_for_identity(
    identity_profile: Dict[str, Any],
    rng: random.Random,
    used_portrait_ids: Optional[List[str]] = None,
    assigned_this_class: Optional[set] = None,
    portrait_count: int = ROOKIE_FACE_COUNT,
) -> Dict[str, str]:
    # Phase 1 safety: only use manually verified portrait IDs.
    # Do not fall back to the old 1-100 range because most of those files do not exist
    # or have not been confirmed as clean transparent PNGs yet.
    profile_key = (identity_profile or {}).get("identityKey") or ""
    matching = list(SAFE_ROOKIE_FACE_IDS_BY_PROFILE.get(profile_key) or [])
    all_safe_ids = list(SAFE_ROOKIE_FACE_IDS)

    if not all_safe_ids:
        return _rookie_face_entry(_rookie_face_id(1))

    # If a profile has no verified bucket yet, use the full safe pool.
    # This keeps every generated prospect visually valid until more assets are added.
    if not matching:
        matching = all_safe_ids

    used = {str(face_id) for face_id in (used_portrait_ids or []) if face_id}
    assigned = assigned_this_class if assigned_this_class is not None else set()

    candidate_layers = [
        [face_id for face_id in matching if face_id not in used and face_id not in assigned],
        [face_id for face_id in matching if face_id not in assigned],
        [face_id for face_id in matching],
        [face_id for face_id in all_safe_ids if face_id not in used and face_id not in assigned],
        [face_id for face_id in all_safe_ids if face_id not in assigned],
        all_safe_ids,
    ]

    for candidates in candidate_layers:
        if candidates:
            face_id = rng.choice(candidates)
            assigned.add(face_id)
            return _rookie_face_entry(face_id)

    return _rookie_face_entry(all_safe_ids[0])


def _build_prospect(
    rank: int,
    season_year: int,
    class_type: str,
    rng: random.Random,
    used_names: set,
    portrait_info: Optional[Dict[str, str]] = None,
    identity_profile: Optional[Dict[str, Any]] = None,
    total_count: int = DRAFT_CLASS_FIXED_COUNT,
    overall_slot: Optional[int] = None,
) -> Dict[str, Any]:
    identity_profile = identity_profile or _make_identity_profile(rng)

    pos_weights = POSITION_WEIGHTS.get(class_type, POSITION_WEIGHTS["normal"])
    if class_type not in {"guard_heavy", "big_man_heavy"}:
        pos_weights = POSITION_WEIGHTS["normal"]

    pos = _weighted_choice(rng, pos_weights)
    secondary = rng.choice(SECONDARY_BY_POS.get(pos, [""]))
    archetype = rng.choice(ARCHETYPES_BY_POS[pos])

    age = _age_for_rank(rank, class_type, rng)
    tier, overall, potential = _talent_for_rank(rank, class_type, age, rng, total_count, overall_slot)

    height = rng.randint(*HEIGHT_RANGES[pos])
    weight = rng.randint(*WEIGHT_RANGES[pos])

    # Build archetype-shaped attributes, then calibrate them against the same
    # overall formula used by progression / Player Editor backend.
    # This prevents generated rookies from being displayed as 72-78 OVR while
    # secretly calculating as 80+ OVR once progression normalizes them.
    target_overall = int(_clamp(overall, MIN_GENERATED_DRAFT_OVR, MAX_GENERATED_DRAFT_OVR))
    attrs = _build_attrs(rng, pos, archetype, target_overall, potential, class_type)
    attrs = _calibrate_attrs_to_source_overall(attrs, pos, target_overall, rng)
    overall = _calc_overall_from_attrs(attrs, pos)
    potential = _clamp(max(overall, potential), overall, MAX_GENERATED_DRAFT_POTENTIAL)
    off_rating, def_rating, scoring_rating = _ratings_from_attrs(attrs)

    boom_bust = round(rng.uniform(0.12, 0.55), 2)
    if tier in {"Generational", "Franchise"}:
        boom_bust = round(rng.uniform(0.08, 0.40), 2)
    if tier == "Undrafted":
        boom_bust = round(rng.uniform(0.20, 0.66), 2)

    floor = _clamp(overall - rng.randint(2, 8), 45, overall)
    ceiling = _clamp(potential + rng.choice([0, 0, 1]), potential, MAX_GENERATED_DRAFT_POTENTIAL)

    visible_rank = _clamp(rank + rng.randint(-5, 7), 1, 110)
    if rank <= 5:
        visible_rank = _clamp(rank + rng.randint(-1, 2), 1, 10)

    name = _make_name(rng, used_names, identity_profile)
    birth_month = rng.randint(1, 12)
    birth_day = rng.randint(1, 28)

    prospect_id = f"draft_{season_year}_{rank:03d}_{name.lower().replace(' ', '_').replace('.', '')}"
    portrait_info = portrait_info or {}
    portrait_id = portrait_info.get("id") or ""
    portrait_url = portrait_info.get("url") or ""

    return {
        "id": prospect_id,
        "draftClassYear": season_year,
        "name": name,
        "portraitId": portrait_id,
        "portraitFamilyId": portrait_id,
        "portraitVariant": "rookie",
        "headshot": portrait_url,
        "image": portrait_url,
        "img": portrait_url,
        "age": age,
        "birthMonth": birth_month,
        "birthDay": birth_day,
        "pos": pos,
        "secondaryPos": secondary,
        "height": height,
        "weight": weight,
        # Keep the rookie source in multiple aliases so draft conversion/front-end
        # code can display it consistently after a player is drafted.
        "college": identity_profile.get("college") or rng.choice(COLLEGES),
        "school": identity_profile.get("college") or rng.choice(COLLEGES),
        "university": identity_profile.get("college") or "",
        "academy": identity_profile.get("college") or "",
        "academyName": identity_profile.get("college") or "",
        "sourceName": identity_profile.get("college") or "",
        "draftSource": identity_profile.get("college") or "",
        "sourceType": identity_profile.get("collegeBucket") or "college",
        "collegeBucket": identity_profile.get("collegeBucket") or "college",
        "nationality": identity_profile.get("nationality") or rng.choice(NATIONALITIES),
        "ethnicityGroup": identity_profile.get("ethnicityGroup") or "other",
        "subgroup": identity_profile.get("subgroup") or "other",
        "skinTone": identity_profile.get("skinTone") or "medium",
        "identityKey": identity_profile.get("identityKey") or "unknown",
        "region": identity_profile.get("region") or "unknown",
        "archetype": archetype,
        "tier": tier,
        "overall": overall,
        "potential": potential,
        "floor": floor,
        "ceiling": ceiling,
        "attrs": attrs,
        "offRating": off_rating,
        "defRating": def_rating,
        "stamina": _clamp(rng.randint(72, 91) + (2 if age >= 21 else 0), 60, 96),
        "scoringRating": scoring_rating,
        "draftProjection": visible_rank,
        "trueRank": rank,
        "scouting": {
            "projectedRangeLow": _clamp(visible_rank - rng.randint(1, 7), 1, 100),
            "projectedRangeHigh": _clamp(visible_rank + rng.randint(3, 12), 1, 100),
            "scoutedOverallRange": [
                _clamp(overall - rng.randint(1, 4), 45, 99),
                _clamp(overall + rng.randint(1, 4), 45, 99),
            ],
            "scoutedPotentialRange": [
                _clamp(potential - rng.randint(2, 7), overall, 99),
                _clamp(potential + rng.randint(1, 4), overall, MAX_GENERATED_DRAFT_POTENTIAL),
            ],
        },
        "traits": {
            "nbaReady": round(max(0.05, min(0.98, (overall - 55) / 32)), 2),
            "boomBust": boom_bust,
            "workEthic": round(rng.uniform(0.35, 0.95), 2),
            "injuryRisk": round(rng.uniform(0.04, 0.24), 2),
            "starUpside": round(max(0.02, min(0.98, (potential - 70) / 29)), 2),
        },
    }



def _repair_prospect_to_target_overall(prospect: Dict[str, Any], target_overall: int, rng: random.Random, class_type: str) -> Dict[str, Any]:
    target = int(_clamp(target_overall, MIN_GENERATED_DRAFT_OVR, MAX_GENERATED_DRAFT_OVR))
    pos = prospect.get("pos") or "SF"
    attrs = prospect.get("attrs") if isinstance(prospect.get("attrs"), list) else []
    if attrs:
        attrs = _calibrate_attrs_to_source_overall(attrs, pos, target, rng)
    else:
        attrs = _build_attrs(rng, pos, prospect.get("archetype") or "Two-Way Wing", target, _safe_int(prospect.get("potential"), target), class_type)
        attrs = _calibrate_attrs_to_source_overall(attrs, pos, target, rng)

    actual = _calc_overall_from_attrs(attrs, pos)
    prospect["attrs"] = attrs
    prospect["overall"] = actual
    prospect["potential"] = _clamp(max(actual, _safe_int(prospect.get("potential"), actual)), actual, MAX_GENERATED_DRAFT_POTENTIAL)
    prospect["offRating"], prospect["defRating"], prospect["scoringRating"] = _ratings_from_attrs(attrs)
    prospect["floor"] = _clamp(min(_safe_int(prospect.get("floor"), actual - 4), actual), 45, actual)
    prospect["ceiling"] = _clamp(max(_safe_int(prospect.get("ceiling"), prospect["potential"]), prospect["potential"]), prospect["potential"], MAX_GENERATED_DRAFT_POTENTIAL)
    prospect["tier"] = _tier_label_for_rank(_safe_int(prospect.get("trueRank"), 100), class_type, prospect["overall"], prospect["potential"])
    return prospect


def _repair_prospects_to_overall_slots(prospects: List[Dict[str, Any]], overall_slots: List[int], rng: random.Random, class_type: str) -> List[Dict[str, Any]]:
    repaired: List[Dict[str, Any]] = []
    for index, prospect in enumerate(prospects):
        target = overall_slots[index] if index < len(overall_slots) else MIN_GENERATED_DRAFT_OVR
        if _safe_int(prospect.get("overall"), 0) != target:
            prospect = _repair_prospect_to_target_overall(prospect, target, rng, class_type)
        repaired.append(prospect)
    return repaired

def generate_draft_class(
    season_year: int = 2026,
    count: int = DRAFT_CLASS_FIXED_COUNT,
    seed: Optional[int] = None,
    class_type: Optional[str] = None,
    used_portrait_ids: Optional[List[str]] = None,
    portrait_count: int = ROOKIE_FACE_COUNT,
) -> Dict[str, Any]:
    generated_fresh_seed = seed is None
    if seed is None:
        seed = _fresh_generation_seed("draft_class", season_year, DRAFT_CLASS_FIXED_COUNT, class_type or "auto")

    rng = random.Random(seed)
    if not class_type:
        class_type = rng.choices(
            CLASS_TYPES,
            weights = [0.12, 0.43, 0.15, 0.10, 0.06, 0.06, 0.04, 0.04],
        )[0]

    requested_count = _safe_int(count, DRAFT_CLASS_FIXED_COUNT)
    overall_slots, distribution_profile = _overall_slots_for_class(class_type, rng)
    count = DRAFT_CLASS_FIXED_COUNT
    used_names = set()
    assigned_portrait_ids = set()
    prospects = []

    for rank in range(1, count + 1):
        identity_profile = _make_identity_profile(rng)
        portrait_info = _choose_portrait_for_identity(
            identity_profile = identity_profile,
            rng = rng,
            used_portrait_ids = used_portrait_ids,
            assigned_this_class = assigned_portrait_ids,
            portrait_count = portrait_count,
        )
        prospects.append(
            _build_prospect(
                rank,
                season_year,
                class_type,
                rng,
                used_names,
                portrait_info,
                identity_profile,
                total_count = count,
                overall_slot = overall_slots[rank - 1],
            )
        )

    # Sort by true rank, but keep draftProjection as the visible noisy board.
    prospects = sorted(prospects, key = lambda p: p["trueRank"])
    prospects = _repair_prospects_to_overall_slots(prospects, overall_slots, rng, class_type)

    return {
        "ok": True,
        "version": AUTOGENERATED_DRAFT_CLASS_VERSION,
        "seasonYear": season_year,
        "seed": seed,
        "seedMode": "fresh_random" if generated_fresh_seed else "provided",
        "classType": class_type,
        "count": len(prospects),
        "draftClass": prospects,
        "classMeta": {
            "seasonYear": season_year,
            "classType": class_type,
            "seed": seed,
            "seedMode": "fresh_random" if generated_fresh_seed else "provided",
            "prospectCount": len(prospects),
            "requestedCount": requested_count,
            "forcedCount": DRAFT_CLASS_FIXED_COUNT,
            "distributionProfile": distribution_profile,
            "portraitCount": portrait_count,
            "activeSafePortraitCount": len(SAFE_ROOKIE_FACE_IDS),
            "activeSafePortraitIds": list(SAFE_ROOKIE_FACE_IDS),
            "assignedPortraitCount": len([p for p in prospects if p.get("portraitId")]),
            "identityProfiles": sorted(list({p.get("identityKey") for p in prospects if p.get("identityKey")})),
            "ratingModel": DRAFT_RATING_MODEL_VERSION,
            "minGeneratedOverall": MIN_GENERATED_DRAFT_OVR,
            "maxGeneratedOverall": MAX_GENERATED_DRAFT_OVR,
            "maxGeneratedPotential": MAX_GENERATED_DRAFT_POTENTIAL,
            "overallDistribution": _overall_distribution_summary(prospects),
            "targetOverallDistribution": distribution_profile.get("targetDistribution", {}),
            "summary": f"{season_year} generated {class_type.replace('_', ' ')} draft class",
        },
    }


def handle_request(request: Dict[str, Any]) -> Dict[str, Any]:
    req = _plain(request) or {}
    payload = req.get("payload") or {}
    action = req.get("action") or "generate_draft_class"

    if action not in {"generate_draft_class", "create_draft_class", "load_or_generate_draft_class"}:
        return {
            "ok": False,
            "reason": f"UNKNOWN_DRAFT_CLASS_ACTION: {action}",
            "version": AUTOGENERATED_DRAFT_CLASS_VERSION,
        }

    season_year = _safe_int(payload.get("seasonYear"), 2026)
    count = _safe_int(payload.get("count"), DRAFT_CLASS_FIXED_COUNT)
    seed = payload.get("seed")
    seed = _safe_int(seed, _stable_seed("draft_class", season_year)) if seed is not None else None
    class_type = payload.get("classType") or payload.get("classStrength") or None
    used_portrait_ids = payload.get("usedPortraitIds") or payload.get("usedPortraitIDs") or []
    portrait_count = _safe_int(payload.get("portraitCount"), ROOKIE_FACE_COUNT)

    return generate_draft_class(
        season_year = season_year,
        count = count,
        seed = seed,
        class_type = class_type,
        used_portrait_ids = used_portrait_ids,
        portrait_count = portrait_count,
    )
