"""
draft_logic.py
Basketball Manager NBA Draft logic.

This file handles:
- Initializing a draft from a locked draft order.
- CPU pick decisions using talent, upside, roster need, timeline, and randomness.
- User picks.
- Converting prospects into the game's normal player structure.
- Adding drafted rookies to rosters and undrafted prospects to free agency.
"""

from __future__ import annotations

import copy
import math
import random
import re
from typing import Any, Dict, List, Optional, Tuple

try:
    from autogenerated_draft_class import generate_draft_class
except Exception:
    generate_draft_class = None

DRAFT_LOGIC_VERSION = "2026-06-08_draft_logic_v19_off_def_source_truth_v6"

POSITION_ORDER = ["PG", "SG", "SF", "PF", "C"]
POSITION_BUCKETS = {
    "PG": {"PG"},
    "SG": {"SG", "PG"},
    "SF": {"SF", "SG", "PF"},
    "PF": {"PF", "SF", "C"},
    "C": {"C", "PF"},
}


def _plain(value: Any) -> Any:
    if value is None:
        return None
    if isinstance(value, dict):
        return {str(k): _plain(v) for k, v in value.items()}
    if isinstance(value, list):
        return [_plain(v) for v in value]
    if isinstance(value, tuple):
        return [_plain(v) for v in value]
    try:
        if hasattr(value, "to_py"):
            return _plain(value.to_py())
    except Exception:
        pass
    return value


def _safe_int(value: Any, default: int = 0) -> int:
    try:
        if value is None:
            return default
        return int(float(value))
    except Exception:
        return default


def _safe_float(value: Any, default: float = 0.0) -> float:
    try:
        if value is None:
            return default
        return float(value)
    except Exception:
        return default


def _clamp(value: float, lo: int, hi: int) -> int:
    return int(max(lo, min(hi, round(value))))


def _stable_seed(*parts: Any) -> int:
    text = "|".join(str(part) for part in parts)
    total = 0
    for i, ch in enumerate(text):
        total = (total + (i + 1) * ord(ch)) % 2_147_483_647
    return total or 20260527


def _safe_id_text(text: str) -> str:
    clean = re.sub(r"[^a-zA-Z0-9]+", "_", str(text or "").lower()).strip("_")
    return clean or "player"


OVERALL_POS_PARAMS = {
    "PG": {
        "weights": [0.11, 0.05, 0.03, 0.05, 0.17, 0.17, 0.10, 0.07, 0.10, 0.02, 0.01, 0.07, 0.05, 0.01, 0.01],
        "prim": [5, 6, 1, 7],
        "alpha": 0.25,
    },
    "SG": {
        "weights": [0.15, 0.08, 0.05, 0.05, 0.12, 0.07, 0.11, 0.07, 0.11, 0.03, 0.02, 0.08, 0.06, 0.01, 0.01],
        "prim": [1, 5, 7],
        "alpha": 0.28,
    },
    "SF": {
        "weights": [0.12, 0.09, 0.07, 0.04, 0.08, 0.07, 0.10, 0.10, 0.10, 0.06, 0.04, 0.08, 0.05, 0.01, 0.01],
        "prim": [1, 8, 9],
        "alpha": 0.22,
    },
    "PF": {
        "weights": [0.07, 0.07, 0.12, 0.03, 0.05, 0.05, 0.08, 0.12, 0.07, 0.13, 0.08, 0.08, 0.05, 0.01, 0.01],
        "prim": [3, 10, 8],
        "alpha": 0.24,
    },
    "C": {
        "weights": [0.04, 0.06, 0.17, 0.03, 0.02, 0.04, 0.07, 0.12, 0.05, 0.16, 0.13, 0.06, 0.08, 0.01, 0.01],
        "prim": [3, 10, 11, 13],
        "alpha": 0.30,
    },
}


def _normalize_attrs(attrs: Any, default: int = 75) -> List[int]:
    out: List[int] = []
    if isinstance(attrs, list):
        for value in attrs[:15]:
            out.append(_clamp(_safe_float(value, default), 25, 99))
    while len(out) < 15:
        out.append(default)
    return out


def _calc_overall_from_attrs(attrs: List[int], pos: str) -> int:
    p = OVERALL_POS_PARAMS.get(str(pos or "SF").upper(), OVERALL_POS_PARAMS["SF"])
    safe_attrs = _normalize_attrs(attrs)
    weighted = sum(w * safe_attrs[i] for i, w in enumerate(p["weights"]))
    primary_indices = [max(0, int(i) - 1) for i in p["prim"]]
    peak = max(safe_attrs[i] for i in primary_indices)
    blended = p["alpha"] * peak + (1 - p["alpha"]) * weighted
    overall = round(min(99, max(60, 60 + 39 * (1 / (1 + math.exp(-0.12 * (blended - 77)))))))
    num_90 = len([a for a in safe_attrs if a >= 90])
    if num_90 >= 3:
        overall = min(99, overall + (num_90 - 2))
    return int(overall)


def _has_source_truth_attrs(raw_attrs: Any) -> bool:
    # The current source-of-truth calculator expects the 15-attribute model.
    # Only force formula-based OVR when a prospect actually carries real attrs.
    return isinstance(raw_attrs, list) and len(raw_attrs) >= 15


def _resolve_prospect_overall(prospect: Dict[str, Any], default: int = 65) -> int:
    raw_attrs = prospect.get("attrs") if isinstance(prospect.get("attrs"), list) else prospect.get("attributes")
    if _has_source_truth_attrs(raw_attrs):
        return _calc_overall_from_attrs(
            _normalize_attrs(raw_attrs),
            prospect.get("pos") or prospect.get("position") or "SF",
        )

    for key in ["overall", "ovr", "rating"]:
        if prospect.get(key) is not None:
            return _safe_int(prospect.get(key), default)

    return _calc_overall_from_attrs(
        _normalize_attrs(prospect.get("attrs") or prospect.get("attributes") or []),
        prospect.get("pos") or prospect.get("position") or "SF",
    )


def _calc_stamina_from_attrs(age: Any, attrs: List[int]) -> int:
    resolved_age = max(18, min(45, _safe_int(age, 19)))
    athleticism = max(25, min(99, _safe_int(attrs[7] if len(attrs) > 7 else 75, 75)))
    if resolved_age <= 27:
        age_factor = 1.0
    elif resolved_age <= 34:
        age_factor = 0.95 - (0.15 * (resolved_age - 28)) / 6
    else:
        age_factor = 0.8 - (0.45 * (resolved_age - 35)) / 10
    age_factor = max(0.35, min(1.0, age_factor))
    raw = age_factor * 99 * 0.575 + athleticism * 0.425
    norm = (raw - 40) / (99 - 40)
    return _clamp(40 + norm * 59, 40, 99)


def _get_all_teams(league: Dict[str, Any]) -> List[Dict[str, Any]]:
    if isinstance(league.get("teams"), list):
        return league.get("teams") or []

    conferences = league.get("conferences") or {}
    teams: List[Dict[str, Any]] = []
    if isinstance(conferences, dict):
        for conf_name, conf_teams in conferences.items():
            for team in conf_teams or []:
                if isinstance(team, dict):
                    team.setdefault("conference", conf_name)
                    teams.append(team)
    return teams


def _find_team(league: Dict[str, Any], team_name: str) -> Optional[Dict[str, Any]]:
    if not team_name:
        return None

    if isinstance(league.get("teams"), list):
        for team in league.get("teams") or []:
            if team.get("name") == team_name or team.get("teamName") == team_name:
                return team

    conferences = league.get("conferences") or {}
    if isinstance(conferences, dict):
        for teams in conferences.values():
            for team in teams or []:
                if team.get("name") == team_name or team.get("teamName") == team_name:
                    return team

    return None


def _team_logo(team: Dict[str, Any]) -> str:
    return (
        team.get("logo")
        or team.get("teamLogo")
        or team.get("newTeamLogo")
        or team.get("logoUrl")
        or team.get("image")
        or team.get("img")
        or ""
    )


def _get_season_year(league: Dict[str, Any], payload: Dict[str, Any]) -> int:
    for value in [
        payload.get("seasonYear"),
        league.get("seasonYear"),
        league.get("currentSeasonYear"),
        league.get("seasonStartYear"),
    ]:
        year = _safe_int(value, 0)
        if 2020 <= year <= 2100:
            return year
    return 2026


def _draft_class_year_from_prospect(prospect: Dict[str, Any]) -> int:
    if not isinstance(prospect, dict):
        return 0
    meta = prospect.get("meta") if isinstance(prospect.get("meta"), dict) else {}
    for value in [
        prospect.get("draftClassYear"),
        prospect.get("seasonYear"),
        prospect.get("draftYear"),
        prospect.get("rookieYear"),
        meta.get("draftYear"),
    ]:
        year = _safe_int(value, 0)
        if 2020 <= year <= 2100:
            return year
    return 0


def _draft_class_matches_season(draft_class: Any, season_year: int) -> bool:
    if not isinstance(draft_class, list) or not draft_class:
        return False

    checked = 0
    for prospect in draft_class[:10]:
        year = _draft_class_year_from_prospect(prospect)
        if year:
            checked += 1
            if year != season_year:
                return False

    return True if checked else True


def _latest_history_entry(league: Dict[str, Any], season_year: int) -> Optional[Dict[str, Any]]:
    history = league.get("seasonHistory") or []
    if not isinstance(history, list):
        return None

    matches = [
        row
        for row in history
        if isinstance(row, dict) and _safe_int(row.get("seasonYear"), 0) == season_year
    ]
    if matches:
        complete = [row for row in matches if row.get("status") == "complete"]
        return complete[-1] if complete else matches[-1]

    valid = [row for row in history if isinstance(row, dict) and isinstance(row.get("teams"), list)]
    if not valid:
        return None

    return sorted(valid, key = lambda row: _safe_int(row.get("seasonYear"), 0))[-1]


def _history_by_team(league: Dict[str, Any], season_year: int) -> Dict[str, Dict[str, Any]]:
    latest = _latest_history_entry(league, season_year)
    out: Dict[str, Dict[str, Any]] = {}
    for row in latest.get("teams", []) if latest else []:
        name = row.get("teamName") or row.get("team") or row.get("name")
        if name:
            out[name] = row
    return out


def _player_overall(player: Dict[str, Any]) -> int:
    return _safe_int(player.get("overall", player.get("ovr", player.get("rating", 70))), 70)


def _team_direction(team: Dict[str, Any], history_row: Optional[Dict[str, Any]]) -> str:
    players = team.get("players") or []
    top = sorted([_player_overall(p) for p in players if isinstance(p, dict)], reverse = True)[:8]
    avg_top = sum(top) / max(1, len(top)) if top else 72

    wins = _safe_int(history_row.get("wins"), 0) if history_row else 0
    made_playoffs = bool(history_row.get("madePlayoffs")) if history_row else False
    result = str(history_row.get("playoffResult") or "") if history_row else ""

    if result in {"champion", "finals", "conference_finals"} or wins >= 50 or (made_playoffs and avg_top >= 80):
        return "contending"
    if wins <= 34 or avg_top < 75:
        return "rebuilding"
    return "middle"


def _pos_matches(player: Dict[str, Any], pos: str) -> bool:
    primary = str(player.get("pos") or player.get("position") or "").upper()
    secondary = str(player.get("secondaryPos") or player.get("secondaryPosition") or "").upper()
    acceptable = POSITION_BUCKETS.get(pos, {pos})
    return primary in acceptable or secondary in acceptable


def _need_score(team: Dict[str, Any], pos: str) -> float:
    players = [p for p in (team.get("players") or []) if isinstance(p, dict)]
    matching = [p for p in players if _pos_matches(p, pos)]
    matching_ovrs = sorted([_player_overall(p) for p in matching], reverse = True)

    if not matching_ovrs:
        return 18.0

    best = matching_ovrs[0]
    second = matching_ovrs[1] if len(matching_ovrs) > 1 else 58
    depth_count = len([ovr for ovr in matching_ovrs if ovr >= 72])

    need = 0.0
    if best < 78:
        need += 9.0
    if best < 74:
        need += 6.0
    if second < 72:
        need += 4.0
    if depth_count <= 1:
        need += 3.0

    return max(0.0, min(18.0, need))


def _prospect_score(
    prospect: Dict[str, Any],
    team: Dict[str, Any],
    history_row: Optional[Dict[str, Any]],
    pick: Dict[str, Any],
    rng: random.Random,
) -> float:
    overall = _resolve_prospect_overall(prospect, 60)
    potential = _safe_int(prospect.get("potential"), overall)
    age = _safe_int(prospect.get("age"), 20)
    pos = prospect.get("pos") or "SF"
    pick_num = _safe_int(pick.get("pick"), 60)
    round_num = _safe_int(pick.get("round"), 1)
    direction = _team_direction(team, history_row)

    if pick_num <= 5:
        ovr_w, pot_w, need_w, ready_w = 0.56, 0.70, 0.10, 0.05
    elif pick_num <= 14:
        ovr_w, pot_w, need_w, ready_w = 0.54, 0.50, 0.20, 0.07
    elif round_num == 1:
        ovr_w, pot_w, need_w, ready_w = 0.54, 0.34, 0.36, 0.12
    else:
        ovr_w, pot_w, need_w, ready_w = 0.38, 0.44, 0.28, 0.10

    if direction == "rebuilding":
        pot_w += 0.16
        need_w -= 0.04
    elif direction == "contending":
        ovr_w += 0.10
        need_w += 0.08
        ready_w += 0.10
        pot_w -= 0.06

    need = _need_score(team, pos)
    upside_gap = max(0, potential - overall)
    nba_ready = _safe_float((prospect.get("traits") or {}).get("nbaReady"), max(0.0, (overall - 55) / 35))
    boom_bust = _safe_float((prospect.get("traits") or {}).get("boomBust"), 0.35)
    work_ethic = _safe_float((prospect.get("traits") or {}).get("workEthic"), 0.65)
    injury_risk = _safe_float((prospect.get("traits") or {}).get("injuryRisk"), 0.12)

    specialist_bonus = 0.0
    attrs = prospect.get("attrs") or []
    if len(attrs) >= 15:
        if round_num == 2:
            if attrs[0] >= 82:
                specialist_bonus += 2.2
            if attrs[8] >= 82 or attrs[10] >= 82 or attrs[12] >= 84:
                specialist_bonus += 2.0
            if attrs[13] >= 82 or attrs[14] >= 82:
                specialist_bonus += 1.2

    age_bonus = 0.0
    if direction == "rebuilding" and age <= 20:
        age_bonus += 1.5
    if direction == "contending" and age >= 21:
        age_bonus += 1.1

    risk_penalty = 0.0
    if direction == "contending":
        risk_penalty += boom_bust * 2.2
    else:
        risk_penalty += boom_bust * 0.9
    risk_penalty += injury_risk * 3.0

    randomness = rng.uniform(-2.8, 2.8)
    if round_num == 2:
        randomness = rng.uniform(-4.5, 4.5)

    score = (
        overall * ovr_w
        + potential * pot_w
        + need * need_w
        + upside_gap * 0.20
        + nba_ready * 6.0 * ready_w
        + work_ethic * 2.8
        + specialist_bonus
        + age_bonus
        - risk_penalty
        + randomness
    )

    return float(score)


def _choose_cpu_prospect(
    state: Dict[str, Any],
    league: Dict[str, Any],
    pick: Dict[str, Any],
    season_year: int,
) -> Dict[str, Any]:
    team_name = pick.get("currentOwnerTeamName") or pick.get("teamName")
    team = _find_team(league, team_name) or {"name": team_name, "players": []}
    history = _history_by_team(league, season_year).get(team_name)
    available = state.get("availableProspects") or []

    pick_num = _safe_int(pick.get("pick"), 60)
    candidate_pool_size = 18 if pick_num <= 10 else 26 if pick_num <= 30 else 34
    pool = sorted(
        available,
        key = lambda p: (_safe_int(p.get("draftProjection"), 999), _safe_int(p.get("trueRank"), 999)),
    )[:candidate_pool_size]

    rng = random.Random(_stable_seed(season_year, pick_num, team_name, "cpu_pick"))
    scored = []
    for prospect in pool:
        scored.append((_prospect_score(prospect, team, history, pick, rng), prospect))

    scored.sort(key = lambda item: item[0], reverse = True)
    return scored[0][1] if scored else available[0]


def _rookie_salary_for_pick(round_num: int, pick_num: int) -> int:
    if round_num == 1:
        # Rough rookie scale approximation. It is intentionally simple for v1.
        return max(2_400_000, int(11_800_000 - (pick_num - 1) * 315_000))

    pick_in_round = max(1, pick_num - 30)
    return max(1_250_000, int(2_250_000 - (pick_in_round - 1) * 28_000))


def _rookie_contract(round_num: int, pick_num: int, season_year: int) -> Dict[str, Any]:
    first_salary = _rookie_salary_for_pick(round_num, pick_num)

    # All drafted players now go through the Rookie Signings event first.
    # First-rounders keep a projected rookie-scale contract, but it is not
    # applied to the 15-man roster until Rookie Signings resolves them.
    if round_num == 1:
        projected_salary_by_year = [
            first_salary,
            int(first_salary * 1.05),
            int(first_salary * 1.10),
            int(first_salary * 1.22),
        ]
        projected_option = {
            "type": "team",
            "yearIndices": [2, 3],
            "picked": None,
        }
        return {
            "type": "unsigned_rookie",
            "startYear": season_year,
            "salaryByYear": [],
            "projectedSalaryByYear": projected_salary_by_year,
            "projectedOption": projected_option,
            "option": None,
            "pendingRookieSigning": True,
            "source": "first_round_pending_rookie_signing",
            "countsAgainstStandardRoster": False,
        }

    projected_salary_by_year = [first_salary, int(first_salary * 1.08)]
    return {
        "type": "unsigned_rookie",
        "startYear": season_year,
        "salaryByYear": [],
        "projectedSalaryByYear": projected_salary_by_year,
        "option": None,
        "pendingRookieSigning": True,
        "source": "draft_pick_pending_rookie_signing",
        "countsAgainstStandardRoster": False,
    }


def _prospect_portrait_url(prospect: Dict[str, Any]) -> str:
    return (
        prospect.get("headshot")
        or prospect.get("image")
        or prospect.get("img")
        or ""
    )


def _scoring_rating(attrs: List[int]) -> float:
    if len(attrs) < 15:
        return 60.0
    return float(
        attrs[0] * 0.28
        + attrs[1] * 0.21
        + attrs[2] * 0.24
        + attrs[4] * 0.10
        + attrs[7] * 0.08
        + attrs[13] * 0.09
    )


# LeagueEditor.jsx v19 OFF/DEF parity helpers.
# These intentionally mirror the advanced player editor math so draft-generated
# rookies do not enter the league with correct OVR but stale OFF/DEF.
T3, MID, CLOSE, FT, BH, PAS, SPD, ATH = 0, 1, 2, 3, 4, 5, 6, 7
PERD, INTD, BLK, STL, REB, OIQ, DIQ = 8, 9, 10, 11, 12, 13, 14

OFF_WEIGHTS_POSZ = {
    "PG": {T3: 0.18, MID: 0.18, CLOSE: 0.18, BH: 0.20, PAS: 0.20, SPD: 0.04, ATH: 0.02, OIQ: 0.00},
    "SG": {T3: 0.18, MID: 0.18, CLOSE: 0.18, BH: 0.14, PAS: 0.14, SPD: 0.06, ATH: 0.06, OIQ: 0.02},
    "SF": {T3: 0.18, MID: 0.18, CLOSE: 0.18, BH: 0.10, PAS: 0.10, SPD: 0.08, ATH: 0.10, OIQ: 0.08},
    "PF": {T3: 0.18, MID: 0.18, CLOSE: 0.18, BH: 0.10, PAS: 0.12, SPD: 0.08, ATH: 0.08, OIQ: 0.08},
    "C": {T3: 0.18, MID: 0.18, CLOSE: 0.18, BH: 0.04, PAS: 0.10, SPD: 0.06, ATH: 0.16, OIQ: 0.10},
}

DEF_WEIGHTS_POSZ = {
    "PG": {PERD: 0.58, STL: 0.32, SPD: 0.06, ATH: 0.04},
    "SG": {PERD: 0.46, STL: 0.26, INTD: 0.12, BLK: 0.08, SPD: 0.04, ATH: 0.04},
    "SF": {PERD: 0.28, STL: 0.18, INTD: 0.28, BLK: 0.18, ATH: 0.05, SPD: 0.03},
    "PF": {INTD: 0.45, BLK: 0.35, PERD: 0.08, STL: 0.08, ATH: 0.04},
    "C": {INTD: 0.52, BLK: 0.40, ATH: 0.06, PERD: 0.01, STL: 0.01},
}

V19_OFF_IDX = [T3, MID, CLOSE, BH, PAS, SPD, ATH, OIQ]
V19_DEF_IDX = [PERD, STL, INTD, BLK, SPD, ATH]
V19_POSITIONS = ["PG", "SG", "SF", "PF", "C"]


def _clamp_float(value: float, lo: float, hi: float) -> float:
    return float(max(lo, min(hi, value)))


def _three_penalty_mult(pos: str) -> float:
    return {"PG": 1.10, "SG": 1.00, "SF": 0.75, "PF": 0.80, "C": 0.30}.get(pos, 1.0)


def _close_penalty_mult(pos: str) -> float:
    return {"PG": 0.30, "SG": 0.45, "SF": 0.70, "PF": 0.85, "C": 1.10}.get(pos, 1.0)


def _bankers_round_js(n: float) -> int:
    f = math.floor(float(n))
    diff = float(n) - f
    if abs(diff - 0.5) < 1e-9:
        return int(f if f % 2 == 0 else f + 1)
    return int(math.floor(float(n) + 0.5))


def _v19_jitter(name: str = "", attrs: Optional[List[int]] = None) -> float:
    safe_attrs = attrs or []
    s_attrs = 0.0
    for i, value in enumerate(safe_attrs):
        s_attrs += (i + 1) * _safe_float(value, 0.0)

    s_name = 0.0
    for ch in str(name or ""):
        s_name += ord(ch)

    seed = (s_attrs + 0.13 * s_name) * 12.9898
    raw = math.sin(seed) * 43758.5453
    frac = raw - math.floor(raw)
    return (frac - 0.5) * 0.7


def _sample_std(values: List[float]) -> float:
    n = len(values)
    if n < 2:
        return 1.0
    mean = sum(values) / n
    variance = sum((value - mean) * (value - mean) for value in values) / (n - 1)
    return max(1.0, math.sqrt(variance))


def _safe_std(value: Any) -> float:
    value = _safe_float(value, 1.0)
    return value if value > 1e-6 else 1.0


def _v19_pf_bridged_weights() -> Dict[int, float]:
    pf = OFF_WEIGHTS_POSZ["PF"]
    sf = OFF_WEIGHTS_POSZ["SF"]
    keys = set(pf.keys()) | set(sf.keys())
    return {key: 0.7 * pf.get(key, 0.0) + 0.3 * sf.get(key, 0.0) for key in keys}


def _league_players_for_v19_baselines(league: Dict[str, Any]) -> List[Dict[str, Any]]:
    conferences = league.get("conferences") or {}
    teams: List[Dict[str, Any]] = []

    if isinstance(conferences, dict):
        if "East" in conferences or "West" in conferences:
            for side in ["East", "West"]:
                teams.extend([team for team in conferences.get(side, []) if isinstance(team, dict)])
        else:
            for conf_teams in conferences.values():
                teams.extend([team for team in conf_teams or [] if isinstance(team, dict)])
    elif isinstance(league.get("teams"), list):
        teams = [team for team in league.get("teams") or [] if isinstance(team, dict)]

    players: List[Dict[str, Any]] = []
    for team in teams:
        for player in team.get("players") or []:
            if isinstance(player, dict):
                players.append(player)
    return players


def _empty_v19_baselines() -> Dict[str, Any]:
    pos_mean = {pos: {idx: 75.0 for idx in set(V19_OFF_IDX + V19_DEF_IDX)} for pos in V19_POSITIONS}
    pos_std = {pos: {idx: 1.0 for idx in set(V19_OFF_IDX + V19_DEF_IDX)} for pos in V19_POSITIONS}
    abs_mean = {idx: 75.0 for idx in V19_OFF_IDX}
    abs_std = {idx: 1.0 for idx in V19_OFF_IDX}
    return {
        "posMean": pos_mean,
        "posStd": pos_std,
        "absMean": abs_mean,
        "absStd": abs_std,
        "offShift": 0.0,
        "defShift": 0.0,
    }


def _calc_off_def_v19_preview(attrs: List[int], pos: str, baselines: Dict[str, Any]) -> Tuple[float, float]:
    p = pos if pos in V19_POSITIONS else "SF"
    safe_attrs = _normalize_attrs(attrs)
    pos_mean = baselines.get("posMean") or {}
    pos_std = baselines.get("posStd") or {}
    abs_mean = baselines.get("absMean") or {}
    abs_std = baselines.get("absStd") or {}

    def z_pos(idx: int) -> float:
        return (_safe_float(safe_attrs[idx], 75.0) - _safe_float((pos_mean.get(p) or {}).get(idx), 75.0)) / _safe_std((pos_std.get(p) or {}).get(idx))

    def z_abs(idx: int) -> float:
        return (_safe_float(safe_attrs[idx], 75.0) - _safe_float(abs_mean.get(idx), 75.0)) / _safe_std(abs_std.get(idx))

    def z_to_rating(z: float) -> float:
        return _clamp_float(75 + 12 * z, 50, 99)

    abs_mix = {"PF": 0.70, "SF": 0.20, "PG": 0.10, "SG": 0.10, "C": 0.10}
    off_weights = _v19_pf_bridged_weights() if p == "PF" else OFF_WEIGHTS_POSZ.get(p, OFF_WEIGHTS_POSZ["SF"])

    z_pos_sum = 0.0
    z_abs_sum = 0.0
    for idx, weight in off_weights.items():
        z_pos_sum += float(weight) * z_pos(idx)
        z_abs_sum += float(weight) * z_abs(idx)

    mix = abs_mix.get(p, 0.10)
    off = z_to_rating((1 - mix) * z_pos_sum + mix * z_abs_sum)

    t3_gap = max(0.0, 50 - _safe_float(safe_attrs[T3], 0.0) - 2)
    close_gap = max(0.0, 60 - _safe_float(safe_attrs[CLOSE], 0.0) - 2)
    off -= min(6.0, 0.07 * _three_penalty_mult(p) * t3_gap)
    off -= min(6.0, 0.07 * _close_penalty_mult(p) * close_gap)
    off = _clamp_float(off, 50, 99)

    def_weights = DEF_WEIGHTS_POSZ.get(p, {})
    zsum_d = 0.0
    for idx, weight in def_weights.items():
        zsum_d += float(weight) * z_pos(idx)
    defense = z_to_rating(zsum_d)

    athleticism = _safe_float(safe_attrs[ATH], 75.0)
    abs_pen = max(0.0, 78 - athleticism) * 0.08
    rel_pen = max(0.0, _safe_float((pos_mean.get(p) or {}).get(ATH), 75.0) - athleticism) * 0.05

    if p == "SF":
        abs_pen *= 0.8
        rel_pen *= 0.8
        defense += 2.5
        perimeter_d = _safe_float(safe_attrs[PERD], 75.0)
        interior_d = _safe_float(safe_attrs[INTD], 75.0)
        high = max(perimeter_d, interior_d)
        low = min(perimeter_d, interior_d)
        if perimeter_d >= 88 and interior_d >= 88:
            defense += min(1.0, (min(perimeter_d, interior_d) - 88) * 0.05)
        tier = 0.0
        if perimeter_d >= 90 or interior_d >= 90:
            tier += 0.5
        if perimeter_d >= 85 and interior_d >= 85:
            tier += 0.5
        if high >= 93 and low >= 84:
            tier += 0.5
        if high >= 94 and low >= 90:
            tier += 0.5
        defense += min(2.0, tier)

    defense -= min(4.0, abs_pen + rel_pen)
    def_cap = 99 if p == "C" else 98 if p == "PF" else 96
    defense = _clamp_float(defense, 50, def_cap)

    return off, defense


def _build_v19_rating_baselines(league: Dict[str, Any]) -> Dict[str, Any]:
    players = _league_players_for_v19_baselines(league or {})
    baselines = _empty_v19_baselines()

    pos_buckets = {
        pos: {idx: [] for idx in set(V19_OFF_IDX + V19_DEF_IDX)}
        for pos in V19_POSITIONS
    }
    abs_buckets = {idx: [] for idx in V19_OFF_IDX}

    for player in players:
        pos = str(player.get("pos") or player.get("position") or "SF").upper()
        if pos not in V19_POSITIONS:
            pos = "SF"
        attrs = _normalize_attrs(player.get("attrs") or player.get("attributes") or [])

        # This mirrors LeagueEditor.jsx, including the duplicate SPD/ATH pushes
        # created by concatenating offensive and defensive index arrays.
        for idx in V19_OFF_IDX + V19_DEF_IDX:
            pos_buckets[pos][idx].append(_safe_float(attrs[idx], 75.0))
        for idx in V19_OFF_IDX:
            abs_buckets[idx].append(_safe_float(attrs[idx], 75.0))

    for pos in V19_POSITIONS:
        for idx in set(V19_OFF_IDX + V19_DEF_IDX):
            arr = pos_buckets[pos][idx]
            baselines["posMean"][pos][idx] = sum(arr) / len(arr) if arr else 75.0
            baselines["posStd"][pos][idx] = _sample_std(arr) if arr else 1.0

    for idx in V19_OFF_IDX:
        arr = abs_buckets[idx]
        baselines["absMean"][idx] = sum(arr) / len(arr) if arr else 75.0
        baselines["absStd"][idx] = _sample_std(arr) if arr else 1.0

    if not players:
        return baselines

    sum_ovr = 0.0
    sum_off = 0.0
    sum_def = 0.0
    n = 0
    for player in players:
        pos = str(player.get("pos") or player.get("position") or "SF").upper()
        if pos not in V19_POSITIONS:
            pos = "SF"
        attrs = _normalize_attrs(player.get("attrs") or player.get("attributes") or [])
        sum_ovr += _calc_overall_from_attrs(attrs, pos)
        off_preview, def_preview = _calc_off_def_v19_preview(attrs, pos, baselines)
        sum_off += off_preview
        sum_def += def_preview
        n += 1

    if n:
        ov_mean = sum_ovr / n
        off_mean = sum_off / n
        def_mean = sum_def / n
        baselines["offShift"] = _clamp_float(ov_mean - off_mean, -1.5, 1.5)
        baselines["defShift"] = _clamp_float(ov_mean - def_mean, -1.5, 1.5)

    return baselines


def _calc_off_def_v19(
    attrs: List[int],
    pos: str,
    name: str = "",
    height: Any = 78,
    baselines: Optional[Dict[str, Any]] = None,
) -> Tuple[int, int]:
    # height is accepted for exact call-shape parity with LeagueEditor.jsx. The
    # current v19 formula does not use height directly.
    _ = height
    p = str(pos or "SF").upper()
    if p not in V19_POSITIONS:
        p = "SF"

    safe_attrs = _normalize_attrs(attrs)
    active_baselines = baselines or _empty_v19_baselines()
    off, defense = _calc_off_def_v19_preview(safe_attrs, p, active_baselines)

    jitter = _v19_jitter(name, safe_attrs)
    off = _clamp_float(off + _safe_float(active_baselines.get("offShift"), 0.0) + jitter, 50, 99)
    def_cap = 99 if p == "C" else 98 if p == "PF" else 96
    defense = _clamp_float(
        defense + _safe_float(active_baselines.get("defShift"), 0.0) + 0.7 * jitter,
        50,
        def_cap,
    )

    return _bankers_round_js(off), _bankers_round_js(defense)



def _explode_v19(value: Any, power: float) -> float:
    return (_safe_float(value, 0.0) / 100.0) ** power


def _close_penalty_v19(close: Any) -> float:
    close_value = _safe_float(close, 0.0)
    if close_value >= 70:
        return 0.0
    return ((70 - close_value) / 30.0) ** 2.3


def _calc_scoring_rating_v19(pos: str, three: Any, mid: Any, close: Any) -> float:
    p = str(pos or "SF").upper()
    three_value = _safe_float(three, 75.0)
    mid_value = _safe_float(mid, 75.0)
    close_value = _safe_float(close, 75.0)

    if p in {"PG", "SG"}:
        three_term = _explode_v19(three_value, 7) * 1.2
        mid_term = _explode_v19(mid_value, 7) * 1.55
        close_term = _explode_v19(close_value, 6) * 1.1
        base = 0.38 * (three_value / 100.0) + 0.4 * (mid_value / 100.0) + 0.22 * (close_value / 100.0)
        penalty = _close_penalty_v19(close_value) * 1.7
        raw = base + three_term + mid_term + close_term - penalty
        return float(raw * 14.75 + 43.5)

    if p == "SF":
        three_term = _explode_v19(three_value, 7) * 1.05
        mid_term = _explode_v19(mid_value, 7) * 1.4
        close_term = _explode_v19(close_value, 7) * 1.5
        base = 0.32 * (three_value / 100.0) + 0.35 * (mid_value / 100.0) + 0.33 * (close_value / 100.0)
        penalty = _close_penalty_v19(close_value) * 1.2
        raw = base + three_term + mid_term + close_term - penalty
        return float(raw * 14.75 + 43.5)

    if p in {"PF", "C"}:
        close_term = _explode_v19(close_value, 8) * 1.95
        mid_term = _explode_v19(mid_value, 6) * 1.3
        three_term = _explode_v19(three_value, 5) * 0.6
        base = 0.58 * (close_value / 100.0) + 0.27 * (mid_value / 100.0) + 0.15 * (three_value / 100.0)
        penalty = _close_penalty_v19(close_value) * 2.0
        raw = base + three_term + mid_term + close_term - penalty
        return float(raw * 14.75 + 43.5)

    return 50.0


def _ratings_from_attrs(attrs: List[int]) -> Tuple[int, int]:
    if len(attrs) < 15:
        return 70, 70
    off_indices = [0, 1, 2, 3, 4, 5, 7, 13]
    def_indices = [8, 9, 10, 11, 12, 14]
    off_rating = round(sum(attrs[i] for i in off_indices) / len(off_indices))
    def_rating = round(sum(attrs[i] for i in def_indices) / len(def_indices))
    return int(off_rating), int(def_rating)


def _normalize_draft_prospect_for_state(
    prospect: Dict[str, Any],
    season_year: int,
    index: int = 0,
    rating_baselines: Optional[Dict[str, Any]] = None,
) -> Dict[str, Any]:
    p = copy.deepcopy(prospect or {})
    raw_attrs = p.get("attrs") if isinstance(p.get("attrs"), list) else p.get("attributes")
    has_source_truth_attrs = _has_source_truth_attrs(raw_attrs)
    attrs = _normalize_attrs(raw_attrs or [])
    p["attrs"] = attrs

    if has_source_truth_attrs:
        source_truth_overall = _calc_overall_from_attrs(
            attrs,
            p.get("pos") or p.get("position") or "SF",
        )
        p["overall"] = source_truth_overall
        p["ovr"] = source_truth_overall
        p["rating"] = source_truth_overall
        p["overallSource"] = "attrs_source_truth"

    if not p.get("name") and p.get("playerName"):
        p["name"] = p.get("playerName")
    if not p.get("playerName") and p.get("name"):
        p["playerName"] = p.get("name")

    p.setdefault("draftClassYear", season_year)
    p.setdefault("seasonYear", season_year)
    p.setdefault("draftProjection", _safe_int(p.get("trueRank") or p.get("rank"), index + 1))
    p.setdefault("trueRank", _safe_int(p.get("draftProjection") or p.get("rank"), index + 1))

    if p.get("id") is None or p.get("id") == "":
        p["id"] = f"custom_{season_year}_{str(index + 1).zfill(3)}_{_safe_id_text(p.get('name') or p.get('playerName') or 'prospect')}"

    if p.get("overall") is None and p.get("ovr") is None and p.get("rating") is None:
        p["overall"] = _resolve_prospect_overall(p, 65)

    overall = _resolve_prospect_overall(p, 65)
    if p.get("potential") is None or _safe_int(p.get("potential"), 0) <= 0:
        p["potential"] = overall
    else:
        p["potential"] = max(overall, _safe_int(p.get("potential"), overall))

    off_rating, def_rating = _calc_off_def_v19(
        attrs,
        p.get("pos") or p.get("position") or "SF",
        p.get("name") or p.get("playerName") or "",
        p.get("height") or 78,
        rating_baselines,
    )
    p["offRating"] = off_rating
    p["defRating"] = def_rating
    p["offense"] = off_rating
    p["defense"] = def_rating
    p["offRatingSource"] = "v19_attrs_source_truth"
    p["defRatingSource"] = "v19_attrs_source_truth"
    p["stamina"] = _calc_stamina_from_attrs(p.get("age"), attrs)
    p["staminaSource"] = "attrs_age_source_truth"
    p["scoringRating"] = _calc_scoring_rating_v19(
        p.get("pos") or p.get("position") or "SF",
        attrs[T3],
        attrs[MID],
        attrs[CLOSE],
    )
    p["scoringRatingSource"] = "v19_attrs_source_truth"

    source = (
        p.get("college") or p.get("school") or p.get("university") or p.get("academy") or
        p.get("academyName") or p.get("sourceName") or p.get("draftSource") or ""
    )
    if source:
        p.setdefault("college", source)
        p.setdefault("school", source)
        p.setdefault("academy", source)
        p.setdefault("academyName", source)
        p.setdefault("sourceName", source)
        p.setdefault("draftSource", source)

    return p


def _prospect_to_player(
    prospect: Dict[str, Any],
    team_name: str,
    pick: Optional[Dict[str, Any]],
    season_year: int,
    drafted: bool = True,
    rating_baselines: Optional[Dict[str, Any]] = None,
) -> Dict[str, Any]:
    attrs = [int(x) for x in (prospect.get("attrs") or [])]
    while len(attrs) < 15:
        attrs.append(60)

    overall_rating = _resolve_prospect_overall(prospect, 65)
    off_rating, def_rating = _calc_off_def_v19(
        attrs,
        prospect.get("pos") or prospect.get("position") or "SF",
        prospect.get("name") or prospect.get("playerName") or "",
        prospect.get("height") or 78,
        rating_baselines,
    )

    overall_pick = _safe_int(pick.get("pick"), 0) if pick else None
    round_num = _safe_int(pick.get("round"), 0) if pick else None
    pick_in_round = _safe_int(pick.get("pickInRound"), 0) if pick else None
    player_id_suffix = _safe_id_text(prospect.get("name") or prospect.get("id") or "rookie")
    player_id = f"rookie_{season_year}_{overall_pick or 'udfa'}_{player_id_suffix}"

    contract = _rookie_contract(round_num, overall_pick or 60, season_year) if drafted and pick else {
        "startYear": season_year,
        "salaryByYear": [],
        "option": None,
    }

    rights_team = team_name if drafted else None
    acquired_via = "draft" if drafted else "undrafted_free_agent"
    contract_type = contract.get("type") if isinstance(contract, dict) else "standard"
    if drafted:
        roster_status = "rookie_pending"
        assignment_status = "unsigned_rookie"
        rookie_pending = True
    else:
        roster_status = "free_agent"
        assignment_status = "free_agent"
        rookie_pending = False

    transaction_label = (
        f"Drafted No. {overall_pick} by {team_name}"
        if drafted and overall_pick
        else "Entered free agency as an undrafted rookie"
    )

    portrait_url = _prospect_portrait_url(prospect)

    return {
        "id": player_id,
        "name": prospect.get("name") or "Generated Rookie",
        "pos": prospect.get("pos") or "SF",
        "secondaryPos": prospect.get("secondaryPos") or "",
        "age": _safe_int(prospect.get("age"), 20),
        "height": _safe_int(prospect.get("height"), 78),
        "weight": _safe_int(prospect.get("weight"), 215),
        "potential": max(overall_rating, _safe_int(prospect.get("potential"), overall_rating)),
        "overall": overall_rating,
        "offRating": off_rating,
        "defRating": def_rating,
        "offense": off_rating,
        "defense": def_rating,
        "offRatingSource": "v19_attrs_source_truth",
        "defRatingSource": "v19_attrs_source_truth",
        "stamina": _calc_stamina_from_attrs(_safe_int(prospect.get("age"), 20), attrs),
        "staminaSource": "attrs_age_source_truth",
        "scoringRating": _calc_scoring_rating_v19(
            prospect.get("pos") or prospect.get("position") or "SF",
            attrs[T3],
            attrs[MID],
            attrs[CLOSE],
        ),
        "scoringRatingSource": "v19_attrs_source_truth",
        "attrs": attrs,
        "portraitId": prospect.get("portraitId") or "",
        "headshot": portrait_url,
        "image": portrait_url,
        "img": portrait_url,
        "birthMonth": _safe_int(prospect.get("birthMonth"), 1),
        "birthDay": _safe_int(prospect.get("birthDay"), 1),
        "lastBirthdayYear": season_year,
        "team": team_name if drafted else "Free Agent",
        "contract": contract,
        "contractType": contract_type,
        "rosterStatus": roster_status,
        "assignmentStatus": assignment_status,
        "rookieSigningPending": rookie_pending,
        "rights": {
            "heldByTeam": rights_team,
            "seasonsTowardBird": 0,
            "birdLevel": "none" if not drafted else "non_bird",
            "rookieScale": bool(drafted and round_num == 1),
            "restrictedFreeAgent": False,
        },
        "meta": {
            "draftYear": season_year if drafted else None,
            "draftRound": round_num if drafted else None,
            "draftPick": overall_pick if drafted else None,
            "draftPickInRound": pick_in_round if drafted else None,
            "draftedBy": team_name if drafted else None,
            "acquiredVia": acquired_via,
            "rookieSigningPending": rookie_pending,
            "rookieSigningDecision": None,
            "proSeasons": 0,
            "yearsWithCurrentTeam": 0,
            "college": prospect.get("college") or "",
            "nationality": prospect.get("nationality") or "",
            "archetype": prospect.get("archetype") or "",
        },
        "history": {
            "seasons": [],
            "accolades": [],
            "transactions": [
                {
                    "seasonYear": season_year,
                    "type": acquired_via,
                    "label": transaction_label,
                    "teamName": team_name if drafted else "Free Agent",
                }
            ],
        },
    }


def _add_player_to_team(league: Dict[str, Any], team_name: str, player: Dict[str, Any]) -> bool:
    team = _find_team(league, team_name)
    if not team:
        return False
    if not isinstance(team.get("players"), list):
        team["players"] = []
    if not isinstance(team.get("pendingRookieSignings"), list):
        team["pendingRookieSignings"] = []

    player_id = player.get("id")
    contract = player.get("contract") if isinstance(player.get("contract"), dict) else {}
    contract_type = str(player.get("contractType") or contract.get("type") or "standard").lower()
    is_pending_rookie = bool(
        player.get("rookieSigningPending")
        or contract.get("pendingRookieSigning")
        or contract_type in {"unsigned_rookie", "rookie_pending"}
    )

    target = team["pendingRookieSignings"] if is_pending_rookie else team["players"]
    existing_ids = {p.get("id") for p in target if isinstance(p, dict)}
    if player_id not in existing_ids:
        target.append(player)
    return True


def _add_undrafted_to_free_agents(league: Dict[str, Any], state: Dict[str, Any], season_year: int) -> None:
    if state.get("undraftedProcessed"):
        return

    available = state.get("availableProspects") or []
    if not isinstance(league.get("freeAgents"), list):
        league["freeAgents"] = []

    existing_ids = {p.get("id") for p in league["freeAgents"] if isinstance(p, dict)}
    undrafted_added = []
    rating_baselines = _build_v19_rating_baselines(league)

    # Keep the top remaining undrafted prospects available. This gives the FA pool life
    # without bloating localStorage too aggressively.
    for prospect in available[:24]:
        player = _prospect_to_player(
            prospect,
            "Free Agent",
            None,
            season_year,
            drafted = False,
            rating_baselines = rating_baselines,
        )
        if player.get("id") in existing_ids:
            continue
        league["freeAgents"].append(player)
        existing_ids.add(player.get("id"))
        undrafted_added.append({
            "playerId": player.get("id"),
            "playerName": player.get("name"),
            "overall": player.get("overall"),
            "potential": player.get("potential"),
            "pos": player.get("pos"),
        })

    state["undraftedProcessed"] = True
    state["undraftedAddedToFreeAgency"] = undrafted_added


def _normalize_draft_order(draft_order: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    out = []
    for idx, row in enumerate(draft_order or []):
        if not isinstance(row, dict):
            continue
        pick = _safe_int(row.get("pick"), idx + 1)
        round_num = _safe_int(row.get("round"), 1 if pick <= 30 else 2)
        pick_in_round = _safe_int(row.get("pickInRound"), pick if round_num == 1 else pick - 30)
        team_name = row.get("currentOwnerTeamName") or row.get("teamName") or row.get("originalTeamName")
        out.append({
            **row,
            "pick": pick,
            "round": round_num,
            "pickInRound": pick_in_round,
            "teamName": row.get("teamName") or team_name,
            "currentOwnerTeamName": team_name,
            "originalTeamName": row.get("originalTeamName") or row.get("teamName") or team_name,
        })
    return sorted(out, key = lambda r: _safe_int(r.get("pick"), 999))


def initialize_draft(league_data: Dict[str, Any], payload: Dict[str, Any]) -> Dict[str, Any]:
    league = copy.deepcopy(_plain(league_data) or {})
    payload = _plain(payload) or {}
    season_year = _get_season_year(league, payload)

    existing_state = payload.get("draftState") or (league.get("draftState") or {}).get("draft")
    existing_state_season = _safe_int(existing_state.get("seasonYear"), 0) if isinstance(existing_state, dict) else 0
    if (
        isinstance(existing_state, dict)
        and existing_state_season == season_year
        and existing_state.get("draftOrder")
        and existing_state.get("availableProspects")
    ):
        return {
            "ok": True,
            "version": DRAFT_LOGIC_VERSION,
            "leagueData": league,
            "draftState": existing_state,
            "message": "Loaded existing draft state.",
        }

    draft_order = payload.get("draftOrder") or (league.get("draftState") or {}).get("draftOrder") or []
    draft_order = _normalize_draft_order(draft_order)

    if not draft_order:
        return {
            "ok": False,
            "reason": "MISSING_DRAFT_ORDER",
            "version": DRAFT_LOGIC_VERSION,
            "leagueData": league,
        }

    draft_class = payload.get("draftClass") or (league.get("draftState") or {}).get("draftClass")
    if isinstance(draft_class, list) and draft_class and not _draft_class_matches_season(draft_class, season_year):
        draft_class = None

    if not isinstance(draft_class, list) or len(draft_class) < len(draft_order):
        count = max(84, len(draft_order) + 24)
        class_seed = payload.get("classSeed")
        if class_seed is None:
            class_seed = _stable_seed("draft_class", season_year)

        if generate_draft_class is None:
            return {
                "ok": False,
                "reason": "DRAFT_CLASS_GENERATOR_NOT_AVAILABLE",
                "version": DRAFT_LOGIC_VERSION,
                "leagueData": league,
            }

        generated = generate_draft_class(
            season_year = season_year,
            count = count,
            seed = _safe_int(class_seed, _stable_seed("draft_class", season_year)),
        )
        draft_class = generated.get("draftClass") or []
        class_meta = generated.get("classMeta") or {}
    else:
        class_meta = {
            "seasonYear": season_year,
            "summary": "Loaded provided draft class",
            "prospectCount": len(draft_class),
        }

    rating_baselines = _build_v19_rating_baselines(league)
    draft_class = [
        _normalize_draft_prospect_for_state(p, season_year, index, rating_baselines)
        for index, p in enumerate(draft_class or [])
    ]

    available = sorted(
        [copy.deepcopy(p) for p in draft_class],
        key = lambda p: (_safe_int(p.get("draftProjection"), 999), _safe_int(p.get("trueRank"), 999)),
    )

    state = {
        "version": DRAFT_LOGIC_VERSION,
        "seasonYear": season_year,
        "currentPickIndex": 0,
        "draftOrder": draft_order,
        "draftClass": draft_class,
        "classMeta": class_meta,
        "availableProspects": available,
        "draftedPicks": [],
        "completed": False,
        "undraftedProcessed": False,
        "undraftedAddedToFreeAgency": [],
    }

    league.setdefault("draftState", {})
    league["draftState"]["draft"] = state
    league["draftState"]["draftClass"] = draft_class

    return {
        "ok": True,
        "version": DRAFT_LOGIC_VERSION,
        "leagueData": league,
        "draftState": state,
        "message": "Initialized draft.",
    }


def _select_prospect_by_id(available: List[Dict[str, Any]], prospect_id: str) -> Optional[Dict[str, Any]]:
    for prospect in available:
        if prospect.get("id") == prospect_id:
            return prospect
    return None


def _complete_if_needed(league: Dict[str, Any], state: Dict[str, Any], season_year: int) -> None:
    if _safe_int(state.get("currentPickIndex"), 0) >= len(state.get("draftOrder") or []):
        state["completed"] = True
        _add_undrafted_to_free_agents(league, state, season_year)


def make_pick(
    league_data: Dict[str, Any],
    payload: Dict[str, Any],
    force_cpu: bool = False,
) -> Dict[str, Any]:
    league = copy.deepcopy(_plain(league_data) or {})
    payload = _plain(payload) or {}
    season_year = _get_season_year(league, payload)

    state = copy.deepcopy(payload.get("draftState") or (league.get("draftState") or {}).get("draft") or {})
    if not state or not state.get("draftOrder"):
        init = initialize_draft(league, payload)
        if not init.get("ok"):
            return init
        state = init.get("draftState") or {}
        league = init.get("leagueData") or league

    if state.get("completed"):
        _complete_if_needed(league, state, season_year)
        league.setdefault("draftState", {})["draft"] = state
        return {
            "ok": True,
            "version": DRAFT_LOGIC_VERSION,
            "leagueData": league,
            "draftState": state,
            "message": "Draft already complete.",
        }

    current_index = _safe_int(state.get("currentPickIndex"), 0)
    draft_order = state.get("draftOrder") or []
    if current_index >= len(draft_order):
        _complete_if_needed(league, state, season_year)
        league.setdefault("draftState", {})["draft"] = state
        return {
            "ok": True,
            "version": DRAFT_LOGIC_VERSION,
            "leagueData": league,
            "draftState": state,
            "message": "Draft complete.",
        }

    pick = draft_order[current_index]
    team_name = pick.get("currentOwnerTeamName") or pick.get("teamName")
    user_team_name = payload.get("userTeamName")
    prospect_id = payload.get("prospectId")
    available = state.get("availableProspects") or []

    if not available:
        state["completed"] = True
        _complete_if_needed(league, state, season_year)
        league.setdefault("draftState", {})["draft"] = state
        return {
            "ok": True,
            "version": DRAFT_LOGIC_VERSION,
            "leagueData": league,
            "draftState": state,
            "message": "No available prospects remaining.",
        }

    is_user_pick = bool(user_team_name and team_name == user_team_name and not force_cpu)

    if is_user_pick:
        if not prospect_id:
            return {
                "ok": False,
                "reason": "USER_PICK_REQUIRES_PROSPECT_ID",
                "version": DRAFT_LOGIC_VERSION,
                "leagueData": league,
                "draftState": state,
            }
        prospect = _select_prospect_by_id(available, prospect_id)
        if not prospect:
            return {
                "ok": False,
                "reason": "PROSPECT_NOT_AVAILABLE",
                "version": DRAFT_LOGIC_VERSION,
                "leagueData": league,
                "draftState": state,
            }
    else:
        prospect = _choose_cpu_prospect(state, league, pick, season_year)

    rating_baselines = _build_v19_rating_baselines(league)
    player = _prospect_to_player(
        prospect,
        team_name,
        pick,
        season_year,
        drafted = True,
        rating_baselines = rating_baselines,
    )
    added = _add_player_to_team(league, team_name, player)

    pick_record = {
        "pick": pick.get("pick"),
        "round": pick.get("round"),
        "pickInRound": pick.get("pickInRound"),
        "teamName": team_name,
        "originalTeamName": pick.get("originalTeamName") or team_name,
        "playerId": player.get("id"),
        "playerName": player.get("name"),
        "pos": player.get("pos"),
        "overall": player.get("overall"),
        "potential": player.get("potential"),
        "age": player.get("age"),
        "portraitId": player.get("portraitId") or "",
        "headshot": player.get("headshot") or "",
        "image": player.get("image") or "",
        "img": player.get("img") or "",
        "archetype": prospect.get("archetype") or "",
        "tier": prospect.get("tier") or "",
        "userControlled": bool(is_user_pick),
        "addedToRoster": bool(added),
    }

    state["draftedPicks"] = (state.get("draftedPicks") or []) + [pick_record]
    state["availableProspects"] = [p for p in available if p.get("id") != prospect.get("id")]
    state["currentPickIndex"] = current_index + 1

    _complete_if_needed(league, state, season_year)

    league.setdefault("draftState", {})
    league["draftState"]["draft"] = state
    league["draftState"]["draftComplete"] = bool(state.get("completed"))

    return {
        "ok": True,
        "version": DRAFT_LOGIC_VERSION,
        "leagueData": league,
        "draftState": state,
        "pick": pick_record,
    }


def sim_until_user_pick(league_data: Dict[str, Any], payload: Dict[str, Any]) -> Dict[str, Any]:
    league = copy.deepcopy(_plain(league_data) or {})
    payload = _plain(payload) or {}
    user_team_name = payload.get("userTeamName")
    season_year = _get_season_year(league, payload)

    state = copy.deepcopy(payload.get("draftState") or (league.get("draftState") or {}).get("draft") or {})
    if not state or not state.get("draftOrder"):
        init = initialize_draft(league, payload)
        if not init.get("ok"):
            return init
        league = init.get("leagueData") or league
        state = init.get("draftState") or {}

    picks_made = []
    safety = 0

    while not state.get("completed") and safety < 80:
        safety += 1
        idx = _safe_int(state.get("currentPickIndex"), 0)
        order = state.get("draftOrder") or []
        if idx >= len(order):
            break
        current = order[idx]
        team_name = current.get("currentOwnerTeamName") or current.get("teamName")

        if user_team_name and team_name == user_team_name:
            break

        result = make_pick(league, {**payload, "draftState": state, "userTeamName": user_team_name}, force_cpu = True)
        if not result.get("ok"):
            return result
        league = result.get("leagueData") or league
        state = result.get("draftState") or state
        if result.get("pick"):
            picks_made.append(result.get("pick"))

    league.setdefault("draftState", {})["draft"] = state
    return {
        "ok": True,
        "version": DRAFT_LOGIC_VERSION,
        "leagueData": league,
        "draftState": state,
        "picksMade": picks_made,
        "message": "Simmed to user pick or draft completion.",
    }


def sim_rest_of_draft(league_data: Dict[str, Any], payload: Dict[str, Any]) -> Dict[str, Any]:
    league = copy.deepcopy(_plain(league_data) or {})
    payload = _plain(payload) or {}
    user_team_name = payload.get("userTeamName")

    state = copy.deepcopy(payload.get("draftState") or (league.get("draftState") or {}).get("draft") or {})
    if not state or not state.get("draftOrder"):
        init = initialize_draft(league, payload)
        if not init.get("ok"):
            return init
        league = init.get("leagueData") or league
        state = init.get("draftState") or {}

    picks_made = []
    safety = 0

    while not state.get("completed") and safety < 120:
        safety += 1
        result = make_pick(league, {**payload, "draftState": state, "userTeamName": user_team_name}, force_cpu = True)
        if not result.get("ok"):
            return result
        league = result.get("leagueData") or league
        state = result.get("draftState") or state
        if result.get("pick"):
            picks_made.append(result.get("pick"))

    league.setdefault("draftState", {})["draft"] = state
    league["draftState"]["draftComplete"] = bool(state.get("completed"))

    return {
        "ok": True,
        "version": DRAFT_LOGIC_VERSION,
        "leagueData": league,
        "draftState": state,
        "picksMade": picks_made,
        "message": "Simmed rest of draft.",
    }


def handle_request(request: Dict[str, Any]) -> Dict[str, Any]:
    req = _plain(request) or {}
    action = req.get("action") or "initialize_draft"
    league_data = req.get("leagueData") or req.get("league") or {}
    payload = req.get("payload") or {}

    if action == "initialize_draft":
        return initialize_draft(league_data, payload)

    if action == "make_user_pick":
        return make_pick(league_data, payload, force_cpu = False)

    if action == "sim_one_pick":
        return make_pick(league_data, payload, force_cpu = True)

    if action == "sim_to_user_pick":
        return sim_until_user_pick(league_data, payload)

    if action == "sim_rest_of_draft":
        return sim_rest_of_draft(league_data, payload)

    return {
        "ok": False,
        "reason": f"UNKNOWN_DRAFT_ACTION: {action}",
        "version": DRAFT_LOGIC_VERSION,
    }
