"""
draft_logic.py
Basketball Manager NBA Draft logic.

This file handles:
- Initializing a draft from a locked draft order.
- CPU pick decisions using talent, upside, roster need, timeline, and randomness.
- User picks.
- Converting prospects into the game's normal player structure.
- Adding drafted rookies to rosters and undrafted prospects to free agency.
"""

from __future__ import annotations

import copy
import math
import random
import re
from typing import Any, Dict, List, Optional, Tuple

try:
    from autogenerated_draft_class import generate_draft_class
except Exception:
    generate_draft_class = None

DRAFT_LOGIC_VERSION = "2026-05-28_draft_logic_v2_rookie_headshots"

POSITION_ORDER = ["PG", "SG", "SF", "PF", "C"]
POSITION_BUCKETS = {
    "PG": {"PG"},
    "SG": {"SG", "PG"},
    "SF": {"SF", "SG", "PF"},
    "PF": {"PF", "SF", "C"},
    "C": {"C", "PF"},
}


def _plain(value: Any) -> Any:
    if value is None:
        return None
    if isinstance(value, dict):
        return {str(k): _plain(v) for k, v in value.items()}
    if isinstance(value, list):
        return [_plain(v) for v in value]
    if isinstance(value, tuple):
        return [_plain(v) for v in value]
    try:
        if hasattr(value, "to_py"):
            return _plain(value.to_py())
    except Exception:
        pass
    return value


def _safe_int(value: Any, default: int = 0) -> int:
    try:
        if value is None:
            return default
        return int(float(value))
    except Exception:
        return default


def _safe_float(value: Any, default: float = 0.0) -> float:
    try:
        if value is None:
            return default
        return float(value)
    except Exception:
        return default


def _clamp(value: float, lo: int, hi: int) -> int:
    return int(max(lo, min(hi, round(value))))


def _stable_seed(*parts: Any) -> int:
    text = "|".join(str(part) for part in parts)
    total = 0
    for i, ch in enumerate(text):
        total = (total + (i + 1) * ord(ch)) % 2_147_483_647
    return total or 20260527


def _safe_id_text(text: str) -> str:
    clean = re.sub(r"[^a-zA-Z0-9]+", "_", str(text or "").lower()).strip("_")
    return clean or "player"


OVERALL_POS_PARAMS = {
    "PG": {
        "weights": [0.11, 0.05, 0.03, 0.05, 0.17, 0.17, 0.10, 0.07, 0.10, 0.02, 0.01, 0.07, 0.05, 0.01, 0.01],
        "prim": [5, 6, 1, 7],
        "alpha": 0.25,
    },
    "SG": {
        "weights": [0.15, 0.08, 0.05, 0.05, 0.12, 0.07, 0.11, 0.07, 0.11, 0.03, 0.02, 0.08, 0.06, 0.01, 0.01],
        "prim": [1, 5, 7],
        "alpha": 0.28,
    },
    "SF": {
        "weights": [0.12, 0.09, 0.07, 0.04, 0.08, 0.07, 0.10, 0.10, 0.10, 0.06, 0.04, 0.08, 0.05, 0.01, 0.01],
        "prim": [1, 8, 9],
        "alpha": 0.22,
    },
    "PF": {
        "weights": [0.07, 0.07, 0.12, 0.03, 0.05, 0.05, 0.08, 0.12, 0.07, 0.13, 0.08, 0.08, 0.05, 0.01, 0.01],
        "prim": [3, 10, 8],
        "alpha": 0.24,
    },
    "C": {
        "weights": [0.04, 0.06, 0.17, 0.03, 0.02, 0.04, 0.07, 0.12, 0.05, 0.16, 0.13, 0.06, 0.08, 0.01, 0.01],
        "prim": [3, 10, 11, 13],
        "alpha": 0.30,
    },
}


def _normalize_attrs(attrs: Any, default: int = 75) -> List[int]:
    out: List[int] = []
    if isinstance(attrs, list):
        for value in attrs[:15]:
            out.append(_clamp(_safe_float(value, default), 25, 99))
    while len(out) < 15:
        out.append(default)
    return out


def _calc_overall_from_attrs(attrs: List[int], pos: str) -> int:
    p = OVERALL_POS_PARAMS.get(str(pos or "SF").upper(), OVERALL_POS_PARAMS["SF"])
    safe_attrs = _normalize_attrs(attrs)
    weighted = sum(w * safe_attrs[i] for i, w in enumerate(p["weights"]))
    primary_indices = [max(0, int(i) - 1) for i in p["prim"]]
    peak = max(safe_attrs[i] for i in primary_indices)
    blended = p["alpha"] * peak + (1 - p["alpha"]) * weighted
    overall = round(min(99, max(60, 60 + 39 * (1 / (1 + math.exp(-0.12 * (blended - 77)))))))
    num_90 = len([a for a in safe_attrs if a >= 90])
    if num_90 >= 3:
        overall = min(99, overall + (num_90 - 2))
    return int(overall)


def _resolve_prospect_overall(prospect: Dict[str, Any], default: int = 65) -> int:
    for key in ["overall", "ovr", "rating"]:
        if prospect.get(key) is not None:
            return _safe_int(prospect.get(key), default)
    return _calc_overall_from_attrs(_normalize_attrs(prospect.get("attrs") or prospect.get("attributes") or []), prospect.get("pos") or prospect.get("position") or "SF")


def _calc_stamina_from_attrs(age: Any, attrs: List[int]) -> int:
    resolved_age = max(18, min(45, _safe_int(age, 19)))
    athleticism = max(25, min(99, _safe_int(attrs[7] if len(attrs) > 7 else 75, 75)))
    if resolved_age <= 27:
        age_factor = 1.0
    elif resolved_age <= 34:
        age_factor = 0.95 - (0.15 * (resolved_age - 28)) / 6
    else:
        age_factor = 0.8 - (0.45 * (resolved_age - 35)) / 10
    age_factor = max(0.35, min(1.0, age_factor))
    raw = age_factor * 99 * 0.575 + athleticism * 0.425
    norm = (raw - 40) / (99 - 40)
    return _clamp(40 + norm * 59, 40, 99)


def _get_all_teams(league: Dict[str, Any]) -> List[Dict[str, Any]]:
    if isinstance(league.get("teams"), list):
        return league.get("teams") or []

    conferences = league.get("conferences") or {}
    teams: List[Dict[str, Any]] = []
    if isinstance(conferences, dict):
        for conf_name, conf_teams in conferences.items():
            for team in conf_teams or []:
                if isinstance(team, dict):
                    team.setdefault("conference", conf_name)
                    teams.append(team)
    return teams


def _find_team(league: Dict[str, Any], team_name: str) -> Optional[Dict[str, Any]]:
    if not team_name:
        return None

    if isinstance(league.get("teams"), list):
        for team in league.get("teams") or []:
            if team.get("name") == team_name or team.get("teamName") == team_name:
                return team

    conferences = league.get("conferences") or {}
    if isinstance(conferences, dict):
        for teams in conferences.values():
            for team in teams or []:
                if team.get("name") == team_name or team.get("teamName") == team_name:
                    return team

    return None


def _team_logo(team: Dict[str, Any]) -> str:
    return (
        team.get("logo")
        or team.get("teamLogo")
        or team.get("newTeamLogo")
        or team.get("logoUrl")
        or team.get("image")
        or team.get("img")
        or ""
    )


def _get_season_year(league: Dict[str, Any], payload: Dict[str, Any]) -> int:
    for value in [
        payload.get("seasonYear"),
        league.get("seasonYear"),
        league.get("currentSeasonYear"),
        league.get("seasonStartYear"),
    ]:
        year = _safe_int(value, 0)
        if 2020 <= year <= 2100:
            return year
    return 2026


def _draft_class_year_from_prospect(prospect: Dict[str, Any]) -> int:
    if not isinstance(prospect, dict):
        return 0
    meta = prospect.get("meta") if isinstance(prospect.get("meta"), dict) else {}
    for value in [
        prospect.get("draftClassYear"),
        prospect.get("seasonYear"),
        prospect.get("draftYear"),
        prospect.get("rookieYear"),
        meta.get("draftYear"),
    ]:
        year = _safe_int(value, 0)
        if 2020 <= year <= 2100:
            return year
    return 0


def _draft_class_matches_season(draft_class: Any, season_year: int) -> bool:
    if not isinstance(draft_class, list) or not draft_class:
        return False

    checked = 0
    for prospect in draft_class[:10]:
        year = _draft_class_year_from_prospect(prospect)
        if year:
            checked += 1
            if year != season_year:
                return False

    return True if checked else True


def _latest_history_entry(league: Dict[str, Any], season_year: int) -> Optional[Dict[str, Any]]:
    history = league.get("seasonHistory") or []
    if not isinstance(history, list):
        return None

    matches = [
        row
        for row in history
        if isinstance(row, dict) and _safe_int(row.get("seasonYear"), 0) == season_year
    ]
    if matches:
        complete = [row for row in matches if row.get("status") == "complete"]
        return complete[-1] if complete else matches[-1]

    valid = [row for row in history if isinstance(row, dict) and isinstance(row.get("teams"), list)]
    if not valid:
        return None

    return sorted(valid, key = lambda row: _safe_int(row.get("seasonYear"), 0))[-1]


def _history_by_team(league: Dict[str, Any], season_year: int) -> Dict[str, Dict[str, Any]]:
    latest = _latest_history_entry(league, season_year)
    out: Dict[str, Dict[str, Any]] = {}
    for row in latest.get("teams", []) if latest else []:
        name = row.get("teamName") or row.get("team") or row.get("name")
        if name:
            out[name] = row
    return out


def _player_overall(player: Dict[str, Any]) -> int:
    return _safe_int(player.get("overall", player.get("ovr", player.get("rating", 70))), 70)


def _team_direction(team: Dict[str, Any], history_row: Optional[Dict[str, Any]]) -> str:
    players = team.get("players") or []
    top = sorted([_player_overall(p) for p in players if isinstance(p, dict)], reverse = True)[:8]
    avg_top = sum(top) / max(1, len(top)) if top else 72

    wins = _safe_int(history_row.get("wins"), 0) if history_row else 0
    made_playoffs = bool(history_row.get("madePlayoffs")) if history_row else False
    result = str(history_row.get("playoffResult") or "") if history_row else ""

    if result in {"champion", "finals", "conference_finals"} or wins >= 50 or (made_playoffs and avg_top >= 80):
        return "contending"
    if wins <= 34 or avg_top < 75:
        return "rebuilding"
    return "middle"


def _pos_matches(player: Dict[str, Any], pos: str) -> bool:
    primary = str(player.get("pos") or player.get("position") or "").upper()
    secondary = str(player.get("secondaryPos") or player.get("secondaryPosition") or "").upper()
    acceptable = POSITION_BUCKETS.get(pos, {pos})
    return primary in acceptable or secondary in acceptable


def _need_score(team: Dict[str, Any], pos: str) -> float:
    players = [p for p in (team.get("players") or []) if isinstance(p, dict)]
    matching = [p for p in players if _pos_matches(p, pos)]
    matching_ovrs = sorted([_player_overall(p) for p in matching], reverse = True)

    if not matching_ovrs:
        return 18.0

    best = matching_ovrs[0]
    second = matching_ovrs[1] if len(matching_ovrs) > 1 else 58
    depth_count = len([ovr for ovr in matching_ovrs if ovr >= 72])

    need = 0.0
    if best < 78:
        need += 9.0
    if best < 74:
        need += 6.0
    if second < 72:
        need += 4.0
    if depth_count <= 1:
        need += 3.0

    return max(0.0, min(18.0, need))


def _prospect_score(
    prospect: Dict[str, Any],
    team: Dict[str, Any],
    history_row: Optional[Dict[str, Any]],
    pick: Dict[str, Any],
    rng: random.Random,
) -> float:
    overall = _resolve_prospect_overall(prospect, 60)
    potential = _safe_int(prospect.get("potential"), overall)
    age = _safe_int(prospect.get("age"), 20)
    pos = prospect.get("pos") or "SF"
    pick_num = _safe_int(pick.get("pick"), 60)
    round_num = _safe_int(pick.get("round"), 1)
    direction = _team_direction(team, history_row)

    if pick_num <= 5:
        ovr_w, pot_w, need_w, ready_w = 0.56, 0.70, 0.10, 0.05
    elif pick_num <= 14:
        ovr_w, pot_w, need_w, ready_w = 0.54, 0.50, 0.20, 0.07
    elif round_num == 1:
        ovr_w, pot_w, need_w, ready_w = 0.54, 0.34, 0.36, 0.12
    else:
        ovr_w, pot_w, need_w, ready_w = 0.38, 0.44, 0.28, 0.10

    if direction == "rebuilding":
        pot_w += 0.16
        need_w -= 0.04
    elif direction == "contending":
        ovr_w += 0.10
        need_w += 0.08
        ready_w += 0.10
        pot_w -= 0.06

    need = _need_score(team, pos)
    upside_gap = max(0, potential - overall)
    nba_ready = _safe_float((prospect.get("traits") or {}).get("nbaReady"), max(0.0, (overall - 55) / 35))
    boom_bust = _safe_float((prospect.get("traits") or {}).get("boomBust"), 0.35)
    work_ethic = _safe_float((prospect.get("traits") or {}).get("workEthic"), 0.65)
    injury_risk = _safe_float((prospect.get("traits") or {}).get("injuryRisk"), 0.12)

    specialist_bonus = 0.0
    attrs = prospect.get("attrs") or []
    if len(attrs) >= 15:
        if round_num == 2:
            if attrs[0] >= 82:
                specialist_bonus += 2.2
            if attrs[8] >= 82 or attrs[10] >= 82 or attrs[12] >= 84:
                specialist_bonus += 2.0
            if attrs[13] >= 82 or attrs[14] >= 82:
                specialist_bonus += 1.2

    age_bonus = 0.0
    if direction == "rebuilding" and age <= 20:
        age_bonus += 1.5
    if direction == "contending" and age >= 21:
        age_bonus += 1.1

    risk_penalty = 0.0
    if direction == "contending":
        risk_penalty += boom_bust * 2.2
    else:
        risk_penalty += boom_bust * 0.9
    risk_penalty += injury_risk * 3.0

    randomness = rng.uniform(-2.8, 2.8)
    if round_num == 2:
        randomness = rng.uniform(-4.5, 4.5)

    score = (
        overall * ovr_w
        + potential * pot_w
        + need * need_w
        + upside_gap * 0.20
        + nba_ready * 6.0 * ready_w
        + work_ethic * 2.8
        + specialist_bonus
        + age_bonus
        - risk_penalty
        + randomness
    )

    return float(score)


def _choose_cpu_prospect(
    state: Dict[str, Any],
    league: Dict[str, Any],
    pick: Dict[str, Any],
    season_year: int,
) -> Dict[str, Any]:
    team_name = pick.get("currentOwnerTeamName") or pick.get("teamName")
    team = _find_team(league, team_name) or {"name": team_name, "players": []}
    history = _history_by_team(league, season_year).get(team_name)
    available = state.get("availableProspects") or []

    pick_num = _safe_int(pick.get("pick"), 60)
    candidate_pool_size = 18 if pick_num <= 10 else 26 if pick_num <= 30 else 34
    pool = sorted(
        available,
        key = lambda p: (_safe_int(p.get("draftProjection"), 999), _safe_int(p.get("trueRank"), 999)),
    )[:candidate_pool_size]

    rng = random.Random(_stable_seed(season_year, pick_num, team_name, "cpu_pick"))
    scored = []
    for prospect in pool:
        scored.append((_prospect_score(prospect, team, history, pick, rng), prospect))

    scored.sort(key = lambda item: item[0], reverse = True)
    return scored[0][1] if scored else available[0]


def _rookie_salary_for_pick(round_num: int, pick_num: int) -> int:
    if round_num == 1:
        # Rough rookie scale approximation. It is intentionally simple for v1.
        return max(2_400_000, int(11_800_000 - (pick_num - 1) * 315_000))

    pick_in_round = max(1, pick_num - 30)
    return max(1_250_000, int(2_250_000 - (pick_in_round - 1) * 28_000))


def _rookie_contract(round_num: int, pick_num: int, season_year: int) -> Dict[str, Any]:
    first_salary = _rookie_salary_for_pick(round_num, pick_num)

    if round_num == 1:
        salary_by_year = [
            first_salary,
            int(first_salary * 1.05),
            int(first_salary * 1.10),
            int(first_salary * 1.22),
        ]
        return {
            "type": "standard",
            "startYear": season_year,
            "salaryByYear": salary_by_year,
            "option": {
                "type": "team",
                "yearIndices": [2, 3],
                "picked": None,
            },
            "source": "first_round_rookie_scale",
            "countsAgainstStandardRoster": True,
        }

    # Second-round rookies do not become automatic standard contracts.
    # They move to the Rookie Signings event where the team can choose
    # standard contract, two-way contract, draft rights, or release.
    projected_salary_by_year = [first_salary, int(first_salary * 1.08)]
    return {
        "type": "unsigned_rookie",
        "startYear": season_year,
        "salaryByYear": [],
        "projectedSalaryByYear": projected_salary_by_year,
        "option": None,
        "pendingRookieSigning": True,
        "source": "second_round_pending_rookie_signing",
        "countsAgainstStandardRoster": False,
    }


def _prospect_portrait_url(prospect: Dict[str, Any]) -> str:
    return (
        prospect.get("headshot")
        or prospect.get("image")
        or prospect.get("img")
        or ""
    )


def _scoring_rating(attrs: List[int]) -> float:
    if len(attrs) < 15:
        return 60.0
    return float(
        attrs[0] * 0.28
        + attrs[1] * 0.21
        + attrs[2] * 0.24
        + attrs[4] * 0.10
        + attrs[7] * 0.08
        + attrs[13] * 0.09
    )


def _ratings_from_attrs(attrs: List[int]) -> Tuple[int, int]:
    if len(attrs) < 15:
        return 70, 70
    off_indices = [0, 1, 2, 3, 4, 5, 7, 13]
    def_indices = [8, 9, 10, 11, 12, 14]
    off_rating = round(sum(attrs[i] for i in off_indices) / len(off_indices))
    def_rating = round(sum(attrs[i] for i in def_indices) / len(def_indices))
    return int(off_rating), int(def_rating)


def _normalize_draft_prospect_for_state(prospect: Dict[str, Any], season_year: int, index: int = 0) -> Dict[str, Any]:
    p = copy.deepcopy(prospect or {})
    attrs = _normalize_attrs(p.get("attrs") or p.get("attributes") or [])
    p["attrs"] = attrs

    if not p.get("name") and p.get("playerName"):
        p["name"] = p.get("playerName")
    if not p.get("playerName") and p.get("name"):
        p["playerName"] = p.get("name")

    p.setdefault("draftClassYear", season_year)
    p.setdefault("seasonYear", season_year)
    p.setdefault("draftProjection", _safe_int(p.get("trueRank") or p.get("rank"), index + 1))
    p.setdefault("trueRank", _safe_int(p.get("draftProjection") or p.get("rank"), index + 1))

    if p.get("id") is None or p.get("id") == "":
        p["id"] = f"custom_{season_year}_{str(index + 1).zfill(3)}_{_safe_id_text(p.get('name') or p.get('playerName') or 'prospect')}"

    if p.get("overall") is None and p.get("ovr") is None and p.get("rating") is None:
        p["overall"] = _resolve_prospect_overall(p, 65)

    overall = _resolve_prospect_overall(p, 65)
    if p.get("potential") is None or _safe_int(p.get("potential"), 0) <= 0:
        p["potential"] = overall

    off_rating, def_rating = _ratings_from_attrs(attrs)
    if p.get("offRating") is None and p.get("off_rating") is None:
        p["offRating"] = off_rating
    if p.get("defRating") is None and p.get("def_rating") is None:
        p["defRating"] = def_rating
    if p.get("stamina") is None:
        p["stamina"] = _calc_stamina_from_attrs(p.get("age"), attrs)
    if p.get("scoringRating") is None:
        p["scoringRating"] = _scoring_rating(attrs)

    source = (
        p.get("college") or p.get("school") or p.get("university") or p.get("academy") or
        p.get("academyName") or p.get("sourceName") or p.get("draftSource") or ""
    )
    if source:
        p.setdefault("college", source)
        p.setdefault("school", source)
        p.setdefault("academy", source)
        p.setdefault("academyName", source)
        p.setdefault("sourceName", source)
        p.setdefault("draftSource", source)

    return p


def _prospect_to_player(
    prospect: Dict[str, Any],
    team_name: str,
    pick: Optional[Dict[str, Any]],
    season_year: int,
    drafted: bool = True,
) -> Dict[str, Any]:
    attrs = [int(x) for x in (prospect.get("attrs") or [])]
    while len(attrs) < 15:
        attrs.append(60)

    overall_rating = _resolve_prospect_overall(prospect, 65)
    off_rating = _safe_int(prospect.get("offRating") or prospect.get("off_rating"), 0)
    def_rating = _safe_int(prospect.get("defRating") or prospect.get("def_rating"), 0)
    if not off_rating or not def_rating:
        off_rating, def_rating = _ratings_from_attrs(attrs)

    overall_pick = _safe_int(pick.get("pick"), 0) if pick else None
    round_num = _safe_int(pick.get("round"), 0) if pick else None
    pick_in_round = _safe_int(pick.get("pickInRound"), 0) if pick else None
    player_id_suffix = _safe_id_text(prospect.get("name") or prospect.get("id") or "rookie")
    player_id = f"rookie_{season_year}_{overall_pick or 'udfa'}_{player_id_suffix}"

    contract = _rookie_contract(round_num, overall_pick or 60, season_year) if drafted and pick else {
        "startYear": season_year,
        "salaryByYear": [],
        "option": None,
    }

    rights_team = team_name if drafted else None
    acquired_via = "draft" if drafted else "undrafted_free_agent"
    contract_type = contract.get("type") if isinstance(contract, dict) else "standard"
    if drafted and round_num == 1:
        roster_status = "standard"
        assignment_status = "nba"
        rookie_pending = False
    elif drafted and round_num == 2:
        roster_status = "rookie_pending"
        assignment_status = "unsigned_rookie"
        rookie_pending = True
    else:
        roster_status = "free_agent"
        assignment_status = "free_agent"
        rookie_pending = False

    transaction_label = (
        f"Drafted No. {overall_pick} by {team_name}"
        if drafted and overall_pick
        else "Entered free agency as an undrafted rookie"
    )

    portrait_url = _prospect_portrait_url(prospect)

    return {
        "id": player_id,
        "name": prospect.get("name") or "Generated Rookie",
        "pos": prospect.get("pos") or "SF",
        "secondaryPos": prospect.get("secondaryPos") or "",
        "age": _safe_int(prospect.get("age"), 20),
        "height": _safe_int(prospect.get("height"), 78),
        "weight": _safe_int(prospect.get("weight"), 215),
        "potential": _safe_int(prospect.get("potential"), overall_rating),
        "overall": overall_rating,
        "offRating": off_rating,
        "defRating": def_rating,
        "stamina": _safe_int(prospect.get("stamina"), _calc_stamina_from_attrs(_safe_int(prospect.get("age"), 20), attrs)),
        "scoringRating": _safe_float(prospect.get("scoringRating"), _scoring_rating(attrs)),
        "attrs": attrs,
        "portraitId": prospect.get("portraitId") or "",
        "headshot": portrait_url,
        "image": portrait_url,
        "img": portrait_url,
        "birthMonth": _safe_int(prospect.get("birthMonth"), 1),
        "birthDay": _safe_int(prospect.get("birthDay"), 1),
        "lastBirthdayYear": season_year,
        "team": team_name if drafted else "Free Agent",
        "contract": contract,
        "contractType": contract_type,
        "rosterStatus": roster_status,
        "assignmentStatus": assignment_status,
        "rookieSigningPending": rookie_pending,
        "rights": {
            "heldByTeam": rights_team,
            "seasonsTowardBird": 0,
            "birdLevel": "none" if not drafted else "non_bird",
            "rookieScale": bool(drafted and round_num == 1),
            "restrictedFreeAgent": False,
        },
        "meta": {
            "draftYear": season_year if drafted else None,
            "draftRound": round_num if drafted else None,
            "draftPick": overall_pick if drafted else None,
            "draftPickInRound": pick_in_round if drafted else None,
            "draftedBy": team_name if drafted else None,
            "acquiredVia": acquired_via,
            "rookieSigningPending": rookie_pending,
            "rookieSigningDecision": None,
            "proSeasons": 0,
            "yearsWithCurrentTeam": 0,
            "college": prospect.get("college") or "",
            "nationality": prospect.get("nationality") or "",
            "archetype": prospect.get("archetype") or "",
        },
        "history": {
            "seasons": [],
            "accolades": [],
            "transactions": [
                {
                    "seasonYear": season_year,
                    "type": acquired_via,
                    "label": transaction_label,
                    "teamName": team_name if drafted else "Free Agent",
                }
            ],
        },
    }


def _add_player_to_team(league: Dict[str, Any], team_name: str, player: Dict[str, Any]) -> bool:
    team = _find_team(league, team_name)
    if not team:
        return False
    if not isinstance(team.get("players"), list):
        team["players"] = []
    if not isinstance(team.get("pendingRookieSignings"), list):
        team["pendingRookieSignings"] = []

    player_id = player.get("id")
    contract = player.get("contract") if isinstance(player.get("contract"), dict) else {}
    contract_type = str(player.get("contractType") or contract.get("type") or "standard").lower()
    is_pending_rookie = bool(
        player.get("rookieSigningPending")
        or contract.get("pendingRookieSigning")
        or contract_type in {"unsigned_rookie", "rookie_pending"}
    )

    target = team["pendingRookieSignings"] if is_pending_rookie else team["players"]
    existing_ids = {p.get("id") for p in target if isinstance(p, dict)}
    if player_id not in existing_ids:
        target.append(player)
    return True


def _add_undrafted_to_free_agents(league: Dict[str, Any], state: Dict[str, Any], season_year: int) -> None:
    if state.get("undraftedProcessed"):
        return

    available = state.get("availableProspects") or []
    if not isinstance(league.get("freeAgents"), list):
        league["freeAgents"] = []

    existing_ids = {p.get("id") for p in league["freeAgents"] if isinstance(p, dict)}
    undrafted_added = []

    # Keep the top remaining undrafted prospects available. This gives the FA pool life
    # without bloating localStorage too aggressively.
    for prospect in available[:24]:
        player = _prospect_to_player(prospect, "Free Agent", None, season_year, drafted = False)
        if player.get("id") in existing_ids:
            continue
        league["freeAgents"].append(player)
        existing_ids.add(player.get("id"))
        undrafted_added.append({
            "playerId": player.get("id"),
            "playerName": player.get("name"),
            "overall": player.get("overall"),
            "potential": player.get("potential"),
            "pos": player.get("pos"),
        })

    state["undraftedProcessed"] = True
    state["undraftedAddedToFreeAgency"] = undrafted_added


def _normalize_draft_order(draft_order: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    out = []
    for idx, row in enumerate(draft_order or []):
        if not isinstance(row, dict):
            continue
        pick = _safe_int(row.get("pick"), idx + 1)
        round_num = _safe_int(row.get("round"), 1 if pick <= 30 else 2)
        pick_in_round = _safe_int(row.get("pickInRound"), pick if round_num == 1 else pick - 30)
        team_name = row.get("currentOwnerTeamName") or row.get("teamName") or row.get("originalTeamName")
        out.append({
            **row,
            "pick": pick,
            "round": round_num,
            "pickInRound": pick_in_round,
            "teamName": row.get("teamName") or team_name,
            "currentOwnerTeamName": team_name,
            "originalTeamName": row.get("originalTeamName") or row.get("teamName") or team_name,
        })
    return sorted(out, key = lambda r: _safe_int(r.get("pick"), 999))


def initialize_draft(league_data: Dict[str, Any], payload: Dict[str, Any]) -> Dict[str, Any]:
    league = copy.deepcopy(_plain(league_data) or {})
    payload = _plain(payload) or {}
    season_year = _get_season_year(league, payload)

    existing_state = payload.get("draftState") or (league.get("draftState") or {}).get("draft")
    existing_state_season = _safe_int(existing_state.get("seasonYear"), 0) if isinstance(existing_state, dict) else 0
    if (
        isinstance(existing_state, dict)
        and existing_state_season == season_year
        and existing_state.get("draftOrder")
        and existing_state.get("availableProspects")
    ):
        return {
            "ok": True,
            "version": DRAFT_LOGIC_VERSION,
            "leagueData": league,
            "draftState": existing_state,
            "message": "Loaded existing draft state.",
        }

    draft_order = payload.get("draftOrder") or (league.get("draftState") or {}).get("draftOrder") or []
    draft_order = _normalize_draft_order(draft_order)

    if not draft_order:
        return {
            "ok": False,
            "reason": "MISSING_DRAFT_ORDER",
            "version": DRAFT_LOGIC_VERSION,
            "leagueData": league,
        }

    draft_class = payload.get("draftClass") or (league.get("draftState") or {}).get("draftClass")
    if isinstance(draft_class, list) and draft_class and not _draft_class_matches_season(draft_class, season_year):
        draft_class = None

    if not isinstance(draft_class, list) or len(draft_class) < len(draft_order):
        count = max(84, len(draft_order) + 24)
        class_seed = payload.get("classSeed")
        if class_seed is None:
            class_seed = _stable_seed("draft_class", season_year)

        if generate_draft_class is None:
            return {
                "ok": False,
                "reason": "DRAFT_CLASS_GENERATOR_NOT_AVAILABLE",
                "version": DRAFT_LOGIC_VERSION,
                "leagueData": league,
            }

        generated = generate_draft_class(
            season_year = season_year,
            count = count,
            seed = _safe_int(class_seed, _stable_seed("draft_class", season_year)),
        )
        draft_class = generated.get("draftClass") or []
        class_meta = generated.get("classMeta") or {}
    else:
        class_meta = {
            "seasonYear": season_year,
            "summary": "Loaded provided draft class",
            "prospectCount": len(draft_class),
        }

    draft_class = [
        _normalize_draft_prospect_for_state(p, season_year, index)
        for index, p in enumerate(draft_class or [])
    ]

    available = sorted(
        [copy.deepcopy(p) for p in draft_class],
        key = lambda p: (_safe_int(p.get("draftProjection"), 999), _safe_int(p.get("trueRank"), 999)),
    )

    state = {
        "version": DRAFT_LOGIC_VERSION,
        "seasonYear": season_year,
        "currentPickIndex": 0,
        "draftOrder": draft_order,
        "draftClass": draft_class,
        "classMeta": class_meta,
        "availableProspects": available,
        "draftedPicks": [],
        "completed": False,
        "undraftedProcessed": False,
        "undraftedAddedToFreeAgency": [],
    }

    league.setdefault("draftState", {})
    league["draftState"]["draft"] = state
    league["draftState"]["draftClass"] = draft_class

    return {
        "ok": True,
        "version": DRAFT_LOGIC_VERSION,
        "leagueData": league,
        "draftState": state,
        "message": "Initialized draft.",
    }


def _select_prospect_by_id(available: List[Dict[str, Any]], prospect_id: str) -> Optional[Dict[str, Any]]:
    for prospect in available:
        if prospect.get("id") == prospect_id:
            return prospect
    return None


def _complete_if_needed(league: Dict[str, Any], state: Dict[str, Any], season_year: int) -> None:
    if _safe_int(state.get("currentPickIndex"), 0) >= len(state.get("draftOrder") or []):
        state["completed"] = True
        _add_undrafted_to_free_agents(league, state, season_year)


def make_pick(
    league_data: Dict[str, Any],
    payload: Dict[str, Any],
    force_cpu: bool = False,
) -> Dict[str, Any]:
    league = copy.deepcopy(_plain(league_data) or {})
    payload = _plain(payload) or {}
    season_year = _get_season_year(league, payload)

    state = copy.deepcopy(payload.get("draftState") or (league.get("draftState") or {}).get("draft") or {})
    if not state or not state.get("draftOrder"):
        init = initialize_draft(league, payload)
        if not init.get("ok"):
            return init
        state = init.get("draftState") or {}
        league = init.get("leagueData") or league

    if state.get("completed"):
        _complete_if_needed(league, state, season_year)
        league.setdefault("draftState", {})["draft"] = state
        return {
            "ok": True,
            "version": DRAFT_LOGIC_VERSION,
            "leagueData": league,
            "draftState": state,
            "message": "Draft already complete.",
        }

    current_index = _safe_int(state.get("currentPickIndex"), 0)
    draft_order = state.get("draftOrder") or []
    if current_index >= len(draft_order):
        _complete_if_needed(league, state, season_year)
        league.setdefault("draftState", {})["draft"] = state
        return {
            "ok": True,
            "version": DRAFT_LOGIC_VERSION,
            "leagueData": league,
            "draftState": state,
            "message": "Draft complete.",
        }

    pick = draft_order[current_index]
    team_name = pick.get("currentOwnerTeamName") or pick.get("teamName")
    user_team_name = payload.get("userTeamName")
    prospect_id = payload.get("prospectId")
    available = state.get("availableProspects") or []

    if not available:
        state["completed"] = True
        _complete_if_needed(league, state, season_year)
        league.setdefault("draftState", {})["draft"] = state
        return {
            "ok": True,
            "version": DRAFT_LOGIC_VERSION,
            "leagueData": league,
            "draftState": state,
            "message": "No available prospects remaining.",
        }

    is_user_pick = bool(user_team_name and team_name == user_team_name and not force_cpu)

    if is_user_pick:
        if not prospect_id:
            return {
                "ok": False,
                "reason": "USER_PICK_REQUIRES_PROSPECT_ID",
                "version": DRAFT_LOGIC_VERSION,
                "leagueData": league,
                "draftState": state,
            }
        prospect = _select_prospect_by_id(available, prospect_id)
        if not prospect:
            return {
                "ok": False,
                "reason": "PROSPECT_NOT_AVAILABLE",
                "version": DRAFT_LOGIC_VERSION,
                "leagueData": league,
                "draftState": state,
            }
    else:
        prospect = _choose_cpu_prospect(state, league, pick, season_year)

    player = _prospect_to_player(prospect, team_name, pick, season_year, drafted = True)
    added = _add_player_to_team(league, team_name, player)

    pick_record = {
        "pick": pick.get("pick"),
        "round": pick.get("round"),
        "pickInRound": pick.get("pickInRound"),
        "teamName": team_name,
        "originalTeamName": pick.get("originalTeamName") or team_name,
        "playerId": player.get("id"),
        "playerName": player.get("name"),
        "pos": player.get("pos"),
        "overall": player.get("overall"),
        "potential": player.get("potential"),
        "age": player.get("age"),
        "portraitId": player.get("portraitId") or "",
        "headshot": player.get("headshot") or "",
        "image": player.get("image") or "",
        "img": player.get("img") or "",
        "archetype": prospect.get("archetype") or "",
        "tier": prospect.get("tier") or "",
        "userControlled": bool(is_user_pick),
        "addedToRoster": bool(added),
    }

    state["draftedPicks"] = (state.get("draftedPicks") or []) + [pick_record]
    state["availableProspects"] = [p for p in available if p.get("id") != prospect.get("id")]
    state["currentPickIndex"] = current_index + 1

    _complete_if_needed(league, state, season_year)

    league.setdefault("draftState", {})
    league["draftState"]["draft"] = state
    league["draftState"]["draftComplete"] = bool(state.get("completed"))

    return {
        "ok": True,
        "version": DRAFT_LOGIC_VERSION,
        "leagueData": league,
        "draftState": state,
        "pick": pick_record,
    }


def sim_until_user_pick(league_data: Dict[str, Any], payload: Dict[str, Any]) -> Dict[str, Any]:
    league = copy.deepcopy(_plain(league_data) or {})
    payload = _plain(payload) or {}
    user_team_name = payload.get("userTeamName")
    season_year = _get_season_year(league, payload)

    state = copy.deepcopy(payload.get("draftState") or (league.get("draftState") or {}).get("draft") or {})
    if not state or not state.get("draftOrder"):
        init = initialize_draft(league, payload)
        if not init.get("ok"):
            return init
        league = init.get("leagueData") or league
        state = init.get("draftState") or {}

    picks_made = []
    safety = 0

    while not state.get("completed") and safety < 80:
        safety += 1
        idx = _safe_int(state.get("currentPickIndex"), 0)
        order = state.get("draftOrder") or []
        if idx >= len(order):
            break
        current = order[idx]
        team_name = current.get("currentOwnerTeamName") or current.get("teamName")

        if user_team_name and team_name == user_team_name:
            break

        result = make_pick(league, {**payload, "draftState": state, "userTeamName": user_team_name}, force_cpu = True)
        if not result.get("ok"):
            return result
        league = result.get("leagueData") or league
        state = result.get("draftState") or state
        if result.get("pick"):
            picks_made.append(result.get("pick"))

    league.setdefault("draftState", {})["draft"] = state
    return {
        "ok": True,
        "version": DRAFT_LOGIC_VERSION,
        "leagueData": league,
        "draftState": state,
        "picksMade": picks_made,
        "message": "Simmed to user pick or draft completion.",
    }


def sim_rest_of_draft(league_data: Dict[str, Any], payload: Dict[str, Any]) -> Dict[str, Any]:
    league = copy.deepcopy(_plain(league_data) or {})
    payload = _plain(payload) or {}
    user_team_name = payload.get("userTeamName")

    state = copy.deepcopy(payload.get("draftState") or (league.get("draftState") or {}).get("draft") or {})
    if not state or not state.get("draftOrder"):
        init = initialize_draft(league, payload)
        if not init.get("ok"):
            return init
        league = init.get("leagueData") or league
        state = init.get("draftState") or {}

    picks_made = []
    safety = 0

    while not state.get("completed") and safety < 120:
        safety += 1
        result = make_pick(league, {**payload, "draftState": state, "userTeamName": user_team_name}, force_cpu = True)
        if not result.get("ok"):
            return result
        league = result.get("leagueData") or league
        state = result.get("draftState") or state
        if result.get("pick"):
            picks_made.append(result.get("pick"))

    league.setdefault("draftState", {})["draft"] = state
    league["draftState"]["draftComplete"] = bool(state.get("completed"))

    return {
        "ok": True,
        "version": DRAFT_LOGIC_VERSION,
        "leagueData": league,
        "draftState": state,
        "picksMade": picks_made,
        "message": "Simmed rest of draft.",
    }


def handle_request(request: Dict[str, Any]) -> Dict[str, Any]:
    req = _plain(request) or {}
    action = req.get("action") or "initialize_draft"
    league_data = req.get("leagueData") or req.get("league") or {}
    payload = req.get("payload") or {}

    if action == "initialize_draft":
        return initialize_draft(league_data, payload)

    if action == "make_user_pick":
        return make_pick(league_data, payload, force_cpu = False)

    if action == "sim_one_pick":
        return make_pick(league_data, payload, force_cpu = True)

    if action == "sim_to_user_pick":
        return sim_until_user_pick(league_data, payload)

    if action == "sim_rest_of_draft":
        return sim_rest_of_draft(league_data, payload)

    return {
        "ok": False,
        "reason": f"UNKNOWN_DRAFT_ACTION: {action}",
        "version": DRAFT_LOGIC_VERSION,
    }
