#!/usr/bin/env python3
"""Fast Basketball Manager progression/draft audit.

Runs progression outside the browser so roster/draft/progression tuning can be
validated in seconds instead of clicking through many UI seasons.

Example:
  python frontend/scripts/progression-batch-audit.py \
    --roster "2026-27 rosters (aug 21).json" \
    --custom-draft "2027 draft(2).json" \
    --years 20 --sims 10 --output progression_audit_outputs
"""
from __future__ import annotations

import argparse
import csv
import copy
import json
import os
import sys
from pathlib import Path
from typing import Any, Dict, Iterable, List, Tuple

ROOT = Path(__file__).resolve().parents[1]
PY_DIR = ROOT / "public" / "python"
sys.path.insert(0, str(PY_DIR))

import draft_logic  # type: ignore
import progression  # type: ignore
try:
    import autogenerated_draft_class  # type: ignore
except Exception:  # pragma: no cover
    autogenerated_draft_class = None


def load_json(path: str | Path) -> Any:
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def write_csv(path: Path, rows: List[Dict[str, Any]], fieldnames: List[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for row in rows:
            writer.writerow({key: row.get(key, "") for key in fieldnames})


def teams(league: Dict[str, Any]) -> List[Dict[str, Any]]:
    if isinstance(league.get("teams"), list):
        return [t for t in league.get("teams", []) if isinstance(t, dict)]
    confs = league.get("conferences") if isinstance(league.get("conferences"), dict) else {}
    out: List[Dict[str, Any]] = []
    for arr in confs.values():
        if isinstance(arr, list):
            out.extend([t for t in arr if isinstance(t, dict)])
    return out


def iter_players(league: Dict[str, Any]) -> Iterable[Tuple[str, Dict[str, Any]]]:
    for t in teams(league):
        name = str(t.get("name") or t.get("teamName") or "")
        for bucket in ("players", "twoWayPlayers", "stashPlayers"):
            for p in t.get(bucket, []) or []:
                if isinstance(p, dict):
                    yield name, p
    for p in league.get("freeAgents", []) or []:
        if isinstance(p, dict):
            yield "__FREE_AGENCY__", p


def player_key(team: str, p: Dict[str, Any]) -> str:
    return f"{p.get('name') or p.get('playerName') or 'Unknown'}__{team}"


def shape_counts(league: Dict[str, Any]) -> Dict[str, Any]:
    vals = [int(float(p.get("overall", 0) or 0)) for _, p in iter_players(league)]
    vals = [v for v in vals if v > 0]
    return {
        "playerCount": len(vals),
        "avgOverall": round(sum(vals) / len(vals), 3) if vals else 0,
        "maxOverall": max(vals) if vals else 0,
        "95plus": sum(v >= 95 for v in vals),
        "90plus": sum(v >= 90 for v in vals),
        "85plus": sum(v >= 85 for v in vals),
        "80plus": sum(v >= 80 for v in vals),
        "77plus": sum(v >= 77 for v in vals),
        "74plus": sum(v >= 74 for v in vals),
        "70plus": sum(v >= 70 for v in vals),
    }


def normalize_custom_draft(draft_payload: Dict[str, Any], season_year: int, league: Dict[str, Any]) -> Tuple[List[Dict[str, Any]], List[Dict[str, Any]]]:
    raw = draft_payload.get("draftClass") or draft_payload.get("prospects") or []
    baselines = draft_logic._build_v19_rating_baselines(league)  # type: ignore[attr-defined]
    normalized: List[Dict[str, Any]] = []
    audit: List[Dict[str, Any]] = []
    for idx, prospect in enumerate(raw):
        if not isinstance(prospect, dict):
            continue
        before_ovr = int(float(prospect.get("overall", prospect.get("ovr", prospect.get("rating", 0))) or 0))
        before_pot = int(float(prospect.get("potential", before_ovr) or before_ovr))
        p = draft_logic._normalize_draft_prospect_for_state(prospect, season_year, idx, baselines)  # type: ignore[attr-defined]
        after_ovr = int(float(p.get("overall", 0) or 0))
        after_pot = int(float(p.get("potential", after_ovr) or after_ovr))
        normalized.append(p)
        audit.append({
            "rank": p.get("draftProjection") or p.get("rank") or idx + 1,
            "name": p.get("name") or p.get("playerName"),
            "jsonOverall": before_ovr,
            "normalizedOverall": after_ovr,
            "overallDelta": after_ovr - before_ovr,
            "jsonPotential": before_pot,
            "normalizedPotential": after_pot,
            "potentialDelta": after_pot - before_pot,
            "formulaOverallBeforeRepair": p.get("calculatedOverallFromAttrs", ""),
            "attrsRepairedToOverall": p.get("attrsRepairedToOverall", False),
            "overallSource": p.get("overallSource", ""),
        })
    return normalized, audit


def inject_draft_class(league: Dict[str, Any], prospects: List[Dict[str, Any]], season_year: int, limit: int = 60) -> None:
    ts = teams(league)
    if not ts:
        league.setdefault("freeAgents", [])
        ts = []
    baselines = draft_logic._build_v19_rating_baselines(league)  # type: ignore[attr-defined]
    for idx, prospect in enumerate(prospects[:limit]):
        team = ts[idx % len(ts)] if ts else None
        team_name = str(team.get("name") if team else "Free Agents")
        pick = {
            "pick": idx + 1,
            "round": 1 if idx < 30 else 2,
            "pickInRound": (idx % 30) + 1,
            "teamName": team_name,
            "currentOwnerTeamName": team_name,
        }
        rookie = draft_logic._prospect_to_player(  # type: ignore[attr-defined]
            prospect,
            team_name,
            pick,
            season_year,
            drafted=True,
            rating_baselines=baselines,
            league_data=league,
        )
        rookie["__auditSourceClassYear"] = season_year
        rookie["__auditDraftRank"] = idx + 1
        if team is not None:
            team.setdefault("players", []).append(rookie)
        else:
            league.setdefault("freeAgents", []).append(rookie)


def generate_future_draft(season_year: int, seed: int, league: Dict[str, Any]) -> List[Dict[str, Any]]:
    if autogenerated_draft_class is None:
        return []
    avoid = [p.get("name") for _, p in iter_players(league) if p.get("name")]
    res = autogenerated_draft_class.generate_draft_class(season_year=season_year, seed=seed, avoid_names=avoid)
    draft = res.get("draftClass") or []
    normalized, _audit = normalize_custom_draft({"draftClass": draft}, season_year, league)
    return normalized


def run_one_sim(base_league: Dict[str, Any], custom_draft: Dict[str, Any] | None, years: int, seed: int, output_dir: Path, sim_index: int) -> Tuple[List[Dict[str, Any]], List[Dict[str, Any]], List[Dict[str, Any]], List[Dict[str, Any]]]:
    league = copy.deepcopy(base_league)
    start_records: Dict[str, Dict[str, Any]] = {}
    for team, p in iter_players(league):
        key = str(p.get("id") or player_key(team, p))
        start_records[key] = {
            "sim": sim_index,
            "id": key,
            "name": p.get("name") or p.get("playerName"),
            "startTeam": team,
            "startAge": p.get("age"),
            "startOverall": p.get("overall"),
            "startPotential": p.get("potential", p.get("overall")),
            "peakOverall": p.get("overall"),
            "peakAge": p.get("age"),
            "finalOverall": p.get("overall"),
            "finalAge": p.get("age"),
            "exceededPotentialBy": 0,
            "trajectory": [int(float(p.get("overall", 0) or 0))],
        }

    league_rows: List[Dict[str, Any]] = []
    top_rows: List[Dict[str, Any]] = []
    import_audit_rows: List[Dict[str, Any]] = []

    start_year = int(league.get("seasonYear") or league.get("seasonStartYear") or 2026)
    for offset in range(years):
        season_year = start_year + offset
        if offset == 1 and custom_draft:
            prospects, import_audit = normalize_custom_draft(custom_draft, season_year, league)
            for row in import_audit:
                row.update({"sim": sim_index, "seasonYear": season_year, "classType": "custom"})
            import_audit_rows.extend(import_audit)
            inject_draft_class(league, prospects, season_year, limit=60)
        elif offset > 1:
            prospects = generate_future_draft(season_year, seed + offset * 1009, league)
            inject_draft_class(league, prospects, season_year, limit=60)

        res = progression.apply_end_of_season_progression_with_deltas(
            league,
            stats_by_key={},
            settings=getattr(progression, "DEFAULT_SETTINGS", None),
            seed=seed + offset * 7919,
            season_year=season_year,
        )
        league = res.get("league") or league
        league["seasonYear"] = season_year + 1
        metrics = shape_counts(league)
        metrics.update({"sim": sim_index, "seasonYear": season_year})
        league_rows.append(metrics)

        ranked = sorted([p for _, p in iter_players(league)], key=lambda p: int(float(p.get("overall", 0) or 0)), reverse=True)[:25]
        for rank, p in enumerate(ranked, 1):
            top_rows.append({
                "sim": sim_index,
                "seasonYear": season_year,
                "rank": rank,
                "name": p.get("name"),
                "age": p.get("age"),
                "overall": p.get("overall"),
                "potential": p.get("potential", p.get("overall")),
                "teamOrBucket": "",
            })

        for team, p in iter_players(league):
            key = str(p.get("id") or player_key(team, p))
            rec = start_records.get(key)
            if rec is None:
                rec = {
                    "sim": sim_index,
                    "id": key,
                    "name": p.get("name") or p.get("playerName"),
                    "startTeam": team,
                    "startAge": p.get("age"),
                    "startOverall": p.get("overall"),
                    "startPotential": p.get("potential", p.get("overall")),
                    "peakOverall": p.get("overall"),
                    "peakAge": p.get("age"),
                    "finalOverall": p.get("overall"),
                    "finalAge": p.get("age"),
                    "exceededPotentialBy": 0,
                    "trajectory": [],
                }
                start_records[key] = rec
            ovr = int(float(p.get("overall", 0) or 0))
            age = int(float(p.get("age", 0) or 0))
            rec["trajectory"].append(ovr)
            if ovr > int(float(rec.get("peakOverall", 0) or 0)):
                rec["peakOverall"] = ovr
                rec["peakAge"] = age
            rec["finalOverall"] = ovr
            rec["finalAge"] = age
            rec["exceededPotentialBy"] = max(0, int(rec["peakOverall"]) - int(float(rec.get("startPotential", rec["peakOverall"]) or rec["peakOverall"])))

    career_rows = []
    for rec in start_records.values():
        traj = rec.pop("trajectory")
        rec["trajectory"] = "-".join(map(str, traj))
        rec["netOverallChange"] = int(rec.get("finalOverall") or 0) - int(float(rec.get("startOverall") or 0))
        rec["peakGain"] = int(rec.get("peakOverall") or 0) - int(float(rec.get("startOverall") or 0))
        career_rows.append(rec)

    return league_rows, top_rows, career_rows, import_audit_rows


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--roster", required=True)
    ap.add_argument("--custom-draft", default=None)
    ap.add_argument("--years", type=int, default=20)
    ap.add_argument("--sims", type=int, default=5)
    ap.add_argument("--seed", type=int, default=5400)
    ap.add_argument("--output", default="progression_audit_outputs")
    args = ap.parse_args()

    base_league = load_json(args.roster)
    custom = load_json(args.custom_draft) if args.custom_draft else None
    out = Path(args.output)
    out.mkdir(parents=True, exist_ok=True)

    league_rows: List[Dict[str, Any]] = []
    top_rows: List[Dict[str, Any]] = []
    career_rows: List[Dict[str, Any]] = []
    import_rows: List[Dict[str, Any]] = []

    for sim in range(1, args.sims + 1):
        rows = run_one_sim(base_league, custom, args.years, args.seed + sim * 100000, out, sim)
        lr, tr, cr, ir = rows
        league_rows.extend(lr)
        top_rows.extend(tr)
        career_rows.extend(cr)
        import_rows.extend(ir)
        print(f"sim {sim}/{args.sims} complete: years={args.years}")

    write_csv(out / "league_shape_by_year.csv", league_rows, ["sim", "seasonYear", "playerCount", "avgOverall", "maxOverall", "95plus", "90plus", "85plus", "80plus", "77plus", "74plus", "70plus"])
    write_csv(out / "top_players_by_year.csv", top_rows, ["sim", "seasonYear", "rank", "name", "age", "overall", "potential", "teamOrBucket"])
    write_csv(out / "player_career_paths.csv", career_rows, ["sim", "id", "name", "startTeam", "startAge", "startOverall", "startPotential", "peakOverall", "peakAge", "finalOverall", "finalAge", "netOverallChange", "peakGain", "exceededPotentialBy", "trajectory"])
    write_csv(out / "draft_import_audit.csv", import_rows, ["sim", "seasonYear", "classType", "rank", "name", "jsonOverall", "normalizedOverall", "overallDelta", "jsonPotential", "normalizedPotential", "potentialDelta", "formulaOverallBeforeRepair", "attrsRepairedToOverall", "overallSource"])
    exceeded = [r for r in career_rows if int(r.get("exceededPotentialBy") or 0) > 0]
    write_csv(out / "players_exceeding_potential.csv", exceeded, ["sim", "name", "startTeam", "startAge", "startOverall", "startPotential", "peakOverall", "peakAge", "exceededPotentialBy", "trajectory"])
    breakout = [r for r in career_rows if int(r.get("peakGain") or 0) >= 8 or int(r.get("netOverallChange") or 0) <= -8]
    write_csv(out / "busts_and_breakouts.csv", breakout, ["sim", "name", "startTeam", "startAge", "startOverall", "startPotential", "peakOverall", "peakAge", "finalOverall", "finalAge", "netOverallChange", "peakGain", "exceededPotentialBy", "trajectory"])
    print(f"wrote audit files to {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
