#!/usr/bin/env python3
"""Fast Basketball Manager progression/draft/ecology audit.

Runs progression outside the browser so roster/draft/progression tuning can be
validated in seconds instead of clicking through UI seasons.

Example:
  python frontend/scripts/progression-batch-audit.py \
    --roster "2026-27 rosters (aug 21).json" \
    --custom-draft "2027 draft.json" \
    --years 20 --sims 1 --output progression_audit_outputs
"""
from __future__ import annotations

import argparse
import gc
import csv
import copy
import json
import math
import random
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Tuple

ROOT = Path(__file__).resolve().parents[1]
PY_DIR = ROOT / "public" / "python"
sys.path.insert(0, str(PY_DIR))

import draft_logic  # type: ignore
import progression  # type: ignore
try:
    import autogenerated_draft_class  # type: ignore
except Exception:  # pragma: no cover
    autogenerated_draft_class = None
try:
    import retirement_logic  # type: ignore
except Exception:  # pragma: no cover
    retirement_logic = None


AUDIT_VERSION = "2026-09-01_patch58_jump7_cpu_cpu_tax_audit_v1"


def load_json(path: str | Path) -> Any:
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def write_csv(path: Path, rows: List[Dict[str, Any]], fieldnames: List[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for row in rows:
            writer.writerow({key: row.get(key, "") for key in fieldnames})


def safe_int(value: Any, default: int = 0) -> int:
    try:
        if value is None or value == "":
            return default
        return int(float(value))
    except Exception:
        return default


def teams(league: Dict[str, Any]) -> List[Dict[str, Any]]:
    if isinstance(league.get("teams"), list):
        return [t for t in league.get("teams", []) if isinstance(t, dict)]
    confs = league.get("conferences") if isinstance(league.get("conferences"), dict) else {}
    out: List[Dict[str, Any]] = []
    for arr in confs.values():
        if isinstance(arr, list):
            out.extend([t for t in arr if isinstance(t, dict)])
    return out


def iter_players(league: Dict[str, Any]) -> Iterable[Tuple[str, Dict[str, Any]]]:
    for t in teams(league):
        name = str(t.get("name") or t.get("teamName") or "")
        for bucket in ("players", "twoWayPlayers", "stashPlayers"):
            for p in t.get(bucket, []) or []:
                if isinstance(p, dict):
                    yield name, p
    for p in league.get("freeAgents", []) or []:
        if isinstance(p, dict):
            yield "__FREE_AGENCY__", p


def player_key(team: str, p: Dict[str, Any]) -> str:
    return f"{p.get('name') or p.get('playerName') or 'Unknown'}__{team}"


def player_origin_label(p: Dict[str, Any]) -> str:
    meta = p.get("meta") if isinstance(p.get("meta"), dict) else {}
    round_num = safe_int(meta.get("draftRound"), safe_int(p.get("draftRound"), 0))
    pick = safe_int(meta.get("draftPick"), safe_int(p.get("draftPick"), 0))
    if round_num == 1:
        if pick == 1:
            return "pick_1"
        if pick <= 3:
            return "top_3"
        if pick <= 5:
            return "top_5"
        if pick <= 14:
            return "lottery"
        return "first_round"
    if round_num == 2:
        return "second_round"
    if str(meta.get("acquiredVia") or p.get("acquiredVia") or "").lower() == "undrafted_free_agent":
        return "undrafted"
    return "existing_or_unknown"


def shape_counts(league: Dict[str, Any]) -> Dict[str, Any]:
    vals = [safe_int(p.get("overall"), 0) for _, p in iter_players(league)]
    vals = [v for v in vals if v > 0]
    return {
        "playerCount": len(vals),
        "avgOverall": round(sum(vals) / len(vals), 3) if vals else 0,
        "maxOverall": max(vals) if vals else 0,
        "99plus": sum(v >= 99 for v in vals),
        "98plus": sum(v >= 98 for v in vals),
        "97plus": sum(v >= 97 for v in vals),
        "95plus": sum(v >= 95 for v in vals),
        "90plus": sum(v >= 90 for v in vals),
        "85plus": sum(v >= 85 for v in vals),
        "80plus": sum(v >= 80 for v in vals),
        "77plus": sum(v >= 77 for v in vals),
        "74plus": sum(v >= 74 for v in vals),
        "70plus": sum(v >= 70 for v in vals),
    }


def team_strength(team: Dict[str, Any]) -> float:
    players = [p for p in team.get("players", []) or [] if isinstance(p, dict)]
    vals = sorted([safe_int(p.get("overall"), 0) for p in players], reverse=True)
    if not vals:
        return 0.0
    top8 = vals[:8]
    top3 = vals[:3]
    return sum(top8) / max(1, len(top8)) + 0.22 * sum(top3) / max(1, len(top3))


def team_ecology_rows(league: Dict[str, Any], sim: int, season_year: int) -> List[Dict[str, Any]]:
    rows: List[Dict[str, Any]] = []
    ranked_teams = sorted(teams(league), key=team_strength, reverse=True)
    for rank, team in enumerate(ranked_teams, 1):
        players = [p for p in team.get("players", []) or [] if isinstance(p, dict)]
        top = sorted(players, key=lambda p: safe_int(p.get("overall"), 0), reverse=True)
        vals = [safe_int(p.get("overall"), 0) for p in top]
        top3 = top[:3]
        top5 = top[:5]
        rows.append({
            "sim": sim,
            "seasonYear": season_year,
            "teamRank": rank,
            "team": team.get("name") or team.get("teamName"),
            "teamStrength": round(team_strength(team), 3),
            "rosterCount": len(players),
            "top1Overall": vals[0] if vals else 0,
            "top2Overall": vals[1] if len(vals) > 1 else 0,
            "top3Overall": vals[2] if len(vals) > 2 else 0,
            "avgTop3": round(sum(vals[:3]) / max(1, len(vals[:3])), 3) if vals else 0,
            "avgTop8": round(sum(vals[:8]) / max(1, len(vals[:8])), 3) if vals else 0,
            "players95plus": sum(v >= 95 for v in vals),
            "players90plus": sum(v >= 90 for v in vals),
            "players85plus": sum(v >= 85 for v in vals),
            "players80plus": sum(v >= 80 for v in vals),
            "topPlayers": "; ".join(f"{p.get('name')} {safe_int(p.get('overall'))}" for p in top5),
        })
    return rows


def top_age_distribution_rows(league: Dict[str, Any], sim: int, season_year: int) -> List[Dict[str, Any]]:
    allp = [(team, p) for team, p in iter_players(league)]
    ranked = sorted(allp, key=lambda it: safe_int(it[1].get("overall"), 0), reverse=True)
    rows: List[Dict[str, Any]] = []
    for cutoff in (5, 10, 20, 30):
        group = ranked[:cutoff]
        ages = [safe_int(p.get("age"), 0) for _, p in group if safe_int(p.get("age"), 0) > 0]
        rows.append({
            "sim": sim,
            "seasonYear": season_year,
            "topN": cutoff,
            "avgAge": round(sum(ages) / max(1, len(ages)), 3),
            "minAge": min(ages) if ages else 0,
            "maxAge": max(ages) if ages else 0,
            "age22under": sum(a <= 22 for a in ages),
            "age25under": sum(a <= 25 for a in ages),
            "age26to29": sum(26 <= a <= 29 for a in ages),
            "age30to34": sum(30 <= a <= 34 for a in ages),
            "age35plus": sum(a >= 35 for a in ages),
        })
    return rows


def progression_jump_distribution_row(league: Dict[str, Any], deltas: Dict[str, Dict[str, Any]], sim: int, season_year: int) -> Dict[str, Any]:
    by_key: Dict[str, Dict[str, Any]] = {}
    for team, p in iter_players(league):
        name = str(p.get("name") or p.get("playerName") or "Unknown")
        by_key[f"{name}__{team}"] = p

    vals: List[int] = []
    age_vals: List[Tuple[int, int]] = []
    top_jumpers: List[Tuple[int, str, int, int]] = []
    for key, row in (deltas or {}).items():
        if not isinstance(row, dict):
            continue
        d = safe_int(row.get("overall"), 0)
        vals.append(d)
        p = by_key.get(key) or {}
        after_age = safe_int(p.get("age"), 0)
        before_age = after_age - safe_int(row.get("age"), 1) if after_age else 0
        age_vals.append((before_age, d))
        if d >= 4:
            name = str((p.get("name") or key.split("__", 1)[0] or "Unknown"))
            top_jumpers.append((d, name, before_age, safe_int(p.get("overall"), 0)))

    top_jumpers.sort(key=lambda x: (-x[0], x[2], x[1]))
    return {
        "sim": sim,
        "seasonYear": season_year,
        "playerCount": len(vals),
        "maxJump": max(vals) if vals else 0,
        "minJump": min(vals) if vals else 0,
        "plus7": sum(1 for d in vals if d >= 7),
        "plus6": sum(1 for d in vals if d == 6),
        "plus5": sum(1 for d in vals if d == 5),
        "plus4": sum(1 for d in vals if d == 4),
        "plus5plus": sum(1 for d in vals if d >= 5),
        "plus4plus": sum(1 for d in vals if d >= 4),
        "age22underPlus7": sum(1 for a, d in age_vals if a <= 22 and d >= 7),
        "age22underPlus5plus": sum(1 for a, d in age_vals if a <= 22 and d >= 5),
        "age25underPlus5plus": sum(1 for a, d in age_vals if a <= 25 and d >= 5),
        "age25underPlus4plus": sum(1 for a, d in age_vals if a <= 25 and d >= 4),
        "topJumpers": "; ".join(f"{name} +{d} age{age} now{ovr}" for d, name, age, ovr in top_jumpers[:12]),
    }


def league_balance_row(league: Dict[str, Any], sim: int, season_year: int) -> Dict[str, Any]:
    top30 = sorted([(team, p) for team, p in iter_players(league)], key=lambda it: safe_int(it[1].get("overall"), 0), reverse=True)[:30]
    by_team: Dict[str, int] = {}
    for team, _p in top30:
        by_team[team] = by_team.get(team, 0) + 1
    top_team_count = max(by_team.values()) if by_team else 0
    teams_with_2 = sum(1 for v in by_team.values() if v >= 2)
    teams_with_3 = sum(1 for v in by_team.values() if v >= 3)
    star_stack_teams = 0
    two_90_teams = 0
    three_85_teams = 0
    for t in teams(league):
        vals = [safe_int(p.get("overall"), 0) for p in t.get("players", []) or [] if isinstance(p, dict)]
        if sum(v >= 90 for v in vals) >= 2:
            two_90_teams += 1
        if sum(v >= 85 for v in vals) >= 3:
            three_85_teams += 1
        if sum(v >= 90 for v in vals) >= 1 and sum(v >= 85 for v in vals) >= 3:
            star_stack_teams += 1
    return {
        "sim": sim,
        "seasonYear": season_year,
        "top30TeamsRepresented": len(by_team),
        "largestTop30TeamShare": top_team_count,
        "teamsWith2Top30": teams_with_2,
        "teamsWith3Top30": teams_with_3,
        "teamsWith2Players90plus": two_90_teams,
        "teamsWith3Players85plus": three_85_teams,
        "starStackTeams": star_stack_teams,
        "top30TeamCounts": "; ".join(f"{k}:{v}" for k, v in sorted(by_team.items(), key=lambda item: (-item[1], item[0]))),
    }


def normalize_custom_draft(draft_payload: Dict[str, Any], season_year: int, league: Dict[str, Any]) -> Tuple[List[Dict[str, Any]], List[Dict[str, Any]]]:
    raw = draft_payload.get("draftClass") or draft_payload.get("prospects") or []
    baselines = draft_logic._build_v19_rating_baselines(league)  # type: ignore[attr-defined]
    normalized: List[Dict[str, Any]] = []
    audit: List[Dict[str, Any]] = []
    for idx, prospect in enumerate(raw):
        if not isinstance(prospect, dict):
            continue
        before_ovr = safe_int(prospect.get("overall", prospect.get("ovr", prospect.get("rating", 0))), 0)
        before_pot = safe_int(prospect.get("potential", before_ovr), before_ovr)
        p = draft_logic._normalize_draft_prospect_for_state(prospect, season_year, idx, baselines)  # type: ignore[attr-defined]
        after_ovr = safe_int(p.get("overall"), 0)
        after_pot = safe_int(p.get("potential", after_ovr), after_ovr)
        normalized.append(p)
        audit.append({
            "rank": p.get("draftProjection") or p.get("rank") or idx + 1,
            "name": p.get("name") or p.get("playerName"),
            "jsonOverall": before_ovr,
            "normalizedOverall": after_ovr,
            "overallDelta": after_ovr - before_ovr,
            "jsonPotential": before_pot,
            "normalizedPotential": after_pot,
            "potentialDelta": after_pot - before_pot,
            "formulaOverallBeforeRepair": p.get("calculatedOverallFromAttrs", ""),
            "attrsRepairedToOverall": p.get("attrsRepairedToOverall", False),
            "overallSource": p.get("overallSource", ""),
        })
    return normalized, audit


def build_cpu_draft_order(league: Dict[str, Any], picks: int = 60) -> List[Dict[str, Any]]:
    ranked = sorted(teams(league), key=team_strength)
    if not ranked:
        return []
    out: List[Dict[str, Any]] = []
    for idx in range(picks):
        round_num = 1 if idx < 30 else 2
        # Round two repeats the order. This is a draft-AI/progression audit, not a
        # pick-ownership simulator.
        team = ranked[idx % len(ranked)]
        team_name = str(team.get("name") or team.get("teamName") or "Team")
        out.append({
            "pick": idx + 1,
            "round": round_num,
            "pickInRound": (idx % 30) + 1,
            "teamName": team_name,
            "currentOwnerTeamName": team_name,
        })
    return out


def prospect_snapshot(p: Optional[Dict[str, Any]]) -> Dict[str, Any]:
    if not p:
        return {"name": "", "overall": "", "potential": "", "rank": ""}
    ovr = draft_logic._resolve_prospect_overall(p, 60)  # type: ignore[attr-defined]
    pot = max(ovr, safe_int(p.get("potential"), ovr))
    return {
        "name": p.get("name") or p.get("playerName"),
        "overall": ovr,
        "potential": pot,
        "rank": draft_logic._draft_rank_value(p) if hasattr(draft_logic, "_draft_rank_value") else safe_int(p.get("draftProjection"), 999),
    }


def best_available_by_bpa(available: List[Dict[str, Any]]) -> Optional[Dict[str, Any]]:
    if not available:
        return None
    def key(p: Dict[str, Any]) -> Tuple[int, int, int]:
        snap = prospect_snapshot(p)
        return (safe_int(snap["overall"]), safe_int(snap["potential"]), -safe_int(snap["rank"], 999))
    return sorted(available, key=key, reverse=True)[0]


def summarize_class(prospects: List[Dict[str, Any]], sim: int, season_year: int, class_type: str) -> Dict[str, Any]:
    vals = [draft_logic._resolve_prospect_overall(p, 60) for p in prospects]  # type: ignore[attr-defined]
    pots = [max(vals[i], safe_int(prospects[i].get("potential"), vals[i])) for i in range(len(prospects))]
    return {
        "sim": sim,
        "seasonYear": season_year,
        "classType": class_type,
        "prospectCount": len(prospects),
        "maxOverall": max(vals) if vals else 0,
        "maxPotential": max(pots) if pots else 0,
        "avgOverall": round(sum(vals) / max(1, len(vals)), 3) if vals else 0,
        "avgPotential": round(sum(pots) / max(1, len(pots)), 3) if pots else 0,
        "overall75plus": sum(v >= 75 for v in vals),
        "overall70plus": sum(v >= 70 for v in vals),
        "potential95plus": sum(v >= 95 for v in pots),
        "potential90plus": sum(v >= 90 for v in pots),
        "top10": "; ".join(f"{p.get('name')} {draft_logic._resolve_prospect_overall(p, 60)}/{max(draft_logic._resolve_prospect_overall(p, 60), safe_int(p.get('potential'), 60))}" for p in prospects[:10]),  # type: ignore[attr-defined]
    }


def cpu_draft_inject(league: Dict[str, Any], prospects: List[Dict[str, Any]], season_year: int, sim_index: int, class_type: str, limit: int = 60) -> List[Dict[str, Any]]:
    ts = teams(league)
    if not ts:
        league.setdefault("freeAgents", [])
    baselines = draft_logic._build_v19_rating_baselines(league)  # type: ignore[attr-defined]
    available = list(prospects)
    audit_rows: List[Dict[str, Any]] = []
    order = build_cpu_draft_order(league, picks=min(limit, len(available)))
    by_name = {str(t.get("name") or t.get("teamName") or ""): t for t in ts}

    for pick in order:
        if not available:
            break
        pick_num = safe_int(pick.get("pick"), 60)
        team_name = str(pick.get("currentOwnerTeamName") or pick.get("teamName") or "")
        state = {"availableProspects": available}
        selected = draft_logic._choose_cpu_prospect(state, league, pick, season_year)  # type: ignore[attr-defined]
        if not selected:
            selected = available[0]
        best_bpa = best_available_by_bpa(available)
        obvious = []
        if hasattr(draft_logic, "_is_obvious_better_draft_option"):
            obvious = [p for p in available if draft_logic._is_obvious_better_draft_option(p, selected, pick_num)]  # type: ignore[attr-defined]
        selected_snap = prospect_snapshot(selected)
        best_snap = prospect_snapshot(best_bpa)
        audit_rows.append({
            "sim": sim_index,
            "seasonYear": season_year,
            "classType": class_type,
            "pick": pick_num,
            "round": pick.get("round"),
            "team": team_name,
            "selectedName": selected_snap["name"],
            "selectedOverall": selected_snap["overall"],
            "selectedPotential": selected_snap["potential"],
            "selectedRank": selected_snap["rank"],
            "bestAvailableName": best_snap["name"],
            "bestAvailableOverall": best_snap["overall"],
            "bestAvailablePotential": best_snap["potential"],
            "bestAvailableRank": best_snap["rank"],
            "obviousBetterAvailableCount": len(obvious),
            "obviousBetterNames": "; ".join(str(prospect_snapshot(p)["name"]) for p in obvious[:5]),
            "lotteryMistakeFlag": bool(pick_num <= 14 and obvious),
        })
        rookie = draft_logic._prospect_to_player(  # type: ignore[attr-defined]
            selected,
            team_name,
            pick,
            season_year,
            drafted=True,
            rating_baselines=baselines,
            league_data=league,
        )
        rookie["__auditSourceClassYear"] = season_year
        rookie["__auditDraftRank"] = pick_num
        rookie["__auditClassType"] = class_type
        team = by_name.get(team_name)
        if team is not None:
            team.setdefault("players", []).append(rookie)
        else:
            league.setdefault("freeAgents", []).append(rookie)
        selected_id = str(selected.get("id") or id(selected))
        available = [p for p in available if str(p.get("id") or id(p)) != selected_id]
    return audit_rows


def generate_future_draft(season_year: int, seed: int, league: Dict[str, Any]) -> List[Dict[str, Any]]:
    if autogenerated_draft_class is None:
        return []
    avoid = [p.get("name") for _, p in iter_players(league) if p.get("name")]
    res = autogenerated_draft_class.generate_draft_class(season_year=season_year, seed=seed, avoid_names=avoid)
    draft = res.get("draftClass") or []
    normalized, _audit = normalize_custom_draft({"draftClass": draft}, season_year, league)
    return normalized


def remember_player(records: Dict[str, Dict[str, Any]], team: str, p: Dict[str, Any], sim_index: int) -> Dict[str, Any]:
    key = str(p.get("id") or player_key(team, p))
    rec = records.get(key)
    if rec is not None:
        return rec
    meta = p.get("meta") if isinstance(p.get("meta"), dict) else {}
    rec = {
        "sim": sim_index,
        "id": key,
        "name": p.get("name") or p.get("playerName"),
        "startTeam": team,
        "startAge": p.get("age"),
        "startOverall": p.get("overall"),
        "startPotential": p.get("potential", p.get("overall")),
        "draftYear": meta.get("draftYear") or p.get("draftClassYear") or p.get("__auditSourceClassYear"),
        "draftRound": meta.get("draftRound"),
        "draftPick": meta.get("draftPick") or p.get("__auditDraftRank"),
        "originLabel": player_origin_label(p),
        "classType": p.get("__auditClassType", "starting_roster"),
        "peakOverall": p.get("overall"),
        "peakAge": p.get("age"),
        "finalOverall": p.get("overall"),
        "finalAge": p.get("age"),
        "exceededPotentialBy": 0,
        "trajectory": [],
    }
    records[key] = rec
    return rec


def update_career_records(records: Dict[str, Dict[str, Any]], league: Dict[str, Any], sim_index: int) -> None:
    for team, p in iter_players(league):
        rec = remember_player(records, team, p, sim_index)
        ovr = safe_int(p.get("overall"), 0)
        age = safe_int(p.get("age"), 0)
        rec["trajectory"].append(ovr)
        if ovr > safe_int(rec.get("peakOverall"), 0):
            rec["peakOverall"] = ovr
            rec["peakAge"] = age
        rec["finalOverall"] = ovr
        rec["finalAge"] = age
        rec["exceededPotentialBy"] = max(0, safe_int(rec["peakOverall"]) - safe_int(rec.get("startPotential", rec["peakOverall"])))




def audit_retirement_probability(age: int, overall: int, potential: int) -> float:
    """Lightweight audit-only retirement model.

    The browser offseason has its own retirement screen. For progression/ecology
    lab runs we only need to prevent the player pool from growing forever while
    keeping rare elite late-career players alive long enough to test longevity.
    """
    if age < 34:
        if age >= 31 and overall <= 56:
            return 0.04
        return 0.0
    if age == 34:
        return 0.02 if overall < 70 else 0.0
    if age == 35:
        if overall >= 88:
            return 0.01
        if overall >= 80:
            return 0.04
        if overall >= 72:
            return 0.12
        return 0.28
    if age == 36:
        if overall >= 90:
            return 0.02
        if overall >= 84:
            return 0.07
        if overall >= 76:
            return 0.20
        return 0.42
    if age == 37:
        if overall >= 90:
            return 0.04
        if overall >= 85:
            return 0.12
        if overall >= 78:
            return 0.34
        return 0.60
    if age == 38:
        if overall >= 90:
            return 0.08
        if overall >= 85:
            return 0.20
        if overall >= 80:
            return 0.46
        return 0.76
    if age == 39:
        if overall >= 90:
            return 0.16
        if overall >= 85:
            return 0.36
        if overall >= 80:
            return 0.68
        return 0.88
    if age == 40:
        if overall >= 90:
            return 0.30
        if overall >= 85:
            return 0.58
        return 0.92
    if age == 41:
        return 0.55 if overall >= 90 else 0.85 if overall >= 84 else 0.97
    if age == 42:
        return 0.78 if overall >= 90 else 0.95
    return 1.0


def apply_audit_retirements(league: Dict[str, Any], season_year: int, seed: int) -> int:
    retired = 0
    for team in teams(league):
        kept = []
        for p in team.get("players") or []:
            age = safe_int(p.get("age"), 25)
            ovr = safe_int(p.get("overall"), 70)
            pot = safe_int(p.get("potential"), ovr)
            prob = audit_retirement_probability(age, ovr, pot)
            roll = random.Random(f"patch57_retire|{seed}|{season_year}|{p.get('id') or p.get('name')}").random()
            if roll < prob:
                retired += 1
            else:
                kept.append(p)
        team["players"] = kept
    # Keep free agents from growing forever too, but with the same light model.
    fa = league.get("freeAgents")
    if isinstance(fa, list):
        kept_fa = []
        for p in fa:
            age = safe_int(p.get("age"), 25)
            ovr = safe_int(p.get("overall"), 70)
            pot = safe_int(p.get("potential"), ovr)
            prob = audit_retirement_probability(age, ovr, pot)
            roll = random.Random(f"patch57_retire_fa|{seed}|{season_year}|{p.get('id') or p.get('name')}").random()
            if roll < prob:
                retired += 1
            else:
                kept_fa.append(p)
        league["freeAgents"] = kept_fa
    return retired

def run_one_sim(base_league: Dict[str, Any], custom_draft: Dict[str, Any] | None, years: int, seed: int, sim_index: int, use_retirements: bool = True) -> Tuple[List[Dict[str, Any]], List[Dict[str, Any]], List[Dict[str, Any]], List[Dict[str, Any]], List[Dict[str, Any]], List[Dict[str, Any]], List[Dict[str, Any]], List[Dict[str, Any]], List[Dict[str, Any]], List[Dict[str, Any]], List[Dict[str, Any]]]:
    league = copy.deepcopy(base_league)
    league.setdefault("meta", {})
    league["meta"]["progressionSeedV25"] = f"batch_audit_sim_{sim_index}_{seed}"
    league["progressionSeedV25"] = league["meta"]["progressionSeedV25"]

    career_records: Dict[str, Dict[str, Any]] = {}
    for team, p in iter_players(league):
        remember_player(career_records, team, p, sim_index)

    league_rows: List[Dict[str, Any]] = []
    top_rows: List[Dict[str, Any]] = []
    import_audit_rows: List[Dict[str, Any]] = []
    draft_ai_rows: List[Dict[str, Any]] = []
    team_rows: List[Dict[str, Any]] = []
    age_rows: List[Dict[str, Any]] = []
    balance_rows: List[Dict[str, Any]] = []
    class_rows: List[Dict[str, Any]] = []
    retirement_rows: List[Dict[str, Any]] = []
    jump_rows: List[Dict[str, Any]] = []

    start_year = int(league.get("seasonYear") or league.get("seasonStartYear") or 2026)
    for offset in range(years):
        season_year = start_year + offset
        if offset == 1 and custom_draft:
            prospects, import_audit = normalize_custom_draft(custom_draft, season_year, league)
            for row in import_audit:
                row.update({"sim": sim_index, "seasonYear": season_year, "classType": "custom"})
            import_audit_rows.extend(import_audit)
            class_rows.append(summarize_class(prospects, sim_index, season_year, "custom"))
            draft_ai_rows.extend(cpu_draft_inject(league, prospects, season_year, sim_index, "custom", limit=60))
        elif offset > 1:
            prospects = generate_future_draft(season_year, seed + offset * 1009, league)
            class_rows.append(summarize_class(prospects, sim_index, season_year, "autogenerated"))
            draft_ai_rows.extend(cpu_draft_inject(league, prospects, season_year, sim_index, "autogenerated", limit=60))

        res = progression.apply_end_of_season_progression_with_deltas(
            league,
            stats_by_key={},
            settings=getattr(progression, "DEFAULT_SETTINGS", None),
            seed=seed + offset * 7919,
            season_year=season_year,
        )
        league = res.get("league") or league
        jump_rows.append(progression_jump_distribution_row(league, res.get("deltas") or {}, sim_index, season_year))

        retired_count = 0
        if use_retirements:
            retired_count = apply_audit_retirements(league, season_year, seed + offset * 3571 + 17)
        retirement_rows.append({"sim": sim_index, "seasonYear": season_year, "retiredCount": retired_count})
        league["seasonYear"] = season_year + 1
        metrics = shape_counts(league)
        metrics.update({"sim": sim_index, "seasonYear": season_year})
        league_rows.append(metrics)

        ranked = sorted([(team, p) for team, p in iter_players(league)], key=lambda it: safe_int(it[1].get("overall"), 0), reverse=True)[:30]
        for rank, (team, p) in enumerate(ranked, 1):
            prof = p.get("devProfileV25") or (p.get("meta") or {}).get("devProfileV25") if isinstance(p.get("meta"), dict) else p.get("devProfileV25")
            top_rows.append({
                "sim": sim_index,
                "seasonYear": season_year,
                "rank": rank,
                "name": p.get("name"),
                "age": p.get("age"),
                "overall": p.get("overall"),
                "potential": p.get("potential", p.get("overall")),
                "teamOrBucket": team,
                "profile": prof.get("profile") if isinstance(prof, dict) else "",
                "hiddenCeiling": prof.get("hiddenCeiling") if isinstance(prof, dict) else "",
            })

        team_rows.extend(team_ecology_rows(league, sim_index, season_year))
        age_rows.extend(top_age_distribution_rows(league, sim_index, season_year))
        balance_rows.append(league_balance_row(league, sim_index, season_year))
        update_career_records(career_records, league, sim_index)

    career_rows: List[Dict[str, Any]] = []
    for rec in career_records.values():
        traj = rec.pop("trajectory")
        rec["trajectory"] = "-".join(map(str, traj))
        rec["netOverallChange"] = safe_int(rec.get("finalOverall"), 0) - safe_int(rec.get("startOverall"), 0)
        rec["peakGain"] = safe_int(rec.get("peakOverall"), 0) - safe_int(rec.get("startOverall"), 0)
        career_rows.append(rec)

    return league_rows, top_rows, career_rows, import_audit_rows, draft_ai_rows, team_rows, age_rows, balance_rows, class_rows, retirement_rows, jump_rows



CSV_OUTPUT_FILES = [
    "league_shape_by_year.csv",
    "top_players_by_year.csv",
    "player_career_paths.csv",
    "draft_import_audit.csv",
    "draft_ai_audit.csv",
    "draft_class_strength_by_year.csv",
    "team_star_concentration_by_year.csv",
    "top_player_age_distribution.csv",
    "league_balance_summary.csv",
    "retirements_by_year.csv",
    "progression_jump_distribution.csv",
    "players_exceeding_potential.csv",
    "busts_and_breakouts.csv",
]


def run_multi_sim_isolated(args: argparse.Namespace) -> int:
    """Run each sim in a fresh Python process, then merge CSV outputs.

    The progression modules keep a lot of deterministic career/profile cache state.
    A fresh process per sim is safer for 10x/20x audit runs and prevents one long
    Python process from carrying stale state across unrelated universes.
    """
    out = Path(args.output)
    out.mkdir(parents=True, exist_ok=True)
    per_sim_root = out / "_per_sim"
    if per_sim_root.exists():
        shutil.rmtree(per_sim_root)
    per_sim_root.mkdir(parents=True, exist_ok=True)

    for sim in range(1, args.sims + 1):
        sim_out = per_sim_root / f"sim{sim:02d}"
        sim_seed = int(args.seed) + sim * 100000
        cmd = [
            sys.executable,
            str(Path(__file__).resolve()),
            "--roster", str(args.roster),
            "--years", str(args.years),
            "--sims", "1",
            "--sim-index", str(sim),
            "--seed", str(sim_seed),
            "--output", str(sim_out),
            "--retirements", str(args.retirements),
        ]
        if args.custom_draft:
            cmd.extend(["--custom-draft", str(args.custom_draft)])
        subprocess.run(cmd, check=True)
        print(f"isolated sim {sim}/{args.sims} merged source ready", flush=True)

    (out / "AUDIT_VERSION.txt").write_text(AUDIT_VERSION + "\n", encoding="utf-8")
    for filename in CSV_OUTPUT_FILES:
        target = out / filename
        wrote_header = False
        with target.open("w", newline="", encoding="utf-8") as fout:
            writer = None
            for sim_dir in sorted(per_sim_root.glob("sim*")):
                src = sim_dir / filename
                if not src.exists():
                    continue
                with src.open("r", newline="", encoding="utf-8") as fin:
                    reader = csv.reader(fin)
                    try:
                        header = next(reader)
                    except StopIteration:
                        continue
                    if not wrote_header:
                        writer = csv.writer(fout)
                        writer.writerow(header)
                        wrote_header = True
                    if writer is None:
                        continue
                    for row in reader:
                        writer.writerow(row)
    print(f"wrote merged isolated audit files to {out}", flush=True)
    return 0


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--roster", required=True)
    ap.add_argument("--custom-draft", default=None)
    ap.add_argument("--years", type=int, default=20)
    ap.add_argument("--sims", type=int, default=5)
    ap.add_argument("--sim-index", type=int, default=1, help=argparse.SUPPRESS)
    ap.add_argument("--seed", type=int, default=5400)
    ap.add_argument("--output", default="progression_audit_outputs")
    ap.add_argument("--retirements", choices=["on", "off"], default="on")
    args = ap.parse_args()

    if args.sims > 1:
        # Automatically run each simulation in a fresh Python process, then merge
        # the CSVs. This keeps the command simple for VS terminal while avoiding
        # cached hidden-career state leaking between universes.
        return run_multi_sim_isolated(args)

    base_league = load_json(args.roster)
    custom = load_json(args.custom_draft) if args.custom_draft else None
    out = Path(args.output)
    out.mkdir(parents=True, exist_ok=True)

    league_rows: List[Dict[str, Any]] = []
    top_rows: List[Dict[str, Any]] = []
    career_rows: List[Dict[str, Any]] = []
    import_rows: List[Dict[str, Any]] = []
    draft_ai_rows: List[Dict[str, Any]] = []
    team_rows: List[Dict[str, Any]] = []
    age_rows: List[Dict[str, Any]] = []
    balance_rows: List[Dict[str, Any]] = []
    class_rows: List[Dict[str, Any]] = []
    retirement_rows: List[Dict[str, Any]] = []
    jump_rows: List[Dict[str, Any]] = []

    for sim in range(1, args.sims + 1):
        sim_index = int(args.sim_index) if args.sims == 1 else sim
        sim_seed = int(args.seed) if args.sims == 1 else int(args.seed) + sim * 100000
        lr, tr, cr, ir, dr, er, ar, br, cls, rr, jr = run_one_sim(base_league, custom, args.years, sim_seed, sim_index, use_retirements=(args.retirements == "on"))
        league_rows.extend(lr)
        top_rows.extend(tr)
        career_rows.extend(cr)
        import_rows.extend(ir)
        draft_ai_rows.extend(dr)
        team_rows.extend(er)
        age_rows.extend(ar)
        balance_rows.extend(br)
        class_rows.extend(cls)
        retirement_rows.extend(rr)
        jump_rows.extend(jr)
        print(f"sim {sim}/{args.sims} complete: years={args.years}", flush=True)
        gc.collect()

    (out / "AUDIT_VERSION.txt").write_text(AUDIT_VERSION + "\n", encoding="utf-8")
    write_csv(out / "league_shape_by_year.csv", league_rows, ["sim", "seasonYear", "playerCount", "avgOverall", "maxOverall", "99plus", "98plus", "97plus", "95plus", "90plus", "85plus", "80plus", "77plus", "74plus", "70plus"])
    write_csv(out / "top_players_by_year.csv", top_rows, ["sim", "seasonYear", "rank", "name", "age", "overall", "potential", "teamOrBucket", "profile", "hiddenCeiling"])
    write_csv(out / "player_career_paths.csv", career_rows, ["sim", "id", "name", "startTeam", "startAge", "startOverall", "startPotential", "draftYear", "draftRound", "draftPick", "originLabel", "classType", "peakOverall", "peakAge", "finalOverall", "finalAge", "netOverallChange", "peakGain", "exceededPotentialBy", "trajectory"])
    write_csv(out / "draft_import_audit.csv", import_rows, ["sim", "seasonYear", "classType", "rank", "name", "jsonOverall", "normalizedOverall", "overallDelta", "jsonPotential", "normalizedPotential", "potentialDelta", "formulaOverallBeforeRepair", "attrsRepairedToOverall", "overallSource"])
    write_csv(out / "draft_ai_audit.csv", draft_ai_rows, ["sim", "seasonYear", "classType", "pick", "round", "team", "selectedName", "selectedOverall", "selectedPotential", "selectedRank", "bestAvailableName", "bestAvailableOverall", "bestAvailablePotential", "bestAvailableRank", "obviousBetterAvailableCount", "obviousBetterNames", "lotteryMistakeFlag"])
    write_csv(out / "draft_class_strength_by_year.csv", class_rows, ["sim", "seasonYear", "classType", "prospectCount", "maxOverall", "maxPotential", "avgOverall", "avgPotential", "overall75plus", "overall70plus", "potential95plus", "potential90plus", "top10"])
    write_csv(out / "team_star_concentration_by_year.csv", team_rows, ["sim", "seasonYear", "teamRank", "team", "teamStrength", "rosterCount", "top1Overall", "top2Overall", "top3Overall", "avgTop3", "avgTop8", "players95plus", "players90plus", "players85plus", "players80plus", "topPlayers"])
    write_csv(out / "top_player_age_distribution.csv", age_rows, ["sim", "seasonYear", "topN", "avgAge", "minAge", "maxAge", "age22under", "age25under", "age26to29", "age30to34", "age35plus"])
    write_csv(out / "league_balance_summary.csv", balance_rows, ["sim", "seasonYear", "top30TeamsRepresented", "largestTop30TeamShare", "teamsWith2Top30", "teamsWith3Top30", "teamsWith2Players90plus", "teamsWith3Players85plus", "starStackTeams", "top30TeamCounts"])
    write_csv(out / "retirements_by_year.csv", retirement_rows, ["sim", "seasonYear", "retiredCount"])
    write_csv(out / "progression_jump_distribution.csv", jump_rows, ["sim", "seasonYear", "playerCount", "maxJump", "minJump", "plus7", "plus6", "plus5", "plus4", "plus5plus", "plus4plus", "age22underPlus7", "age22underPlus5plus", "age25underPlus5plus", "age25underPlus4plus", "topJumpers"])

    exceeded = [r for r in career_rows if safe_int(r.get("exceededPotentialBy"), 0) > 0]
    write_csv(out / "players_exceeding_potential.csv", exceeded, ["sim", "name", "startTeam", "startAge", "startOverall", "startPotential", "draftYear", "draftRound", "draftPick", "originLabel", "classType", "peakOverall", "peakAge", "exceededPotentialBy", "trajectory"])
    breakout = [r for r in career_rows if safe_int(r.get("peakGain"), 0) >= 8 or safe_int(r.get("netOverallChange"), 0) <= -8]
    write_csv(out / "busts_and_breakouts.csv", breakout, ["sim", "name", "startTeam", "startAge", "startOverall", "startPotential", "draftYear", "draftRound", "draftPick", "originLabel", "classType", "peakOverall", "peakAge", "finalOverall", "finalAge", "netOverallChange", "peakGain", "exceededPotentialBy", "trajectory"])
    print(f"wrote audit files to {out}", flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
