  import React, { useEffect, useMemo, useRef, useState } from "react";
  import { useNavigate } from "react-router-dom";
  import { useGame } from "../context/GameContext";
import { getDraftYear } from "../utils/seasonContext.js";
  import * as simEngine from "../api/simEnginePy.js";
import { saveLeagueData } from "../utils/leagueStorage.js";
import { applyDraftPickOwnershipToOrder, rollDraftPickAssetsForCompletedSeason } from "../utils/draftPicks.js";
import { recordCompletedDraftMoodEvents } from "../utils/offseasonMoodEvents.js";
import {
  getDraftClassFingerprint,
  markDraftStartedForYear,
  normalizeDraftClassRows,
  readUpcomingDraftClassForYear,
} from "../utils/upcomingDraftClass.js";
import {
  readCustomDraftClassForYear,
  readDefaultCustomDraftClass,
} from "../utils/customDraftClassStorage.js";

  const OFFSEASON_STATE_KEY = "bm_offseason_state_v1";
  const DRAFT_LOTTERY_KEY = "bm_draft_lottery_v1";
  const DRAFT_STATE_KEY = "bm_draft_state_v1";
  const CUSTOM_DRAFT_CLASS_MODE_KEY = "bm_draft_class_mode_v1";
  const CUSTOM_DRAFT_CLASS_MODE_BY_YEAR_KEY = "bm_draft_class_mode_by_year_v1";
  const LEAGUE_KEY = "leagueData";


// Draft classes created by the old generator used season-year/stable seeds, so
// new leagues repeatedly loaded the same 2026/2027/etc class. Treat any
// not-started, non-custom draft state without the fresh_random marker as stale
// and force a true regeneration.
function getDraftRowsFromState(state = {}) {
  if (!state || typeof state !== "object") return [];
  if (Array.isArray(state.availableProspects)) return state.availableProspects;
  if (Array.isArray(state.draftClass)) return state.draftClass;
  if (Array.isArray(state.prospects)) return state.prospects;
  if (Array.isArray(state.players)) return state.players;
  if (Array.isArray(state.currentDraftClass?.draftClass)) return state.currentDraftClass.draftClass;
  return [];
}

function isCustomDraftState(state = {}) {
  const classType = String(state?.classType || state?.classMeta?.classType || "").toLowerCase();
  return classType === "custom" || Boolean(state?.customDraftClass || state?.isCustomDraftClass);
}

function isFreshRandomDraftState(state = {}) {
  const seedMode = String(state?.seedMode || state?.classMeta?.seedMode || "").toLowerCase();
  return seedMode === "fresh_random";
}

function isLegacyAutoGeneratedDraftState(state = {}, seasonYear = 2026) {
  if (!state || typeof state !== "object") return false;
  if (Number(state.seasonYear || seasonYear) !== Number(seasonYear)) return false;
  if (isCustomDraftState(state)) return false;
  if (isFreshRandomDraftState(state)) return false;

  const draftedCount = Array.isArray(state.draftedPicks) ? state.draftedPicks.length : 0;
  if (state.completed || draftedCount > 0) return false;

  const rows = getDraftRowsFromState(state);
  if (!rows.length) return false;

  // Old saved auto classes either explicitly report seedMode="provided" or do
  // not report a seedMode at all. Both should be regenerated before the draft starts.
  return true;
}

function clearSavedLegacyDraftState(seasonYear, reason = "legacy auto draft state") {
  const saved = safeJSON(localStorage.getItem(DRAFT_STATE_KEY), null);
  if (isLegacyAutoGeneratedDraftState(saved, seasonYear)) {
    console.warn(`[Draft] Clearing ${reason} from ${DRAFT_STATE_KEY}`, {
      seasonYear,
      seed: saved?.seed || saved?.classMeta?.seed || null,
      seedMode: saved?.seedMode || saved?.classMeta?.seedMode || null,
      classType: saved?.classType || saved?.classMeta?.classType || null,
      topProspect: getDraftRowsFromState(saved)?.[0]?.name || null,
    });
    localStorage.removeItem(DRAFT_STATE_KEY);
    return true;
  }
  return false;
}

function stripLegacyDraftStateFromLeagueData(leagueData, seasonYear) {
  if (!leagueData || typeof leagueData !== "object") return leagueData;

  const staleDraftState = isLegacyAutoGeneratedDraftState(leagueData.draftState, seasonYear);
  const staleCurrentClass = isLegacyAutoGeneratedDraftState(leagueData.currentDraftClass, seasonYear);
  const staleDraftClass = isLegacyAutoGeneratedDraftState({
    seasonYear,
    draftClass: Array.isArray(leagueData.draftClass) ? leagueData.draftClass : [],
  }, seasonYear);
  const staleProspects = isLegacyAutoGeneratedDraftState({
    seasonYear,
    prospects: Array.isArray(leagueData.prospects) ? leagueData.prospects : [],
  }, seasonYear);

  if (!staleDraftState && !staleCurrentClass && !staleDraftClass && !staleProspects) {
    return leagueData;
  }

  const next = { ...leagueData };
  const preservedDraftOrder = Array.isArray(leagueData.draftState?.draftOrder)
    ? leagueData.draftState.draftOrder
    : [];

  if (preservedDraftOrder.length) {
    next.draftState = {
      seasonYear: Number(seasonYear),
      draftOrder: preservedDraftOrder,
      staleAutoClassCleared: true,
    };
  } else {
    delete next.draftState;
  }

  delete next.currentDraftClass;
  delete next.draftClass;
  delete next.prospects;

  return next;
}

  function safeJSON(raw, fallback = null) {
    try {
      const parsed = JSON.parse(raw);
      return parsed ?? fallback;
    } catch {
      return fallback;
    }
  }

  function getSeasonYear(leagueData) {
    const candidates = [];

    const pushYear = (value) => {
      const y = Number(value);
      if (Number.isFinite(y) && y >= 2020 && y <= 2100) {
        candidates.push(y);
      }
    };

    const meta = safeJSON(localStorage.getItem("bm_league_meta_v1"), {}) || {};
    const offseasonState = safeJSON(localStorage.getItem(OFFSEASON_STATE_KEY), {}) || {};

    pushYear(offseasonState?.draftYear);
    pushYear(leagueData?.draftYear);
    pushYear(leagueData?.currentDraftYear);
    pushYear(leagueData?.draftState?.seasonYear);
    pushYear(meta?.draftYear);
    pushYear(getDraftYear(leagueData || {}));
    pushYear(offseasonState?.seasonYear);

    if (candidates.length) return Math.max(...candidates);
    return 2026;
  }

  function readDraftLottery(seasonYear) {
    const saved = safeJSON(localStorage.getItem(DRAFT_LOTTERY_KEY), null);
    if (!saved || typeof saved !== "object") return null;
    if (Number(saved.seasonYear) !== Number(seasonYear)) return null;
    return saved;
  }


  function isLotteryDraftOrderLocked(lottery) {
    if (!lottery || typeof lottery !== "object") return false;
    if (lottery.isPreview || lottery?.result?.meta?.isPreview) return false;
    return Boolean(
      lottery.firstRoundRevealed &&
      lottery.secondRoundRevealed &&
      Array.isArray(lottery?.result?.fullDraftOrder) &&
      lottery.result.fullDraftOrder.length >= 60
    );
  }

  function readDraftState(seasonYear) {
    const saved = safeJSON(localStorage.getItem(DRAFT_STATE_KEY), null);
    if (!saved || typeof saved !== "object") return null;
    if (Number(saved.seasonYear) !== Number(seasonYear)) return null;

    if (isLegacyAutoGeneratedDraftState(saved, seasonYear)) {
      clearSavedLegacyDraftState(seasonYear, "old deterministic auto draft state");
      return null;
    }

    return saved;
  }

  function getRowsFromDraftClassPayload(payload) {
    if (Array.isArray(payload)) return payload;
    if (Array.isArray(payload?.draftClass)) return payload.draftClass;
    if (Array.isArray(payload?.prospects)) return payload.prospects;
    if (Array.isArray(payload?.players)) return payload.players;
    return [];
  }

  function readDraftClassModeForYear(seasonYear, hasCustomClass = false) {
    const yearKey = String(Number(seasonYear || 2026));
    const modesByYear = safeJSON(localStorage.getItem(CUSTOM_DRAFT_CLASS_MODE_BY_YEAR_KEY), null) || {};
    const explicitYearMode = modesByYear?.[yearKey];

    if (explicitYearMode === "custom" || explicitYearMode === "auto") {
      return explicitYearMode;
    }

    const legacyModeConfig = safeJSON(localStorage.getItem(CUSTOM_DRAFT_CLASS_MODE_KEY), null) || {};
    if (legacyModeConfig.mode === "custom") return "custom";
    if (legacyModeConfig.mode === "auto") return "auto";

    // If a class exists but no explicit choice exists yet, use it.
    // Play.jsx writes an explicit auto/custom value, so users can still override per year.
    return hasCustomClass ? "custom" : "auto";
  }

  function readCustomDraftClassSetup(seasonYear) {
    const savedSeasonClass = readCustomDraftClassForYear(seasonYear);
    const savedDefaultClass = readDefaultCustomDraftClass();
    const draftClassPayload = savedSeasonClass || savedDefaultClass || null;
    const rows = getRowsFromDraftClassPayload(draftClassPayload);
    const hasCustomClass = rows.length > 0;
    const mode = readDraftClassModeForYear(seasonYear, hasCustomClass);

    if (mode !== "custom") {
      return { mode, draftClassPayload: null, hasCustomClass };
    }

    if (!draftClassPayload || typeof draftClassPayload !== "object" || !hasCustomClass) {
      return { mode, draftClassPayload: null, hasCustomClass: false };
    }

    const classSeasonYear = Number(draftClassPayload.seasonYear || draftClassPayload.draftClassYear || rows?.[0]?.draftClassYear || rows?.[0]?.seasonYear || seasonYear);
    if (classSeasonYear && Number(classSeasonYear) !== Number(seasonYear)) {
      return { mode, draftClassPayload: null, hasCustomClass: false };
    }

    return {
      mode,
      hasCustomClass: true,
      draftClassPayload: {
        ...draftClassPayload,
        seasonYear: Number(seasonYear),
        draftClass: rows.map((row, index) => ({
          ...row,
          draftClassYear: Number(row?.draftClassYear || row?.seasonYear || seasonYear),
          seasonYear: Number(row?.seasonYear || row?.draftClassYear || seasonYear),
          draftProjection: Number(row?.draftProjection || row?.trueRank || row?.rank || index + 1),
          trueRank: Number(row?.trueRank || row?.draftProjection || row?.rank || index + 1),
        })),
      },
    };
  }

  function getMatchingUpcomingDraftPreview(seasonYear, customSetup) {
    const preview = readUpcomingDraftClassForYear(seasonYear);
    if (!preview?.draftClass?.length) return null;

    if (customSetup?.mode === "custom") {
      const customRows = customSetup?.draftClassPayload?.draftClass || [];
      const customFingerprint = getDraftClassFingerprint(customRows);
      if (
        preview.sourceMode === "custom" &&
        preview.sourceFingerprint &&
        preview.sourceFingerprint === customFingerprint
      ) {
        return preview;
      }
      return null;
    }

    return preview.sourceMode === "auto" ? preview : null;
  }

  function applyDraftClassSourceMetadata(result, descriptor, seasonYear) {
    if (!result?.ok || !descriptor) return result;

    const sourceMode = descriptor.sourceMode === "custom" ? "custom" : "auto";
    const classType =
      sourceMode === "custom"
        ? "custom"
        : descriptor.classType || descriptor.classMeta?.classType || "auto";
    const seedMode = sourceMode === "custom" ? "custom" : "fresh_random";
    const classMeta = {
      ...(descriptor.classMeta || {}),
      seasonYear: Number(seasonYear),
      classType,
      seedMode,
      sourceMode,
      previewGenerated: Boolean(descriptor.previewGenerated || descriptor.sourceMode === "auto"),
    };

    const nextState = result?.draftState
      ? {
          ...result.draftState,
          seasonYear: Number(seasonYear),
          classType,
          seedMode,
          classMeta,
          customDraftClass: sourceMode === "custom",
          isCustomDraftClass: sourceMode === "custom",
        }
      : result?.draftState;

    if (!result?.leagueData || !nextState) {
      return { ...result, draftState: nextState };
    }

    const rootDraftState =
      result.leagueData.draftState && typeof result.leagueData.draftState === "object"
        ? result.leagueData.draftState
        : {};

    return {
      ...result,
      draftState: nextState,
      leagueData: {
        ...result.leagueData,
        draftState: {
          ...rootDraftState,
          seasonYear: Number(seasonYear),
          draftClass: nextState.draftClass || rootDraftState.draftClass || [],
          classType,
          seedMode,
          classMeta,
          draft: nextState,
        },
      },
    };
  }

  function getDraftOrderSignature(order = []) {
    if (!Array.isArray(order) || !order.length) return "";
    return order
      .map((pick, index) => {
        const number = Number(pick?.pick || index + 1);
        const owner = pick?.currentOwnerTeamName || pick?.teamName || "";
        const original = pick?.originalTeamName || pick?.originalOwnerTeamName || "";
        return `${number}:${owner}:${original}`;
      })
      .join("|");
  }

  function getProspectIdentityKey(prospect = {}) {
    return String(prospect?.id || prospect?.playerId || prospect?.prospectId || prospect?.name || prospect?.playerName || "");
  }

  function applyDraftBoardRanksFromClass(rows = [], fullClass = []) {
    if (!Array.isArray(rows)) return [];
    const normalizedFullClass = Array.isArray(fullClass) && fullClass.length ? fullClass : [];
    const rankById = new Map(
      normalizedFullClass
        .map((prospect) => [getProspectIdentityKey(prospect), getProspectRank(prospect, null)])
        .filter(([id, rank]) => id && Number.isFinite(Number(rank)))
    );

    return rows.map((row) => {
      const rank = rankById.get(getProspectIdentityKey(row));
      if (!Number.isFinite(Number(rank))) return row;
      return {
        ...row,
        draftProjection: Number(rank),
        rank: Number(rank),
        boardRank: Number(rank),
      };
    });
  }

  function normalizeSavedDraftState(saved, currentOrder = [], seasonYear) {
    if (!saved || typeof saved !== "object") return null;
    if (Number(saved.seasonYear) !== Number(seasonYear)) return null;
    if (!Array.isArray(saved.draftOrder) || !saved.draftOrder.length) return null;

    const hasFullDraftClass = Array.isArray(saved.draftClass) && saved.draftClass.length;
    const normalizedDraftClass = normalizeDraftClassRows(
      hasFullDraftClass ? saved.draftClass : saved.availableProspects || [],
      seasonYear
    );
    const normalizedAvailableProspects = hasFullDraftClass
      ? applyDraftBoardRanksFromClass(saved.availableProspects || [], normalizedDraftClass)
      : normalizedDraftClass;

    const savedSignature = saved.draftOrderSignature || getDraftOrderSignature(saved.draftOrder);
    const currentSignature = getDraftOrderSignature(currentOrder);
    if (currentSignature && savedSignature && savedSignature !== currentSignature) return null;

    const draftedPicks = Array.isArray(saved.draftedPicks) ? saved.draftedPicks : [];
    const currentPickIndex = Math.max(0, Math.min(
      Number(saved.currentPickIndex ?? draftedPicks.length) || 0,
      saved.draftOrder.length
    ));
    const completed = Boolean(
      saved.completed &&
      draftedPicks.length >= saved.draftOrder.length &&
      currentPickIndex >= saved.draftOrder.length
    );

    return {
      ...saved,
      seasonYear: Number(seasonYear),
      draftClass: normalizedDraftClass.length ? normalizedDraftClass : saved.draftClass,
      availableProspects: normalizedAvailableProspects.length
        ? normalizedAvailableProspects
        : saved.availableProspects || [],
      draftedPicks,
      currentPickIndex,
      completed,
      draftOrderSignature: savedSignature,
    };
  }

  function saveDraftState(draftState) {
    if (!draftState) return;
    const next = {
      ...draftState,
      draftOrderSignature:
        draftState.draftOrderSignature || getDraftOrderSignature(draftState.draftOrder || []),
    };
    localStorage.setItem(DRAFT_STATE_KEY, JSON.stringify(next));
  }

  function updateOffseasonState(patch) {
    const current = safeJSON(localStorage.getItem(OFFSEASON_STATE_KEY), {}) || {};
    const next = { ...current, ...patch };
    localStorage.setItem(OFFSEASON_STATE_KEY, JSON.stringify(next));
    return next;
  }

  async function persistLeagueData(updated, setLeagueData) {
    if (!updated) return;
    setLeagueData(updated);

    // The draft state is stored in localStorage, while the full league lives in
    // IndexedDB. Await the league write before marking a pick or the whole draft
    // complete so a fast navigation/reload cannot leave a 60/60 draft with zero
    // rookie rights in the league save.
    await saveLeagueData(updated);
  }

  function formatMoney(amount) {
    const value = Number(amount || 0);
    if (value >= 1_000_000) return `$${(value / 1_000_000).toFixed(1)}M`;
    if (value >= 1_000) return `$${Math.round(value / 1_000)}K`;
    return `$${value}`;
  }

  function getPickTeam(pick = {}) {
    return pick.currentOwnerTeamName || pick.teamName || pick.originalTeamName || "Unknown Team";
  }

  function normalizeTeamName(name = "") {
    return String(name || "").trim().toLowerCase();
  }

  function getAllTeamsFromLeague(leagueData) {
    if (!leagueData) return [];
    if (Array.isArray(leagueData.teams)) return leagueData.teams;
    if (leagueData.conferences) return Object.values(leagueData.conferences).flat();
    return [];
  }

  function getLeagueDraftedPlayerIds(leagueData) {
    const ids = new Set();
    const addPlayers = (rows) => {
      for (const player of rows || []) {
        if (player?.id) ids.add(String(player.id));
      }
    };

    for (const team of getAllTeamsFromLeague(leagueData)) {
      addPlayers(team?.players);
      addPlayers(team?.twoWayPlayers);
      addPlayers(team?.stashPlayers);
      addPlayers(team?.pendingRookieSignings);
    }
    addPlayers(leagueData?.freeAgents);
    return ids;
  }

  function getDraftStatePlayerIds(draftState) {
    return (draftState?.draftedPicks || [])
      .map((pick) => pick?.playerId)
      .filter(Boolean)
      .map(String);
  }

  function isDraftStateConsistentWithLeague(draftState, leagueData) {
    if (!draftState || typeof draftState !== "object") return false;
    const draftedIds = getDraftStatePlayerIds(draftState);
    if (!draftedIds.length) return !draftState.completed;

    const leagueIds = getLeagueDraftedPlayerIds(leagueData);
    if (!leagueIds.size) return false;

    return draftedIds.every((id) => leagueIds.has(id));
  }

  function removeInvalidDraftCompletionFromLeague(leagueData) {
    if (!leagueData || typeof leagueData !== "object") return leagueData;
    const next = { ...leagueData };
    const currentDraftState = next.draftState && typeof next.draftState === "object"
      ? { ...next.draftState }
      : {};
    delete currentDraftState.draft;
    currentDraftState.draftComplete = false;
    next.draftState = currentDraftState;
    return next;
  }

  function resolveTeamLogo(source = {}) {
    return (
      source.logo ||
      source.teamLogo ||
      source.newTeamLogo ||
      source.logoUrl ||
      source.image ||
      source.img ||
      ""
    );
  }

  function resolveDraftRowTeamLogo(source = {}) {
    return (
      source.currentOwnerTeamLogo ||
      source.currentOwnerLogo ||
      source.ownerLogo ||
      source.teamLogo ||
      source.logo ||
      source.logoUrl ||
      source.newTeamLogo ||
      source.originalTeamLogo ||
      ""
    );
  }

  function buildTeamLogoMap(leagueData, draftOrder = []) {
    const map = {};

    for (const team of getAllTeamsFromLeague(leagueData)) {
      const logo = resolveTeamLogo(team);
      if (!logo) continue;

      for (const name of [team.name, team.teamName, team.abbreviation, team.abbr, team.shortName]) {
        const key = normalizeTeamName(name);
        if (key) map[key] = logo;
      }
    }

    for (const row of draftOrder || []) {
      const logo = resolveDraftRowTeamLogo(row);
      if (!logo) continue;

      for (const name of [row.currentOwnerTeamName, row.teamName, row.originalTeamName]) {
        const key = normalizeTeamName(name);
        if (key && !map[key]) map[key] = logo;
      }
    }

    return map;
  }

  function draftTeamLogoRowBackground(logo, controls = {}) {
    if (!logo) return {};

    const safeLogo = String(logo).replaceAll('\"', '\\"');
    const size = Number(controls.size ?? 90);
    const x = Number(controls.x ?? 0);
    const y = Number(controls.y ?? 0);
    const opacity = Math.max(0, Math.min(1, Number(controls.opacity ?? 1)));
    const logoFade = 1 - opacity;
    const rightOffset = Number(controls.rightOffset ?? 34);

    return {
      backgroundImage: `linear-gradient(rgba(10,10,10,${logoFade}), rgba(10,10,10,${logoFade})), url("${safeLogo}")`,
      backgroundRepeat: "no-repeat, no-repeat",
      backgroundSize: `100% 100%, ${size}px ${size}px`,
      backgroundPosition: `center, calc(100% - ${rightOffset - x}px) calc(50% + ${y}px)`,
    };
  }

  function TinyTeamLogo({ src, name }) {
    if (!src) {
      return (
        <div className="h-9 w-9 rounded-full bg-white/5 border border-white/10 shrink-0" />
      );
    }

    return (
      <img
        src={src}
        alt={name || "Team"}
        className="h-9 w-9 object-contain shrink-0 drop-shadow-[0_6px_12px_rgba(0,0,0,0.45)]"
        loading="lazy"
      />
    );
  }

  function getHeadshot(source = {}) {
    return source.headshot || source.image || source.img || "";
  }

  function getDraftSource(source = {}) {
    return (
      source.college ||
      source.school ||
      source.university ||
      source.academy ||
      source.academyName ||
      source.sourceName ||
      source.draftSource ||
      source.nationality ||
      ""
    );
  }

  function getFullProspectSnapshot(pick = {}) {
    return (
      pick.prospect ||
      pick.prospectSnapshot ||
      pick.fullProspect ||
      pick.draftProspect ||
      pick.originalProspect ||
      {}
    );
  }

  function normalizePlayerName(value = "") {
    return String(value || "").trim().toLowerCase();
  }

  function getTeamPlayers(team = {}) {
    const groups = [
      team.roster,
      team.players,
      team.playerList,
      team.signedPlayers,
    ];

    return groups.flatMap((group) => (Array.isArray(group) ? group : []));
  }

  function findDraftedPlayerInLeague(leagueData, pick = {}) {
    const teams = getAllTeamsFromLeague(leagueData);
    const pickId = String(pick.playerId || pick.id || pick.prospectId || "");
    const pickName = normalizePlayerName(pick.playerName || pick.name);

    for (const team of teams) {
      for (const player of getTeamPlayers(team)) {
        const playerIds = [
          player.id,
          player.playerId,
          player.prospectId,
          player.draftId,
          player.originalProspectId,
        ].map((value) => String(value || ""));

        const playerName = normalizePlayerName(player.name || player.playerName);

        if (pickId && playerIds.includes(pickId)) {
          return player;
        }

        if (pickName && playerName === pickName) {
          return player;
        }
      }
    }

    return {};
  }

  function getDraftIdentityIds(source = {}) {
    return [
      source.id,
      source.playerId,
      source.prospectId,
      source.draftId,
      source.originalProspectId,
    ]
      .map((value) => String(value || ""))
      .filter(Boolean);
  }

  function draftIdentityMatches(candidate = {}, pick = {}) {
    if (!candidate || typeof candidate !== "object") return false;

    const pickIds = getDraftIdentityIds(pick);
    const candidateIds = getDraftIdentityIds(candidate);

    if (pickIds.length && candidateIds.some((id) => pickIds.includes(id))) {
      return true;
    }

    const pickName = normalizePlayerName(pick.playerName || pick.name);
    const candidateName = normalizePlayerName(candidate.playerName || candidate.name);

    return Boolean(pickName && candidateName && pickName === candidateName);
  }

  function findDraftSourceDeep(root, pick = {}) {
    if (!root || typeof root !== "object") return "";

    const stack = [root];
    const seen = new Set();
    let searched = 0;

    while (stack.length && searched < 12000) {
      const current = stack.pop();
      searched += 1;

      if (!current || typeof current !== "object" || seen.has(current)) continue;
      seen.add(current);

      if (draftIdentityMatches(current, pick)) {
        const source = getDraftSource(current);
        if (source) return source;

        const nestedSource = getDraftSource(getFullProspectSnapshot(current));
        if (nestedSource) return nestedSource;
      }

      if (Array.isArray(current)) {
        for (const item of current) {
          if (item && typeof item === "object") stack.push(item);
        }
      } else {
        for (const value of Object.values(current)) {
          if (value && typeof value === "object") stack.push(value);
        }
      }
    }

    return "";
  }

  function getDraftSourceForPick({ pick = {}, displayPick = {}, fullProspect = {}, leaguePlayer = {}, draftState = null, workingLeagueData = null }) {
    return (
      getDraftSource(displayPick) ||
      getDraftSource(pick) ||
      getDraftSource(fullProspect) ||
      getDraftSource(leaguePlayer) ||
      findDraftSourceDeep(draftState, pick) ||
      findDraftSourceDeep(workingLeagueData, pick) ||
      ""
    );
  }

  function enrichDraftStateWithDraftSources(nextState = {}, previousState = null, leagueData = null) {
    if (!nextState || !Array.isArray(nextState.draftedPicks)) return nextState;

    return {
      ...nextState,
      draftedPicks: nextState.draftedPicks.map((pick) => {
        const fullProspect = getFullProspectSnapshot(pick);
        const leaguePlayer = findDraftedPlayerInLeague(leagueData, pick);
        const source = getDraftSourceForPick({
          pick,
          fullProspect,
          leaguePlayer,
          draftState: previousState,
          workingLeagueData: leagueData,
        }) || getDraftSourceForPick({
          pick,
          fullProspect,
          leaguePlayer,
          draftState: nextState,
          workingLeagueData: leagueData,
        });

        if (!source) return pick;

        return {
          ...pick,
          college: pick.college || source,
          school: pick.school || source,
          university: pick.university || source,
          academy: pick.academy || source,
          academyName: pick.academyName || source,
          sourceName: pick.sourceName || source,
          draftSource: pick.draftSource || source,
          prospectSnapshot: {
            ...fullProspect,
            college: fullProspect.college || source,
            school: fullProspect.school || source,
            university: fullProspect.university || source,
            academy: fullProspect.academy || source,
            academyName: fullProspect.academyName || source,
            sourceName: fullProspect.sourceName || source,
            draftSource: fullProspect.draftSource || source,
          },
        };
      }),
    };
  }

  function getDraftedPickSelectId(pick = {}) {
    return `drafted-${pick.pick || ""}-${pick.playerId || pick.id || pick.playerName || pick.name || ""}`;
  }

  function normalizeDraftedPickForCard(pick = {}) {
    if (!pick) return null;

    const fullProspect = getFullProspectSnapshot(pick);
    const merged = { ...fullProspect, ...pick };

    const attrs =
      Array.isArray(pick.attrs) && pick.attrs.length
        ? pick.attrs
        : Array.isArray(pick.attributes) && pick.attributes.length
        ? pick.attributes
        : Array.isArray(fullProspect.attrs) && fullProspect.attrs.length
        ? fullProspect.attrs
        : Array.isArray(fullProspect.attributes) && fullProspect.attributes.length
        ? fullProspect.attributes
        : [];

    const traits = pick.traits || fullProspect.traits || {};

    return {
      ...merged,
      id: getDraftedPickSelectId(pick),
      name: merged.name || merged.playerName || "Drafted Player",
      playerName: merged.playerName || merged.name || "Drafted Player",
      pos: merged.pos || "-",
      secondaryPos: merged.secondaryPos || "",
      age: merged.age ?? "-",
      overall: merged.overall ?? merged.ovr ?? "-",
      potential: merged.potential ?? merged.pot ?? "-",
      draftProjection: merged.draftProjection || merged.pick || merged.trueRank || "-",
      trueRank: merged.trueRank || merged.pick || merged.draftProjection || "-",
      archetype: merged.archetype || merged.type || "Drafted Prospect",
      tier: merged.tier || (merged.round ? `Round ${merged.round}` : "Drafted"),
      headshot: getHeadshot(merged),
      attrs,
      traits,
      height: merged.height,
      weight: merged.weight,
      college: getDraftSource(merged),
      school: merged.school || "",
      university: merged.university || "",
      academy: merged.academy || "",
      academyName: merged.academyName || "",
      sourceName: merged.sourceName || "",
      draftSource: merged.draftSource || "",
      nationality: merged.nationality || "",
      identityKey: merged.identityKey || "",
      contract: merged.contract || null,
    };
  }

  function ProspectHeadshot({ src, name, size = "sm" }) {
    const sizeClass =
      size === "lg"
        ? "h-28 w-24"
        : size === "md"
        ? "h-16 w-14"
        : "h-16 w-14";

    if (!src) {
      return (
        <div
          className={`${sizeClass} shrink-0 flex items-center justify-center text-[10px] font-black text-white/25`}
        >
          IMG
        </div>
      );
    }

    return (
      <div className={`${sizeClass} shrink-0 overflow-hidden flex items-end justify-center`}>
        <img
          src={src}
          alt={name || "Prospect"}
          className="h-full w-full object-contain object-bottom drop-shadow-[0_8px_12px_rgba(0,0,0,0.5)]"
          loading="lazy"
        />
      </div>
    );
  }

  function ProspectHeroHeadshot({ src, name }) {
    return (
      <div className="relative flex h-40 w-44 shrink-0 self-end items-end justify-center overflow-hidden">
        {src ? (
          <img
            src={src}
            alt={name || "Prospect"}
            className="h-full w-full object-contain object-bottom drop-shadow-[0_16px_18px_rgba(0,0,0,0.5)]"
            loading="lazy"
          />
        ) : (
          <div className="flex h-28 w-24 items-center justify-center text-[10px] font-black text-white/25">
            IMG
          </div>
        )}
      </div>
    );
  }

  function getProspectRank(prospect = {}, fallback = 999) {
    const rank = Number(prospect?.draftProjection ?? prospect?.rank ?? prospect?.boardRank ?? prospect?.trueRank);
    return Number.isFinite(rank) ? rank : fallback;
  }

  function prospectSort(a, b) {
    return (
      getProspectRank(a, 999) - getProspectRank(b, 999) ||
      Number(b.potential || 0) - Number(a.potential || 0) ||
      Number(b.overall || 0) - Number(a.overall || 0) ||
      String(a.name || "").localeCompare(String(b.name || ""))
    );
  }

  const DEFAULT_DRAFT_SORT = { key: null, direction: null };

  function safeDraftSortNumber(value, fallback) {
    const n = Number(value);
    return Number.isFinite(n) ? n : fallback;
  }

  function getProspectSortValue(prospect = {}, key = "") {
    if (key === "rank") {
      return getProspectRank(prospect, 999);
    }

    if (key === "overall") {
      return safeDraftSortNumber(prospect.overall ?? prospect.ovr ?? prospect.rating, -1);
    }

    if (key === "potential") {
      return safeDraftSortNumber(prospect.potential ?? prospect.pot ?? prospect.potential_rating, -1);
    }

    if (key === "age") {
      return safeDraftSortNumber(prospect.age, 99);
    }

    if (key === "position") {
      return String(prospect.pos || prospect.position || "").toUpperCase();
    }

    return "";
  }

  function sortDraftProspects(prospects = [], sortState = DEFAULT_DRAFT_SORT) {
    const key = sortState?.key;
    const direction = sortState?.direction;

    if (!key || !direction) {
      return [...prospects].sort(prospectSort);
    }

    const multiplier = direction === "desc" ? -1 : 1;

    return [...prospects].sort((a, b) => {
      const aValue = getProspectSortValue(a, key);
      const bValue = getProspectSortValue(b, key);

      let result = 0;

      if (typeof aValue === "number" && typeof bValue === "number") {
        result = aValue - bValue;
      } else {
        result = String(aValue || "").localeCompare(String(bValue || ""));
      }

      if (result !== 0) return result * multiplier;

      return prospectSort(a, b);
    });
  }

  function getNextDraftSortState(currentSort = DEFAULT_DRAFT_SORT, key = "") {
    if (currentSort?.key !== key) {
      return { key, direction: "asc" };
    }

    if (currentSort?.direction === "asc") {
      return { key, direction: "desc" };
    }

    return DEFAULT_DRAFT_SORT;
  }

  function SortableDraftHeader({ label, sortKey, sortState, onSortChange, className = "" }) {
    const active = sortState?.key === sortKey;
    const arrow = !active ? "↕" : sortState.direction === "asc" ? "▲" : "▼";

    return (
      <th className={className}>
        <button
          type="button"
          onClick={() => onSortChange(sortKey)}
          className={`inline-flex items-center justify-center gap-1 rounded-md px-2 py-1 font-extrabold transition ${
            active
              ? "bg-orange-600/25 text-orange-200"
              : "text-white/70 hover:bg-white/10 hover:text-white"
          }`}
        >
          <span>{label}</span>
          <span className="text-[10px] opacity-80">{arrow}</span>
        </button>
      </th>
    );
  }

  function attrLetter(value) {
    const n = Number(value || 0);
    if (n >= 94) return "A+";
    if (n >= 87) return "A";
    if (n >= 80) return "A-";
    if (n >= 77) return "B+";
    if (n >= 73) return "B";
    if (n >= 70) return "B-";
    if (n >= 67) return "C+";
    if (n >= 63) return "C";
    if (n >= 60) return "C-";
    if (n >= 57) return "D+";
    if (n >= 53) return "D";
    if (n >= 50) return "D-";
    return "F";
  }

  function SmallPill({ label, value }) {
    return (
      <div className="rounded-xl bg-white/5 border border-white/10 px-3 py-2">
        <div className="text-[10px] text-white/40 uppercase tracking-wide">{label}</div>
        <div className="text-sm font-extrabold text-white mt-1">{value}</div>
      </div>
    );
  }
  function OverallPill({ value }) {
    const overall = Number(value || 0);
    const fillPercent = Math.min(overall / 99, 1);
    const circleCircumference = 2 * Math.PI * 50;
    const strokeOffset = circleCircumference * (1 - fillPercent);

    return (
      <div className="rounded-xl bg-white/5 border border-white/10 px-1 py-1 flex items-center justify-center">
        <div className="relative flex items-center justify-center">
          <svg width="42" height="42" viewBox="0 0 120 120">
            <defs>
              <linearGradient id="draftOvrGradient" x1="0%" y1="0%" x2="100%" y2="0%">
                <stop offset="0%" stopColor="#FFA500" />
                <stop offset="100%" stopColor="#FFD54F" />
              </linearGradient>
            </defs>

            <circle
              cx="60"
              cy="60"
              r="50"
              stroke="rgba(255,255,255,0.08)"
              strokeWidth="8"
              fill="none"
            />

            <circle
              cx="60"
              cy="60"
              r="50"
              stroke="url(#draftOvrGradient)"
              strokeWidth="8"
              strokeLinecap="round"
              fill="none"
              strokeDasharray={circleCircumference}
              strokeDashoffset={strokeOffset}
              transform="rotate(-90 60 60)"
            />
          </svg>

          <div className="absolute flex flex-col items-center justify-center text-center">
            <p className="text-[9px] text-gray-300 tracking-wide mb-0.5">OVR</p>
            <p className="text-[14px] font-extrabold text-orange-400 leading-none mt-[-4px]">
              {value ?? "-"}
            </p>
          </div>
        </div>
      </div>
    );
  }
  function DraftBoardPlayerMeta({ overall, potential, age, pos }) {
    return (
      <div className="mt-1 flex flex-wrap items-center gap-x-3 gap-y-1 text-[11px] font-bold text-white/55">
        <span>OVR <b className="text-orange-300">{overall ?? "-"}</b></span>
        <span>POT <b className="text-orange-300">{potential ?? "-"}</b></span>
        <span>{pos || "-"}</span>
        <span>Age {age ?? "-"}</span>
      </div>
    );
  }

  function CombinedDraftBoard({
    prospects,
    draftedPicks = [],
    draftOrder = [],
    teamLogoByName = {},
    selectedProspectId,
    onSelect,
    onOpenReport = () => {},
    disabled,
    availableStartRef,
    draftCompleted = false,
    workingLeagueData = null,
    draftState = null,
    sortState = DEFAULT_DRAFT_SORT,
    onSortChange = () => {},
    canDraft = false,
    onDraft = () => {},
  }) {
    const orderedPicks = [...draftedPicks].sort(
      (a, b) => Number(a.pick || 0) - Number(b.pick || 0)
    );

    const draftOrderByPick = new Map(
      (draftOrder || []).map((row) => [Number(row.pick || 0), row])
    );

    const boardCountText = draftCompleted
      ? `${orderedPicks.length} drafted`
      : `${prospects.length} left`;

    const availableCountText = draftCompleted
      ? `${prospects.length} undrafted`
      : `${prospects.length} left`;

    const selectedAvailableProspect = (prospects || []).find(
      (row) => String(row?.id) === String(selectedProspectId || "")
    );

    // Manual team-logo background controls.
    // x: positive = right, negative = left.
    // y: positive = lower, negative = higher.
    // size: normal un-enlarged logo background is around 90.
    // opacity: 1 = current/full strength, 0.5 = half visible, 0 = hidden.
    const draftBoardTeamLogo = {
      x: 155,
      y: 30,
      size: 300,
      opacity: 0.5,
    };

    const nextPick = !draftCompleted ? (draftOrder || [])[orderedPicks.length] || null : null;
    const nextPickTeamName = nextPick ? getPickTeam(nextPick) : "";
    const nextPickLogo = nextPick
      ? teamLogoByName[normalizeTeamName(nextPickTeamName)] || resolveDraftRowTeamLogo(nextPick)
      : "";

    return (
      <div className="bmTablePanel bmDraftBoardPanel flex h-full min-h-0 flex-col overflow-hidden rounded-2xl border border-white/10 bg-neutral-900 shadow-2xl">
        <div className="flex shrink-0 items-center justify-between gap-4 border-b border-white/10 bg-neutral-800/90 px-4 py-2.5">
          <div>
            <h2 className="text-2xl font-extrabold">Draft Board</h2>
            <p className="text-xs text-white/50">Drafted players and available prospects.</p>
          </div>
          <div className="flex items-center gap-3">
            <div className="text-sm font-bold text-white/50">{boardCountText}</div>
            {!draftCompleted && (
              <button
                type="button"
                onClick={onDraft}
                disabled={!canDraft}
                className="rounded-lg bg-emerald-600 px-4 py-2 text-sm font-extrabold text-white transition hover:bg-emerald-500 disabled:cursor-not-allowed disabled:bg-neutral-700 disabled:text-white/40"
              >
                {selectedAvailableProspect ? `Draft ${selectedAvailableProspect.name}` : "Select a Prospect"}
              </button>
            )}
          </div>
        </div>

        <div className="bmOrangeScrollbar min-h-0 flex-1 overflow-auto">
          {orderedPicks.length > 0 && (
            <div className="bg-black/10 border-b border-white/10">
              <div className="sticky top-0 z-20 bg-neutral-800/95 px-5 py-3 border-b border-white/10">
                <div className="text-xs uppercase tracking-[0.2em] text-white/45">
                  Drafted Players
                </div>
              </div>

              {orderedPicks.map((pick, index) => {
                const orderPick = draftOrderByPick.get(Number(pick.pick || 0)) || {};
                const leaguePlayer = findDraftedPlayerInLeague(workingLeagueData, pick);
                const fullProspect = getFullProspectSnapshot(pick);
                const displayPick = normalizeDraftedPickForCard({
                  ...leaguePlayer,
                  ...pick,
                  prospectSnapshot: {
                    ...leaguePlayer,
                    ...fullProspect,
                  },
                });
                const displayName = displayPick.playerName || displayPick.name || "Drafted Player";
                const displaySource = getDraftSourceForPick({
                  pick,
                  displayPick,
                  fullProspect,
                  leaguePlayer,
                  draftState,
                  workingLeagueData,
                });
                const teamName = pick.teamName || orderPick.currentOwnerTeamName || orderPick.teamName || "";
                const logo =
                  teamLogoByName[normalizeTeamName(teamName)] ||
                  resolveDraftRowTeamLogo(orderPick) ||
                  resolveDraftRowTeamLogo(pick);
                const headshot =
                  getHeadshot(displayPick) ||
                  getHeadshot(fullProspect) ||
                  getHeadshot(leaguePlayer);
                const draftedSelectId = getDraftedPickSelectId(pick);
                const active = selectedProspectId === draftedSelectId;

                return (
                  <div
                    key={`${pick.pick}-${pick.playerId}`}
                    onClick={() => onSelect(draftedSelectId)}
                    className={`bmRowEnter bmDraftBoardRow grid grid-cols-[22px_minmax(0,1fr)] items-center gap-3 px-4 py-2.5 border-b border-white/10 transition cursor-pointer ${
                      active
                        ? "bmDraftBoardRowActive"
                        : pick.userControlled
                        ? "bmDraftBoardRowUser"
                        : ""
                    }`}
                    style={{
                      animationDelay: `${Math.min(index, 12) * 22}ms`,
                      ...draftTeamLogoRowBackground(logo, draftBoardTeamLogo),
                    }}
                  >
                    <div className="font-extrabold text-orange-200">#{pick.pick}</div>

                    <div className="flex items-center gap-4 min-w-0">
                      <ProspectHeadshot src={headshot} name={displayName} />
  <div className="min-w-0 -translate-y-1">
    <div className="text-lg font-extrabold text-white leading-tight break-words">
      {displayName}
      {pick.userControlled ? (
        <span className="ml-2 text-xs text-emerald-300">Your pick</span>
      ) : null}
    </div>
    {displaySource ? (
      <div className="mt-0.5 text-xs text-white/45 leading-snug break-words">
        {displaySource}
      </div>
    ) : null}

    <DraftBoardPlayerMeta
      overall={displayPick.overall ?? displayPick.ovr}
      potential={displayPick.potential ?? displayPick.pot}
      age={displayPick.age}
      pos={displayPick.pos}
    />
  </div>
                    </div>

                  </div>
                );
              })}
            </div>
          )}

          <div ref={availableStartRef} />

          <div className="shrink-0 bg-neutral-800/95 px-5 py-3 border-b border-white/10">
            <div className="flex items-center justify-between">
              <div>
                <div className="text-xs uppercase tracking-[0.2em] text-white/45">
                  Available Prospects
                </div>
                <div className="text-xs text-white/50">Select a prospect to view or draft.</div>
              </div>
              <div className="text-xs text-white/45 font-bold">
                {availableCountText}
              </div>
            </div>
          </div>

          <table className="w-full min-w-[1040px] text-sm">
            <thead className="sticky top-0 bg-neutral-800/95 text-white/70 z-10">
              <tr>
                <SortableDraftHeader
                  label="Rank"
                  sortKey="rank"
                  sortState={sortState}
                  onSortChange={onSortChange}
                  className="px-4 py-3 text-left"
                />
                <th className="px-4 py-3 text-left min-w-[310px]">Player</th>
                <SortableDraftHeader
                  label="POS"
                  sortKey="position"
                  sortState={sortState}
                  onSortChange={onSortChange}
                  className="px-4 py-3 text-center"
                />
                <SortableDraftHeader
                  label="OVR"
                  sortKey="overall"
                  sortState={sortState}
                  onSortChange={onSortChange}
                  className="px-4 py-3 text-center"
                />
                <SortableDraftHeader
                  label="POT"
                  sortKey="potential"
                  sortState={sortState}
                  onSortChange={onSortChange}
                  className="px-4 py-3 text-center"
                />
                <SortableDraftHeader
                  label="Age"
                  sortKey="age"
                  sortState={sortState}
                  onSortChange={onSortChange}
                  className="px-4 py-3 text-center"
                />
                <th className="px-4 py-3 text-left">Type</th>
              </tr>
            </thead>

            <tbody>
              {prospects.map((prospect, index) => {
                const active = selectedProspectId === prospect.id;

                return (
                  <tr
                    key={prospect.id}
                    onClick={() => !disabled && onSelect(prospect.id)}
                    onDoubleClick={() => {
                      if (!disabled) {
                        onSelect(prospect.id);
                        onOpenReport(prospect.id);
                      }
                    }}
                    className={`bmRowEnter bmDraftBoardRow border-b border-white/10 transition ${
                      disabled
                        ? "opacity-70"
                        : active
                        ? "bmDraftBoardRowActive cursor-pointer"
                        : "cursor-pointer"
                    }`}
                    style={{
                      animationDelay: `${Math.min(index, 18) * 18}ms`,
                      ...draftTeamLogoRowBackground(nextPickLogo, draftBoardTeamLogo),
                    }}
                  >
                    <td className="px-4 py-2.5 font-bold text-orange-200">
                      #{getProspectRank(prospect, "-")}
                    </td>

                    <td className="px-4 py-2.5 min-w-[310px]">
                      <div className="flex items-center gap-4 min-w-0">
                        <ProspectHeadshot src={getHeadshot(prospect)} name={prospect.name} />
                        <div className="min-w-0 flex-1">
                          <div className="flex flex-wrap items-center gap-2 text-lg font-extrabold text-white leading-tight break-words">
                            <span>{prospect.name}</span>
                            <span className="bmDraftSelectedBadge hidden rounded-full border border-orange-300/70 bg-orange-500/20 px-2 py-0.5 text-[9px] font-black uppercase tracking-[0.14em] text-orange-100">
                              Selected
                            </span>
                          </div>
                          <div className="text-xs text-white/45 leading-snug break-words">
                            {getDraftSource(prospect)}
                          </div>
                          <button
                            type="button"
                            onClick={(e) => {
                              e.stopPropagation();
                              onSelect(prospect.id);
                              onOpenReport(prospect.id);
                            }}
                            className="mt-2 rounded-lg border border-white/10 bg-white/[0.05] px-3 py-1 text-[11px] font-black uppercase tracking-wide text-white/65 hover:border-orange-300/50 hover:bg-orange-500/15 hover:text-orange-100"
                          >
                            View Report
                          </button>
                        </div>
                      </div>
                    </td>

                    <td className="px-4 py-2.5 text-center font-black text-white/75">
                      {prospect.pos || prospect.position || "-"}
                    </td>

                    <td className="px-4 py-2.5 text-center font-black text-orange-200">
                      {prospect.overall ?? prospect.ovr ?? "-"}
                    </td>

                    <td className="px-4 py-2.5 text-center font-black text-white/75">
                      {prospect.potential ?? prospect.pot ?? "-"}
                    </td>

                    <td className="px-4 py-2.5 text-center font-bold text-white/75">{prospect.age}</td>

                    <td className="px-4 py-2.5 text-left">
                      <div className="font-semibold text-white/80">{prospect.archetype}</div>
                      <div className="text-xs text-white/45">{prospect.tier}</div>
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>

          {!prospects.length && (
            <div className="p-8 text-white/50 text-center">
              No prospects remaining.
            </div>
          )}
        </div>
      </div>
    );
  }

  function ProspectCard({ prospect }) {
    if (!prospect) {
      return (
        <div className="bmSolidPanel rounded-3xl bg-neutral-900 border border-white/10 p-6 text-white/50">
          Select a prospect to view scouting details.
        </div>
      );
    }

    const attrs = Array.isArray(prospect.attrs) ? prospect.attrs : [];
    const labels = [
      ["3PT", attrs[0]],
      ["MID", attrs[1]],
      ["CLS", attrs[2]],
      ["BALL", attrs[4]],
      ["PASS", attrs[5]],
      ["ATH", attrs[7]],
      ["PER D", attrs[8]],
      ["INS D", attrs[9]],
      ["REB", attrs[12]],
      ["IQ", attrs[13]],
    ];

    const salary = prospect?.contract?.salaryByYear?.[0];
    const headshot = getHeadshot(prospect);

    return (
      <div className="bmSolidPanel bmRowEnter rounded-3xl bg-neutral-900 border border-white/10 p-6 shadow-2xl">
        <div className="flex items-start justify-between gap-4 mb-4">
          <div className="flex items-end gap-5 min-w-0">
            <ProspectHeroHeadshot src={headshot} name={prospect.name} />
            <div className="min-w-0">
              <div className="text-xs uppercase tracking-[0.2em] text-white/40 mb-2">Scouting Report</div>
              <h2 className="text-3xl font-extrabold text-white leading-tight">{prospect.name}</h2>
              <p className="text-white/55 mt-1">
                {prospect.pos}{prospect.secondaryPos ? ` / ${prospect.secondaryPos}` : ""} - {prospect.archetype}
              </p>
              {getDraftSource(prospect) && (
                <p className="text-xs text-white/40 mt-1">
                  {getDraftSource(prospect)}
                </p>
              )}
              {(prospect.nationality || prospect.identityKey) && (
                <p className="text-xs text-white/35 mt-1">
                  {prospect.nationality || ""}{prospect.identityKey ? ` - ${String(prospect.identityKey).replaceAll("_", " ")}` : ""}
                </p>
              )}
            </div>
          </div>
          <div className="text-right shrink-0">
            <div className="text-xs text-white/40 uppercase">Projection</div>
            <div className="text-2xl font-extrabold text-orange-300">#{getProspectRank(prospect, "-")}</div>
          </div>
        </div>

  <div className="grid grid-cols-3 gap-3 mb-5">
    <OverallPill value={prospect.overall} />
    <SmallPill label="POT" value={prospect.potential} />
    <SmallPill label="Age" value={prospect.age} />
          <SmallPill label="Height" value={prospect.height ? `${Math.floor(prospect.height / 12)}'${prospect.height % 12}` : "-"} />
          <SmallPill label="Weight" value={prospect.weight || "-"} />
          <SmallPill label="Salary" value={salary ? formatMoney(salary) : "Rookie"} />
        </div>

        <div className="grid grid-cols-2 gap-2 mb-5">
          {labels.map(([label, value]) => {
            const hasValue = Number.isFinite(Number(value));

            return (
              <div key={label} className="flex items-center justify-between rounded-xl bg-white/5 border border-white/10 px-3 py-2">
                <span className="text-xs text-white/45 font-semibold">{label}</span>
                <span className="text-sm font-extrabold text-white">
                  {hasValue ? attrLetter(value) : "-"} <span className="text-white/35">{hasValue ? value : ""}</span>
                </span>
              </div>
            );
          })}
        </div>

        <div className="rounded-2xl bg-black/25 border border-white/10 p-4">
          <div className="text-xs uppercase tracking-wide text-white/40 mb-2">Traits</div>
          <div className="grid grid-cols-2 gap-2 text-sm">
            <div>NBA Ready: <span className="font-bold">{Math.round(Number(prospect.traits?.nbaReady || 0) * 100)}%</span></div>
            <div>Star Upside: <span className="font-bold">{Math.round(Number(prospect.traits?.starUpside || 0) * 100)}%</span></div>
            <div>Boom/Bust: <span className="font-bold">{Math.round(Number(prospect.traits?.boomBust || 0) * 100)}%</span></div>
            <div>Work Ethic: <span className="font-bold">{Math.round(Number(prospect.traits?.workEthic || 0) * 100)}%</span></div>
          </div>
        </div>
      </div>
    );
  }

  function DraftedPicks({ picks = [] }) {
    const recent = [...picks].slice(-12).reverse();

    return (
      <div className="bmTablePanel rounded-3xl bg-neutral-900 border border-white/10 overflow-hidden shadow-2xl">
        <div className="px-5 py-4 bg-neutral-800/90 border-b border-white/10">
          <h2 className="text-2xl font-extrabold">Draft Log</h2>
          <p className="text-sm text-white/50">Latest selections.</p>
        </div>
        <div className="max-h-[360px] overflow-auto">
          {recent.length ? (
            recent.map((pick, index) => (
              <div key={`${pick.pick}-${pick.playerId}`} className="bmRowEnter px-4 py-3 border-b border-white/10" style={{ animationDelay: `${Math.min(index, 12) * 22}ms` }}>
                <div className="flex items-center justify-between gap-3">
                  <div className="font-extrabold text-orange-200">#{pick.pick}</div>
                  <div className="text-right text-xs text-white/45">{pick.teamName}</div>
                </div>
                <div className="mt-1 font-bold text-white">{pick.playerName}</div>
                <div className="text-xs text-white/50">
                  {pick.pos} - {pick.overall} OVR - {pick.potential} POT {pick.userControlled ? "- Your pick" : ""}
                </div>
              </div>
            ))
          ) : (
            <div className="p-6 text-white/50">No picks made yet.</div>
          )}
        </div>
      </div>
    );
  }

  export default function Draft() {
    const navigate = useNavigate();
    const { leagueData, setLeagueData, selectedTeam } = useGame();

    const seasonYear = getSeasonYear(leagueData);
    const savedSelectedTeam = safeJSON(localStorage.getItem("selectedTeam"), "");
    const selectedTeamName =
      selectedTeam?.name ||
      (typeof savedSelectedTeam === "string" ? savedSelectedTeam : savedSelectedTeam?.name) ||
      "";

    const [workingLeagueData, setWorkingLeagueData] = useState(leagueData || null);
    const [draftState, setDraftState] = useState(null);
    const [selectedProspectId, setSelectedProspectId] = useState(null);
    const [scoutingReportOpen, setScoutingReportOpen] = useState(false);
    const [draftBoardSort, setDraftBoardSort] = useState(DEFAULT_DRAFT_SORT);
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState("");
    const availableStartRef = useRef(null);

    useEffect(() => {
      if (!leagueData) return;

      const cleanedLeagueData = stripLegacyDraftStateFromLeagueData(leagueData, seasonYear);
      setWorkingLeagueData(cleanedLeagueData);

      if (cleanedLeagueData !== leagueData) {
        persistLeagueData(cleanedLeagueData, setLeagueData);
      }
    }, [leagueData, seasonYear, setLeagueData]);

    const lottery = useMemo(() => readDraftLottery(seasonYear), [seasonYear]);
    const lotteryOrderLocked = isLotteryDraftOrderLocked(lottery);
    const draftOrder = useMemo(() => {
      const rawOrder = lotteryOrderLocked
        ? lottery?.result?.fullDraftOrder || []
        : workingLeagueData?.draftState?.draftLotteryComplete
        ? workingLeagueData?.draftState?.draftOrder || []
        : [];

      if (!rawOrder?.length || !workingLeagueData) return rawOrder || [];
      return applyDraftPickOwnershipToOrder(rawOrder, { leagueData: workingLeagueData, seasonYear });
    }, [lotteryOrderLocked, lottery, workingLeagueData, seasonYear]);

    const teamLogoByName = useMemo(() => {
      return buildTeamLogoMap(workingLeagueData, draftOrder);
    }, [workingLeagueData, draftOrder]);

    useEffect(() => {
      if (!draftOrder?.length) return;
      markDraftStartedForYear(seasonYear);
    }, [draftOrder?.length, seasonYear]);

    const currentPick = useMemo(() => {
      if (!draftState || draftState.completed) return null;
      return draftState.draftOrder?.[draftState.currentPickIndex] || null;
    }, [draftState]);

    const currentTeamName = getPickTeam(currentPick || {});
    const userOnClock = Boolean(currentPick && selectedTeamName && currentTeamName === selectedTeamName);
    const remainingUserPicks = useMemo(() => {
      if (!selectedTeamName || !Array.isArray(draftState?.draftOrder)) return [];
      const start = Math.max(0, Number(draftState?.currentPickIndex || 0));
      return draftState.draftOrder.slice(start).filter((pick) => getPickTeam(pick) === selectedTeamName);
    }, [draftState?.draftOrder, draftState?.currentPickIndex, selectedTeamName]);
    const hasRemainingUserPick = remainingUserPicks.length > 0;

    const availableProspects = useMemo(() => {
      const fullClass = normalizeDraftClassRows(
        draftState?.draftClass?.length ? draftState.draftClass : draftState?.availableProspects || [],
        seasonYear
      );
      const availableWithStableRanks = draftState?.draftClass?.length
        ? applyDraftBoardRanksFromClass(draftState?.availableProspects || [], fullClass)
        : fullClass;
      return sortDraftProspects(availableWithStableRanks, draftBoardSort);
    }, [draftState, draftBoardSort, seasonYear]);

    const handleDraftBoardSortChange = (key) => {
      setDraftBoardSort((prev) => getNextDraftSortState(prev, key));
    };

    const draftedProspectCards = useMemo(() => {
      return (draftState?.draftedPicks || [])
        .map((pick) => {
          const leaguePlayer = findDraftedPlayerInLeague(workingLeagueData, pick);
          const fullProspect = getFullProspectSnapshot(pick);

          const source = getDraftSourceForPick({
            pick,
            fullProspect,
            leaguePlayer,
            draftState,
            workingLeagueData,
          });

          return normalizeDraftedPickForCard({
            ...leaguePlayer,
            ...pick,
            college: pick.college || leaguePlayer.college || fullProspect.college || source,
            school: pick.school || leaguePlayer.school || fullProspect.school || source,
            university: pick.university || leaguePlayer.university || fullProspect.university || source,
            academy: pick.academy || leaguePlayer.academy || fullProspect.academy || source,
            academyName: pick.academyName || leaguePlayer.academyName || fullProspect.academyName || source,
            sourceName: pick.sourceName || leaguePlayer.sourceName || fullProspect.sourceName || source,
            draftSource: pick.draftSource || leaguePlayer.draftSource || fullProspect.draftSource || source,
            prospectSnapshot: {
              ...leaguePlayer,
              ...fullProspect,
              college: leaguePlayer.college || fullProspect.college || source,
              school: leaguePlayer.school || fullProspect.school || source,
              university: leaguePlayer.university || fullProspect.university || source,
              academy: leaguePlayer.academy || fullProspect.academy || source,
              academyName: leaguePlayer.academyName || fullProspect.academyName || source,
              sourceName: leaguePlayer.sourceName || fullProspect.sourceName || source,
              draftSource: leaguePlayer.draftSource || fullProspect.draftSource || source,
            },
          });
        })
        .filter(Boolean);
    }, [draftState, workingLeagueData]);

    const reportProspects = useMemo(() => {
      return [...draftedProspectCards, ...availableProspects];
    }, [draftedProspectCards, availableProspects]);

    const selectedProspect = useMemo(() => {
      return (
        reportProspects.find((p) => p.id === selectedProspectId) ||
        (draftState?.completed ? draftedProspectCards[0] : availableProspects[0]) ||
        reportProspects[0] ||
        null
      );
    }, [reportProspects, selectedProspectId, draftState?.completed, draftedProspectCards, availableProspects]);

    const openScoutingReport = (prospectId = selectedProspectId) => {
      if (prospectId) setSelectedProspectId(prospectId);
      setScoutingReportOpen(true);
    };

    useEffect(() => {
      const selectedStillExists = reportProspects.some((p) => p.id === selectedProspectId);
      if (selectedStillExists) return;

      const nextDefault =
        draftState?.completed && draftedProspectCards[0]?.id
          ? draftedProspectCards[0].id
          : availableProspects[0]?.id || reportProspects[0]?.id;

      if (nextDefault) {
        setSelectedProspectId(nextDefault);
      }
    }, [reportProspects, selectedProspectId, draftState?.completed, draftedProspectCards, availableProspects]);

    const applyDraftResult = async (result) => {
      if (!result?.ok) {
        throw new Error(result?.reason || "Draft action failed.");
      }

      let nextLeague = result.leagueData || workingLeagueData;
      const rawNextState = result.draftState || draftState;
      const enrichedState = enrichDraftStateWithDraftSources(rawNextState, draftState, nextLeague);
      const nextState = enrichedState
        ? {
            ...enrichedState,
            seasonYear: Number(seasonYear),
            draftOrderSignature: getDraftOrderSignature(enrichedState.draftOrder || draftOrder || []),
          }
        : enrichedState;

      if (nextState?.completed) {
        nextLeague = rollDraftPickAssetsForCompletedSeason(nextLeague, seasonYear);
      }

      if (nextState?.completed) {
        try {
          recordCompletedDraftMoodEvents(nextLeague, nextState, { seasonYear });
        } catch (err) {
          console.warn("[Draft] Failed to record offseason draft mood events", err);
        }
      }

      setWorkingLeagueData(nextLeague);
      setDraftState(nextState);

      await persistLeagueData(nextLeague, setLeagueData);
      saveDraftState(nextState);

      if (nextState?.completed) {
        updateOffseasonState({ draftComplete: true, rookieSigningsComplete: false });
      }

      return result;
    };

    const initializeDraft = async () => {
      setLoading(true);
      setError("");

      try {
        if (!draftOrder?.length) {
          throw new Error("Draft order is missing. Complete the Draft Lottery first.");
        }
        if (typeof simEngine.initializeDraft !== "function") {
          throw new Error("initializeDraft is not wired in simEnginePy.js yet.");
        }

        const customSetup = readCustomDraftClassSetup(seasonYear);
        if (customSetup.mode === "custom" && !customSetup.draftClassPayload?.draftClass?.length) {
          throw new Error("Custom draft class mode is selected, but no custom class is loaded for this season. Add one in League Editor or switch back to auto-generate rookies.");
        }

        const draftPayload = {
          seasonYear,
          userTeamName: selectedTeamName,
          draftOrder,
        };

        const matchingPreview = getMatchingUpcomingDraftPreview(seasonYear, customSetup);
        let draftClassDescriptor = null;

        if (matchingPreview?.draftClass?.length) {
          draftPayload.draftClass = matchingPreview.draftClass;
          draftPayload.classType = matchingPreview.sourceMode === "custom" ? "custom" : "auto";
          draftClassDescriptor = matchingPreview;
        } else if (customSetup.draftClassPayload?.draftClass?.length) {
          draftPayload.draftClass = customSetup.draftClassPayload.draftClass;
          draftPayload.classType = "custom";
          draftClassDescriptor = {
            sourceMode: "custom",
            sourceFingerprint: getDraftClassFingerprint(customSetup.draftClassPayload.draftClass),
            classType: "custom",
            classMeta: customSetup.draftClassPayload.classMeta || {},
            previewGenerated: false,
          };
        }

        clearSavedLegacyDraftState(seasonYear, "old deterministic auto draft state before initializeDraft");
        const leagueForDraftInit = stripLegacyDraftStateFromLeagueData(workingLeagueData, seasonYear);

        let result = await simEngine.initializeDraft(leagueForDraftInit, draftPayload);
        result = applyDraftClassSourceMetadata(result, draftClassDescriptor, seasonYear);

        await applyDraftResult(result);
      } catch (err) {
        console.error("[Draft] initializeDraft failed", err);
        setError(String(err?.message || err));
      } finally {
        setLoading(false);
      }
    };

    useEffect(() => {
      if (!workingLeagueData || !draftOrder?.length || loading) return;

      const rawSaved = readDraftState(seasonYear);
      const saved = normalizeSavedDraftState(rawSaved, draftOrder, seasonYear);

      if (saved?.draftOrder?.length) {
        const picksAlreadyMade = Array.isArray(saved.draftedPicks) && saved.draftedPicks.length > 0;

        if (picksAlreadyMade && !isDraftStateConsistentWithLeague(saved, workingLeagueData)) {
          // A completed/partial local draft without matching rookie records in the
          // IndexedDB league is stale or was interrupted mid-save. Never show a
          // fake 60/60 board; clear it and rebuild the draft from the locked order.
          localStorage.removeItem(DRAFT_STATE_KEY);
          updateOffseasonState({ draftComplete: false, rookieSigningsComplete: false });
          const cleanedLeague = removeInvalidDraftCompletionFromLeague(workingLeagueData);
          setWorkingLeagueData(cleanedLeague);
          setDraftState(null);
          persistLeagueData(cleanedLeague, setLeagueData).catch((err) => {
            console.warn("[Draft] Failed to persist stale-draft cleanup", err);
          });
          return;
        }

        if (!picksAlreadyMade && !saved.completed) {
          const ownedOrder = applyDraftPickOwnershipToOrder(saved.draftOrder, {
            leagueData: workingLeagueData,
            seasonYear,
          });
          setDraftState({
            ...saved,
            draftOrder: ownedOrder,
            draftOrderSignature: getDraftOrderSignature(ownedOrder),
            pickOwnershipVersion: "draft_pick_ownership_v6",
          });
        } else {
          setDraftState(saved);
        }
        return;
      }

      if (rawSaved?.draftOrder?.length) {
        localStorage.removeItem(DRAFT_STATE_KEY);
        updateOffseasonState({ draftComplete: false, rookieSigningsComplete: false });
      }

      if (!draftState) {
        initializeDraft();
      }
      // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [workingLeagueData, draftOrder?.length, seasonYear, loading]);

    const scrollToAvailableProspects = () => {
      window.setTimeout(() => {
        availableStartRef.current?.scrollIntoView({
          behavior: "smooth",
          block: "start",
        });
      }, 100);
    };

    const runDraftAction = async (fnName, payload = {}) => {
      setLoading(true);
      setError("");

      try {
        const fn = simEngine[fnName];
        if (typeof fn !== "function") {
          throw new Error(`${fnName} is not wired in simEnginePy.js yet.`);
        }

        const { scrollToAvailable = false, ...backendPayload } = payload || {};

        const result = await fn(workingLeagueData, {
          seasonYear,
          userTeamName: selectedTeamName,
          draftState,
          ...backendPayload,
        });

        const applied = await applyDraftResult(result);

        if (scrollToAvailable) {
          scrollToAvailableProspects();
        }

        return applied;
      } catch (err) {
        console.error(`[Draft] ${fnName} failed`, err);
        setError(String(err?.message || err));
      } finally {
        setLoading(false);
      }
    };

    const handleUserPick = async () => {
      if (!selectedProspect?.id) {
        setError("Select a prospect first.");
        return;
      }
      await runDraftAction("makeUserDraftPick", { prospectId: selectedProspect.id });
    };

    const handleFinish = async () => {
      setError("");
      setLoading(true);
      try {
        if (!draftState?.completed || !isDraftStateConsistentWithLeague(draftState, workingLeagueData)) {
          throw new Error("Draft results are out of sync with the league save. Reopen the draft to rebuild the current class.");
        }

        const rolledLeague = rollDraftPickAssetsForCompletedSeason(workingLeagueData, seasonYear);
        try {
          recordCompletedDraftMoodEvents(rolledLeague, draftState, { seasonYear });
        } catch (err) {
          console.warn("[Draft] Failed to record offseason draft mood events", err);
        }

        setWorkingLeagueData(rolledLeague);
        await persistLeagueData(rolledLeague, setLeagueData);
        saveDraftState(draftState);
        updateOffseasonState({ draftComplete: true, rookieSigningsComplete: false });
        navigate("/offseason");
      } catch (err) {
        setError(String(err?.message || err));
      } finally {
        setLoading(false);
      }
    };

    if (!workingLeagueData) {
      return (
        <div className="min-h-screen bmCourtPage text-white flex items-center justify-center">
          Loading draft...
        </div>
      );
    }

    if (!draftOrder?.length) {
      return (
        <div className="min-h-screen bmCourtPage text-white flex items-center justify-center px-4">
          <div className="bmSolidPanel rounded-3xl bg-neutral-900 border border-white/10 p-8 max-w-xl text-center">
            <h1 className="text-3xl font-extrabold text-orange-500 mb-3">Draft Order Missing</h1>
            <p className="text-white/60 mb-6">Complete the Draft Lottery before opening the NBA Draft.</p>
            <button onClick={() => navigate("/draft-lottery")} className="bmSmoothButton px-6 py-3 rounded-xl bg-orange-600 hover:bg-orange-500 font-bold">
              Go to Draft Lottery
            </button>
          </div>
        </div>
      );
    }

    const completed = Boolean(draftState?.completed);
    const pickNumber = currentPick?.pick || "-";
    const pickRound = currentPick?.round || "-";
    const picksMade = draftState?.draftedPicks?.length || 0;
    const totalPicks = draftState?.draftOrder?.length || draftOrder.length || 60;

    return (
      <div className="bmCourtPage h-full min-h-0 overflow-hidden px-4 py-3 text-white">
        <style>{`
          .bmOrangeScrollbar {
            scrollbar-width: thin;
            scrollbar-color: rgba(249, 115, 22, 0.92) rgba(12, 12, 12, 0.78);
          }

          .bmOrangeScrollbar::-webkit-scrollbar {
            width: 12px;
            height: 12px;
          }

          .bmOrangeScrollbar::-webkit-scrollbar-track {
            background: rgba(12, 12, 12, 0.78);
            border-left: 1px solid rgba(255, 255, 255, 0.08);
            border-radius: 999px;
          }

          .bmOrangeScrollbar::-webkit-scrollbar-thumb {
            background: linear-gradient(180deg, #fb923c 0%, #f97316 55%, #ea580c 100%);
            border: 3px solid rgba(12, 12, 12, 0.92);
            border-radius: 999px;
            box-shadow: 0 0 14px rgba(249, 115, 22, 0.22);
          }

          .bmOrangeScrollbar::-webkit-scrollbar-thumb:hover {
            background: linear-gradient(180deg, #fdba74 0%, #fb923c 45%, #f97316 100%);
          }

          .bmOrangeScrollbar::-webkit-scrollbar-corner {
            background: rgba(12, 12, 12, 0.78);
          }

          .bmDraftBoardPanel {
            background-image:
              radial-gradient(circle at 18% 0%, rgba(249, 115, 22, 0.12), transparent 34%),
              radial-gradient(circle at 92% 16%, rgba(255, 255, 255, 0.06), transparent 28%),
              repeating-linear-gradient(45deg, rgba(255,255,255,0.035) 0 1px, transparent 1px 22px),
              linear-gradient(135deg, rgba(18,18,18,0.97), rgba(8,8,8,0.98));
            background-blend-mode: screen, normal, soft-light, normal;
          }

          .bmDraftBoardRow {
            position: relative;
            isolation: isolate;
            background: rgba(10, 10, 10, 0.64);
          }

          .bmDraftBoardRow > * {
            position: relative;
            z-index: 1;
          }

  .bmDraftBoardRow {
    position: relative;
    isolation: isolate;
    background: rgba(10, 10, 10, 0.72);
  }

  .bmDraftBoardRow:hover {
    background-color: rgba(255, 255, 255, 0.055);
  }

  .bmDraftBoardRowActive {
    background: linear-gradient(90deg, rgba(249, 115, 22, 0.28), rgba(249, 115, 22, 0.08)) !important;
    box-shadow: inset 5px 0 0 #f97316, inset 0 0 0 1px rgba(251, 146, 60, 0.55);
  }
  .bmDraftBoardRowActive .bmDraftSelectedBadge {
    display: inline-flex;
  }

          .bmDraftBoardRowUser:not(.bmDraftBoardRowActive) {
            background: rgba(5, 150, 105, 0.14);
          }
        `}</style>
        <div className="mx-auto flex h-full min-h-0 w-full max-w-7xl flex-col">
          <div className="mb-2 flex shrink-0 items-center justify-between gap-4">
            <div>
              <p className="mb-1 text-[10px] uppercase tracking-[0.25em] text-white/40">Offseason</p>
              <h1 className="text-3xl font-extrabold text-orange-500">NBA Draft</h1>
              <p className="mt-1 text-xs text-white/55">
                {completed ? "Draft complete." : `Pick ${pickNumber} - Round ${pickRound} - ${currentTeamName} is on the clock.`}
              </p>
            </div>

            <div className="flex flex-wrap justify-end gap-3 shrink-0">
              {completed && (
                <button
                  onClick={handleFinish}
                  className="bmSmoothButton px-6 py-3 rounded-xl bg-emerald-600 hover:bg-emerald-500 font-extrabold"
                >
                  Complete Draft and Return
                </button>
              )}

              <button
                onClick={() => navigate("/offseason")}
                className="bmLegacyRouteBack bmSmoothButton rounded-lg bg-neutral-800 px-4 py-2 text-sm font-bold hover:bg-neutral-700"
              >
                Back to Offseason
              </button>
            </div>
          </div>

          {error && (
            <div className="mb-6 rounded-2xl border border-red-500/40 bg-red-500/10 px-4 py-3 text-red-200 font-semibold">
              {error}
            </div>
          )}

          <div className="mb-2 grid shrink-0 grid-cols-5 gap-2">
            <SmallPill label="Season" value={seasonYear} />
            <SmallPill label="Progress" value={`${picksMade}/${totalPicks}`} />
            <SmallPill label="Current Pick" value={completed ? "Done" : `#${pickNumber}`} />
            <SmallPill label="On Clock" value={completed ? "-" : currentTeamName} />
            <SmallPill label="Your Team" value={selectedTeamName || "-"} />
          </div>

          {!completed && (
            <div className="mb-2 flex shrink-0 flex-wrap gap-2">
              <button
                disabled={loading || userOnClock}
                onClick={() => runDraftAction("simOneDraftPick")}
                className="bmSmoothButton px-5 py-3 rounded-xl bg-neutral-800 hover:bg-neutral-700 disabled:bg-neutral-700 disabled:text-white/45 font-extrabold"
              >
                Sim One Pick
              </button>

              <button
                disabled={loading || userOnClock || !hasRemainingUserPick}
                onClick={() => runDraftAction("simToUserDraftPick", { scrollToAvailable: true })}
                className="bmSmoothButton px-5 py-3 rounded-xl bg-orange-600 hover:bg-orange-500 disabled:bg-neutral-700 disabled:text-white/45 font-extrabold"
                title={hasRemainingUserPick ? `Next user pick: #${remainingUserPicks[0]?.pick || "-"}` : "Your team has no remaining picks"}
              >
                {hasRemainingUserPick ? "Sim To User Pick" : "No User Picks"}
              </button>

              <button
                disabled={loading}
                onClick={() => runDraftAction("simRestOfDraft")}
                className="bmSmoothButton px-5 py-3 rounded-xl bg-purple-700 hover:bg-purple-600 disabled:bg-neutral-700 disabled:text-white/45 font-extrabold"
              >
                Sim Rest Of Draft
              </button>

              <button
                disabled={loading || !userOnClock || !selectedProspect?.id}
                onClick={handleUserPick}
                className="bmSmoothButton px-5 py-3 rounded-xl bg-emerald-600 hover:bg-emerald-500 disabled:bg-neutral-700 disabled:text-white/45 font-extrabold"
              >
                Draft Selected Player
              </button>
            </div>
          )}

          {loading && (
            <div className="mb-2 shrink-0 rounded-xl border border-orange-500/30 bg-orange-500/10 px-3 py-2 text-sm font-semibold text-orange-100">
              Processing draft action...
            </div>
          )}

          {userOnClock && !completed && (
            <div className="mb-2 shrink-0 rounded-xl border border-emerald-500/40 bg-emerald-500/10 px-3 py-2 text-sm font-semibold text-emerald-100">
              You are on the clock.
            </div>
          )}

          <div className="min-h-0 flex-1">
            <CombinedDraftBoard
              prospects={availableProspects}
              draftedPicks={draftState?.draftedPicks || []}
              draftOrder={draftState?.draftOrder || draftOrder}
              teamLogoByName={teamLogoByName}
              selectedProspectId={selectedProspect?.id}
              onSelect={setSelectedProspectId}
              onOpenReport={openScoutingReport}
              disabled={loading}
              availableStartRef={availableStartRef}
              draftCompleted={completed}
              workingLeagueData={workingLeagueData}
              draftState={draftState}
              sortState={draftBoardSort}
              onSortChange={handleDraftBoardSortChange}
              canDraft={userOnClock && !!selectedProspect?.id && !loading}
              onDraft={handleUserPick}
            />

            {completed && (
              <div className="bmSolidPanel bmRowEnter rounded-3xl bg-neutral-900 border border-white/10 p-6">
                <h2 className="text-2xl font-extrabold text-white mb-3">Undrafted Free Agents</h2>
                <p className="text-white/60 text-sm mb-4">
                  Top undrafted prospects have been added to the free-agent pool.
                </p>
                <div className="text-sm text-white/50">
                  Added: {draftState?.undraftedAddedToFreeAgency?.length || 0}
                </div>
              </div>
            )}
          </div>

          {scoutingReportOpen && selectedProspect && (
            <div
              className="fixed inset-0 z-[220] flex items-center justify-center bg-black/70 px-4 py-6 backdrop-blur-sm"
              onClick={() => setScoutingReportOpen(false)}
            >
              <div
                className="relative w-[min(760px,96vw)] max-h-[88vh] overflow-y-auto"
                onClick={(e) => e.stopPropagation()}
              >
                <button
                  type="button"
                  onClick={() => setScoutingReportOpen(false)}
                  className="absolute right-4 top-4 z-10 rounded-lg bg-neutral-800/90 px-3 py-2 text-xs font-black uppercase tracking-wide text-white/80 hover:bg-neutral-700"
                >
                  Close
                </button>
                <ProspectCard prospect={selectedProspect} />
              </div>
            </div>
          )}
        </div>
      </div>
    );
  }
