// BM Patch 33: Native deflated trade / contract economy scale.
export const BM_PATCH32_TRADE_SCALE_VERSION = "patch33_contract_market_parity_v1";
export const BM_PATCH33_CONTRACT_SCALE_VERSION = "patch33_contract_market_parity_v1";
export const TRADE_TIER = Object.freeze({ DEPTH:65, BENCH:68, ROTATION:70, GOOD_ROTATION:73, STARTER:76, CORE:80, STAR:84, MEGA:86, SUPERSTAR:88, FRANCHISE:90 });
const ECONOMY_POINTS = Object.freeze([[50,55],[55,60],[60,66],[65,71.5],[68,75],[69,75.5],[70,76],[72,77.5],[73,78.5],[75,80],[76,81],[80,84],[82,86],[85,89],[88,92],[90,94],[92,95.5],[95,97],[99,99]]);
export function clampNumber(value,min,max,fallback=0){const n=Number(value); const r=Number.isFinite(n)?n:Number(fallback||0); return Math.max(min,Math.min(max,r));}
export function rawOverallOf(player={},fallback=0){ if(player && player.__bmPatch32VisibleOverall!==undefined) return clampNumber(player.__bmPatch32VisibleOverall,-999,999,fallback); return clampNumber(player?.overall ?? player?.ovr ?? player?.rating,-999,999,fallback);}
export function rawPotentialOf(player={},fallback=null){const ovr=rawOverallOf(player,0); if(player && player.__bmPatch32VisiblePotential!==undefined) return clampNumber(player.__bmPatch32VisiblePotential,-999,999,fallback??ovr); return clampNumber(player?.potential ?? player?.pot ?? (fallback??ovr),-999,999,fallback??ovr);}
export function economyOvr(visibleOverall=0){const x=Number(visibleOverall); if(!Number.isFinite(x)) return 0; const pts=ECONOMY_POINTS; if(x<=pts[0][0]){const [x0,y0]=pts[0]; const [x1,y1]=pts[1]; return y0+((x-x0)*(y1-y0))/(x1-x0);} for(let i=0;i<pts.length-1;i+=1){const [x0,y0]=pts[i]; const [x1,y1]=pts[i+1]; if(x>=x0 && x<=x1){return y0+((x-x0)*(y1-y0))/Math.max(0.0001,x1-x0);}} const [xa,ya]=pts[pts.length-2]; const [xb,yb]=pts[pts.length-1]; return yb+((x-xb)*(yb-ya))/Math.max(0.0001,xb-xa);}
export function economyOvrForPlayer(player={}){return economyOvr(rawOverallOf(player,0));}
export function economyPotentialForPlayer(player={}){const econ=economyOvrForPlayer(player); return Math.max(econ,economyOvr(rawPotentialOf(player,rawOverallOf(player,0))));}
export function economicTradePlayerCopy(player={}){if(!player || typeof player!=="object") return player; const rawOverall=rawOverallOf(player,0); const rawPotential=rawPotentialOf(player,rawOverall); const economicOverall=economyOvr(rawOverall); const economicPotential=Math.max(economicOverall,economyOvr(rawPotential)); return {...player,overall:economicOverall,ovr:economicOverall,potential:economicPotential,pot:economicPotential,__bmPatch32VisibleOverall:rawOverall,__bmPatch32VisiblePotential:rawPotential,__bmPatch32EconomicProxy:true,__bmPatch33EconomicProxy:true};}
export function tradeTierLabel(playerOrOverall=0){const ovr=typeof playerOrOverall==="object"?rawOverallOf(playerOrOverall,0):Number(playerOrOverall||0); if(ovr>=TRADE_TIER.FRANCHISE)return"franchise"; if(ovr>=TRADE_TIER.SUPERSTAR)return"superstar"; if(ovr>=TRADE_TIER.MEGA)return"mega_star"; if(ovr>=TRADE_TIER.STAR)return"star"; if(ovr>=TRADE_TIER.CORE)return"core"; if(ovr>=TRADE_TIER.STARTER)return"starter"; if(ovr>=TRADE_TIER.GOOD_ROTATION)return"good_rotation"; if(ovr>=TRADE_TIER.ROTATION)return"rotation"; if(ovr>=TRADE_TIER.BENCH)return"bench"; return"depth";}
export function isMegaTradeCandidate(player={}){return rawOverallOf(player,0)>=TRADE_TIER.MEGA;}
export function isPrimeFranchiseAsset(player={}){const age=Number(player?.age??27); const ovr=rawOverallOf(player,0); const pot=rawPotentialOf(player,ovr); return Boolean((ovr>=TRADE_TIER.FRANCHISE&&age<=31)||(ovr>=TRADE_TIER.SUPERSTAR&&age<=29&&pot>=ovr));}
export function isYoungCoreAsset(player={}){const age=Number(player?.age??27); const ovr=rawOverallOf(player,0); const pot=rawPotentialOf(player,ovr); return Boolean(age<=25&&((ovr>=TRADE_TIER.STARTER&&pot>=82)||(ovr>=TRADE_TIER.GOOD_ROTATION&&pot>=84)));}
export function marketAavMillionsFromEconomicOverall(economicOverall=70,age=27){const ovr=Number(economicOverall); const a=Number(age); let base; if(ovr<=66)base=1.4+Math.max(0,ovr-60)*0.18; else if(ovr<=70)base=2.4+(ovr-66)*0.50; else if(ovr<=75)base=4.6+(ovr-70)*1.25; else if(ovr<=80)base=11.5+(ovr-75)*2.55; else if(ovr<=84)base=24.5+(ovr-80)*3.3; else if(ovr<=88)base=36.5+(ovr-84)*2.6; else if(ovr<=92)base=46+(ovr-88)*2.2; else base=54+(ovr-92)*1.25; if(a>=31&&ovr<88)base*=Math.max(0.72,1-(a-30)*0.055); if(a>=34&&ovr<92)base*=Math.max(0.62,1-(a-33)*0.070); if(a<=24&&ovr>=76)base*=1.04; return Math.max(1.2,base);}
