import LZString from "lz-string";
import { computeTeamRatings } from "../api/teamRatings.js";
import {
  GAMEPLAN_VERSION,
  buildFullTeamRating,
  buildSmartRotation,
  calculateTeamPotentialRating,
} from "./ensureGameplans.js";
import { evaluateCpuContractFriction } from "./tradeContractValue.js";
import { evaluateTradePickImpact } from "./tradePickValue.js";

const RESULT_V3_INDEX_KEY = "bm_results_index_v3";
const RESULT_V3_PREFIX = "bm_result_v3_";
const SCHEDULE_KEY = "bm_schedule_v3";

const TEAM_IMPACT_EPS = 0.015;
const NO_DOWNSIDE_MIN_GAIN = 0.10;
const CLEAN_PICK_UPGRADE_ACCEPT_LINE = 0.015;
const NO_DOWNSIDE_PICK_SWEETENER_LINE = 0.075;
const OVR_IMPACT_MULT = 10;
const POT_IMPACT_MULT = 7;
const FTR_FLAT_OVR_WINDOW = 0.15;
const FTR_TIEBREAKER_MULT = 0.45;
const BASE_ACCEPT_THRESHOLD = 0.85;
const TOP_CONFERENCE_THRESHOLD_TAX = 0.45;
const ELITE_TEAM_THRESHOLD_TAX = 0.10;

// CPU-to-CPU trades are generated by a separate market engine after it has
// already identified buyer/seller intent. Keep manual/user proposals strict,
// but make CPU-to-CPU acceptance less brittle so reasonable deadline deals
// can actually complete instead of only creating rumor-board noise.
const CPU_CPU_THRESHOLD_DISCOUNT = 1.05;
const CPU_CPU_TOP_CONFERENCE_THRESHOLD_TAX = 0.15;
const CPU_CPU_ELITE_TEAM_THRESHOLD_TAX = 0.05;
const CPU_CPU_MAX_BUYER_PICK_GIVE = -2.00;
const CPU_CPU_MAX_SELLER_OVR_DROP = -1.65;

// Extra threshold required when the CPU is asked to send out a true star.
// This is intentionally non-net-aware: receiving another star does not erase
// the organizational cost of moving a franchise player.
const STAR_RETENTION_TAX_CAP = 32.00;
const STAR_RETENTION_TAX_BY_OVR = {
  91: [0.50, 0.41, 0.27, 0.15, 0.09, 0.05],
  92: [1.50, 1.23, 0.82, 0.45, 0.27, 0.13],
  93: [3.00, 2.46, 1.64, 0.90, 0.54, 0.25],
  94: [6.00, 4.92, 3.28, 1.80, 1.08, 0.50],
  95: [10.00, 8.20, 5.47, 3.00, 1.80, 0.83],
  96: [13.50, 11.07, 7.38, 4.05, 2.43, 1.12],
  97: [17.50, 14.35, 9.57, 5.25, 3.15, 1.45],
  98: [22.50, 18.45, 12.30, 6.75, 4.05, 1.87],
  99: [28.00, 22.96, 15.31, 8.40, 5.04, 2.32],
};
const RATING_CACHE_MAX = 900;
const POWER_CONTEXT_CACHE_MAX = 24;
const TRADE_FINDER_IMPACT_CACHE_MAX = 2600;
const TRADE_FINDER_IMPACT_MODE_KEY = "bm_trade_finder_impact_mode_v1";
const TRADE_DEBUG_KEY = "bm_trade_debug_v1";
const TRADE_FINDER_FAST_FTR_MODE = "fast-ftr";
const TRADE_FINDER_FAST_SCAN_MODE = "fast-scan";
const TRADE_FINDER_IMPACT_BREAKDOWN_KEY = "bm_trade_finder_impact_breakdown_v1";
const TRADE_FINDER_IMPACT_BREAKDOWN_MAX_ROWS = 600;

const rosterRatingCache = new Map();
const rankOnlyRatingCache = new Map();
const powerContextCache = new Map();
const tradeFinderImpactCache = new Map();

const round4 = (value) => Math.round(Number(value || 0) * 10000) / 10000;
const clamp = (value, min, max) => Math.max(min, Math.min(max, value));

function toNum(value, fallback = 0) {
  const n = Number(value);
  return Number.isFinite(n) ? n : fallback;
}

function normalizeName(value = "") {
  return String(value || "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "")
    .trim();
}

function sameTeamName(a = "", b = "") {
  return normalizeName(a) === normalizeName(b);
}

function getTeamName(team = {}) {
  return team?.name || team?.teamName || team?.team || "";
}

function touchLimitedCache(cache, key, value, maxSize) {
  if (!key) return value;
  if (cache.has(key)) cache.delete(key);
  cache.set(key, value);

  while (cache.size > maxSize) {
    const oldest = cache.keys().next().value;
    cache.delete(oldest);
  }

  return value;
}

function getLimitedCache(cache, key) {
  if (!key || !cache.has(key)) return null;
  const value = cache.get(key);
  cache.delete(key);
  cache.set(key, value);
  return value;
}

function stablePrimitive(value = "") {
  if (value === null || value === undefined) return "";
  if (typeof value === "number") return Number.isFinite(value) ? String(value) : "";
  if (typeof value === "boolean") return value ? "1" : "0";
  return String(value);
}

function stableTradeRuleSignature(rule = {}) {
  if (!rule || typeof rule !== "object") return "";
  return [
    stablePrimitive(rule.action),
    stablePrimitive(rule.swapId),
    stablePrimitive(rule.mirror),
    stablePrimitive(rule.protectStart),
    stablePrimitive(rule.protectEnd),
    stablePrimitive(rule.swapDirection),
    stablePrimitive(rule.ownedRange?.start),
    stablePrimitive(rule.ownedRange?.end),
    stablePrimitive(rule.retainedRange?.start),
    stablePrimitive(rule.retainedRange?.end),
    stablePrimitive(rule.conveyedRange?.start),
    stablePrimitive(rule.conveyedRange?.end),
  ].join(":");
}

function tradeItemImpactSignature(item = {}) {
  if (item?.type === "player") {
    const player = item.player || {};
    return [
      "player",
      getPlayerIdentity(player),
      normalizeName(player?.name || player?.player || ""),
      stablePrimitive(player?.pos),
      stablePrimitive(player?.secondaryPos),
      stablePrimitive(player?.age),
      stablePrimitive(player?.overall ?? player?.ovr),
      stablePrimitive(player?.potential ?? player?.pot),
      stablePrimitive(player?.offRating ?? player?.off),
      stablePrimitive(player?.defRating ?? player?.def),
      stablePrimitive(player?.stamina ?? player?.sta),
      stablePrimitive(player?.salary ?? player?.currentSalary ?? player?.contractSalary ?? player?.capHit ?? player?.aav),
      Array.isArray(player?.contract?.salaryByYear) ? player.contract.salaryByYear.map(stablePrimitive).join(",") : "",
      stablePrimitive(player?.contract?.startYear),
    ].join("|");
  }

  if (item?.type === "pick") {
    const pick = item.pick || {};
    const rule = item.tradeRule || pick.tradeRule || {};
    return [
      "pick",
      stablePrimitive(pick.id || pick.pickId),
      stablePrimitive(pick.assetType || pick.type),
      stablePrimitive(pick.year || pick.seasonYear),
      stablePrimitive(pick.round || pick.rnd),
      stablePrimitive(pick.pickNumber || pick.overallPick || pick.resolvedPickNumber || pick.draftPickNumber || pick.projectedRank),
      normalizeName(pick.originalTeam || pick.originalTeamName || pick.team || ""),
      normalizeName(pick.ownerTeam || pick.owner || pick.currentOwnerTeamName || ""),
      stablePrimitive(item.protection || pick.displayProtection || pick.protections || pick.protection),
      stableTradeRuleSignature(rule),
    ].join("|");
  }

  return `${stablePrimitive(item?.type)}:${stablePrimitive(JSON.stringify(item || {}))}`;
}

function tradeItemsImpactSignature(items = []) {
  return (items || []).map(tradeItemImpactSignature).sort().join("||");
}

function makeTradeFinderImpactCacheKey({
  leagueData,
  cpuTeam,
  userTeamName = "",
  cpuTeamName = "",
  userItems = [],
  cpuItems = [],
  evaluationMode = "standard",
  cpuTradeRole = "",
  cpuTradeContext = null,
} = {}) {
  if (String(cpuTradeRole || "").toLowerCase() !== "trade_finder") return null;
  const teams = getAllTeamsFromLeague(leagueData);
  const leagueSignature = leaguePowerSignature(leagueData, teams);
  const cpuName = cpuTeamName || getTeamName(cpuTeam) || "";
  const fastScanKey = cpuTradeContext?.tradeFinderFastScan
    ? `fastscan:${cpuTradeContext?.searchPhase || ""}`
    : "normal";
  return [
    "tf-impact-v5",
    stablePrimitive(getTradeFinderImpactMode()),
    stablePrimitive(fastScanKey),
    stablePrimitive(evaluationMode),
    normalizeName(userTeamName),
    normalizeName(cpuName),
    leagueSignature,
    rosterRatingSignature(cpuTeam?.players || []),
    tradeItemsImpactSignature(userItems),
    tradeItemsImpactSignature(cpuItems),
  ].join("::");
}

function playerRatingSignature(player = {}) {
  return [
    player?.id ?? player?.playerId ?? player?.player_id ?? player?.uuid ?? "",
    normalizeName(player?.name || player?.player || ""),
    player?.pos || "",
    player?.secondaryPos || "",
    toNum(player?.age, 0),
    toNum(player?.overall ?? player?.ovr, 0),
    toNum(player?.potential ?? player?.pot, 0),
    toNum(player?.offRating ?? player?.off ?? player?.overall ?? player?.ovr, 0),
    toNum(player?.defRating ?? player?.def ?? player?.overall ?? player?.ovr, 0),
    toNum(player?.stamina ?? player?.sta, 0),
  ].join("|");
}

function rosterRatingSignature(players = []) {
  return (players || [])
    .map(playerRatingSignature)
    .sort()
    .join("||");
}

function gameplanRosterSignature(players = []) {
  return [...(players || [])]
    .map((p) =>
      [
        p?.name || p?.player || "",
        p?.pos || "",
        p?.secondaryPos || "",
        toNum(p?.overall ?? p?.ovr, 0),
      ].join("|")
    )
    .sort()
    .join("||");
}

function leaguePowerSignature(leagueData, teams = []) {
  const rosterPart = (teams || [])
    .map((team) => `${normalizeName(getTeamName(team))}:${rosterRatingSignature(team?.players || [])}`)
    .sort()
    .join("##");

  return [
    rosterPart,
    safeLocalStorageGet(RESULT_V3_INDEX_KEY) || "",
    safeLocalStorageGet(SCHEDULE_KEY) || "",
  ].join("::");
}

function getAllTeamsFromLeague(leagueData) {
  if (!leagueData) return [];
  if (Array.isArray(leagueData.teams)) return leagueData.teams;
  if (leagueData.conferences) return Object.values(leagueData.conferences).flat();
  return [];
}

function getTeamConferenceMap(leagueData, teams) {
  const map = {};

  if (leagueData?.conferences && typeof leagueData.conferences === "object") {
    for (const [conf, arr] of Object.entries(leagueData.conferences)) {
      for (const team of arr || []) {
        const name = getTeamName(team);
        if (name) map[name] = conf;
      }
    }
  }

  for (const team of teams || []) {
    const name = getTeamName(team);
    if (!name || map[name]) continue;
    map[name] = team?.conference || team?.conf || team?.divisionConference || "";
  }

  return map;
}

function parseMaybeCompressed(raw, fallback = null) {
  if (!raw) return fallback;

  try {
    if (raw.startsWith("lz:")) {
      const decompressed = LZString.decompressFromUTF16(raw.slice(3));
      return decompressed ? JSON.parse(decompressed) : fallback;
    }
  } catch {}

  try {
    return JSON.parse(raw);
  } catch {}

  try {
    const decompressed = LZString.decompressFromUTF16(raw);
    return decompressed ? JSON.parse(decompressed) : fallback;
  } catch {
    return fallback;
  }
}

function safeLocalStorageGet(key) {
  try {
    if (typeof localStorage === "undefined") return null;
    return localStorage.getItem(key);
  } catch {
    return null;
  }
}


function isTradeDebugEnabled() {
  try {
    return Boolean(
      typeof window !== "undefined" &&
        (window.__BM_TRADE_DEBUG || safeLocalStorageGet(TRADE_DEBUG_KEY) === "1")
    );
  } catch {
    return false;
  }
}

function debugTradeImpactItems(items = []) {
  return (Array.isArray(items) ? items : []).map((item) => {
    if (item?.type === "player") {
      const player = item.player || {};
      return {
        type: "player",
        name: getPlayerDisplayName(player),
        ovr: toNum(player?.overall ?? player?.ovr, 0),
        pot: toNum(player?.potential ?? player?.pot ?? player?.overall ?? player?.ovr, 0),
        age: toNum(player?.age, 0),
      };
    }
    if (item?.type === "pick") {
      const pick = item.pick || {};
      return {
        type: "pick",
        year: pick.year,
        round: pick.round,
        originalTeam: pick.originalTeam || pick.originalTeamName,
        ownerTeam: pick.ownerTeam || pick.owner || pick.currentOwnerTeamName,
        protection: item.protection || pick.displayProtection || pick.protection || "Unprotected",
        tradeRule: item.tradeRule || pick.tradeRule || null,
      };
    }
    return { type: item?.type || "unknown" };
  });
}

function debugTradeImpactEvaluation(args = {}, result = {}, extra = {}) {
  if (!isTradeDebugEnabled()) return;

  const impact = result?.teamImpact || {};
  const breakdown = impact?.scoreBreakdown || {};
  const accepted = Boolean(result?.accepted || ["accept", "accepted"].includes(String(result?.decision || "").toLowerCase()));
  const payload = {
    source: String(args?.cpuTradeRole || "").toLowerCase() === "trade_finder" ? "Trade Finder" : "Builder / exact",
    userTeam: args?.userTeamName || getTeamName(args?.userTeam) || "Your team",
    cpuTeam: args?.cpuTeamName || getTeamName(args?.cpuTeam) || "CPU team",
    cpuTradeRole: args?.cpuTradeRole || "",
    cpuTradeContext: args?.cpuTradeContext || null,
    evaluationMode: args?.evaluationMode || "standard",
    cacheHit: Boolean(extra.cacheHit),
    totalMs: extra.totalMs,
    accepted,
    decision: result?.decision,
    score: Number(result?.score ?? 0),
    threshold: Number(impact?.threshold ?? 0),
    margin: Number(result?.score ?? 0) - Number(impact?.threshold ?? 0),
    ratingMode: impact?.ratingMode || "",
    fastScan: Boolean(impact?.fastScan),
    fastFtr: Boolean(impact?.fastFtr),
    rank: impact?.rank,
    deltas: impact?.deltas || null,
    scoreBreakdown: {
      ovrScore: breakdown?.ovrScore,
      potScore: breakdown?.potScore,
      ftrScore: breakdown?.ftrScore,
      pickScore: breakdown?.pickScore,
      contractFriction: impact?.contractFriction ?? breakdown?.contractFriction,
      starRetentionTax: impact?.starRetentionTax ?? breakdown?.starRetentionTax,
      incomingPickValue: breakdown?.incomingPickValue,
      outgoingPickValue: breakdown?.outgoingPickValue,
    },
    userItems: debugTradeImpactItems(args?.userItems || []),
    cpuItems: debugTradeImpactItems(args?.cpuItems || []),
    reasons: Array.isArray(result?.reasons) ? result.reasons.slice(0, 12) : [],
  };

  const label = `[TRADE DEBUG][IMPACT ${accepted ? "ACCEPT" : "REJECT"}] ${payload.source} • ${payload.cpuTeam} • score ${payload.score} / threshold ${payload.threshold}`;
  if (accepted) console.log(label, payload);
  else console.warn(label, payload);
}


function tfImpactNow() {
  try {
    return typeof performance !== "undefined" && performance.now ? performance.now() : Date.now();
  } catch {
    return Date.now();
  }
}

function tfImpactRoundMs(value) {
  const n = Number(value || 0);
  return Math.round(n * 10) / 10;
}

function isTradeFinderImpactBreakdownEnabled() {
  try {
    return Boolean(
      typeof window !== "undefined" &&
        (window.__TF_IMPACT_BREAKDOWN_ENABLED || safeLocalStorageGet(TRADE_FINDER_IMPACT_BREAKDOWN_KEY) === "1")
    );
  } catch {
    return false;
  }
}

function addBreakdownMetric(metrics, key, value) {
  if (!metrics || !key) return;
  const n = Number(value || 0);
  if (!Number.isFinite(n)) return;
  metrics[key] = Number(metrics[key] || 0) + n;
}

function incrementBreakdownMetric(metrics, key, amount = 1) {
  addBreakdownMetric(metrics, key, amount);
}

function getBreakdownRolePrefix(role = "rating") {
  const raw = String(role || "rating").replace(/[^a-z0-9]+/gi, "");
  return raw ? raw.charAt(0).toLowerCase() + raw.slice(1) : "rating";
}

function countBreakdownTradeItems(items = []) {
  const rows = Array.isArray(items) ? items : [];
  return {
    assetCount: rows.length,
    playerCount: rows.filter((item) => item?.type === "player").length,
    pickCount: rows.filter((item) => item?.type === "pick").length,
  };
}

function makeTradeFinderImpactBreakdownBase(args = {}) {
  const cpuTeam = args?.cpuTeam || {};
  const userTeam = args?.userTeam || {};
  return {
    team: args?.cpuTeamName || getTeamName(cpuTeam) || "CPU team",
    userTeam: args?.userTeamName || getTeamName(userTeam) || "Your team",
    evaluationMode: args?.evaluationMode || "standard",
    cpuTradeRole: String(args?.cpuTradeRole || "").toLowerCase(),
    impactMode: getTradeFinderImpactMode(),
    userItems: countBreakdownTradeItems(args?.userItems || []),
    cpuItems: countBreakdownTradeItems(args?.cpuItems || []),
    cpuItemSignature: tradeItemsImpactSignature(args?.cpuItems || []),
    userItemSignature: tradeItemsImpactSignature(args?.userItems || []),
  };
}

function ensureTradeFinderImpactBreakdownStore() {
  if (typeof window === "undefined") return null;
  if (!window.__TF_IMPACT_BREAKDOWN || typeof window.__TF_IMPACT_BREAKDOWN !== "object" || !Array.isArray(window.__TF_IMPACT_BREAKDOWN.rows)) {
    window.__TF_IMPACT_BREAKDOWN = {
      rows: [],
      totals: {},
      byTeam: {},
      createdAt: new Date().toISOString(),
      updatedAt: null,
    };
  }
  if (!window.__TF_RESET_IMPACT_BREAKDOWN) {
    window.__TF_RESET_IMPACT_BREAKDOWN = () => {
      window.__TF_IMPACT_BREAKDOWN = {
        rows: [],
        totals: {},
        byTeam: {},
        createdAt: new Date().toISOString(),
        updatedAt: null,
      };
      return window.__TF_IMPACT_BREAKDOWN;
    };
  }
  return window.__TF_IMPACT_BREAKDOWN;
}

function recordTradeFinderImpactBreakdown(row = {}) {
  if (!isTradeFinderImpactBreakdownEnabled()) return;
  try {
    const store = ensureTradeFinderImpactBreakdownStore();
    if (!store) return;

    const cleanRow = {
      callIndex: Number(store.totals?.calls || 0) + 1,
      ...row,
    };
    store.rows.push(cleanRow);
    while (store.rows.length > TRADE_FINDER_IMPACT_BREAKDOWN_MAX_ROWS) store.rows.shift();

    const totals = store.totals || {};
    totals.calls = Number(totals.calls || 0) + 1;
    totals.cacheHits = Number(totals.cacheHits || 0) + (cleanRow.cacheHit ? 1 : 0);
    totals.cacheMisses = Number(totals.cacheMisses || 0) + (cleanRow.cacheHit ? 0 : 1);

    for (const [key, value] of Object.entries(cleanRow.metrics || {})) {
      if (typeof value !== "number" || !Number.isFinite(value)) continue;
      totals[key] = Number(totals[key] || 0) + value;
    }
    totals.totalMs = Number(totals.totalMs || 0) + Number(cleanRow.totalMs || 0);
    totals.updatedAtMs = tfImpactNow();

    const teamKey = cleanRow.team || "Unknown";
    const byTeam = store.byTeam || {};
    const teamRow = byTeam[teamKey] || { team: teamKey, calls: 0, totalMs: 0, cacheHits: 0, metrics: {} };
    teamRow.calls += 1;
    teamRow.totalMs += Number(cleanRow.totalMs || 0);
    teamRow.cacheHits += cleanRow.cacheHit ? 1 : 0;
    for (const [key, value] of Object.entries(cleanRow.metrics || {})) {
      if (typeof value !== "number" || !Number.isFinite(value)) continue;
      teamRow.metrics[key] = Number(teamRow.metrics[key] || 0) + value;
    }
    byTeam[teamKey] = teamRow;

    store.totals = totals;
    store.byTeam = byTeam;
    store.updatedAt = new Date().toISOString();
  } catch {}
}

function getTradeFinderImpactMode() {
  const raw = safeLocalStorageGet(TRADE_FINDER_IMPACT_MODE_KEY);
  const mode = String(raw || "").toLowerCase().trim();

  // Default Trade Finder to the fast FTR approximation. Propose Trade and
  // non-Trade-Finder evaluations still use exact logic because this mode is
  // only checked when cpuTradeRole === "trade_finder".
  if (!mode) return TRADE_FINDER_FAST_FTR_MODE;
  if (["exact", "slow", "full", "standard"].includes(mode)) return "exact";
  if ([TRADE_FINDER_FAST_FTR_MODE, "fast_ftr", "fast", "1", "on", "true"].includes(mode)) {
    return TRADE_FINDER_FAST_FTR_MODE;
  }
  return TRADE_FINDER_FAST_FTR_MODE;
}

function shouldUseTradeFinderFastFtr({ cpuTradeRole = "" } = {}) {
  return (
    String(cpuTradeRole || "").toLowerCase() === "trade_finder" &&
    getTradeFinderImpactMode() === TRADE_FINDER_FAST_FTR_MODE
  );
}

function shouldUseTradeFinderFastScanImpact({ cpuTradeRole = "", cpuTradeContext = null } = {}) {
  return Boolean(
    String(cpuTradeRole || "").toLowerCase() === "trade_finder" &&
      cpuTradeContext &&
      cpuTradeContext.tradeFinderFastScan
  );
}

function parseSavedGameplan(raw) {
  if (!raw) return null;
  try {
    return JSON.parse(raw);
  } catch {
    return null;
  }
}

function namesSet(players = []) {
  return new Set(
    (players || [])
      .map((player) => player?.name || player?.player || "")
      .filter(Boolean)
  );
}

function setMatches(a, b) {
  if (a.size !== b.size) return false;
  for (const value of a) {
    if (!b.has(value)) return false;
  }
  return true;
}

function getCachedAutoMinutes(teamName, players = []) {
  const saved = parseSavedGameplan(safeLocalStorageGet(`gameplan_${teamName}`));
  if (!saved || saved.manualLocked || saved.userEdited || saved.source === "coach_gameplan") return null;
  if (saved.version !== GAMEPLAN_VERSION) return null;
  if (saved.teamName && teamName && !sameTeamName(saved.teamName, teamName)) return null;
  if (saved.rosterSignature !== gameplanRosterSignature(players)) return null;
  if (!saved.minutes || typeof saved.minutes !== "object") return null;

  const liveNames = namesSet(players);
  const minuteNames = new Set(Object.keys(saved.minutes || {}).filter(Boolean));
  if (!setMatches(liveNames, minuteNames)) return null;

  for (const name of minuteNames) {
    if (!Number.isFinite(Number(saved.minutes[name]))) return null;
  }

  return saved.minutes;
}

function resultV3Key(gameId) {
  return `${RESULT_V3_PREFIX}${gameId}`;
}

function loadSchedule() {
  return parseMaybeCompressed(safeLocalStorageGet(SCHEDULE_KEY), {}) || {};
}

function loadResultsV3() {
  const ids = parseMaybeCompressed(safeLocalStorageGet(RESULT_V3_INDEX_KEY), []) || [];
  const out = {};

  for (const id of ids) {
    const result = parseMaybeCompressed(safeLocalStorageGet(resultV3Key(id)), null);
    if (result) out[String(id)] = result;
  }

  return out;
}

function buildRecordMap() {
  const schedule = loadSchedule();
  const results = loadResultsV3();
  const map = {};

  const ensure = (teamName) => {
    if (!teamName) return null;
    if (!map[teamName]) {
      map[teamName] = { w: 0, l: 0, gp: 0, pf: 0, pa: 0 };
    }
    return map[teamName];
  };

  for (const games of Object.values(schedule || {})) {
    for (const game of games || []) {
      if (!game?.id) continue;

      const result = results?.[String(game.id)];
      if (!game.played && !result) continue;

      const homePts = toNum(result?.totals?.home ?? result?.winner?.home, NaN);
      const awayPts = toNum(result?.totals?.away ?? result?.winner?.away, NaN);
      if (!Number.isFinite(homePts) || !Number.isFinite(awayPts)) continue;
      if (homePts === awayPts) continue;

      const homeName = game.home;
      const awayName = game.away;
      const home = ensure(homeName);
      const away = ensure(awayName);
      if (!home || !away) continue;

      home.gp += 1;
      away.gp += 1;
      home.pf += homePts;
      home.pa += awayPts;
      away.pf += awayPts;
      away.pa += homePts;

      if (homePts > awayPts) {
        home.w += 1;
        away.l += 1;
      } else {
        away.w += 1;
        home.l += 1;
      }
    }
  }

  return map;
}

function tradeFinderFastPlayerValue(player = {}) {
  const overall = toNum(player?.overall ?? player?.ovr, 75);
  const off = toNum(player?.offRating ?? player?.off ?? overall, overall);
  const def = toNum(player?.defRating ?? player?.def ?? overall, overall);
  const stamina = toNum(player?.stamina ?? player?.sta, 75);
  return overall * 1.0 + off * 0.18 + def * 0.18 + (stamina - 70) * 0.08;
}

function compareTradeFinderFastPlayers(a = {}, b = {}) {
  const diff = tradeFinderFastPlayerValue(b) - tradeFinderFastPlayerValue(a);
  if (Math.abs(diff) > 1e-9) return diff;
  const ovrDiff = toNum(b?.overall ?? b?.ovr, 0) - toNum(a?.overall ?? a?.ovr, 0);
  if (ovrDiff !== 0) return ovrDiff;
  return String(a?.name || a?.player || "").localeCompare(String(b?.name || b?.player || ""));
}

const TRADE_FINDER_FAST_SCAN_POSITIONS = ["PG", "SG", "SF", "PF", "C"];
const TRADE_FINDER_FAST_SCAN_STARTER_MINUTES = [34, 34, 34, 34, 34];
const TRADE_FINDER_FAST_SCAN_BENCH_MINUTES = [18, 16, 14, 12, 10];

function tradeFinderFastPlayerName(player = {}) {
  return player?.name || player?.player || "";
}

function tradeFinderFastPlayerOverall(player = {}) {
  return toNum(player?.overall ?? player?.ovr, 0);
}

function tradeFinderFastPlayerPotential(player = {}) {
  return toNum(player?.potential ?? player?.pot ?? player?.overall ?? player?.ovr, 75);
}

function tradeFinderFastCanPlayPosition(player = {}, pos = "") {
  return player?.pos === pos || player?.secondaryPos === pos;
}

function chooseTradeFinderFastScanStarters(valid = []) {
  const remaining = [...(valid || [])].sort(compareTradeFinderFastPlayers);
  const starters = [];
  const used = new Set();

  for (const pos of TRADE_FINDER_FAST_SCAN_POSITIONS) {
    const candidates = remaining
      .filter((player) => {
        const name = tradeFinderFastPlayerName(player);
        return name && !used.has(name) && tradeFinderFastCanPlayPosition(player, pos);
      })
      .sort((a, b) => {
        const primaryDiff = Number(b?.pos === pos) - Number(a?.pos === pos);
        if (primaryDiff !== 0) return primaryDiff;
        return compareTradeFinderFastPlayers(a, b);
      });

    const picked = candidates[0] || remaining.find((player) => {
      const name = tradeFinderFastPlayerName(player);
      return name && !used.has(name);
    });

    if (!picked) continue;
    used.add(tradeFinderFastPlayerName(picked));
    starters.push(picked);
  }

  return starters;
}

function buildTradeFinderFastScanMinutes(valid = []) {
  const minutes = {};
  for (const player of valid || []) {
    const name = tradeFinderFastPlayerName(player);
    if (name) minutes[name] = 0;
  }

  const starters = chooseTradeFinderFastScanStarters(valid);
  const used = new Set(starters.map(tradeFinderFastPlayerName));
  const bench = (valid || [])
    .filter((player) => {
      const name = tradeFinderFastPlayerName(player);
      return name && !used.has(name);
    })
    .sort(compareTradeFinderFastPlayers)
    .slice(0, TRADE_FINDER_FAST_SCAN_BENCH_MINUTES.length);

  const active = [...starters, ...bench].filter(Boolean);
  const minuteSlots = [
    ...TRADE_FINDER_FAST_SCAN_STARTER_MINUTES.slice(0, starters.length),
    ...TRADE_FINDER_FAST_SCAN_BENCH_MINUTES.slice(0, bench.length),
  ];

  for (let idx = 0; idx < active.length; idx += 1) {
    const name = tradeFinderFastPlayerName(active[idx]);
    if (!name) continue;
    minutes[name] = Number(minuteSlots[idx] || 0);
  }

  let total = Object.values(minutes).reduce((sum, value) => sum + Number(value || 0), 0);
  let remaining = Math.max(0, 240 - total);
  const priority = active.slice().sort(compareTradeFinderFastPlayers);

  while (remaining > 0 && priority.length) {
    let moved = false;
    for (const player of priority) {
      if (remaining <= 0) break;
      const name = tradeFinderFastPlayerName(player);
      if (!name) continue;
      const current = Number(minutes[name] || 0);
      const add = Math.min(remaining, Math.max(0, 42 - current), 4);
      if (add <= 0) continue;
      minutes[name] = current + add;
      remaining -= add;
      moved = true;
    }
    if (!moved) break;
  }

  total = Object.values(minutes).reduce((sum, value) => sum + Number(value || 0), 0);
  if (total > 240) {
    let over = total - 240;
    const donors = active.slice().reverse();
    for (const player of donors) {
      if (over <= 0) break;
      const name = tradeFinderFastPlayerName(player);
      const current = Number(minutes[name] || 0);
      const take = Math.min(over, Math.max(0, current - 6));
      if (take <= 0) continue;
      minutes[name] = current - take;
      over -= take;
    }
  }

  return minutes;
}

function estimateTradeFinderFastScanPotential(valid = [], exactOverall = 0) {
  const rows = (valid || [])
    .map((player) => {
      const overall = tradeFinderFastPlayerOverall(player);
      const potential = tradeFinderFastPlayerPotential(player);
      const age = toNum(player?.age, 27);
      const upside = Math.max(0, potential - overall);
      const youth = age <= 20 ? 1.16 : age <= 23 ? 1.10 : age <= 26 ? 1.02 : age <= 30 ? 0.94 : age <= 34 ? 0.82 : 0.66;
      return overall * 0.44 + potential * 0.56 + upside * 0.20 * youth;
    })
    .filter((value) => Number.isFinite(value))
    .sort((a, b) => b - a);

  if (!rows.length) return round4(exactOverall || 0);
  const top2 = rows.slice(0, 2).reduce((sum, value) => sum + value, 0) / Math.max(1, Math.min(2, rows.length));
  const top5 = rows.slice(0, 5).reduce((sum, value) => sum + value, 0) / Math.max(1, Math.min(5, rows.length));
  const weighted = rows.reduce((sum, value, idx) => sum + value * Math.pow(0.86, idx), 0) /
    rows.reduce((sum, _, idx) => sum + Math.pow(0.86, idx), 0);
  const futureScore = top2 * 0.42 + top5 * 0.38 + weighted * 0.20;
  const blended = exactOverall * 0.32 + futureScore * 0.68;
  return round4(clamp(blended, 0, 99));
}

function calculateTradeFinderFastScanRatings(valid = [], metrics = null, rolePrefix = "rating") {
  const totalStart = tfImpactNow();

  const minutesStart = tfImpactNow();
  const minutes = buildTradeFinderFastScanMinutes(valid);
  addBreakdownMetric(metrics, `${rolePrefix}FastScanMinutesMs`, tfImpactNow() - minutesStart);

  const ratingsStart = tfImpactNow();
  const ratings = computeTeamRatings({ players: valid }, minutes);
  addBreakdownMetric(metrics, `${rolePrefix}FastScanTeamRatingsMs`, tfImpactNow() - ratingsStart);

  const exactOverall = round4(ratings?.exactOverall ?? ratings?.overall ?? 0);
  const potentialStart = tfImpactNow();
  const exactPot = estimateTradeFinderFastScanPotential(valid, exactOverall);
  addBreakdownMetric(metrics, `${rolePrefix}FastScanPotentialMs`, tfImpactNow() - potentialStart);
  addBreakdownMetric(metrics, `${rolePrefix}RatingTotalMs`, tfImpactNow() - totalStart);

  return {
    exactOverall,
    exactOff: round4(ratings?.exactOff ?? ratings?.off ?? 0),
    exactDef: round4(ratings?.exactDef ?? ratings?.def ?? 0),
    exactPot,
    exactFtr: exactOverall,
    displayOverall: toNum(ratings?.overall, Math.round(exactOverall || 0)),
    displayPot: Math.round(exactPot),
    displayFtr: toNum(ratings?.overall, Math.round(exactOverall || 0)),
    ratingMode: TRADE_FINDER_FAST_SCAN_MODE,
  };
}

function buildTradeFinderFastFtrMinutes(valid = [], smartMinutes = {}) {
  const minutes = {};
  for (const player of valid || []) {
    const name = player?.name || player?.player;
    if (!name) continue;
    minutes[name] = Math.max(0, Number(smartMinutes?.[name] || 0));
  }

  const activeNames = new Set(
    Object.entries(minutes)
      .filter(([, min]) => Number(min || 0) > 0)
      .map(([name]) => name)
  );
  const depthPlayers = (valid || [])
    .filter((player) => {
      const name = player?.name || player?.player;
      return name && !activeNames.has(name);
    })
    .sort(compareTradeFinderFastPlayers);

  if (!depthPlayers.length) return minutes;

  // Cheap FTR approximation for Trade Finder only. The exact full-team rating
  // optimizer is very expensive because it rebuilds a 10-man group while also
  // forcing deep bench minutes. For search scans, approximate that idea by
  // giving non-rotation depth 5 minutes and taking those minutes from the lowest
  // value active players above a safe floor. Propose Trade and normal ratings
  // still use the exact buildFullTeamRating path.
  const depthMinuteTarget = 5;
  const minActiveFloor = 8;
  let minutesNeeded = 0;
  for (const player of depthPlayers) {
    const name = player?.name || player?.player;
    minutes[name] = depthMinuteTarget;
    minutesNeeded += depthMinuteTarget;
  }

  const donors = (valid || [])
    .filter((player) => {
      const name = player?.name || player?.player;
      return name && Number(minutes[name] || 0) > minActiveFloor && activeNames.has(name);
    })
    .sort((a, b) => tradeFinderFastPlayerValue(a) - tradeFinderFastPlayerValue(b));

  for (const donor of donors) {
    if (minutesNeeded <= 0) break;
    const name = donor?.name || donor?.player;
    const current = Number(minutes[name] || 0);
    const take = Math.min(minutesNeeded, Math.max(0, current - minActiveFloor));
    if (take <= 0) continue;
    minutes[name] = current - take;
    minutesNeeded -= take;
  }

  if (minutesNeeded > 0) {
    const active = (valid || [])
      .filter((player) => {
        const name = player?.name || player?.player;
        return name && Number(minutes[name] || 0) > 0 && activeNames.has(name);
      })
      .sort((a, b) => tradeFinderFastPlayerValue(a) - tradeFinderFastPlayerValue(b));

    for (const donor of active) {
      if (minutesNeeded <= 0) break;
      const name = donor?.name || donor?.player;
      const current = Number(minutes[name] || 0);
      const take = Math.min(minutesNeeded, Math.max(0, current));
      if (take <= 0) continue;
      minutes[name] = current - take;
      minutesNeeded -= take;
    }
  }

  return minutes;
}

function calculateTeamImpactRatings(players = [], options = {}) {
  const metrics = options?.breakdownMetrics || null;
  const rolePrefix = getBreakdownRolePrefix(options?.ratingRole || "rating");
  const totalStart = tfImpactNow();
  const validStart = tfImpactNow();
  const valid = (players || []).filter((p) => p && (p.name || p.player) && Number.isFinite(Number(p.overall ?? p.ovr)));
  addBreakdownMetric(metrics, `${rolePrefix}ValidFilterMs`, tfImpactNow() - validStart);
  incrementBreakdownMetric(metrics, `${rolePrefix}PlayersRated`, valid.length);

  if (!valid.length) {
    addBreakdownMetric(metrics, `${rolePrefix}RatingTotalMs`, tfImpactNow() - totalStart);
    return {
      exactOverall: 0,
      exactOff: 0,
      exactDef: 0,
      exactPot: 0,
      exactFtr: 0,
      displayOverall: 0,
      displayPot: 0,
      displayFtr: 0,
    };
  }

  if (options?.fastScan) {
    return calculateTradeFinderFastScanRatings(valid, metrics, rolePrefix);
  }

  let minutes = {};
  const smartRotationStart = tfImpactNow();
  try {
    const built = buildSmartRotation(valid);
    minutes = built?.obj && typeof built.obj === "object" ? built.obj : {};
  } catch (error) {
    console.warn("Trade impact auto-rotation fallback:", error);
  } finally {
    addBreakdownMetric(metrics, `${rolePrefix}SmartRotationMs`, tfImpactNow() - smartRotationStart);
  }

  const teamRatingsStart = tfImpactNow();
  const teamRatings = computeTeamRatings({ players: valid }, minutes);
  addBreakdownMetric(metrics, `${rolePrefix}TeamRatingsMs`, tfImpactNow() - teamRatingsStart);

  const potentialStart = tfImpactNow();
  const potentialRatings = calculateTeamPotentialRating(valid);
  addBreakdownMetric(metrics, `${rolePrefix}PotentialMs`, tfImpactNow() - potentialStart);

  let fullTeamRatings;

  if (options?.fastFtr) {
    const fastMinutesStart = tfImpactNow();
    const fastFtrMinutes = buildTradeFinderFastFtrMinutes(valid, minutes);
    addBreakdownMetric(metrics, `${rolePrefix}FastFtrMinutesMs`, tfImpactNow() - fastMinutesStart);

    const fastFtrRatingsStart = tfImpactNow();
    const fastFtrRatings = computeTeamRatings({ players: valid }, fastFtrMinutes);
    addBreakdownMetric(metrics, `${rolePrefix}FastFtrRatingsMs`, tfImpactNow() - fastFtrRatingsStart);
    fullTeamRatings = {
      ftr: Number(fastFtrRatings?.overall || 0),
      ftrOff: Number(fastFtrRatings?.off || 0),
      ftrDef: Number(fastFtrRatings?.def || 0),
      exactFtr: Number(fastFtrRatings?.exactOverall ?? fastFtrRatings?.overall ?? 0),
      exactFtrOff: Number(fastFtrRatings?.exactOff ?? fastFtrRatings?.off ?? 0),
      exactFtrDef: Number(fastFtrRatings?.exactDef ?? fastFtrRatings?.def ?? 0),
      minutes: fastFtrMinutes,
      fastApproximation: true,
    };
  } else {
    const fullTeamStart = tfImpactNow();
    fullTeamRatings = buildFullTeamRating(valid);
    addBreakdownMetric(metrics, `${rolePrefix}FullTeamRatingMs`, tfImpactNow() - fullTeamStart);
  }

  addBreakdownMetric(metrics, `${rolePrefix}RatingTotalMs`, tfImpactNow() - totalStart);

  return {
    exactOverall: round4(teamRatings?.exactOverall ?? teamRatings?.overall ?? 0),
    exactOff: round4(teamRatings?.exactOff ?? teamRatings?.off ?? 0),
    exactDef: round4(teamRatings?.exactDef ?? teamRatings?.def ?? 0),
    exactPot: round4(potentialRatings?.exactPot ?? potentialRatings?.pot ?? 0),
    exactFtr: round4(fullTeamRatings?.exactFtr ?? fullTeamRatings?.ftr ?? 0),
    displayOverall: toNum(teamRatings?.overall, Math.round(teamRatings?.exactOverall || 0)),
    displayPot: toNum(potentialRatings?.pot, Math.round(potentialRatings?.exactPot || 0)),
    displayFtr: toNum(fullTeamRatings?.ftr, Math.round(fullTeamRatings?.exactFtr || 0)),
    ratingMode: options?.fastFtr ? TRADE_FINDER_FAST_FTR_MODE : "exact",
  };
}

function rateTeamRoster(players = [], options = {}) {
  const metrics = options?.breakdownMetrics || null;
  const rolePrefix = getBreakdownRolePrefix(options?.ratingRole || "rating");
  const ratingMode = options?.fastScan ? TRADE_FINDER_FAST_SCAN_MODE : options?.fastFtr ? TRADE_FINDER_FAST_FTR_MODE : "exact";
  const keyStart = tfImpactNow();
  const key = `${GAMEPLAN_VERSION}:${ratingMode}:${rosterRatingSignature(players)}`;
  addBreakdownMetric(metrics, `${rolePrefix}RatingKeyMs`, tfImpactNow() - keyStart);

  const lookupStart = tfImpactNow();
  const cached = getLimitedCache(rosterRatingCache, key);
  addBreakdownMetric(metrics, `${rolePrefix}RatingCacheLookupMs`, tfImpactNow() - lookupStart);
  if (cached) {
    incrementBreakdownMetric(metrics, `${rolePrefix}RatingCacheHits`);
    return cached;
  }

  incrementBreakdownMetric(metrics, `${rolePrefix}RatingCacheMisses`);
  const calcStart = tfImpactNow();
  const calculated = calculateTeamImpactRatings(players, { ...options, breakdownMetrics: metrics, ratingRole: rolePrefix });
  addBreakdownMetric(metrics, `${rolePrefix}RatingCalcMs`, tfImpactNow() - calcStart);

  return touchLimitedCache(
    rosterRatingCache,
    key,
    calculated,
    RATING_CACHE_MAX
  );
}

function calculateRankOnlyRatings(team = {}, metrics = null) {
  const totalStart = tfImpactNow();
  const players = Array.isArray(team?.players) ? team.players : [];
  const valid = players.filter((p) => p && (p.name || p.player) && Number.isFinite(Number(p.overall ?? p.ovr)));
  incrementBreakdownMetric(metrics, "powerRankPlayersRated", valid.length);

  if (!valid.length) {
    addBreakdownMetric(metrics, "powerRankRatingTotalMs", tfImpactNow() - totalStart);
    return { exactOverall: 0, exactOff: 0, exactDef: 0 };
  }

  const cachedMinutesStart = tfImpactNow();
  let minutes = getCachedAutoMinutes(getTeamName(team), valid);
  addBreakdownMetric(metrics, "powerRankCachedMinutesMs", tfImpactNow() - cachedMinutesStart);

  if (!minutes) {
    const smartRotationStart = tfImpactNow();
    try {
      const built = buildSmartRotation(valid);
      minutes = built?.obj && typeof built.obj === "object" ? built.obj : {};
    } catch (error) {
      console.warn("Trade power-rank auto-rotation fallback:", error);
      minutes = {};
    } finally {
      addBreakdownMetric(metrics, "powerRankSmartRotationMs", tfImpactNow() - smartRotationStart);
    }
  } else {
    incrementBreakdownMetric(metrics, "powerRankCachedMinutesHits");
  }

  const ratingsStart = tfImpactNow();
  const ratings = computeTeamRatings({ players: valid }, minutes);
  addBreakdownMetric(metrics, "powerRankTeamRatingsMs", tfImpactNow() - ratingsStart);
  addBreakdownMetric(metrics, "powerRankRatingTotalMs", tfImpactNow() - totalStart);
  incrementBreakdownMetric(metrics, "powerRankTeamsRated");

  return {
    exactOverall: round4(ratings?.exactOverall ?? ratings?.overall ?? 0),
    exactOff: round4(ratings?.exactOff ?? ratings?.off ?? 0),
    exactDef: round4(ratings?.exactDef ?? ratings?.def ?? 0),
  };
}

function rateTeamForPowerRank(team = {}, metrics = null) {
  const keyStart = tfImpactNow();
  const key = `${GAMEPLAN_VERSION}:${normalizeName(getTeamName(team))}:${rosterRatingSignature(team?.players || [])}`;
  addBreakdownMetric(metrics, "powerRankKeyMs", tfImpactNow() - keyStart);

  const lookupStart = tfImpactNow();
  const cached = getLimitedCache(rankOnlyRatingCache, key);
  addBreakdownMetric(metrics, "powerRankCacheLookupMs", tfImpactNow() - lookupStart);
  if (cached) {
    incrementBreakdownMetric(metrics, "powerRankCacheHits");
    return cached;
  }

  incrementBreakdownMetric(metrics, "powerRankCacheMisses");
  return touchLimitedCache(
    rankOnlyRatingCache,
    key,
    calculateRankOnlyRatings(team, metrics),
    RATING_CACHE_MAX
  );
}

function buildPowerRankingRows(leagueData, metrics = null) {
  const totalStart = tfImpactNow();
  const teamsStart = tfImpactNow();
  const teams = getAllTeamsFromLeague(leagueData);
  addBreakdownMetric(metrics, "powerRowsGetTeamsMs", tfImpactNow() - teamsStart);

  const cacheKeyStart = tfImpactNow();
  const cacheKey = leaguePowerSignature(leagueData, teams);
  addBreakdownMetric(metrics, "powerRowsCacheKeyMs", tfImpactNow() - cacheKeyStart);

  const lookupStart = tfImpactNow();
  const cached = getLimitedCache(powerContextCache, cacheKey);
  addBreakdownMetric(metrics, "powerRowsCacheLookupMs", tfImpactNow() - lookupStart);
  if (cached) {
    incrementBreakdownMetric(metrics, "powerRowsCacheHits");
    addBreakdownMetric(metrics, "powerRowsTotalMs", tfImpactNow() - totalStart);
    return cached;
  }

  incrementBreakdownMetric(metrics, "powerRowsCacheMisses");
  const recordsStart = tfImpactNow();
  const records = buildRecordMap();
  addBreakdownMetric(metrics, "powerRowsRecordMapMs", tfImpactNow() - recordsStart);

  const confStart = tfImpactNow();
  const confMap = getTeamConferenceMap(leagueData, teams);
  addBreakdownMetric(metrics, "powerRowsConferenceMapMs", tfImpactNow() - confStart);

  const baseRowsStart = tfImpactNow();
  const baseRows = teams.map((team) => {
    const name = getTeamName(team);
    const ratings = rateTeamForPowerRank(team, metrics);
    const record = records?.[name] || { w: 0, l: 0, gp: 0, pf: 0, pa: 0 };
    const gp = toNum(record.gp, 0);
    const diff = toNum(record.pf, 0) - toNum(record.pa, 0);

    return {
      team,
      name,
      conference: confMap?.[name] || "",
      exactOverall: ratings.exactOverall,
      offDef: ratings.exactOff + ratings.exactDef,
      w: toNum(record.w, 0),
      l: toNum(record.l, 0),
      gp,
      winPct: gp > 0 ? toNum(record.w, 0) / gp : 0,
      pointDiff: gp > 0 ? diff / gp : 0,
    };
  });
  addBreakdownMetric(metrics, "powerRowsBaseRowsMs", tfImpactNow() - baseRowsStart);

  const scoringStart = tfImpactNow();
  const useRecordPowerRankings = baseRows.length > 0 && baseRows.every((row) => row.gp >= 20);

  const rowsWithScores = baseRows.map((row) => {
    const recordScore = row.winPct * 100;
    const powerScore = useRecordPowerRankings
      ? row.exactOverall * 0.5 + recordScore * 0.5
      : row.exactOverall;

    return {
      ...row,
      recordScore,
      powerScore,
      useRecordPowerRankings,
    };
  });

  rowsWithScores.sort(
    (a, b) =>
      b.powerScore - a.powerScore ||
      (useRecordPowerRankings ? b.winPct - a.winPct : 0) ||
      b.exactOverall - a.exactOverall ||
      b.offDef - a.offDef ||
      b.pointDiff - a.pointDiff ||
      b.w - a.w ||
      String(a.name || "").localeCompare(String(b.name || ""))
  );

  const rankedRows = rowsWithScores.map((row, idx) => ({ ...row, rank: idx + 1 }));
  addBreakdownMetric(metrics, "powerRowsScoringSortMs", tfImpactNow() - scoringStart);
  addBreakdownMetric(metrics, "powerRowsTotalMs", tfImpactNow() - totalStart);
  return touchLimitedCache(powerContextCache, cacheKey, rankedRows, POWER_CONTEXT_CACHE_MAX);
}

function getTeamPowerContext(leagueData, cpuTeamName, metrics = null) {
  const totalStart = tfImpactNow();
  const rows = buildPowerRankingRows(leagueData, metrics);
  const findStart = tfImpactNow();
  const cpuRow = rows.find((row) => sameTeamName(row.name, cpuTeamName)) || null;
  const conference = cpuRow?.conference || "";
  const conferenceRows = rows.filter(
    (row) => String(row.conference || "").toLowerCase() === String(conference || "").toLowerCase()
  );
  const topConferenceRow = conferenceRows[0] || null;
  addBreakdownMetric(metrics, "powerContextFindTeamMs", tfImpactNow() - findStart);
  addBreakdownMetric(metrics, "powerContextTotalMs", tfImpactNow() - totalStart);

  return {
    rows,
    rank: cpuRow?.rank || rows.length || 30,
    conference,
    isTopConferenceTeam: Boolean(cpuRow && topConferenceRow && sameTeamName(cpuRow.name, topConferenceRow.name)),
    useRecordPowerRankings: Boolean(cpuRow?.useRecordPowerRankings),
  };
}

function getOvrPotWeights(leagueRank = 15) {
  const rank = clamp(Number(leagueRank || 15), 1, 30);
  let ovrWeight;

  if (rank <= 12) {
    ovrWeight = 0.68 - ((rank - 1) / 11) * 0.18;
  } else if (rank <= 26) {
    ovrWeight = 0.50 - ((rank - 12) / 14) * 0.17;
  } else if (rank === 27) {
    ovrWeight = 0.35;
  } else if (rank === 28) {
    ovrWeight = 0.365;
  } else if (rank === 29) {
    ovrWeight = 0.38;
  } else {
    ovrWeight = 0.395;
  }

  ovrWeight = clamp(ovrWeight, 0.30, 0.70);
  return {
    ovrWeight: round4(ovrWeight),
    potWeight: round4(1 - ovrWeight),
  };
}

function getPlayerIdentity(player = {}) {
  const id = player?.id ?? player?.playerId ?? player?.player_id ?? player?.uuid ?? null;
  if (id !== null && id !== undefined && String(id).trim() !== "") return `id:${String(id)}`;
  return `name:${normalizeName(player?.name || player?.player || "")}`;
}

function samePlayer(a = {}, b = {}) {
  const aid = getPlayerIdentity(a);
  const bid = getPlayerIdentity(b);
  return Boolean(aid && bid && aid === bid);
}

function clonePlain(value) {
  try {
    return JSON.parse(JSON.stringify(value));
  } catch {
    return { ...(value || {}) };
  }
}

function getTradePlayers(items = []) {
  return (items || [])
    .filter((item) => item?.type === "player" && item.player)
    .map((item) => item.player);
}

function getPlayerDisplayName(player = {}) {
  return player?.name || player?.player || "Unknown Player";
}

function getStarRetentionAgeBucket(ageValue) {
  const age = Math.round(toNum(ageValue, 27));
  if (age <= 22) return 0;
  if (age <= 25) return 1;
  if (age <= 29) return 2;
  if (age <= 32) return 3;
  if (age <= 34) return 4;
  return 5;
}

function getCpuOutgoingStarRetentionTaxForPlayer(player = {}) {
  const overall = clamp(Math.round(toNum(player?.overall ?? player?.ovr, 0)), 0, 99);
  if (overall < 91) return null;

  const age = Math.round(toNum(player?.age, 27));
  const bucket = getStarRetentionAgeBucket(age);
  const row = STAR_RETENTION_TAX_BY_OVR[overall] || STAR_RETENTION_TAX_BY_OVR[99];
  const tax = round4(Number(row?.[bucket] || 0));
  if (tax <= TEAM_IMPACT_EPS) return null;

  return {
    playerName: getPlayerDisplayName(player),
    overall,
    age,
    ageBucket: bucket,
    tax,
  };
}

function evaluateCpuOutgoingStarRetentionTax(players = [], cpuTeamName = "CPU team") {
  const rows = (players || [])
    .map(getCpuOutgoingStarRetentionTaxForPlayer)
    .filter(Boolean)
    .sort((a, b) => b.tax - a.tax);

  if (!rows.length) {
    return { tax: 0, rows, reasons: [] };
  }

  const weightedTax = rows.reduce((sum, row, idx) => {
    const weight = idx === 0 ? 1 : idx === 1 ? 0.35 : idx === 2 ? 0.15 : 0;
    return sum + row.tax * weight;
  }, 0);
  const tax = round4(clamp(weightedTax, 0, STAR_RETENTION_TAX_CAP));
  const primary = rows[0];
  const extraCount = Math.max(0, rows.length - 1);
  const extraText = extraCount > 0
    ? `, with reduced stacking credit for ${extraCount} other 91+ OVR outgoing player${extraCount === 1 ? "" : "s"}`
    : "";

  return {
    tax,
    rows,
    reasons: [
      `CPU star-retention tax: +${tax.toFixed(2)} threshold because ${cpuTeamName} is giving up ${primary.playerName}, a ${primary.overall} OVR age-${primary.age} star${extraText}.`,
    ],
  };
}

function getPrimaryTradePickItems(items = []) {
  return (items || []).filter((item) => {
    if (item?.type !== "pick" || !item.pick) return false;
    if (item.tradeValueExcluded) return false;
    const rule = item.tradeRule || item.pick?.tradeRule || {};
    return !rule.mirror;
  });
}

function buildCpuRosterAfterTrade(cpuTeam, userItems = [], cpuItems = [], cpuTeamName = "") {
  const outgoingPlayers = getTradePlayers(cpuItems);
  const incomingPlayers = getTradePlayers(userItems);

  const roster = (cpuTeam?.players || [])
    .filter((player) => !outgoingPlayers.some((outgoing) => samePlayer(player, outgoing)))
    .map(clonePlain);

  for (const incoming of incomingPlayers) {
    if (roster.some((row) => samePlayer(row, incoming))) continue;
    const moved = clonePlain(incoming);
    if (moved.teamName !== undefined) moved.teamName = cpuTeamName;
    if (moved.currentTeam !== undefined) moved.currentTeam = cpuTeamName;
    if (typeof moved.team === "string") moved.team = cpuTeamName;
    roster.push(moved);
  }

  return roster;
}

function getPickRound(pick = {}) {
  const round = Number(pick.round || pick.rnd || pick.pickRound || 0);
  if (round === 1 || round === 2) return round;
  const pickNumber = Number(pick.pickNumber || pick.overallPick || pick.resolvedPickNumber || pick.pick || 0);
  return pickNumber && pickNumber <= 30 ? 1 : 2;
}

function getPickSlot(item = {}) {
  const pick = item.pick || item || {};
  const values = [
    pick.pickNumber,
    pick.overallPick,
    pick.resolvedPickNumber,
    pick.projectedRank,
    pick.recordRank,
    pick.expectedRank,
    pick.slot,
  ];

  for (const value of values) {
    const n = Number(value || 0);
    if (Number.isFinite(n) && n > 0) return n;
  }

  const rule = item.tradeRule || pick.tradeRule || {};
  const range = rule.conveyedRange || rule.ownedRange || pick.ownedRange || pick.ownedSlots || null;
  if (range) {
    const start = Number(range.start || 0);
    const end = Number(range.end || 0);
    if (start > 0 && end >= start) return (start + end) / 2;
  }

  return 0;
}

function genericPickValue(item = {}) {
  const pick = item.pick || item || {};
  const rule = item.tradeRule || pick.tradeRule || {};
  const round = getPickRound(pick);
  const slot = getPickSlot(item);
  const action = String(rule.action || "").toLowerCase();
  const protectionText = String(
    item.protection || pick.displayProtection || pick.protections || pick.protection || ""
  ).toLowerCase();

  if (action === "swap") {
    return round === 1 ? 0.18 : 0.05;
  }

  let value;
  if (round === 1) {
    if (slot > 0) {
      const firstRoundSlot = clamp(slot, 1, 30);
      value = 0.80 + ((30 - firstRoundSlot) / 29) * 7.40;
    } else {
      value = 2.20;
    }
  } else {
    if (slot > 0) {
      const secondRoundSlot = clamp(slot, 31, 60);
      value = 0.05 + ((60 - secondRoundSlot) / 29) * 0.63;
    } else {
      value = 0.22;
    }
  }

  if (action === "protected" || protectionText.includes("protected")) value *= 0.78;
  if (protectionText.includes("top 4") || protectionText.includes("top-4")) value *= 0.86;
  if (protectionText.includes("top 10") || protectionText.includes("top-10")) value *= 0.70;
  if (protectionText.includes("top 14") || protectionText.includes("top-14")) value *= 0.62;

  return round4(value);
}

function genericPickScoreForCpu(userItems = [], cpuItems = []) {
  const received = getPrimaryTradePickItems(userItems).reduce((sum, item) => sum + genericPickValue(item), 0);
  const sent = getPrimaryTradePickItems(cpuItems).reduce((sum, item) => sum + genericPickValue(item), 0);
  return round4(received - sent);
}

function genericPickImpactForCpu(userItems = [], cpuItems = []) {
  const incomingItems = getPrimaryTradePickItems(userItems);
  const outgoingItems = getPrimaryTradePickItems(cpuItems);
  const incomingValue = round4(incomingItems.reduce((sum, item) => sum + genericPickValue(item), 0));
  const outgoingValue = round4(outgoingItems.reduce((sum, item) => sum + genericPickValue(item), 0));
  const netPickScore = round4(incomingValue - outgoingValue);

  const reasons = [];
  if (incomingItems.length || outgoingItems.length) {
    reasons.push(
      `Trade Finder fast-scan draft estimate: ${netPickScore >= 0 ? "+" : ""}${netPickScore.toFixed(3)} net pick score using cheap projected slot/protection values. Exact pick value is restored in rescue/refine/Propose Trade.`
    );
  }

  return {
    netPickScore,
    incomingValue,
    incomingBaseValue: incomingValue,
    outgoingValue,
    outgoingBaseValue: outgoingValue,
    incoming: [],
    outgoing: [],
    reasons,
    invalidSwaps: [],
    invalidSwapReasons: [],
    hasPicks: incomingItems.length > 0 || outgoingItems.length > 0,
    fastScanApproximation: true,
  };
}

function formatDelta(value) {
  const n = Number(value || 0);
  const sign = n > TEAM_IMPACT_EPS ? "+" : "";
  return `${sign}${round4(n).toFixed(4)}`;
}

function makeRejectedResult(message, reasons = []) {
  return {
    accepted: false,
    decision: "reject",
    score: 0,
    message,
    reasons: reasons.length ? reasons : [message],
    counterSuggestions: [],
  };
}

function evaluateTradeTeamImpactUncached({ leagueData, userTeam, cpuTeam, userTeamName, cpuTeamName, userItems = [], cpuItems = [], evaluationMode = "standard", cpuTradeRole = "", cpuTradeContext = null, __tfBreakdownMetrics = null }) {
  const cpuName = cpuTeamName || getTeamName(cpuTeam) || "CPU team";
  const userName = userTeamName || getTeamName(userTeam) || "Your team";
  const isCpuCpuEvaluation = String(evaluationMode || "").toLowerCase() === "cpu_cpu_trade";
  const normalizedCpuTradeRole = String(cpuTradeRole || "").toLowerCase();

  if (!leagueData || !cpuTeam) {
    return makeRejectedResult("CPU evaluation failed because the CPU team could not be found.");
  }

  if (!userItems.length && !cpuItems.length) {
    return makeRejectedResult("Add at least one trade item before evaluation.");
  }

  const beforePlayers = Array.isArray(cpuTeam?.players) ? cpuTeam.players : [];
  const afterRosterStart = tfImpactNow();
  const afterPlayers = buildCpuRosterAfterTrade(cpuTeam, userItems, cpuItems, cpuName);
  addBreakdownMetric(__tfBreakdownMetrics, "afterRosterBuildMs", tfImpactNow() - afterRosterStart);

  const useFastScanImpact = shouldUseTradeFinderFastScanImpact({
    cpuTradeRole: normalizedCpuTradeRole,
    cpuTradeContext,
  });
  const useFastFtr = !useFastScanImpact && shouldUseTradeFinderFastFtr({ cpuTradeRole: normalizedCpuTradeRole, cpuTradeContext });

  const beforeRatingStart = tfImpactNow();
  const before = rateTeamRoster(beforePlayers, { fastFtr: useFastFtr, fastScan: useFastScanImpact, breakdownMetrics: __tfBreakdownMetrics, ratingRole: "before" });
  addBreakdownMetric(__tfBreakdownMetrics, "beforeRatingCallMs", tfImpactNow() - beforeRatingStart);

  const afterRatingStart = tfImpactNow();
  const after = rateTeamRoster(afterPlayers, { fastFtr: useFastFtr, fastScan: useFastScanImpact, breakdownMetrics: __tfBreakdownMetrics, ratingRole: "after" });
  addBreakdownMetric(__tfBreakdownMetrics, "afterRatingCallMs", tfImpactNow() - afterRatingStart);

  const powerContextStart = tfImpactNow();
  const powerContext = getTeamPowerContext(leagueData, cpuName, __tfBreakdownMetrics);
  addBreakdownMetric(__tfBreakdownMetrics, "powerContextCallMs", tfImpactNow() - powerContextStart);

  const weightStart = tfImpactNow();
  const { ovrWeight, potWeight } = getOvrPotWeights(powerContext.rank);
  addBreakdownMetric(__tfBreakdownMetrics, "weightMs", tfImpactNow() - weightStart);

  const deltaOVR = round4(after.exactOverall - before.exactOverall);
  const deltaPOT = round4(after.exactPot - before.exactPot);
  const deltaFTR = round4(after.exactFtr - before.exactFtr);
  const positiveMovement = round4(Math.max(0, deltaOVR) + Math.max(0, deltaPOT) + Math.max(0, deltaFTR));
  const noDownsideMinGain = NO_DOWNSIDE_MIN_GAIN + (powerContext.isTopConferenceTeam ? 0.05 : 0);
  const pickImpactStart = tfImpactNow();
  const pickImpact = useFastScanImpact
    ? genericPickImpactForCpu(userItems, cpuItems)
    : evaluateTradePickImpact({
        leagueData,
        userItems,
        cpuItems,
        userTeamName: userName,
        cpuTeamName: cpuName,
      });
  addBreakdownMetric(__tfBreakdownMetrics, "pickImpactMs", tfImpactNow() - pickImpactStart);

  if (Array.isArray(pickImpact?.invalidSwapReasons) && pickImpact.invalidSwapReasons.length > 0) {
    return makeRejectedResult(
      "Trade has a stale pick swap that does not match the current two teams.",
      [
        "Pick swaps are tied to the exact two negotiating teams. Switch teams again or clear/re-add the swap.",
        ...pickImpact.invalidSwapReasons,
      ]
    );
  }

  const pickScore = Number(pickImpact?.netPickScore || 0);
  const tradePlayersStart = tfImpactNow();
  const cpuIncomingPlayers = getTradePlayers(userItems);
  const cpuOutgoingPlayers = getTradePlayers(cpuItems);
  addBreakdownMetric(__tfBreakdownMetrics, "tradePlayersMs", tfImpactNow() - tradePlayersStart);

  const contractStart = tfImpactNow();
  const contractImpact = evaluateCpuContractFriction({
    leagueData,
    cpuIncomingPlayers,
    cpuOutgoingPlayers,
  });
  addBreakdownMetric(__tfBreakdownMetrics, "contractMs", tfImpactNow() - contractStart);

  const starTaxStart = tfImpactNow();
  const starRetentionImpact = evaluateCpuOutgoingStarRetentionTax(cpuOutgoingPlayers, cpuName);
  addBreakdownMetric(__tfBreakdownMetrics, "starTaxMs", tfImpactNow() - starTaxStart);
  const hasNoMeaningfulDownside =
    deltaOVR >= -TEAM_IMPACT_EPS &&
    deltaPOT >= -TEAM_IMPACT_EPS &&
    deltaFTR >= -TEAM_IMPACT_EPS;

  let ftrScore = 0;
  if (Math.abs(deltaOVR) <= FTR_FLAT_OVR_WINDOW) {
    ftrScore = deltaFTR * FTR_TIEBREAKER_MULT;
  }

  const mainScore =
    ovrWeight * deltaOVR * OVR_IMPACT_MULT +
    potWeight * deltaPOT * POT_IMPACT_MULT +
    ftrScore +
    pickScore;

  const topConferenceTax = powerContext.isTopConferenceTeam
    ? isCpuCpuEvaluation
      ? CPU_CPU_TOP_CONFERENCE_THRESHOLD_TAX
      : TOP_CONFERENCE_THRESHOLD_TAX
    : 0;
  const eliteTeamTax = powerContext.rank <= 5
    ? isCpuCpuEvaluation
      ? CPU_CPU_ELITE_TEAM_THRESHOLD_TAX
      : ELITE_TEAM_THRESHOLD_TAX
    : 0;
  const thresholdDiscount = isCpuCpuEvaluation ? CPU_CPU_THRESHOLD_DISCOUNT : 0;
  const baseThreshold = round4(
    Math.max(0.18, BASE_ACCEPT_THRESHOLD + topConferenceTax + eliteTeamTax - thresholdDiscount)
  );
  const threshold = round4(
    baseThreshold +
      Number(contractImpact?.friction || 0) +
      Number(starRetentionImpact?.tax || 0)
  );

  const hasPlayerMovement = cpuIncomingPlayers.length > 0 || cpuOutgoingPlayers.length > 0;
  const hasMeaningfulContractFriction = Number(contractImpact?.friction || 0) > 0.035;
  const hasMeaningfulStarRetentionTax = Number(starRetentionImpact?.tax || 0) > 0.035;
  const cleanPickUpgradeAccept =
    !hasPlayerMovement &&
    !hasMeaningfulContractFriction &&
    pickScore >= CLEAN_PICK_UPGRADE_ACCEPT_LINE;
  const noDownsidePickSweetenerAccept =
    hasNoMeaningfulDownside &&
    !hasMeaningfulContractFriction &&
    !hasMeaningfulStarRetentionTax &&
    pickScore >= NO_DOWNSIDE_PICK_SWEETENER_LINE;
  const noDownsideAccept =
    hasNoMeaningfulDownside &&
    positiveMovement >= noDownsideMinGain &&
    pickScore >= -TEAM_IMPACT_EPS &&
    mainScore >= threshold - 0.25;
  const tradeoffAccept = mainScore >= threshold;

  const cpuCpuContractOkay = Number(contractImpact?.friction || 0) <= 0.20;

  const cpuCpuBuyerAccept =
    isCpuCpuEvaluation &&
    normalizedCpuTradeRole === "buyer" &&
    cpuCpuContractOkay &&
    pickScore >= CPU_CPU_MAX_BUYER_PICK_GIVE &&
    (deltaOVR >= 0.025 || deltaFTR >= 0.035 || positiveMovement >= 0.055) &&
    mainScore >= threshold - 1.00;

  const cpuCpuSellerAccept =
    isCpuCpuEvaluation &&
    normalizedCpuTradeRole === "seller" &&
    cpuCpuContractOkay &&
    deltaOVR >= CPU_CPU_MAX_SELLER_OVR_DROP &&
    (pickScore >= 0.08 || deltaPOT >= 0.025 || mainScore >= threshold - 1.00) &&
    mainScore >= threshold - 1.35;

  const accepted = Boolean(
    cleanPickUpgradeAccept ||
      noDownsidePickSweetenerAccept ||
      noDownsideAccept ||
      tradeoffAccept ||
      cpuCpuBuyerAccept ||
      cpuCpuSellerAccept
  );

  const reasons = [
    `${cpuName} power rank #${powerContext.rank}: values OVR ${(ovrWeight * 100).toFixed(1)}% / POT ${(potWeight * 100).toFixed(1)}%.`,
    `Before trade: OVR ${before.exactOverall.toFixed(4)}, POT ${before.exactPot.toFixed(4)}, FTR ${before.exactFtr.toFixed(4)}.`,
    `After trade: OVR ${after.exactOverall.toFixed(4)}, POT ${after.exactPot.toFixed(4)}, FTR ${after.exactFtr.toFixed(4)}.`,
    `Team impact: OVR ${formatDelta(deltaOVR)}, POT ${formatDelta(deltaPOT)}, FTR ${formatDelta(deltaFTR)}.`,
  ];

  if (useFastScanImpact) {
    reasons.push("Trade Finder fast-scan mode: using cheap OVR/POT/FTR and pick estimates only during the scan phase. Rescue, refine, and Propose Trade exact evaluation are unchanged.");
  } else if (useFastFtr) {
    reasons.push("Trade Finder speed mode: using fast full-roster rating approximation for FTR only; Propose Trade exact evaluation is unchanged.");
  }

  if (isCpuCpuEvaluation) {
    const roleText = normalizedCpuTradeRole === "seller" ? "seller" : normalizedCpuTradeRole === "buyer" ? "buyer" : "CPU";
    reasons.push(
      `CPU-to-CPU ${roleText} mode: threshold ${threshold.toFixed(2)} after deadline-market discount; manual/user trade standards are unchanged.`
    );
  }

  if (Array.isArray(pickImpact?.reasons) && pickImpact.reasons.length > 0) {
    reasons.push(...pickImpact.reasons.slice(0, 5));
  }

  if (Array.isArray(starRetentionImpact?.reasons) && starRetentionImpact.reasons.length > 0) {
    reasons.push(...starRetentionImpact.reasons);
  }

  if (Array.isArray(contractImpact?.reasons) && contractImpact.reasons.length > 0) {
    reasons.push(...contractImpact.reasons);
  }

  if (powerContext.isTopConferenceTeam) {
    reasons.push(`${cpuName} is currently the top team in its conference, so it needs a clearer reason to move pieces.`);
  }

  if (cleanPickUpgradeAccept) {
    reasons.push("Accepted because this is a clean draft-asset upgrade for the CPU with no player, roster, salary, or contract downside.");
  } else if (cpuCpuBuyerAccept) {
    reasons.push("Accepted in CPU-to-CPU buyer mode because the team gets a meaningful rotation upgrade without an excessive pick/contract cost.");
  } else if (cpuCpuSellerAccept) {
    reasons.push("Accepted in CPU-to-CPU seller mode because the team receives enough future/upside value without an excessive rotation drop.");
  } else if (noDownsidePickSweetenerAccept) {
    reasons.push("Accepted because the CPU receives enough draft-pick value without taking a meaningful team-impact or contract downside.");
  } else if (noDownsideAccept) {
    reasons.push("Accepted because the trade improves or holds every team-impact rating and stays close enough to the adjusted threshold.");
  } else if (accepted) {
    reasons.push(`Accepted because the weighted team-impact score clears the ${threshold.toFixed(2)} adjusted threshold.`);
  } else if (!hasNoMeaningfulDownside) {
    reasons.push(`Rejected because the gains do not justify the rating sacrifice for ${cpuName}'s current team direction.`);
  } else if (pickImpact?.hasPicks && pickScore < CLEAN_PICK_UPGRADE_ACCEPT_LINE) {
    reasons.push(
      pickScore < -TEAM_IMPACT_EPS
        ? `Rejected because ${cpuName} would lose net draft-pick value in a deal without enough team-impact compensation.`
        : `Rejected because the draft-pick value is too small to justify anything beyond a no-downside asset cleanup.`
    );
  } else {
    reasons.push("Rejected because the move is too close to neutral; CPU teams need a clear reason to trade.");
  }

  return {
    accepted,
    decision: accepted ? "accept" : "reject",
    score: round4(mainScore),
    message: accepted
      ? `${cpuName} accepts the proposal.`
      : `${cpuName} rejects the proposal.`,
    reasons,
    counterSuggestions: [],
    teamImpact: {
      userTeamName: userName,
      cpuTeamName: cpuName,
      evaluationMode,
      cpuTradeRole: normalizedCpuTradeRole,
      cpuTradeContext,
      ratingMode: useFastScanImpact ? TRADE_FINDER_FAST_SCAN_MODE : useFastFtr ? TRADE_FINDER_FAST_FTR_MODE : "exact",
      fastScan: Boolean(useFastScanImpact),
      fastFtr: Boolean(useFastFtr),
      rank: powerContext.rank,
      isTopConferenceTeam: powerContext.isTopConferenceTeam,
      useRecordPowerRankings: powerContext.useRecordPowerRankings,
      weights: { ovrWeight, potWeight },
      threshold,
      baseThreshold,
      contractFriction: contractImpact?.friction || 0,
      contractImpact,
      starRetentionTax: starRetentionImpact?.tax || 0,
      starRetentionImpact,
      noDownsideMinGain,
      before,
      after,
      deltas: {
        ovr: deltaOVR,
        pot: deltaPOT,
        ftr: deltaFTR,
      },
      scoreBreakdown: {
        ovrScore: round4(ovrWeight * deltaOVR * OVR_IMPACT_MULT),
        potScore: round4(potWeight * deltaPOT * POT_IMPACT_MULT),
        ftrScore: round4(ftrScore),
        pickScore,
        pickImpact,
        incomingPickValue: pickImpact?.incomingValue || 0,
        outgoingPickValue: pickImpact?.outgoingValue || 0,
        cleanPickUpgradeAccept,
        noDownsidePickSweetenerAccept,
        cpuCpuBuyerAccept,
        cpuCpuSellerAccept,
        hasMeaningfulStarRetentionTax,
        contractFriction: contractImpact?.friction || 0,
        starRetentionTax: starRetentionImpact?.tax || 0,
      },
    },
  };
}

export function evaluateTradeTeamImpact(args = {}) {
  const totalStart = tfImpactNow();
  const breakdownEnabled =
    String(args?.cpuTradeRole || "").toLowerCase() === "trade_finder" && isTradeFinderImpactBreakdownEnabled();
  const metrics = breakdownEnabled ? {} : null;
  const baseBreakdown = breakdownEnabled ? makeTradeFinderImpactBreakdownBase(args) : null;

  const cacheKeyStart = tfImpactNow();
  const cacheKey = makeTradeFinderImpactCacheKey(args);
  addBreakdownMetric(metrics, "impactCacheKeyMs", tfImpactNow() - cacheKeyStart);

  if (cacheKey) {
    const cacheLookupStart = tfImpactNow();
    const cached = getLimitedCache(tradeFinderImpactCache, cacheKey);
    addBreakdownMetric(metrics, "impactCacheLookupMs", tfImpactNow() - cacheLookupStart);
    if (cached) {
      const totalMs = tfImpactNow() - totalStart;
      recordTradeFinderImpactBreakdown({
        ...baseBreakdown,
        cacheHit: true,
        accepted: Boolean(cached?.accepted),
        score: Number(cached?.score || 0),
        threshold: Number(cached?.teamImpact?.threshold || 0),
        totalMs: tfImpactRoundMs(totalMs),
        metrics: Object.fromEntries(Object.entries(metrics || {}).map(([key, value]) => [key, tfImpactRoundMs(value)])),
      });
      debugTradeImpactEvaluation(args, cached, { cacheHit: true, totalMs: tfImpactRoundMs(totalMs) });
      return {
        ...cached,
        __tfImpactCacheHit: true,
      };
    }
  }

  const uncachedStart = tfImpactNow();
  const result = evaluateTradeTeamImpactUncached({ ...args, __tfBreakdownMetrics: metrics });
  addBreakdownMetric(metrics, "uncachedImpactMs", tfImpactNow() - uncachedStart);

  if (cacheKey) {
    const cacheStoreStart = tfImpactNow();
    touchLimitedCache(tradeFinderImpactCache, cacheKey, result, TRADE_FINDER_IMPACT_CACHE_MAX);
    addBreakdownMetric(metrics, "impactCacheStoreMs", tfImpactNow() - cacheStoreStart);
  }

  if (breakdownEnabled) {
    const totalMs = tfImpactNow() - totalStart;
    recordTradeFinderImpactBreakdown({
      ...baseBreakdown,
      cacheHit: false,
      accepted: Boolean(result?.accepted),
      score: Number(result?.score || 0),
      threshold: Number(result?.teamImpact?.threshold || 0),
      ratingMode: result?.teamImpact?.ratingMode || baseBreakdown?.impactMode || "exact",
      rank: result?.teamImpact?.rank || null,
      deltas: result?.teamImpact?.deltas || null,
      totalMs: tfImpactRoundMs(totalMs),
      metrics: Object.fromEntries(Object.entries(metrics || {}).map(([key, value]) => [key, tfImpactRoundMs(value)])),
    });
  }

  debugTradeImpactEvaluation(args, result, { cacheHit: false, totalMs: tfImpactRoundMs(tfImpactNow() - totalStart) });
  return result;
}

export function clearTradeFinderImpactCache() {
  tradeFinderImpactCache.clear();
}

export function getTradeFinderImpactCacheSize() {
  return tradeFinderImpactCache.size;
}

